### ISSUE TITLE
Error migration app from 17.11.3 to 17.12.0

### ISSUE THREAD

**Issue by vanohaker** [sentry-kubernetes/charts#1014]
While updating the application from 22.11.0 to 23.3.1 (charts version 17.11.3 to 17.12.0) in the sentry-snuba-migrate pod I get an error:
```
 $ kubectl -n sentry logs sentry-snuba-migrate-zwrgz
2023-09-13 14:01:09,494 Initializing Snuba...
2023-09-13 14:01:11,543 Snuba initialization took 2.0496524441987276s
2023-09-13 14:01:11,544 Attempting to connect to Clickhouse cluster sentry-clickhouse:9000 (attempt 0)
2023-09-13 14:01:11,547 Connecting. Database: default. User: default
2023-09-13 14:01:11,547 Connecting to sentry-clickhouse:9000
2023-09-13 14:01:11,549 Connected to ClickHouse server version 20.8.19, revision: 54438
2023-09-13 14:01:11,549 Query: SELECT version()
2023-09-13 14:01:11,549 Block "" send time: 0.000032
2023-09-13 14:01:11,552 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'replays', 'generic_metrics')
2023-09-13 14:01:11,552 Block "" send time: 0.000024
2023-09-13 14:01:11,561 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'replays', 'generic_metrics')
2023-09-13 14:01:11,561 Block "" send time: 0.000023
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 74, in migrate
    runner.run_all(force=force, group=migration_group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 163, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 350, in _get_pending_migrations
    group_migrations = self._get_pending_migrations_for_group(group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 373, in _get_pending_migrations_for_group
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: events: 0017_errors_add_indexes
```
Has anyone had a similar error? How to fix it?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
