### ISSUE TITLE
Snuba Connection pool is full Error

### ISSUE THREAD

**Issue by ultherego** [sentry-kubernetes/charts#1015]
Hi.
I changed the number of replicas for all snuba deployments - 3,6,8, etc.
In the configmap for clickhouse, I added different values for the `pool_size` / `background_buffer_flush_schedule_pool_size` / `background_common_pool_size` ---> https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings

What I reviewed and what I tried to change:
https://github.com/getsentry/snuba/issues/4596
https://github.com/reportportal/agent-python-pytest/issues/248
https://github.com/sentry-kubernetes/charts/issues/365
and more.

### Helm
Chart Verison: **20.5.3**
App Version: **23.8.0**

###  Stack
Replicas:
- 3x sentry-clickhouse
- 3x sentry-zookeeper-clickhouse
- 3x sentry-kafka
- 3x sentry-worker
- 3x sentry-snuba-api
- 3x sentry-nginx
- 2x sentry-relay

### Error
Error in snuba pods:
- sentry-snuba-outcomes-consumer
- sentry-snuba-consumer

```
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 260, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 365, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 149, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 98, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 122, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 330, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 160, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 347, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 239, in join
    response = self._result.result(timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
````
and
```
Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
```

### Clickhouse
```
keep_alive_timeout: "120"
mark_cache_size: "5368709120"
max_concurrent_queries: "30000"
max_connections: "10240"
max_session_timeout: "3600"
```

### Kafka Config
```
maxMessageBytes: "50000000"
socketRequestMaxBytes: "50000000"
```

### Snuba
```
# Consumer / OutcomesConsumer / TransactionsConsumer
maxBatchTimeMs: 30000
```

### Redis
```
  replica:
    replicaCount: 0
  commonConfiguration: |-
    appendonly yes
    save ""
    maxmemory 2684354560
    maxmemory-policy allkeys-lru
```

#### Example script to debug
```
#!/usr/bin/env python3

import sentry_sdk

sentry_sdk.init(dsn='set_to_dsn_for_your_org')

traces_sample_rate=1.0

def perform_critical_operation():
    my_list = [1, 2, 3]
    print(my_list[4])

if __name__ == "__main__":
    for i in range(1, 10000000000):
        try:
            perform_critical_operation(i)
        except Exception as e:
            sentry_sdk.capture_exception(e)
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by rojinebrahimi** [comment]
Any news on this topic?

**Comment by ultherego** [comment]
Absolutely nothing. We changed the tool.
The chart version of Sentry became too cumbersome to monitor and manage. Too many components, each generating some type of error. Error tracking tool, became an error itself ;) 
We don't have time to fix every now and then problems related to cleanup snuba / kafka, etc.

**Comment by notypecheck** [comment]
@UltherEgo What did you ended up using?

**Comment by ultherego** [comment]
> @UltherEgo What did you ended up using?

Glitchtip is based on Django. The only components it has are worker web and redis + database. Redis is mainly a cache, not a database. This minimizes the problems that occur between snuba -> kafka, clickhouse, zookeeper.

**Comment by notypecheck** [comment]
@UltherEgo I tried glitchtip too, but it's much less feature rich than sentry

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
