### ISSUE TITLE
Unable to deploy chart 20 or higher on fresh setup

### ISSUE THREAD

**Issue by dvadgama** [sentry-kubernetes/charts#1027]
**With zookeeper** 

sentry-values.yaml
```yaml
kafka:
  zookeeper:
    enabled: true
  kraft:
    enabled: false
```

No pods are in my test space
```bash
kubectl get pods -n sentry-test
No resources found in sentry-test namespace.
```

Helm install indicates install has failed 

```bash
helm install ci-sentry sentry/sentry -f sentry-staging.yml --wait
coalesce.go:175: warning: skipped value for kafka.config: Not a table.
coalesce.go:175: warning: skipped value for kafka.zookeeper.topologySpreadConstraints: Not a table.
W0928 10:46:44.346440   19564 warnings.go:70] spec.template.spec.containers[0].env[39].name: duplicate name "KAFKA_ENABLE_KRAFT"
Error: INSTALLATION FAILED: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
```

Reason is, Kafka fails to startup with zookeeper
```bash
java.lang.RuntimeException: Found unexpected version in loaded `meta.properties`: {cluster.id=kafka_cluster_id_testw, node.id=0, version=1}. Zk-based brokers only support version 0 (which is implicit when the `version` field is missing).
        at kafka.server.KafkaServer.startup(KafkaServer.scala:227)
        at kafka.Kafka$.main(Kafka.scala:115)
        at kafka.Kafka.main(Kafka.scala)
```

 **with Kraft**

Understanding Zookeeper is being deprecated, we tried another run with clean slate by deleting 

- Sentry install
- Deleting external Postgres and creating new instance with version 15.2 

sentry-values.yaml
```yaml
kafka:
  zookeeper:
    enabled: false
  kraft:
    enabled: true
```

No Pods in test space

```bash 
kubectl get pods -n sentry-test
No resources found in sentry-test namespace.
```

Installation fails
 
```bash
helm install ci-sentry sentry/sentry -f sentry-staging.yml --wait
coalesce.go:175: warning: skipped value for kafka.config: Not a table.
coalesce.go:175: warning: skipped value for kafka.zookeeper.topologySpreadConstraints: Not a table.
Error: INSTALLATION FAILED: failed post-install: 1 error occurred:
        * job failed: DeadlineExceeded
```

Reason snuba migration fails
```bash 
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 392, in _get_pending_migrations
    group_migrations = self._get_pending_migrations_for_group(group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 415, in _get_pending_migrations_for_group
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: search_issues: 0005_search_issues_v2
```

I have had exactly same result for 
- chart version 20.0.0 and higher 
- with both PostgreSQL being deployed as POD and external host, using PostgreSQL version 15.2

**Comment by TartanLeGrand** [comment]
Same for me, have try with the two zookeeper and kraft :smile:

**Comment by pierangelomiceli** [comment]
Have you already tried to set an higher value for `activeDeadlineSeconds` ?
like this
```yaml
hooks:
  activeDeadlineSeconds: 1000
```

**Comment by TartanLeGrand** [comment]
Yes for me have this problem :

https://github.com/sentry-kubernetes/charts/issues/970

**Comment by TartanLeGrand** [comment]
Linked with this https://github.com/sentry-kubernetes/charts/issues/1018 ?

**Comment by dvadgama** [comment]
@pierangelomiceli i had `activeDeadlineSeconds` set to 300 before, i set it to 1000 now, however still the same issue with kafka based deployment, snuba fails to migrate 
```bash
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 97, in migrate
    runner.run_all(
  File "/usr/src/snuba/snuba/migrations/runner.py", line 176, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 392, in _get_pending_migrations
    group_migrations = self._get_pending_migrations_for_group(group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 415, in _get_pending_migrations_for_group
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: search_issues: 0005_search_issues_v2
```

**Comment by pierangelomiceli** [comment]
Do u have enough RAM on your system?
can you provide me some info about the helm command you execute to start the chart?

**Comment by TartanLeGrand** [comment]
Yes, have enough ram on my system. The commande it's helmfile and is execute helm upgrade -i.

**Comment by pierangelomiceli** [comment]
Ok, in your case is a release upgrade, the specific issue is related on a fresh setup.
have you problem even on fresh setup?

**Comment by TartanLeGrand** [comment]
@pierangelomiceli according to the doc of helm:

```
-i, --install                                    if a release by this name doesn't already exist, run an install
```

**Comment by pierangelomiceli** [comment]
> Yes, have enough ram on my system. The commande it's helmfile and is execute helm upgrade -i.

Ok, my bad. You just used upgrade with -i options


Anyway, try this minimal configuration with this `yourvalues.yaml` file:

```yaml
user:
  create: true
  email: e@mail.com
  password: aworkingpassword

mail:
  backend: smtp
  useTls: true
  username: "username"
  password: "password"
  port: 25
  host: "smtp.someprovider.com"
  from: "from@something.domain"

service:
  name: sentry
  type: ClusterIP
  externalPort: 9000
  annotations: {}

hooks:
  activeDeadlineSeconds: 1000

snuba:
  api:
    replicas: 1
  consumer:
    replicas: 1
  issueOccurrenceConsumer:
    replicas: 1
  outcomesConsumer:
    replicas: 1
  profilingFunctionsConsumer:
    replicas: 1
  profilingProfilesConsumer:
    replicas: 1
  replacer:
    replicas: 1
  replaysConsumer:
    replicas: 1
  sessionsConsumer:
    replicas: 1
  subscriptionConsumerEvents:
    replicas: 1
  subscriptionConsumerSessions:
    replicas: 1
  subscriptionConsumerTransactions:
    replicas: 1
  transactionsConsumer:
    replicas: 1
memcached:
  replicaCount: 1
rabbitmq:
  replicaCount: 1
symbolicator:
  replicas: 1

sentry:
  singleOrganization: false
  worker:
    replicas: 1
  ingestConsumer:
    replicas: 1
  ingestMetricsConsumerPerf:
    replicas: 1
  ingestMetricsConsumerRh:
    replicas: 1
  ingestMonitors:
    replicas: 1

clickhouse:
  clickhouse:
    replicas: "1"
  tabix:
    replicas: "1"

kafka:
  replicaCount: 3
  zookeeper:
    replicaCount: 1
zookeeper:
  replicaCount: 3

```

After `yourvalues.yaml` file creation try this:

```sh
kubectl create ns sentry 

helm install -n sentry sentry sentry/sentry --version 20.0.0 \
--values yourvalues.yaml 

```

Hope it helps!

**Comment by kfkawalec** [comment]
I have the same problem, there is any way to resolve?

**Comment by TartanLeGrand** [comment]
Hi @pierangelomiceli, your solution works! 

Just a detail, why don't the default values work? For me, when you install a chart without a value, it uses the default values and it's supposed to work.

**Comment by meltingrock** [comment]
Same issue here.

**Comment by dvadgama** [comment]
> > Yes, have enough ram on my system. The commande it's helmfile and is execute helm upgrade -i.
> 
> Ok, my bad. You just used upgrade with -i options
> 
> Anyway, try this minimal configuration with this `yourvalues.yaml` file:
> 
> ```yaml
> user:
>   create: true
>   email: e@mail.com
>   password: aworkingpassword
> 
> mail:
>   backend: smtp
>   useTls: true
>   username: "username"
>   password: "password"
>   port: 25
>   host: "smtp.someprovider.com"
>   from: "from@something.domain"
> 
> service:
>   name: sentry
>   type: ClusterIP
>   externalPort: 9000
>   annotations: {}
> 
> hooks:
>   activeDeadlineSeconds: 1000
> 
> snuba:
>   api:
>     replicas: 1
>   consumer:
>     replicas: 1
>   issueOccurrenceConsumer:
>     replicas: 1
>   outcomesConsumer:
>     replicas: 1
>   profilingFunctionsConsumer:
>     replicas: 1
>   profilingProfilesConsumer:
>     replicas: 1
>   replacer:
>     replicas: 1
>   replaysConsumer:
>     replicas: 1
>   sessionsConsumer:
>     replicas: 1
>   subscriptionConsumerEvents:
>     replicas: 1
>   subscriptionConsumerSessions:
>     replicas: 1
>   subscriptionConsumerTransactions:
>     replicas: 1
>   transactionsConsumer:
>     replicas: 1
> memcached:
>   replicaCount: 1
> rabbitmq:
>   replicaCount: 1
> symbolicator:
>   replicas: 1
> 
> sentry:
>   singleOrganization: false
>   worker:
>     replicas: 1
>   ingestConsumer:
>     replicas: 1
>   ingestMetricsConsumerPerf:
>     replicas: 1
>   ingestMetricsConsumerRh:
>     replicas: 1
>   ingestMonitors:
>     replicas: 1
> 
> clickhouse:
>   clickhouse:
>     replicas: "1"
>   tabix:
>     replicas: "1"
> 
> kafka:
>   replicaCount: 3
>   zookeeper:
>     replicaCount: 1
> zookeeper:
>   replicaCount: 3
> ```
> 
> After `yourvalues.yaml` file creation try this:
> 
> ```shell
> kubectl create ns sentry 
> 
> helm install -n sentry sentry sentry/sentry --version 20.0.0 \
> --values yourvalues.yaml 
> ```
> 
> Hope it helps!

yes, this config seems to be working and, did not cause any error while deploying sentry ! with build in postgres, will test further and get back by monday, thanks for this 👍

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
