### ISSUE TITLE
Initialization Installation Error

### ISSUE THREAD

**Issue by monlor** [sentry-kubernetes/charts#1056]
### Installation method

Helm Chart 20.0.0

modify clickhouse's replica to 1

### Logs
sentry-web
```
2023-11-02T16:41:49.566130045+08:00     return self.cursor.execute(sql, clean_bad_params(params))

2023-11-02T16:41:49.566133733+08:00 psycopg2.errors.UndefinedTable: UndefinedTable('relation "sentry_projectkey" does not exist\nLINE 1: ...te_limit_window", "sentry_projectkey"."data" FROM "sentry_pr...\n                                                             ^\n')

2023-11-02T16:41:49.566136100+08:00 SQL: SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = %s AND "sentry_projectkey"."roles" = (("sentry_projectkey"."roles" | %s)))

2023-11-02T16:41:49.566140382+08:00 

2023-11-02T16:41:49.566143433+08:00 The above exception was the direct cause of the following exception:

2023-11-02T16:41:49.566145114+08:00 

2023-11-02T16:41:49.566148745+08:00 Traceback (most recent call last):

2023-11-02T16:41:49.566152882+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/wsgi.py", line 34, in __call__

2023-11-02T16:41:49.566180710+08:00     response = super().__call__(environ, start_response)

2023-11-02T16:41:49.566183537+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 148, in sentry_patched_wsgi_handler

2023-11-02T16:41:49.566232604+08:00     return SentryWsgiMiddleware(bound_old_app, use_x_forwarded_for)(

2023-11-02T16:41:49.566235364+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/wsgi.py", line 115, in __call__

2023-11-02T16:41:49.566276376+08:00     reraise(*_capture_exception(hub))

2023-11-02T16:41:49.566278960+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/_compat.py", line 60, in reraise

2023-11-02T16:41:49.566316919+08:00     raise value

2023-11-02T16:41:49.566319623+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/wsgi.py", line 108, in __call__

2023-11-02T16:41:49.566377896+08:00     rv = self.app(

2023-11-02T16:41:49.566384831+08:00   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 141, in __call__

2023-11-02T16:41:49.566433033+08:00     response = self.get_response(request)

2023-11-02T16:41:49.566438871+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 431, in sentry_patched_get_response

2023-11-02T16:41:49.566516616+08:00     rv = old_get_response(self, request)

2023-11-02T16:41:49.566520302+08:00   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response

2023-11-02T16:41:49.566556772+08:00     response = self._middleware_chain(request)

2023-11-02T16:41:49.566559399+08:00   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner

2023-11-02T16:41:49.566591865+08:00     response = response_for_exception(request, exc)

2023-11-02T16:41:49.566594429+08:00   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception

2023-11-02T16:41:49.566632515+08:00     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())

2023-11-02T16:41:49.566635181+08:00   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception

2023-11-02T16:41:49.566675784+08:00     return callback(request, **param_dict)

2023-11-02T16:41:49.566678313+08:00   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view

2023-11-02T16:41:49.566716047+08:00     return self.dispatch(request, *args, **kwargs)

2023-11-02T16:41:49.566718583+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/web/frontend/error_500.py", line 38, in dispatch

2023-11-02T16:41:49.566753016+08:00     return render_to_response("sentry/500.html", status=500, context=context, request=request)

2023-11-02T16:41:49.566755678+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/web/helpers.py", line 40, in render_to_response

2023-11-02T16:41:49.566786546+08:00     response = HttpResponse(render_to_string(template, context, request))

2023-11-02T16:41:49.566790493+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/web/helpers.py", line 27, in render_to_string

2023-11-02T16:41:49.566820316+08:00     rendered = loader.render_to_string(template, context=context, request=request)

2023-11-02T16:41:49.566823345+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string

2023-11-02T16:41:49.566856961+08:00     return template.render(context, request)

2023-11-02T16:41:49.566861381+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render

2023-11-02T16:41:49.566900842+08:00     return self.template.render(context)

2023-11-02T16:41:49.566904818+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 171, in render

2023-11-02T16:41:49.566965177+08:00     return self._render(context)

2023-11-02T16:41:49.566967967+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render

2023-11-02T16:41:49.567025766+08:00     return self.nodelist.render(context)

2023-11-02T16:41:49.567029992+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render

2023-11-02T16:41:49.567187186+08:00     bit = node.render_annotated(context)

2023-11-02T16:41:49.567190801+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated

2023-11-02T16:41:49.567348818+08:00     return self.render(context)

2023-11-02T16:41:49.567353240+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render

2023-11-02T16:41:49.567411997+08:00     return compiled_parent._render(context)

2023-11-02T16:41:49.567418784+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render

2023-11-02T16:41:49.567471923+08:00     return self.nodelist.render(context)

2023-11-02T16:41:49.567475914+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render

2023-11-02T16:41:49.567630780+08:00     bit = node.render_annotated(context)

2023-11-02T16:41:49.567633311+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated

2023-11-02T16:41:49.567784756+08:00     return self.render(context)

2023-11-02T16:41:49.567787323+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render

2023-11-02T16:41:49.567830084+08:00     return compiled_parent._render(context)

2023-11-02T16:41:49.567832528+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render

2023-11-02T16:41:49.567905686+08:00     return self.nodelist.render(context)

2023-11-02T16:41:49.567910651+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render

2023-11-02T16:41:49.568063426+08:00     bit = node.render_annotated(context)

2023-11-02T16:41:49.568068002+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated

2023-11-02T16:41:49.568242905+08:00     return self.render(context)

2023-11-02T16:41:49.568248498+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render

2023-11-02T16:41:49.568276163+08:00     result = block.nodelist.render(context)

2023-11-02T16:41:49.568278962+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render

2023-11-02T16:41:49.568451289+08:00     bit = node.render_annotated(context)

2023-11-02T16:41:49.568459065+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated

2023-11-02T16:41:49.568613247+08:00     return self.render(context)

2023-11-02T16:41:49.568618600+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/templatetags/sentry_assets.py", line 90, in render

2023-11-02T16:41:49.568654324+08:00     content = self.nodelist.render(context).strip()

2023-11-02T16:41:49.568659327+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render

2023-11-02T16:41:49.568811609+08:00     bit = node.render_annotated(context)

2023-11-02T16:41:49.568814876+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated

2023-11-02T16:41:49.568974752+08:00     return self.render(context)

2023-11-02T16:41:49.568979387+08:00   File "/usr/local/lib/python3.8/site-packages/django/template/library.py", line 192, in render

2023-11-02T16:41:49.569026203+08:00     output = self.func(*resolved_args, **resolved_kwargs)

2023-11-02T16:41:49.569030146+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/templatetags/sentry_react.py", line 11, in get_react_config

2023-11-02T16:41:49.569062818+08:00     context = get_client_config(context.get("request", None))

2023-11-02T16:41:49.569067582+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/web/client_config.py", line 163, in get_client_config

2023-11-02T16:41:49.569108535+08:00     public_dsn = _get_public_dsn()

2023-11-02T16:41:49.569112094+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/web/client_config.py", line 90, in _get_public_dsn

2023-11-02T16:41:49.569158581+08:00     key = project_key_service.get_project_key(project_id=project_id, role=ProjectKeyRole.store)

2023-11-02T16:41:49.569170309+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/services/hybrid_cloud/project_key/impl.py", line 20, in get_project_key

2023-11-02T16:41:49.569191465+08:00     if project_keys:

2023-11-02T16:41:49.569194781+08:00   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 278, in __bool__

2023-11-02T16:41:49.569258540+08:00     self._fetch_all()

2023-11-02T16:41:49.569263045+08:00   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all

2023-11-02T16:41:49.569463693+08:00     self._result_cache = list(self._iterable_class(self))

2023-11-02T16:41:49.569469793+08:00   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__

2023-11-02T16:41:49.569498333+08:00     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

2023-11-02T16:41:49.569502552+08:00   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql

2023-11-02T16:41:49.569687486+08:00     cursor.execute(sql, params)

2023-11-02T16:41:49.569692096+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 597, in execute

2023-11-02T16:41:49.569791874+08:00     return real_execute(self, sql, params)

2023-11-02T16:41:49.569795698+08:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute

2023-11-02T16:41:49.569832010+08:00     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

2023-11-02T16:41:49.569835012+08:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

2023-11-02T16:41:49.569869284+08:00     return executor(sql, params, many, context)

2023-11-02T16:41:49.569871880+08:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

2023-11-02T16:41:49.569916729+08:00     return self.cursor.execute(sql, params)

2023-11-02T16:41:49.569919874+08:00   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__

2023-11-02T16:41:49.569956594+08:00     raise dj_exc_value.with_traceback(traceback) from exc_value

2023-11-02T16:41:49.569959448+08:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

2023-11-02T16:41:49.569994871+08:00     return self.cursor.execute(sql, params)

2023-11-02T16:41:49.569997571+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner

2023-11-02T16:41:49.570032982+08:00     raise_the_exception(self.db, e)

2023-11-02T16:41:49.570035526+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner

2023-11-02T16:41:49.570071000+08:00     return func(self, *args, **kwargs)

2023-11-02T16:41:49.570073704+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner

2023-11-02T16:41:49.570102414+08:00     return func(self, *args, **kwargs)

2023-11-02T16:41:49.570106166+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner

2023-11-02T16:41:49.570142098+08:00     raise exc_info[0](msg).with_traceback(exc_info[2])

2023-11-02T16:41:49.570144562+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner

2023-11-02T16:41:49.570182479+08:00     return func(self, sql, *args, **kwargs)

2023-11-02T16:41:49.570185238+08:00   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute

2023-11-02T16:41:49.570224834+08:00     return self.cursor.execute(sql, clean_bad_params(params))

2023-11-02T16:41:49.570233216+08:00 django.db.utils.ProgrammingError: UndefinedTable('relation "sentry_projectkey" does not exist\nLINE 1: ...te_limit_window", "sentry_projectkey"."data" FROM "sentry_pr...\n                                                             ^\n')

2023-11-02T16:41:49.570235243+08:00 SQL: SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = %s AND "sentry_projectkey"."roles" = (("sentry_projectkey"."roles" | %s)))


```

Table 'sentry_projectkey' does not exist in postgres.

**Comment by sp1ke1980** [comment]
Per my understanding this happened because migration job isn't complete successfully. Try to change options
  hooks:
    activeDeadlineSeconds: 100 to 300

**Comment by monlor** [comment]
Thanks a lot!

**Comment by pen-pal** [comment]
i am facing similar issues.
tried with latest version of sentry helm chart and even set the hook to 300
yet the issue persists
