### ISSUE TITLE
Session replays do not work

### ISSUE THREAD

**Issue by mateusz28011** [sentry-kubernetes/charts#1058]
Hi,

I'm experiencing issues with session replays. Today, I noticed that it was supposed to be fixed in version 20.9.1, but the problem still persists.

Here is the relevant log:

10:57:29 [INFO] sentry.access.api: api.access (method='GET' view='sentry.replays.endpoints.project_replay_recording_segment_index.ProjectReplayRecordingSegmentIndexEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/projects/sentry/deep-image-react/replays/3665409be93f4e6182386ab97988a0d2/recording-segments/' caller_ip='10.6.0.5' user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.11983704566955566 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
10:57:29 [INFO] sentry_sdk.errors: event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x7f6e47a2c940>) dropped event
2023-11-06T10:57:29.913360698Z Traceback (most recent call last):
2023-11-06T10:57:29.913369326Z   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/wsgi.py", line 220, in __iter__
    reraise(*_capture_exception(self._hub))
2023-11-06T10:57:29.913566877Z   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/_compat.py", line 99, in reraise
2023-11-06T10:57:29.913650230Z     raise value
2023-11-06T10:57:29.913665083Z   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/wsgi.py", line 216, in __iter__
    chunk = next(iterator)
2023-11-06T10:57:29.913793295Z   File "/usr/local/lib/python3.8/site-packages/sentry/replays/usecases/reader.py", line 264, in download_segments
2023-11-06T10:57:29.913951466Z     for i, result in enumerate(results):
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
2023-11-06T10:57:29.914464136Z     return self.__get_result()
2023-11-06T10:57:29.914477943Z   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
2023-11-06T10:57:29.914789160Z   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2023-11-06T10:57:29.914914417Z     result = self.fn(*self.args, **self.kwargs)
2023-11-06T10:57:29.914926502Z   File "/usr/local/lib/python3.8/site-packages/sentry/replays/usecases/reader.py", line 292, in download_segment
    result = driver.get(segment)
2023-11-06T10:57:29.915213091Z   File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 199, in inner
2023-11-06T10:57:29.915282896Z     return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/replays/lib/storage.py", line 65, in get
    return file.getfile().read()
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/tracing_utils_py3.py", line 70, in func_with_tracing
2023-11-06T10:57:29.915432533Z     return func(*args, **kwargs)
2023-11-06T10:57:29.915440793Z   File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfile.py", line 234, in getfile
    impl = self._get_chunked_blob(mode, prefetch)
2023-11-06T10:57:29.915562009Z   File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfile.py", line 218, in _get_chunked_blob
2023-11-06T10:57:29.915657884Z     return ChunkedFileBlobIndexWrapper(
2023-11-06T10:57:29.915666301Z   File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfile.py", line 41, in __init__
2023-11-06T10:57:29.915720549Z     self.open()
  File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfile.py", line 79, in open
    self.seek(0)
  File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfile.py", line 146, in seek
    return self._seek(pos)
2023-11-06T10:57:29.915893875Z   File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfile.py", line 136, in _seek
    self._nextidx()
  File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfile.py", line 65, in _nextidx
    self._curfile = self._curidx.blob.getfile()
  File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfileblob.py", line 250, in getfile
2023-11-06T10:57:29.916367499Z     return storage.open(self.path)
  File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 38, in open
2023-11-06T10:57:29.916478467Z     return self._open(name, mode)
  File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 243, in _open
2023-11-06T10:57:29.916732982Z     return File(open(self.path(name), mode))
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/sentry/files/16/303d/2626fe475493aab45f74242f21'

Additionally, the request to the following URL returns just "[":

> https://{sentry}/api/0/projects/sentry/deep-image-react/replays/{id}/recording-segments/?cursor=0%3A0%3A0&download=true&per_page=100

>

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
