### ISSUE TITLE
Upgrade 18.0.1 to 19.0.0 fails because of sentry-snuba-migrate jobs

### ISSUE THREAD

**Issue by julian-stierle-heinze** [sentry-kubernetes/charts#1074]
Thank you all for maintaing this project.

I am stuck with a failing upgrade vom Helm chart version 18.0.1 to the next 19.0.0.

The sentry-snuba-migrate job fails with these messages and Sentry then is non-functional.

```
...
...
2023-11-21 12:53:16,619 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'replays', 'generic_metrics')
2023-11-21 12:53:16,619 Block "" send time: 0.000031
2023-11-21 12:53:16,624 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'replays', 'generic_metrics')
2023-11-21 12:53:16,625 Block "" send time: 0.000031
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 96, in migrate
    runner.run_all(
  File "/usr/src/snuba/snuba/migrations/runner.py", line 179, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 395, in _get_pending_migrations
    group_migrations = self._get_pending_migrations_for_group(group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 418, in _get_pending_migrations_for_group
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: replays: 0009_add_dom_index_columns
```

Rolling back to 18.0.1 solves the situation.

I have an external Postgres-DB with Postgres 15.4.0.

Thanks in advance for your help.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
