### ISSUE TITLE
kafka error on startup for sentry-snuba-replays-consumer 

### ISSUE THREAD

**Issue by elee1766** [sentry-kubernetes/charts#1093]
hi,

for some reason the  sentry-snuba-replays-consumer is crashing with this log on startup.

```
2023-12-08 05:42:13,205 Initializing Snuba...
2023-12-08 05:42:20,636 Snuba initialization took 7.433308527106419s
2023-12-08 05:42:20,666 Consumer Starting
2023-12-08 05:42:20,666 Checking Clickhouse connections
2023-12-08 05:42:20,729 librdkafka log level: 6
2023-12-08 05:42:20,859 New partitions assigned: {Partition(topic=Topic(name='ingest-replay-events'), index=0): 54333}
2023-12-08 05:42:21,376 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 291, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 360, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 414, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 0)"}
2023-12-08 05:42:21,378 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f9ef6df2f10>...
2023-12-08 05:42:21,379 Partitions to revoke: [Partition(topic=Topic(name='ingest-replay-events'), index=0)]
2023-12-08 05:42:21,379 Partition revocation complete.
2023-12-08 05:42:21,388 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 279, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 291, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 360, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 414, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 0)"}
```

was some migration missed ?

**Comment by jdemetert** [comment]
This issue is caused by kafka/consumers falling out of sync. See https://develop.sentry.dev/self-hosted/troubleshooting/#kafka for how to resolve

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by elee1766** [comment]
ah, i fixed this through running  commands until sentry became happy.... i guess thats fine lol. thanks!!

**Comment by tejasnadgoud** [comment]
> ah, i fixed this through running commands until sentry became happy.... i guess thats fine lol. thanks!!

I'm facing the same issue, what changes did you make in your values.yaml to fix this?

**Comment by elee1766** [comment]
> > ah, i fixed this through running commands until sentry became happy.... i guess thats fine lol. thanks!!
> 
> I'm facing the same issue, what changes did you make in your values.yaml to fix this?

hi, no changes to values

https://develop.sentry.dev/self-hosted/troubleshooting/#proper-solution

I exec'd into pods and ran relevant commands described here until it was happy, converting from docker compose syntax to kubectl exec

**Comment by tejasnadgoud** [comment]
> > > ah, i fixed this through running commands until sentry became happy.... i guess thats fine lol. thanks!!
> > 
> > 
> > I'm facing the same issue, what changes did you make in your values.yaml to fix this?
> 
> hi, no changes to values
> 
> https://develop.sentry.dev/self-hosted/troubleshooting/#proper-solution
> 
> I exec'd into pods and ran relevant commands described here until it was happy, converting from docker compose syntax to kubectl exec

I see, I did that as well. But I wonder that's like a one time fix and if this issue were to reappear then this would again be a problem. Is there a permanent fix for this?

**Comment by jdemetert** [comment]
> Is there a permanent fix for this?

The issue is that you received more events than you could handle. The Kafka topics overfill and cannot store the older events that are being referenced, which leads to the OFFSET errors seen from the consumers. The fix is to increase your processing capacity to prevent exceeding your kafka limits which can be solved with a few things: 
1. Start by scaling up the number of sentry-workers. If you have monitoring available check if your workers are CPU bound.
2. Try increasing the `maxBatchSize` and `processes`  on your ingest consumers to improve processing rates. 
3. Increase the kafka PVC partition size (`kafka.persistence.size`) to allow for more delay offset, this can help with handling temporary spikes in load but won't fix continuous events exceeding processing capacity. 
4. If the workers are not being CPU bound you can try to scale the ingest-consumers with replicas, this requires you to add partitions to the kafka topics that you are consuming from. The process for this was to increase the replicas: 
From within the kafka pod run `/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server $BOOTSTRAP --alter --topic TOPIC-NAME --partitions NUM_PARTITIONS` replace topic-name with the topic that has a high lag and partitions can be the number of replicas. After this delete the corresponding ingestor pods so that new pods are created which will find available partitions and all start doing work, if you don't do this you will only see one ingestor doing work (can verify with logs/cpu usage). Note that increasing the number of partitions will increase the PVC usage so you might need to scale the kafka instance and reduce log retention. I added the following to my kafka instance:
```
kafka:
  # existing values
  # Prevent disk space running out
  logRetentionBytes: LESS THAN DEFAULT
  logSegmentBytes: HALF OF logRetentionBytes
  logRetentionCheckIntervalMs: 60000
```

I would also recommend [adding monitoring to your kafka queues](https://github.com/bitnami/charts/tree/main/bitnami/kafka#metrics-parameters) so that you can catch when inbound events start to exceed worker capacity. The prometheus metric to monitor is `kafka_consumergroup_lag`

This thread was pretty helpful for myself when I was scaling up event handling and talks about the partitioning if you determine that you need it: https://github.com/sentry-kubernetes/charts/issues/827

**Comment by tejasnadgoud** [comment]
> > Is there a permanent fix for this?
> 
> The issue is that you received more events than you could handle. The Kafka topics overfill and cannot store the older events that are being referenced, which leads to the OFFSET errors seen from the consumers. The fix is to increase your processing capacity to prevent exceeding your kafka limits which can be solved with a few things:
> 
>     1. Start by scaling up the number of sentry-workers. If you have monitoring available check if your workers are CPU bound.
> 
>     2. Try increasing the `maxBatchSize` and `processes`  on your ingest consumers to improve processing rates.
> 
>     3. Increase the kafka PVC partition size (`kafka.persistence.size`) to allow for more delay offset, this can help with handling temporary spikes in load but won't fix continuous events exceeding processing capacity.
> 
>     4. If the workers are not being CPU bound you can try to scale the ingest-consumers with replicas, this requires you to add partitions to the kafka topics that you are consuming from. The process for this was to increase the replicas:
>        From within the kafka pod run `/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server $BOOTSTRAP --alter --topic TOPIC-NAME --partitions NUM_PARTITIONS` replace topic-name with the topic that has a high lag and partitions can be the number of replicas. After this delete the corresponding ingestor pods so that new pods are created which will find available partitions and all start doing work, if you don't do this you will only see one ingestor doing work (can verify with logs/cpu usage). Note that increasing the number of partitions will increase the PVC usage so you might need to scale the kafka instance and reduce log retention. I added the following to my kafka instance:
> 
> 
> ```
> kafka:
>   # existing values
>   # Prevent disk space running out
>   logRetentionBytes: LESS THAN DEFAULT
>   logSegmentBytes: HALF OF logRetentionBytes
>   logRetentionCheckIntervalMs: 60000
> ```
> 
> I would also recommend [adding monitoring to your kafka queues](https://github.com/bitnami/charts/tree/main/bitnami/kafka#metrics-parameters) so that you can catch when inbound events start to exceed worker capacity. The prometheus metric to monitor is `kafka_consumergroup_lag`
> 
> This thread was pretty helpful for myself when I was scaling up event handling and talks about the partitioning if you determine that you need it: #827

Thank you so much for the inputs! I'll try these and monitor how sentry handles surge of events after the changes.
