### ISSUE TITLE
sentry-zookeeper-clickhouse fills up storage

### ISSUE THREAD

**Issue by tejasnadgoud** [sentry-kubernetes/charts#1111]
I'm using the latest version of the chart i.e `v20.0.0` with external redis.
After deploying, sentry works fine and all the pods are up and running for a few days after which some of the pods start crashing and redis db starts filling up and no events are logged into sentry.

Elasticache redis shoots up to 100% exponentially:
![Screenshot 2024-01-17 at 2 11 11 PM](https://github.com/sentry-kubernetes/charts/assets/50693747/1b748a8a-4ba4-45bf-8c4f-bb6f3118905c)

```
workstation % kubectl get pods
NAME                                                              READY   STATUS             RESTARTS        AGE
sentry-billing-metrics-consumer-78d59c4575-vkr6z                  1/1     Running            0               5d
sentry-clickhouse-0                                               1/1     Running            0               5d
sentry-clickhouse-1                                               1/1     Running            0               5d
sentry-clickhouse-2                                               1/1     Running            0               5d
sentry-cron-56c794bc65-vgf4t                                      1/1     Running            0               5d
sentry-ingest-consumer-attachments-7cbf58888c-bs8kw               1/1     Running            0               5d
sentry-ingest-consumer-events-6799b9665f-6xjg2                    1/1     Running            0               5d
sentry-ingest-consumer-transactions-746b6b9875-78klf              1/1     Running            0               5d
sentry-ingest-metrics-consumer-perf-579f9547c8-cswh9              1/1     Running            0               5d
sentry-ingest-metrics-consumer-rh-bcdc866f8-lxp7h                 1/1     Running            0               5d
sentry-ingest-monitors-6989589dfc-j85g7                           1/1     Running            0               5d
sentry-ingest-replay-recordings-57cd7545cd-d6mt7                  1/1     Running            0               5d
sentry-kafka-0                                                    1/1     Running            0               5d
sentry-kafka-1                                                    1/1     Running            0               5d
sentry-kafka-2                                                    1/1     Running            0               5d
sentry-post-process-forward-errors-7b6cd64989-wtrxn               1/1     Running            0               5d
sentry-post-process-forward-transactions-c58d5666c-cfvlb          1/1     Running            0               5d
sentry-rabbitmq-0                                                 1/1     Running            0               5d
sentry-rabbitmq-1                                                 1/1     Running            0               5d
sentry-rabbitmq-2                                                 1/1     Running            0               5d
sentry-relay-85649ffb4b-79dmf                                     1/1     Running            0               5d
sentry-sentry-cleanup-28418400-lp9vk                              0/1     Completed          0               4d19h
sentry-sentry-cleanup-28419840-2kwjj                              0/1     Completed          0               3d19h
sentry-sentry-cleanup-28421280-tctbd                              0/1     Completed          0               2d19h
sentry-sentry-cleanup-28422720-7j7nz                              0/1     Completed          0               43h
sentry-sentry-cleanup-28424160-td6x2                              0/1     Completed          0               19h
sentry-sessions-consumer-65cf5fc65c-hk6rm                         0/1     CrashLoopBackOff   47 (2m5s ago)   5d
sentry-snuba-api-59c8b6ff66-xxcws                                 1/1     Running            0               5d
sentry-snuba-consumer-6dd6c6b9f8-mlzxc                            0/1     CrashLoopBackOff   50 (86s ago)    3h57m
sentry-snuba-outcomes-consumer-66676499bc-zvqdw                   0/1     CrashLoopBackOff   49 (3m9s ago)   3h57m
sentry-snuba-replacer-7b9d89c794-gvkgb                            1/1     Running            0               5d
sentry-snuba-replays-consumer-7dd4b58bb6-w6pzd                    1/1     Running            0               5d
sentry-snuba-subscription-consumer-events-7789459946-5b684        1/1     Running            0               5d
sentry-snuba-subscription-consumer-sessions-579dd8d654-x2k7k      1/1     Running            0               5d
sentry-snuba-subscription-consumer-transactions-66d7f89656gct8k   1/1     Running            0               5d
sentry-snuba-transactions-consumer-68468c55b9-8hq25               1/1     Running            0               5d
sentry-subscription-consumer-events-578d96dd9b-dlvhj              1/1     Running            0               5d
sentry-subscription-consumer-transactions-c747b657b-29gjs         1/1     Running            0               5d
sentry-web-778846f9fd-sdx4g                                       1/1     Running            0               5d
sentry-worker-7b6d444d5f-gw4lj                                    1/1     Running            0               5d
sentry-worker-7b6d444d5f-j5jp8                                    1/1     Running            0               5d
sentry-worker-7b6d444d5f-ng8tw                                    1/1     Running            0               5d
sentry-zookeeper-clickhouse-0                                     1/1     Running            0               5d
sentry-zookeeper-clickhouse-1                                     1/1     Running            0               3h59m
sentry-zookeeper-clickhouse-2                                     0/1     CrashLoopBackOff   48 (14s ago)    3h44m

```

Interestingly only one `sentry-zookeeper-clickhouse-2` fails out of the 3 pods from `sentry-zookeeper-clickhouse` StatefulSet.

```
2024-01-17 19:00:10,891 [myid:] - INFO  [QuorumPeer[myid=3](plain=[0:0:0:0:0:0:0:0]:2181)(secure=disabled):o.a.z.s.ZooKeeperServer@365] - Created server with tickTime 2000 ms minSessionTimeout 4000 ms maxSessionTimeout 40000 ms clientPortListenBacklog -1 datadir /bitnami/zookeeper/data/version-2 snapdir /bitnami/zookeeper/data/version-2
2024-01-17 19:00:10,893 [myid:] - INFO  [QuorumPeer[myid=3](plain=[0:0:0:0:0:0:0:0]:2181)(secure=disabled):o.a.z.s.q.Leader@588] - LEADING - LEADER ELECTION TOOK - 661 MS
2024-01-17 19:00:10,897 [myid:] - INFO  [QuorumPeer[myid=3](plain=[0:0:0:0:0:0:0:0]:2181)(secure=disabled):o.a.z.s.q.QuorumPeer@917] - Peer state changed: leading - discovery
2024-01-17 19:00:10,899 [myid:] - INFO  [QuorumPeer[myid=3](plain=[0:0:0:0:0:0:0:0]:2181)(secure=disabled):o.a.z.s.p.FileTxnSnapLog@479] - Snapshotting: 0x97c00002557 to /bitnami/zookeeper/data/version-2/snapshot.97c00002557
2024-01-17 19:00:10,904 [myid:] - INFO  [QuorumPeer[myid=3](plain=[0:0:0:0:0:0:0:0]:2181)(secure=disabled):o.a.z.s.p.FileTxnSnapLog@490] - Deleted empty snapshot file: /bitnami/zookeeper/data/version-2/snapshot.97c00002557
2024-01-17 19:00:10,909 [myid:] - ERROR [QuorumPeer[myid=3](plain=[0:0:0:0:0:0:0:0]:2181)(secure=disabled):o.a.z.s.ZooKeeperServer@541] - Severe unrecoverable error, exiting
java.io.IOException: No space left on device
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
        at java.base/java.util.zip.CheckedOutputStream.write(CheckedOutputStream.java:74)
        at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
        at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
        at org.apache.jute.BinaryOutputArchive.writeBuffer(BinaryOutputArchive.java:122)
        at org.apache.zookeeper.server.DataNode.serialize(DataNode.java:185)
        at org.apache.jute.BinaryOutputArchive.writeRecord(BinaryOutputArchive.java:126)
        at org.apache.zookeeper.server.DataTree.serializeNodeData(DataTree.java:1335)
        at org.apache.zookeeper.server.DataTree.serializeNode(DataTree.java:1319)
        at org.apache.zookeeper.server.DataTree.serializeNode(DataTree.java:1328)
        at org.apache.zookeeper.server.DataTree.serializeNode(DataTree.java:1328)
        at org.apache.zookeeper.server.DataTree.serializeNode(DataTree.java:1328)
        at org.apache.zookeeper.server.DataTree.serializeNode(DataTree.java:1328)
        at org.apache.zookeeper.server.DataTree.serializeNode(DataTree.java:1328)
        at org.apache.zookeeper.server.DataTree.serializeNode(DataTree.java:1328)
        at org.apache.zookeeper.server.DataTree.serializeNode(DataTree.java:1328)
        at org.apache.zookeeper.server.DataTree.serializeNodes(DataTree.java:1343)
        at org.apache.zookeeper.server.DataTree.serialize(DataTree.java:1353)
        at org.apache.zookeeper.server.util.SerializeUtils.serializeSnapshot(SerializeUtils.java:171)
        at org.apache.zookeeper.server.persistence.FileSnap.serialize(FileSnap.java:226)
        at org.apache.zookeeper.server.persistence.FileSnap.serialize(FileSnap.java:245)
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.save(FileTxnSnapLog.java:481)
        at org.apache.zookeeper.server.ZooKeeperServer.takeSnapshot(ZooKeeperServer.java:539)
        at org.apache.zookeeper.server.ZooKeeperServer.takeSnapshot(ZooKeeperServer.java:533)
        at org.apache.zookeeper.server.ZooKeeperServer.loadData(ZooKeeperServer.java:529)
        at org.apache.zookeeper.server.quorum.Leader.lead(Leader.java:597)
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1552)
        Suppressed: java.io.IOException: No space left on device
                at java.base/java.io.FileOutputStream.writeBytes(Native Method)
                at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
                at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
                at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
                at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
                at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:191)
                at org.apache.zookeeper.server.persistence.FileSnap.serialize(FileSnap.java:261)
                ... 6 common frames omitted
                Suppressed: java.io.IOException: No space left on device
                        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
                        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
                        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
                        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
                        at java.base/java.io.FilterOutputStream.flush(FilterOutputStream.java:153)
                        at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
                        ... 7 common frames omitted
2024-01-17 19:00:10,913 [myid:] - ERROR [QuorumPeer[myid=3](plain=[0:0:0:0:0:0:0:0]:2181)(secure=disabled):o.a.z.u.ServiceUtils@42] - Exiting JVM with code 10
```

`sentry-snuba-consumer` logs:
```
2024-01-17 19:09:14,907 Initializing Snuba...
2024-01-17 19:09:18,274 Snuba initialization took 3.369992682011798s
2024-01-17 19:09:18,282 Consumer Starting
2024-01-17 19:09:18,283 librdkafka log level: 6
2024-01-17 19:09:21,305 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 2910883}
2024-01-17 19:09:21,307 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 407, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 2)"}
2024-01-17 19:09:21,308 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f992f60ddc0>...
2024-01-17 19:09:21,309 Partitions to revoke: [Partition(topic=Topic(name='events'), index=0)]
2024-01-17 19:09:21,309 Partition revocation complete.
2024-01-17 19:09:21,310 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 214, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 407, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 2)"}

```

`sentry-snuba-outcomes-consumer` logs:
```
2024-01-17 19:12:49,356 Initializing Snuba...
2024-01-17 19:12:52,636 Snuba initialization took 3.282414130982943s
2024-01-17 19:12:52,643 Consumer Starting
2024-01-17 19:12:52,644 librdkafka log level: 6
2024-01-17 19:12:55,675 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 2212738}
2024-01-17 19:12:55,791 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 365, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 149, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 98, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 114, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 329, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 159, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 347, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Table is in readonly mode (zookeeper path: /clickhouse/tables/outcomes/2/default/outcomes_hourly_local): Insertion status:

```

I'm not sure whats causing the disk to fillup and if some cleanup script isn't working as expected?
Using AWS ebs for my pv's and have 5 nodes EKS cluster.

**Comment by pavels** [comment]
You need to enable autopurge
Here is an excerpt from my values.yaml override file
```yaml
zookeeper:
  autopurge:
    purgeInterval: 6
    snapRetainCount: 3
```

**Comment by tejasnadgoud** [comment]
> You need to enable autopurge Here is an excerpt from my values.yaml override file
> 
> ```yaml
> zookeeper:
>   autopurge:
>     purgeInterval: 6
>     snapRetainCount: 3
> ```

Thanks for the input. This seems to have worked with the zookeeper pods disk issue but redis db still is at 100% and `snuba-consumer` pods are still crashing.

```
$ kubectl logs sentry-snuba-consumer-6dd6c6b9f8-plrtt

2024-01-19 16:13:14,884 Initializing Snuba...
2024-01-19 16:13:18,380 Snuba initialization took 3.4994688578881323s
2024-01-19 16:13:18,386 Consumer Starting
2024-01-19 16:13:18,387 librdkafka log level: 6
2024-01-19 16:13:25,552 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 2910883}
2024-01-19 16:13:25,555 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 407, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 2)"}
2024-01-19 16:13:25,556 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f19e17e7cd0>...
2024-01-19 16:13:25,556 Partitions to revoke: [Partition(topic=Topic(name='events'), index=0)]
2024-01-19 16:13:25,556 Partition revocation complete.
2024-01-19 16:13:25,558 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 214, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 407, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 2)"}

```

**Comment by pavels** [comment]
You can't really fix the redis situation easily - you need to basically stop everything (including redis) (i usually scale everything down to 0 replicas), delete redis stored database file, restart everything back again - there will be some amount of unprocessed events lost but usually this doesn't really matter.

We run external redis, so i can't give example for values.yaml, but what we do is run the redis with `args: ["--maxmemory", "6gb", "--maxmemory-policy", "volatile-ttl"]` and set the memory limit and available storage higher than 6GB - this way we may loose some events but the system doesn't come to a full stop when the sentry processing pipeline decides to work slow or crash (happens sometimes) and can recover by itself

**Comment by tejasnadgoud** [comment]
> You can't really fix the redis situation easily - you need to basically stop everything (including redis) (i usually scale everything down to 0 replicas), delete redis stored database file, restart everything back again - there will be some amount of unprocessed events lost but usually this doesn't really matter.
> 
> We run external redis, so i can't give example for values.yaml, but what we do is run the redis with `args: ["--maxmemory", "6gb", "--maxmemory-policy", "volatile-ttl"]` and set the memory limit and available storage higher than 6GB - this way we may loose some events but the system doesn't come to a full stop when the sentry processing pipeline decides to work slow or crash (happens sometimes) and can recover by itself

Thanks for the suggestion. We're using external redis as well (aws elasticache to be specific). It doesn't seem possible to configure the maxmemory in elasticache redis but I have change the maxmemory policy to volatile-ttl. Not yet sure if this will resolve the issue as it'll take some days to validate.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by tejasnadgoud** [comment]
> > You can't really fix the redis situation easily - you need to basically stop everything (including redis) (i usually scale everything down to 0 replicas), delete redis stored database file, restart everything back again - there will be some amount of unprocessed events lost but usually this doesn't really matter.
> > We run external redis, so i can't give example for values.yaml, but what we do is run the redis with `args: ["--maxmemory", "6gb", "--maxmemory-policy", "volatile-ttl"]` and set the memory limit and available storage higher than 6GB - this way we may loose some events but the system doesn't come to a full stop when the sentry processing pipeline decides to work slow or crash (happens sometimes) and can recover by itself
> 
> Thanks for the suggestion. We're using external redis as well (aws elasticache to be specific). It doesn't seem possible to configure the maxmemory in elasticache redis but I have change the maxmemory policy to volatile-ttl. Not yet sure if this will resolve the issue as it'll take some days to validate.

The redis issue has not come up again yet. Thanks for the help!
Will open another one for redis if it does come up again.

**Comment by Karim-Khamessy** [comment]
Hello, I hope you are doing great ! 
I am running into this issue too (zookeeper's disk is full, but not redis), so I purged the volumes and remounted the clickhouse-zookpeer with the new config of autoPurge, that solved my issue. But, I am still having issue with some pods of snuba (getting CrashLoopBackof) and the issue that I got from the logs is this: 
![Screenshot from 2024-03-25 16-04-34](https://github.com/sentry-kubernetes/charts/assets/60673368/e2cd2fc4-4e60-4c97-9834-78d9da31d9a4)
The pods that are crashing are : sentry-snuba-consumer, sentry-snuba-generic-metrics-counters-consumer , sentry-snuba-generic-metrics-distributions-consumer, sentry-snuba-metrics-consumer , sentry-snuba-outcomes-consumer, sentry-snuba-transactions-consumer
How can I fix it, please so that the remaining pods can start normally ?

**Comment by JustDoItSascha** [comment]
Why is this autoPurge option not the default? Why is it deactivated by default which results 100% in the situation that the volume is full at some point?
