### ISSUE TITLE
db-init job failed with default options

### ISSUE THREAD

**Issue by lanore78** [sentry-kubernetes/charts#112]
Hello, 

I'm trying to install sentry with the helm chart, and having issue with it.

'db-init' job always failed. 

Here is the commands that I used

```
> helm repo add sentry https://sentry-kubernetes.github.io/charts
> helm repo update

// installing sentry with default values.
> helm install test --wait sentry/sentry
```

When I enter 'kubectl get pods' I got few failed pod created by db-init job.
```
> kubectl get pods
...
sentry-test-db-init-bbdrl                              0/1     Error       0          17s
sentry-test-db-init-f5szm                              0/1     Error       0          27s
sentry-test-db-init-hvtqq                              0/1     Error       0          34s
```

Here is the full log of these pods, it saids password authentication failure.
```
2020-07-05T07:24:33.699691445Z 07:24:33 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
2020-07-05T07:24:37.096954703Z 07:24:37 [INFO] sentry.plugins.github: apps-not-configured
2020-07-05T07:24:37.44814423Z Traceback (most recent call last):
2020-07-05T07:24:37.448184276Z   File "/usr/local/bin/sentry", line 8, in <module>
2020-07-05T07:24:37.448190958Z     sys.exit(main())
2020-07-05T07:24:37.448195843Z   File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
2020-07-05T07:24:37.44820079Z     cli(prog_name=get_prog(), obj={}, max_content_width=100)
2020-07-05T07:24:37.448205407Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
2020-07-05T07:24:37.44825461Z     return self.main(*args, **kwargs)
2020-07-05T07:24:37.448325686Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
2020-07-05T07:24:37.448336165Z     rv = self.invoke(ctx)
2020-07-05T07:24:37.4483415Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
2020-07-05T07:24:37.448575913Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-07-05T07:24:37.448593774Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
2020-07-05T07:24:37.448725785Z     return ctx.invoke(self.callback, **ctx.params)
2020-07-05T07:24:37.448741583Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
2020-07-05T07:24:37.448800729Z     return callback(*args, **kwargs)
2020-07-05T07:24:37.448815546Z   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
2020-07-05T07:24:37.448821339Z     return f(get_current_context(), *args, **kwargs)
2020-07-05T07:24:37.448825948Z   File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
2020-07-05T07:24:37.448887917Z     return ctx.invoke(f, *args, **kwargs)
2020-07-05T07:24:37.448898106Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
2020-07-05T07:24:37.44891772Z     return callback(*args, **kwargs)
2020-07-05T07:24:37.44892334Z   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
2020-07-05T07:24:37.448940672Z     return f(get_current_context(), *args, **kwargs)
2020-07-05T07:24:37.44894626Z   File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 174, in upgrade
2020-07-05T07:24:37.449034581Z     _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
2020-07-05T07:24:37.449047054Z   File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 121, in _upgrade
2020-07-05T07:24:37.449053366Z     _migrate_from_south(verbosity)
2020-07-05T07:24:37.449068934Z   File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 93, in _migrate_from_south
2020-07-05T07:24:37.449096207Z     if not _has_south_history(connection):
2020-07-05T07:24:37.449104958Z   File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 78, in _has_south_history
2020-07-05T07:24:37.449110233Z     cursor = connection.cursor()
2020-07-05T07:24:37.449114757Z   File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
2020-07-05T07:24:37.449188661Z     return self._cursor()
2020-07-05T07:24:37.449199228Z   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
2020-07-05T07:24:37.449205047Z     return func(self, *args, **kwargs)
2020-07-05T07:24:37.449210168Z   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 97, in _cursor
2020-07-05T07:24:37.449257896Z     return super(DatabaseWrapper, self)._cursor()
2020-07-05T07:24:37.449267889Z   File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
2020-07-05T07:24:37.449317058Z     self.ensure_connection()
2020-07-05T07:24:37.449326793Z   File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
2020-07-05T07:24:37.44936076Z     self.connect()
2020-07-05T07:24:37.449368767Z   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
2020-07-05T07:24:37.449403008Z     six.reraise(dj_exc_type, dj_exc_value, traceback)
2020-07-05T07:24:37.449413707Z   File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
2020-07-05T07:24:37.449441583Z     self.connect()
2020-07-05T07:24:37.44945057Z   File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
2020-07-05T07:24:37.449481718Z     self.connection = self.get_new_connection(conn_params)
2020-07-05T07:24:37.449489393Z   File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
2020-07-05T07:24:37.449537086Z     connection = Database.connect(**conn_params)
2020-07-05T07:24:37.449544749Z   File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 127, in connect
2020-07-05T07:24:37.449556407Z     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2020-07-05T07:24:37.449650157Z django.db.utils.OperationalError: FATAL:  password authentication failed for user "postgres"
```

**Comment by Mokto** [comment]
Have you run this helm install/upgrade multiple times?

I think you should remove everything and restart by setting a postgres password in your values.

https://github.com/sentry-kubernetes/charts#postgressql

**Comment by lanore78** [comment]
Hi @Mokto 

Thank you for the reply.
Yes I've re installed few times, and it's because of it.

I found PVC is not removed with 'helm delete xxx' command, and this was the source of my problem.
When I remove the PVC, I could install without any errors.

**Comment by fibis** [comment]
@Mokto Is there an easy way to successfully run an upgrade after I forgot to set the password?

**Comment by Mokto** [comment]
Not sure how, to be honest.

**Comment by fibis** [comment]
Found a good way: go into the PostgreSQL container and print the environment variables. There is than also the correct password that can be used for the upgrade process.
