### ISSUE TITLE
KafkaError and ERROR relay_server

### ISSUE THREAD

**Issue by hobbyFind** [sentry-kubernetes/charts#1180]
charts version: 21.6.0

sentry-ingest-monitors   logs is：

```
07:15:33 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
07:15:33 [INFO] arroyo.processing.processor: Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f200bd6f110>...   
07:15:33 [INFO] arroyo.processing.processor: Partitions to revoke: [Partition(topic=Topic(name='ingest-monitors'), index=0)]      
07:15:33 [INFO] arroyo.processing.processor: Partition revocation complete.
07:15:33 [WARNING] arroyo.backends.kafka.consumer: Dropping staged offset for revoked partition (Partition(topic=Topic(name='inges
t-monitors'), index=0))!
07:15:33 [INFO] arroyo.processing.processor: Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/runner/__init__.py", line 190, in main
    func(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/runner/commands/run.py", line 557, in basic_consumer
    run_processor_with_signals(processor, consumer_name)
  File "/usr/local/lib/python3.11/site-packages/sentry/utils/kafka.py", line 46, in run_processor_with_signals
    processor.run()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 319, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 393, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/commit.py", line 24, in poll
    self.__commit({})
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 305, in __commit
    self.__consumer.commit_offsets()
  File "/usr/local/lib/python3.11/site-packages/arroyo/backends/kafka/consumer.py", line 609, in commit_offsets
    return self.__commit_retry_policy.call(self.__commit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/arroyo/utils/retries.py", line 88, in call
    return callable()
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/arroyo/backends/kafka/consumer.py", line 567, in __commit
    result = self.__consumer.commit(
             ^^^^^^^^^^^^^^^^^^^^^^^
cimpl.KafkaException: KafkaError{code=UNKNOWN_MEMBER_ID,val=25,str="Commit failed: Broker: Unknown member"}
```

and  sentry-relay   logs  is :

```
2024-03-18T07:47:09.802885Z ERROR relay_server::services::project_upstream: error fetching project state 9edf4d02158e35873767c6c58
eedbc88: deadline exceeded errors=0 pending=161 tags.did_error=false tags.was_pending=true tags.project_key="9edf4d02158e35873767c
6c58eedbc88"
2024-03-18T07:48:39.916699Z ERROR relay_server::services::project_upstream: error fetching project state 9edf4d02158e35873767c6c58
eedbc88: deadline exceeded errors=0 pending=159 tags.did_error=false tags.was_pending=true tags.project_key="9edf4d02158e35873767c
6c58eedbc88"
```

**Comment by ajith-nataraj** [comment]
I faced the same issue while reducing the Kafka replicas from 3 to 1.
I had to recreate only Kafka with below config
kafka:
  image:
    registry:  abc.registry.com
    repository: sentry/kafka
    tag: 3.5.1-debian-11-r1
  enabled: true
  replicaCount: 1
  allowPlaintextListener: true
  defaultReplicationFactor: 1
  offsetsTopicReplicationFactor: 1
  transactionStateLogReplicationFactor: 1
  transactionStateLogMinIsr: 1

while re-creating we cannot use same disk that was used before. create a new disk . 


had to un-install and install

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by Rahlir** [comment]
The core issue here isn't the change in deployment, it's that messages get stuck in the queue and the consumer is not able to process them within the `--max-poll-interval-ms`. This is solvable by editing the `sentry-ingest-monitors` deployment and setting `--max-poll-interval-ms` to a large value. I would also suggest @Mokto adds this as an option in the `values.yaml` file, because right now it is possible to change this value only for `ingestConsumerAttachments`, `genericMetricsConsumer`, and `metricsConsumer` deployments.
