### ISSUE TITLE
sentry-snuba-consumer and sentry-snuba-outcomes-consumer crashing

### ISSUE THREAD

**Issue by Yomanz** [sentry-kubernetes/charts#119]
Hey

I recently installed sentry on-premise but I'm experiencing weird errors when attempting to load projects/issue streams.

sentry-snuba-consumer and sentry-snuba-outcomes-consumer both crash and have the following logs:

Consumer:
```
2020-07-17 19:08:15,209 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 0, Partition(topic=Topic(name='events'), index=1): 2, Partition(topic=Topic(name='events'), index=2): 0, Partition(topic=Topic(name='events'), index=3): 0, Partition(topic=Topic(name='events'), index=4): 0, Partition(topic=Topic(name='events'), index=5): 0, Partition(topic=Topic(name='events'), index=6): 19, Partition(topic=Topic(name='events'), index=7): 0, Partition(topic=Topic(name='events'), index=8): 0, Partition(topic=Topic(name='events'), index=9): 0, Partition(topic=Topic(name='events'), index=10): 0, Partition(topic=Topic(name='events'), index=11): 69}

2020-07-17 19:08:16,316 Flushing 13 items (from {Partition(topic=Topic(name='events'), index=11): Offsets(lo=69, hi=70), Partition(topic=Topic(name='events'), index=6): Offsets(lo=19, hi=29)}): forced:False size:False time:True

2020-07-17 19:08:16,434 Worker flush took 118ms

2020-07-17 19:08:21,255 Flushing 1 items (from {Partition(topic=Topic(name='events'), index=11): Offsets(lo=71, hi=71)}): forced:False size:False time:True

Traceback (most recent call last):

  File "/usr/local/bin/snuba", line 11, in <module>

    load_entry_point('snuba', 'console_scripts', 'snuba')()

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__

    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main

    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke

    return callback(*args, **kwargs)

  File "/usr/src/snuba/snuba/cli/consumer.py", line 162, in consumer

    consumer.run()

  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 137, in run

    self._run_once()

  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 142, in _run_once

    self._flush()

  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 242, in _flush

    self.worker.flush_batch(self.__batch_results)

  File "/usr/src/snuba/snuba/consumer.py", line 109, in flush_batch

    self.__writer.write(inserts)

  File "/usr/src/snuba/snuba/clickhouse/http.py", line 84, in write

    raise ClickhouseError(int(code), message)

snuba.clickhouse.errors.ClickhouseError: [60] Table default.sentry_dist doesn't exist. (version 19.16.19.85 (official build))
```
Outcomes Consumer:
```
2020-07-17 19:09:06,207 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 21, Partition(topic=Topic(name='outcomes'), index=1): 11, Partition(topic=Topic(name='outcomes'), index=2): 1, Partition(topic=Topic(name='outcomes'), index=3): 9, Partition(topic=Topic(name='outcomes'), index=4): 2, Partition(topic=Topic(name='outcomes'), index=5): 7, Partition(topic=Topic(name='outcomes'), index=6): 7, Partition(topic=Topic(name='outcomes'), index=7): 32, Partition(topic=Topic(name='outcomes'), index=8): 5, Partition(topic=Topic(name='outcomes'), index=9): 10, Partition(topic=Topic(name='outcomes'), index=10): 11, Partition(topic=Topic(name='outcomes'), index=11): 10}

2020-07-17 19:09:09,779 Flushing 1 items (from {Partition(topic=Topic(name='outcomes'), index=8): Offsets(lo=5, hi=5)}): forced:False size:False time:True

Traceback (most recent call last):

  File "/usr/local/bin/snuba", line 11, in <module>

    load_entry_point('snuba', 'console_scripts', 'snuba')()

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__

    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main

    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke

    return callback(*args, **kwargs)

  File "/usr/src/snuba/snuba/cli/consumer.py", line 162, in consumer

    consumer.run()

  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 137, in run

    self._run_once()

  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 142, in _run_once

    self._flush()

  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 242, in _flush

    self.worker.flush_batch(self.__batch_results)

  File "/usr/src/snuba/snuba/consumer.py", line 109, in flush_batch

    self.__writer.write(inserts)

  File "/usr/src/snuba/snuba/clickhouse/http.py", line 84, in write

    raise ClickhouseError(int(code), message)

snuba.clickhouse.errors.ClickhouseError: [60] Table default.outcomes_raw_dist doesn't exist. (version 19.16.19.85 (official build))
```

I have custom values on the template, they are 
```
system:
  url: "xxxxxx"
  adminEmail: "xxxxxxx"
  secretKey: 'xxxxxxxx'
  public: false #  This should only be used if you’re installing Sentry behind your company’s firewall.

# Auth disabled because it'll be using Azure.
auth:
  register: false

# Don't want a user creating by default
user:
  create: false

## -- MICROSERVICE CONFIGURATION --
kafka:
  enabled: false

## This value is only used when kafka.enabled is set to false
externalKafka:
  host: "kafka-0.kafka-headless.databases.svc.cluster.local"
  port: 9092

redis:
  enabled: false

## This value is only used when redis.enabled is set to false
externalRedis:
  host: "redis-master.databases.svc.cluster.local"
  database: 4
  prefix: 'turret'
  port: 6379

postgresql:
  enabled: false

## This value is only used when postgresql.enabled is set to false
externalPostgresql:
  host: "xxxxxxxx"
  port: 0000
  username: "xxxx"
  password: "xxxxx"
  database: xxxxx
  # sslMode: require

rabbitmq:
  ## If disabled, Redis will be used instead as the broker.
  enabled: false

filestore:
  # Set to one of filesystem, gcs or s3 as supported by Sentry.
  backend: s3

  s3:
    accessKey: 'xxx'
    secretKey: 'xxxx'
    bucketName: xxx
    endpointUrl: 'xxxx'
    # signature_version:
    region_name: 'xxxxx'
    # default_acl:
```
I can provide any extra needed info.

Thanks,

**Comment by J0sh0nat0r** [comment]
@Yomanz Would you mind grabbing the output of the `clickhouse-init` job? It's responsible for creating the `*_dist` tables

**Comment by Yomanz** [comment]
> @Yomanz Would you mind grabbing the output of the `clickhouse-init` job? It's responsible for creating the `*_dist` tables

Apparently said job doesn't exist; that would make sense as to why it wasn't working, but why wouldn't it run?

Is there a "proper" way to run this job manually or do i need to just take apart the template

**Comment by J0sh0nat0r** [comment]
@Yomanz It's a hook that should run automatically and get cleaned up when running `helm install`. You could re-run the installation or create the job manually from the template, unfortunately I don't think there's native functionality in helm for streaming hook logs so you'll have to do that manually.

**Comment by Mokto** [comment]
@Yomanz is your issue fixed?

**Comment by Yomanz** [comment]
> @Yomanz is your issue fixed?

I manually migrated the DB from the template, thanks.
