### ISSUE TITLE
How to deal with this crashloop of  sentry-snuba-subscription-consumer-transactions

### ISSUE THREAD

**Issue by snowair** [sentry-kubernetes/charts#1190]
Chats:  sentry:21.5.0

Pod: sentry-snuba-subscription-consumer-transactions-8466c7c86bl89zb

Stauts: **CrashLoopBackOff**

Log: 

```
2024-03-28 08:33:47,780 Initializing Snuba...
2024-03-28 08:33:50,330 Snuba initialization took 2.5505821511615068s
{"module": "builtins", "event": "Checking Clickhouse connections", "severity": "info", "timestamp": "2024-03-28T08:33:50.340465Z"}
2024-03-28 08:33:50,416 New partitions assigned: {Partition(topic=Topic(name='snuba-transactions-commit-log'), index=0): 0, Partition(topic=Topic(name='snuba-transactions-commit-log'), index=1): 0, Partition(topic=Topic(name='snuba-transactions-commit-log'), index=2): 2157}
2024-03-28 08:35:00,194 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 319, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 407, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 275, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
                                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 1
2024-03-28 08:35:00,198 Closing ...
2024-03-28 08:35:00,199 Partitions to revoke: [Partition(topic=Topic(name='snuba-transactions-commit-log'), index=0), Partition(topic=Topic(name='snuba-transactions-commit-log'), index=1), Partition(topic=Topic(name='snuba-transactions-commit-log'), index=2)]
2024-03-28 08:35:00,199 Partition revocation complete.
2024-03-28 08:35:00,203 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in 
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 319, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 407, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 275, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
                                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 1
```

**Comment by rojinebrahimi** [comment]
Hello!
I have had the same problem and the solution was to add the partitioned topics to the configuration like so:
```
TOPIC_PARTITION_COUNTS = {
      "errors-replacements": 1,
      "event-replacements": 1,
      "events": 2,
      "ingest-attachments": 1,
      ...
      "outcomes": 2,
      "snuba-commit-log": 2,
    }

```
