### ISSUE TITLE
Sentry Helm Charts - SNUBA-MIGRATE-* pods connection to external clickhouse errors

### ISSUE THREAD

**Issue by piellick** [sentry-kubernetes/charts#1288]
Helm chart 23.1.0

Hi everyone , when i look this issue: https://github.com/sentry-kubernetes/charts/issues/812
it seems to problem still persist.

I try to configure an external clickhouse and i try many tricks :

```
externalClickhouse:
  ## Hostname or ip address of external clickhouse
  ##
  host: "clickhouse-clickhouse.sentry-clickhouse.svc.cluster.local"
  tcpPort: 9000
  httpPort: 8123
  # https://github.com/sentry-kubernetes/charts/issues/812
  username: sentry 
  password: sentry
  database: default
  singleNode: false
  # existingSecret: secret-name
  ## set existingSecretKey if key name inside existingSecret is different from 'postgres-password'
  # existingSecretKey: secret-key-name
  ## Cluster name, can be found in config
  ## (https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#server-settings-remote-servers)
  ## or by executing `select * from system.clusters`
  ##
  clusterName: default
```

but errors still appear on snuba-migrate-*  pods:

```
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 361, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 305, in disconnect_on_error
    self.establish_connection(settings)
  File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 292, in establish_connection
    self.connection.force_connect()
  File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/connection.py", line 254, in force_connect
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/connection.py", line 416, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Name or service not known (chi-clickhouse-default-0-0:9000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/cli/migrations.py", line 104, in migrate
    check_for_inactive_replicas(get_all_storage_keys(readiness_states=readiness_states))
  File "/usr/src/snuba/snuba/migrations/connect.py", line 182, in check_for_inactive_replicas
    tables_with_inactive = conn.execute(
                           ^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 255, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: Name or service not known (chi-clickhouse-default-0-0:9000)
```

Here is still a bug with user/password for snuba pods ?

Thanks a lot.

**Comment by piellick** [comment]
i dig a bit :

`sentry-snua-api `  **setting.py** configuration looks good, **ENV** are good too (sentry/sentry for login):
```
snuba@sentry-snuba-api-74bd8d8bfd-7lgpx:/usr/src/snuba$ cat /etc/snuba/settings.py 
import os

from snuba.settings import *

env = os.environ.get

DEBUG = env("DEBUG", "0").lower() in ("1", "true")

# Clickhouse Options
CLUSTERS = [
  {
    "host": env("CLICKHOUSE_HOST", "chi-clickhouse-default-0-0.sentry-clickhouse.svc.cluster.local"),
    "port": int(9000),
    "user":  env("CLICKHOUSE_USER", "default"),
    "password": env("CLICKHOUSE_PASSWORD", ""),
    "max_connections": int(os.environ.get("CLICKHOUSE_MAX_CONNECTIONS", 100)),
    "database": env("CLICKHOUSE_DATABASE", "default"),
    "http_port": 8123,
    "storage_sets": {
        "cdc",
        "discover",
        "events",
        "events_ro",
        "metrics",
        "metrics_summaries",
        "migrations",
        "outcomes",
        "querylog",
        "sessions",
        "transactions",
        "profiles",
        "functions",
        "replays",
        "generic_metrics_sets",
        "generic_metrics_distributions",
        "search_issues",
        "generic_metrics_counters",
        "spans",
        "group_attributes",
        "generic_metrics_gauges",
    },
    "single_node": False,
    "cluster_name": "default",
    "distributed_cluster_name": "default",
  },
]
```


And connection test from snuba-api pod to clickhouse works well using internal K8S DNS:

```
snuba@sentry-snuba-api-74bd8d8bfd-7lgpx:/usr/src/snuba$ curl --header "X-ClickHouse-User: sentry" --header "X-ClickHouse-Key: sentry"  'http://clickhouse-clickhouse.sentry-clickhouse.svc.cluster.local:8123/?database=default&query=SELECT%20version()'

24.4.1.2088
```

```
curl --header "X-ClickHouse-User: sentry" --header "X-ClickHouse-Key: sentry"  'http://chi-clickhouse-default-0-0.sentry-clickhouse.svc.cluster.local:8123/?database=default&query=SELECT%20version()'
24.4.1.2088
```

**Comment by piellick** [comment]
Ok,

in my case 
`clickhouse_driver.errors.NetworkError: Code: 210. Name or service not known (chi-clickhouse-default-0-0:9000)` came from :

```
externalClickhouse:
  singleNode: false
```

guys double-check singleNode value depending of your clickhouse configuration. In my case i had a single node.
