### ISSUE TITLE
Missing kafka topic config in kafka.provisioning.topics - monitors-clock-tick

### ISSUE THREAD

**Issue by azhelev** [sentry-kubernetes/charts#1364]
On a fresh install of sentry-23.11.0  the sentry-ingest-monitors pod is in a crash loop

```
15:29:01 [INFO] sentry: monitors.consumer.clock_tick (reference_datetime='2024-07-11 15:29:00+00:00')
Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/monitors/consumers/monitor_consumer.py", line 998, in process_batch
    try_monitor_clock_tick(ts, partition)
  File "/usr/src/sentry/src/sentry/monitors/clock_dispatch.py", line 155, in try_monitor_clock_tick
    _dispatch_tick(tick)
  File "/usr/src/sentry/src/sentry/monitors/clock_dispatch.py", line 70, in _dispatch_tick
    _clock_tick_producer.produce(ArroyoTopic(topic), payload)
  File "/usr/src/sentry/src/sentry/utils/arroyo_producer.py", line 36, in produce
    future = self._get().produce(destination, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/arroyo/backends/kafka/consumer.py", line 703, in produce
    produce(
cimpl.KafkaException: KafkaError{code=_UNKNOWN_TOPIC,val=-188,str="Unable to produce message: Local: Unknown topic"}
15:29:01 [ERROR] sentry.monitors.consumers.monitor_consumer: Failed to trigger monitor tasks
```

I'm using `kafka.provisioning.topics` to set up the kafka topics with my desired partition and replication factor, however `monitors-clock-tick` topic is not in the list.
I've manually created the topic which solved the crashes.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
