### ISSUE TITLE
Snuba ReplicaSet continue crashing

### ISSUE THREAD

**Issue by x-504** [sentry-kubernetes/charts#1387]
Hi there,

I have deployed Sentry in Kubernete susing the Helm chart provided on this repository. This has been working great.

Few days ago we had a Kubernetes node crash due a resource limitation. After that event the replicatset `snuba-generic-metrics-distributions-consumer` continues crashing with the following error:

```
024-08-14 14:32:14,569 Initializing Snuba...
2024-08-14 14:32:15,711 Snuba initialization took 1.1427529670036165s
2024-08-14 14:32:15,720 Consumer Starting
2024-08-14 14:32:15,720 Checking Clickhouse connections...
2024-08-14 14:32:15,730 Successfully connected to Clickhouse: cluster_name=sentry-clickhouse
2024-08-14 14:32:15,730 librdkafka log level: 6
2024-08-14 14:32:18,751 New partitions assigned: {Partition(topic=Topic(name='snuba-generic-metrics'), index=0): 11061}
2024-08-14 14:32:18,755 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 322, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 384, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/arroyo/backends/kafka/consumer.py", line 414, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 0)"}
``` 

It looks like the Kafka broker-0 offset is wrong for the Kafka topic `snuba-generic-metrics`.

Do you guys know how to handle this scenario?.

**Comment by zentavr** [comment]
@albertollamaso how had you fixed that?

**Comment by zentavr** [comment]
...I had to remove Kafka and it's volumes, run Kafka again and re-create all the topics with `sentry-kafka-provisioning` job, like:
```
kubectl get job sentry-kafka-provisioning -n sentry -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f -
```

**Comment by x-504** [comment]
Hi @zentavr 

I resolved by executing following steps:

1. You exec one of the Kafka pods like this `k exec -it sentry-kafka-controller-0 /bin/bash`

2. Check if there is a consumer for the topic in trouble:

```
kafka-consumer-groups.sh --bootstrap-server localhost:9092 --group snuba-gen-metrics-distributions-consumers --describe
```

3. If there is a consumer then get the HOST and identify the pod then scale down to 0

4. Then reset the offsets for the topic with something like this:
```
kafka-consumer-groups.sh --bootstrap-server localhost:9092 --group snuba-gen-metrics-distributions-consumers --reset-offsets --to-latest --execute --topic snuba-generic-metrics
```

5. Then scale the consumer back to 1 or the number it was before


Hope this helps!
