### ISSUE TITLE
[BUG] Sentry config Postgres password empty if no `postgresql.postgresqlPassword` is provided.

### ISSUE THREAD

**Issue by voslartomas** [sentry-kubernetes/charts#14]
Error: rpc error: code = Unknown desc = configmaps "sentry10-sentry" already exists

**Comment by voslartomas** [comment]
This happens every time I rerun sentry (when previously deleted I guess). So it's not cleaning up configmaps properly when you delete this chart.

**Comment by Mokto** [comment]
@DandyDeveloper Do you have this issue also?

I'm using helm template to deploy sentry (through pulumi), so I don't really have that issue.

**Comment by DandyDeveloper** [comment]
Yes I think my change to the hook fixes this. But snuba might still be a problem

**Comment by Mokto** [comment]
Thanks! @voslartomas could you confirm when you have time?

**Comment by voslartomas** [comment]
@Mokto 
Just tested new version and I can't even install it properly anymore :/

sentry-cron, sentry-web and sentry-worker
```
!! Configuration error: TypeError: unsupported operand type(s) for -: 'module' and 'module'
```

**Comment by DandyDeveloper** [comment]
> @Mokto 
> Just tested new version and I can't even install it properly anymore :/
> 
> sentry-cron, sentry-web and sentry-worker
> ```
> !! Configuration error: TypeError: unsupported operand type(s) for -: 'module' and 'module'
> ```
> 
> 

Is that the only error? Can you post the full log, please.

**Comment by voslartomas** [comment]
This is only thing inside logs.

**Comment by DandyDeveloper** [comment]
@voslartomas I might get a change to look at this today, looks like it's the sentry.conf or yaml is rendering wrong. 

You're not appending any configuration are you?

**Comment by DandyDeveloper** [comment]
@voslartomas https://github.com/sentry-kubernetes/charts/pull/39

Fixed. See PR.

**Comment by Mokto** [comment]
@voslartomas could you try again ? 0.11.0 should fix everything ;)

**Comment by voslartomas** [comment]
Almost there, now I am stuck at

<img width="838" alt="Screenshot 2020-04-06 at 15 17 25" src="https://user-images.githubusercontent.com/1945040/78562518-ca31d380-7819-11ea-951c-e888b8a32566.png">

```
Warning  FailedMount  34s (x7 over 14m)  kubelet, ip-172-20-63-223.ec2.internal  Unable to mount volumes for pod "sentry-kafka-0_kube-system(9863892c-7806-11ea-93c6-0a149c9bb14d)": timeout expired waiting for volumes to attach or mount for pod "kube-system"/"sentry-kafka-0". list of unmounted volumes=[data]. list of unattached volumes=[data scripts sentry-kafka-token-qmhn7]
```

**Comment by voslartomas** [comment]
Sry, it just took a while, now it works.

**Comment by voslartomas** [comment]
But I am getting this in browser :/

/auth/login/

<img width="278" alt="Screenshot 2020-04-06 at 15 34 23" src="https://user-images.githubusercontent.com/1945040/78564015-2138a800-781c-11ea-88f6-3cdbd81ebdd2.png">

```
13:41:57 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/excepthook.py", line 59, in sentry_sdk_excepthook
    hub.capture_event(event, hint=hint)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/hub.py", line 323, in capture_event
    rv = client.capture_event(event, hint, scope)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/client.py", line 317, in capture_event
    event_opt = self._prepare_event(event, hint, scope)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/client.py", line 151, in _prepare_event
    event_ = scope.apply_to_event(event, hint)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/scope.py", line 57, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/scope.py", line 328, in apply_to_event
    return _drop(event, event_processor, "event processor")
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/scope.py", line 283, in _drop
    logger.info("%s (%s) dropped event (%s)", ty, cause, event)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1174, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/logging.py", line 77, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/site-packages/sentry/logging/handlers.py", line 98, in emit
    logger.log(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../structlog/stdlib.py", line 102, in log
    return self._proxy_to_logger(_LEVEL_TO_NAME[level], event, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/sentry/../structlog/stdlib.py", line 119, in _proxy_to_logger
    **event_kw)
  File "/usr/local/lib/python2.7/site-packages/sentry/../structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/usr/local/lib/python2.7/site-packages/sentry/../structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/usr/local/lib/python2.7/site-packages/sentry/../structlog/stdlib.py", line 275, in __call__
    event_dict['event'] = event_dict['event'] % args
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 226, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 887, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 99, in _cursor
    cursor = super(DatabaseWrapper, self)._cursor()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: fe_sendauth: no password supplied
```

**Comment by yeouchien** [comment]
I am getting similar error `OperationalError: fe_sendauth: no password supplied` for a fresh `helm install` in `sentry-db-init` job

**Comment by Mokto** [comment]
Could you shared your overridden values.yaml?
Thanks

**Comment by DandyDeveloper** [comment]
Looks like postgres isn't configured with the password for some reason. You sure you all deleted the old PVCs before installing?

Also, check a postgres secret exists and exec into your postgres container and check that the password in the environment variable matches the secret.

**Comment by yeouchien** [comment]
Yes, deleted PVC before installing. This is my `sentry-sentry-postgresql` secret
```
kubectl get secret sentry-sentry-postgresql -o 'go-template={{index .data "postgresql-password"}}' | base64 -D
LLSSl8sPhl
```

```
kubectl exec -it sentry-sentry-postgresql-0 -- bash
$ env
...
POSTGRES_PASSWORD=LLSSl8sPhl
...
```

they matches.

**Comment by voslartomas** [comment]
```
prefix: sentry10

service:
  name: sentry
  type: ClusterIP

mail:
  backend: 'smtp'
  port: 587
  username: 'email'
  password: 'pass'
  use-tls: true
  from: 'email'
  host: 'smtp.gmail.com'

filestore:
  backend: s3
  s3:
    accessKey: key
    secretKey: key
    bucketName: staging-sentry
    region_name: us-east-1

ingress:
  enabled: true

  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: 50m

  hostname: sentry.domain.com

  tls:
  - secretName: sentry10-staging
    hosts:
    - sentry.dmoain.com

```

**Comment by Mokto** [comment]
Guys could you please share the ConfigMap with the 2 sentry configuration files ?

There should be an issue where Postgres is defined in Sentry.

Thanks!

**Comment by voslartomas** [comment]
Not sure which one you need exactly. And you are saying you're not able to reproduce this issue??
```
❯ kubectl get configmap sentry-sentry -n kube-system -o yaml
apiVersion: v1
data:
  config.yml: |-
    system.secret-key: icLq77rCyY_qrMMpXa6TQNjkDV6mU!c

    symbolicator.enabled: false
    symbolicator.options:
      url: "http://sentry-symbolicator:3021"

    mail.backend: "smtp"
    mail.use-tls: false
    mail.username: ""
    mail.password: ""
    mail.port: 587
    mail.host: "smtp.gmail.com"
    mail.from: ""

    ################
    #    Redis     #
    ################
    redis.clusters:
      default:
        hosts:
          0:
            host: "sentry-sentry-redis-master"
            port: 6379

    ################
    # File storage #
    ################
    # Uploaded media uses these `filestore` settings. The available
    # backends are either `filesystem` or `s3`.
    filestore.backend: 's3'
    filestore.options:
      access_key: ''
      secret_key: ''
      bucket_name: 'staging-sentry'
      region_name: 'us-east-1'


    # No YAML Extension Config Given
  sentry.conf.py: "from sentry.conf.server import *  # NOQA\n\nDATABASES = {\n    \"default\":
    {\n        \"ENGINE\": \"sentry.db.postgres\",\n        \"NAME\": \"sentry\",\n
    \       \"USER\": \"postgres\",\n        \"PASSWORD\": \"\",\n        \"HOST\":
    \"sentry-sentry-postgresql\",\n        \"PORT\": \"5432\",\n    }\n}\n\n# You
    should not change this setting after your database has been created\n# unless
    you have altered all schemas first\nSENTRY_USE_BIG_INTS = True\n\n###########\n#
    General #\n###########\n\n# Instruct Sentry that this install intends to be run
    by a single organization\n# and thus various UI optimizations should be enabled.\nSENTRY_SINGLE_ORGANIZATION
    = True\n\nSENTRY_OPTIONS[\"system.event-retention-days\"] = env('SENTRY_EVENT_RETENTION_DAYS')
    or 90\n\n#########\n# Queue #\n#########\n\n# See https://docs.getsentry.com/on-premise/server/queue/
    for more\n# information on configuring your queue broker and workers. Sentry relies\n#
    on a Python framework called Celery to manage queues.\nBROKER_URL = os.environ.get(\"BROKER_URL\",
    \"amqp://guest:guest@sentry-rabbitmq:5672//\")\n  \n#########\n# Cache #\n#########\n\n#
    Sentry currently utilizes two separate mechanisms. While CACHES is not a\n# requirement,
    it will optimize several high throughput patterns.\n\n# CACHES = {\n#     \"default\":
    {\n#         \"BACKEND\": \"django.core.cache.backends.memcached.MemcachedCache\",\n#
    \        \"LOCATION\": [\"memcached:11211\"],\n#         \"TIMEOUT\": 3600,\n#
    \    }\n# }\n\n# A primary cache is required for things such as processing events\nSENTRY_CACHE
    = \"sentry.cache.redis.RedisCache\"\n\nDEFAULT_KAFKA_OPTIONS = {\n    \"bootstrap.servers\":
    \"sentry-kafka:9092\",\n    \"message.max.bytes\": 50000000,\n    \"socket.timeout.ms\":
    1000,\n}\n\nSENTRY_EVENTSTREAM = \"sentry.eventstream.kafka.KafkaEventStream\"\nSENTRY_EVENTSTREAM_OPTIONS
    = {\"producer_configuration\": DEFAULT_KAFKA_OPTIONS}\n\nKAFKA_CLUSTERS[\"default\"]
    = DEFAULT_KAFKA_OPTIONS\n\n###############\n# Rate Limits #\n###############\n\n#
    Rate limits apply to notification handlers and are enforced per-project\n# automatically.\n\nSENTRY_RATELIMITER
    = \"sentry.ratelimits.redis.RedisRateLimiter\"\n\n##################\n# Update
    Buffers #\n##################\n\n# Buffers (combined with queueing) act as an
    intermediate layer between the\n# database and the storage API. They will greatly
    improve efficiency on large\n# numbers of the same events being sent to the API
    in a short amount of time.\n# (read: if you send any kind of real data to Sentry,
    you should enable buffers)\n\nSENTRY_BUFFER = \"sentry.buffer.redis.RedisBuffer\"\n\n##########\n#
    Quotas #\n##########\n\n# Quotas allow you to rate limit individual projects or
    the Sentry install as\n# a whole.\n\nSENTRY_QUOTAS = \"sentry.quotas.redis.RedisQuota\"\n\n########\n#
    TSDB #\n########\n\n# The TSDB is used for building charts as well as making things
    like per-rate\n# alerts possible.\n\nSENTRY_TSDB = \"sentry.tsdb.redissnuba.RedisSnubaTSDB\"\n\n#########\n#
    SNUBA #\n#########\n\nSENTRY_SEARCH = \"sentry.search.snuba.EventsDatasetSnubaSearchBackend\"\nSENTRY_SEARCH_OPTIONS
    = {}\nSENTRY_TAGSTORE_OPTIONS = {}\n\n###########\n# Digests #\n###########\n\n#
    The digest backend powers notification summaries.\n\nSENTRY_DIGESTS = \"sentry.digests.backends.redis.RedisBackend\"\n\n##############\n#
    Web Server #\n##############\n\nSENTRY_WEB_HOST = \"0.0.0.0\"\nSENTRY_WEB_PORT
    = 9000\nSENTRY_PUBLIC = False\nSENTRY_WEB_OPTIONS = {\n    \"http\": \"%s:%s\"
    % (SENTRY_WEB_HOST, SENTRY_WEB_PORT),\n    \"protocol\": \"uwsgi\",\n    # This
    is needed to prevent https://git.io/fj7Lw\n    \"uwsgi-socket\": None,\n    \"http-keepalive\":
    True,\n    \"memory-report\": False,\n    # 'workers': 3,  # the number of web
    workers\n}\n\n###########\n# SSL/TLS #\n###########\n\n# If you're using a reverse
    SSL proxy, you should enable the X-Forwarded-Proto\n# header and enable the settings
    below\n\n# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')\n# SESSION_COOKIE_SECURE
    = True\n# CSRF_COOKIE_SECURE = True\n# SOCIAL_AUTH_REDIRECT_IS_HTTPS = True\n\n#
    End of SSL/TLS settings\n\n############\n# Features #\n############\n\n\nSENTRY_FEATURES
    = {\n  \"auth:register\": True\n}\nSENTRY_FEATURES[\"projects:sample-events\"]
    = False\nSENTRY_FEATURES.update(\n    {\n        feature: True\n        for feature
    in (\n            \"organizations:discover\",\n            \"organizations:events\",\n
    \           \"organizations:global-views\",\n            \"organizations:integrations-issue-basic\",\n
    \           \"organizations:integrations-issue-sync\",\n            \"organizations:invite-members\",\n
    \           \"organizations:new-issue-ui\",\n            \"organizations:repos\",\n
    \           \"organizations:require-2fa\",\n            \"organizations:sentry10\",\n
    \           \"organizations:sso-basic\",\n            \"organizations:sso-rippling\",\n
    \           \"organizations:sso-saml2\",\n            \"organizations:suggested-commits\",\n
    \           \"projects:custom-inbound-filters\",\n            \"projects:data-forwarding\",\n
    \           \"projects:discard-groups\",\n            \"projects:plugins\",\n
    \           \"projects:rate-limits\",\n            \"projects:servicehooks\",\n
    \       )\n    }\n)\n\n\n######################\n# GitHub Integration #\n#####################\n\nGITHUB_APP_ID
    = ''\nGITHUB_API_SECRET = ''\n\n#########################\n# Bitbucket Integration
    #\n########################\n\n# BITBUCKET_CONSUMER_KEY = 'YOUR_BITBUCKET_CONSUMER_KEY'\n#
    BITBUCKET_CONSUMER_SECRET = 'YOUR_BITBUCKET_CONSUMER_SECRET'\n\n# No Python Extension
    Config Given"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-06T13:00:04Z"
  labels:
    app: sentry
    chart: sentry-0.11.0
    heritage: Tiller
    release: sentry
  name: sentry-sentry
  namespace: kube-system
  resourceVersion: "47567988"
  selfLink: /api/v1/namespaces/kube-system/configmaps/sentry-sentry
  uid: 88dadf27-7806-11ea-93c6-0a149c9bb14d
```

**Comment by DandyDeveloper** [comment]
@voslartomas 

```
\"USER\": \"postgres\",\n        \"PASSWORD\": \"\",
```

Yep, this is a problem we need to solve. 

To explain the problem: Due to postgresql being a dependency, we have no way of obtaining the rendered password (randomly generated) and inserting it into this config template. 

Right now, we need people to pass the `postgresql.postgresqlPassword` parameter in order to render this field. 

**This is a bug**

@Mokto We should update the templates:

sentry.conf:
- Use an environment variable

Sentry Deployments (web, worker, etc): 
- Reference the secret key in the `sentry-sentry-postgresql` to populate the above environment variable

**Comment by DandyDeveloper** [comment]
@voslartomas @yeouchien Pending merge of #49. This should solve your problems.

**Comment by Mokto** [comment]
0.11.1 should fix this. 

Thanks for your feedbacks

**Comment by yeouchien** [comment]
thanks, it works in latest release `0.12.1`
