### ISSUE TITLE
Gibberish keys in kafka outcomes topic

### ISSUE THREAD

**Issue by cyxou** [sentry-kubernetes/charts#1421]
Hi! Fresh sentry installation here:
 - chart version 25.2.1 (appVersion: 24.5.1)

No sentry clients configured yet but I've noticed that `sentry-snuba-outcomes-consumer` service started to constantly being crashed with the following errors:

```txt
2024-09-05 07:23:40,416 Initializing Snuba...
2024-09-05 07:23:42,061 Snuba initialization took 1.6458920589993795s
2024-09-05 07:23:42,072 Consumer Starting
2024-09-05 07:23:42,072 Checking Clickhouse connections...
{"module": "snuba.migrations.connect", "event": "Snuba has only been tested on Clickhouse versions up to 23.8.11.29 (clickhouse-service:9000 - 23.8.16.40). Higher versions might not be supported.", "severity": "warning", "timestamp": "2024-09-05T07:23:42.166274Z"}
2024-09-05 07:23:42,167 Successfully connected to Clickhouse: cluster_name=None
2024-09-05 07:23:42,167 librdkafka log level: 6
2024-09-05 07:23:43,935 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 411}
2024-09-05 07:23:44,003 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/stdlib.py", line 128, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1390, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 322, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 396, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/healthcheck.py", line 32, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/reduce.py", line 101, in poll
    self.__buffer_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/buffer.py", line 169, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 135, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 300, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 136, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 359, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 243, in join
    response = self._result.result(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/stdlib.py", line 128, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1390, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-09-05 07:23:44,020 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f3b73d95a50>...
2024-09-05 07:23:44,020 Partitions to revoke: [Partition(topic=Topic(name='outcomes'), index=0)]
2024-09-05 07:23:44,021 Partition revocation complete.
2024-09-05 07:23:44,027 Processor terminated
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/stdlib.py", line 128, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1390, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/cli/consumer.py", line 279, in consumer
    consumer.run()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 322, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 396, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/healthcheck.py", line 32, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/reduce.py", line 101, in poll
    self.__buffer_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/buffer.py", line 169, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 135, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 300, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 136, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 359, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 243, in join
    response = self._result.result(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/stdlib.py", line 128, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1390, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

Having investigated a bit I've noticed messages with weird keys in kafka `outcomes` topic:

![image](https://github.com/user-attachments/assets/3841fd9d-ed09-4210-b656-29b746bbd0f2)

When I clear all messages in that topic, the `sentry-snuba-outcomes-consumer` service stops crashing. But in a while or so a new portion of those weird messages got populated and the service starts crashing again.

Can anybody shed some light on this? Are those `outcomes` messages meant to look like these?

Kind regards

**Comment by patsevanton** [comment]
Hello! Please put values.yaml for reproduce issue.

**Comment by cyxou** [comment]
The values are pretty much default with few overrides:

```yaml
user:
  create: true
  email: admin@sentry.local
  password: shhhhhhhhhhhh

system:
  url: "https://sentry.local"
  adminEmail: admin@sentry.local

auth:
  register: false

sourcemaps:
  # If you want sourcemaps, then memcached needs to be provisioned
  enabled: false
```

**Comment by patsevanton** [comment]
I do not confirm the issue on latest tag:
```
stern -n test -l role=snuba-outcomes-consumer
+ sentry-snuba-outcomes-consumer-6c4bf67d4b-dznzq › sentry-snuba
sentry-snuba-outcomes-consumer-6c4bf67d4b-dznzq sentry-snuba 2024-09-06 15:22:38,590 Initializing Snuba...
sentry-snuba-outcomes-consumer-6c4bf67d4b-dznzq sentry-snuba 2024-09-06 15:22:40,349 Snuba initialization took 1.7600593569950433s
sentry-snuba-outcomes-consumer-6c4bf67d4b-dznzq sentry-snuba 2024-09-06 15:22:40,361 Consumer Starting
sentry-snuba-outcomes-consumer-6c4bf67d4b-dznzq sentry-snuba 2024-09-06 15:22:40,361 Checking Clickhouse connections...
sentry-snuba-outcomes-consumer-6c4bf67d4b-dznzq sentry-snuba 2024-09-06 15:22:40,371 Successfully connected to Clickhouse: cluster_name=sentry-clickhouse
sentry-snuba-outcomes-consumer-6c4bf67d4b-dznzq sentry-snuba 2024-09-06 15:22:40,372 librdkafka log level: 6
sentry-snuba-outcomes-consumer-6c4bf67d4b-dznzq sentry-snuba 2024-09-06 15:22:41,611 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 0}
```

Write full instruction for reproduce issue

**Comment by patsevanton** [comment]
is the error still reproducing?

**Comment by cyxou** [comment]
Hi @patsevanton! If we are talking about gibberish, yes it's still there with latest chart installation. But I think I was wrong regarding failures in `sentry-snuba-outcomes-consumer` service. It was failing due to a different reason... not the gibberish keys in outcomes topic keys. I think we may close this one for now.

**Comment by patsevanton** [comment]
I cannot close issue. You can close issue
