### ISSUE TITLE
[ERROR] tasks.store.symbolicate_event.symbolication when symbolicator.enabled: false

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#1452]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

```
sentry-worker-59566f4cb5-l4xql sentry-worker urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=3021): Max retries exceeded with url: /symbolicate-js?timeout=5&scope=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b577df7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
sentry-worker-59566f4cb5-l4xql sentry-worker 
sentry-worker-59566f4cb5-l4xql sentry-worker During handling of the above exception, another exception occurred:
sentry-worker-59566f4cb5-l4xql sentry-worker 
sentry-worker-59566f4cb5-l4xql sentry-worker Traceback (most recent call last):
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/usr/src/sentry/src/sentry/tasks/symbolication.py", line 289, in _do_symbolicate_event
sentry-worker-59566f4cb5-l4xql sentry-worker     symbolicated_data = symbolication_function(symbolicator, data)
sentry-worker-59566f4cb5-l4xql sentry-worker                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/usr/src/sentry/src/sentry/lang/javascript/processing.py", line 242, in process_js_stacktraces
sentry-worker-59566f4cb5-l4xql sentry-worker     response = symbolicator.process_js(
sentry-worker-59566f4cb5-l4xql sentry-worker                ^^^^^^^^^^^^^^^^^^^^^^^^
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/usr/src/sentry/src/sentry/lang/native/symbolicator.py", line 236, in process_js
sentry-worker-59566f4cb5-l4xql sentry-worker     return self._process("symbolicate_js_stacktraces", "symbolicate-js", json=json)
sentry-worker-59566f4cb5-l4xql sentry-worker            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/usr/src/sentry/src/sentry/lang/native/symbolicator.py", line 125, in _process
sentry-worker-59566f4cb5-l4xql sentry-worker     json_response = session.create_task(path, **kwargs)
sentry-worker-59566f4cb5-l4xql sentry-worker                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/usr/src/sentry/src/sentry/lang/native/symbolicator.py", line 407, in create_task
sentry-worker-59566f4cb5-l4xql sentry-worker     return self._request(method="post", path=path, params=params, **kwargs)
sentry-worker-59566f4cb5-l4xql sentry-worker            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/usr/src/sentry/src/sentry/lang/native/symbolicator.py", line 341, in _request
sentry-worker-59566f4cb5-l4xql sentry-worker     response = self.session.request(method, url, timeout=self.timeout + 1, **kwargs)
sentry-worker-59566f4cb5-l4xql sentry-worker                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/usr/src/sentry/src/sentry/net/http.py", line 194, in request
sentry-worker-59566f4cb5-l4xql sentry-worker     response = _Session.request(self, *args, **kwargs)
sentry-worker-59566f4cb5-l4xql sentry-worker                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/.venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
sentry-worker-59566f4cb5-l4xql sentry-worker     resp = self.send(prep, **send_kwargs)
sentry-worker-59566f4cb5-l4xql sentry-worker            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/.venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
sentry-worker-59566f4cb5-l4xql sentry-worker     r = adapter.send(request, **kwargs)
sentry-worker-59566f4cb5-l4xql sentry-worker         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-worker-59566f4cb5-l4xql sentry-worker   File "/.venv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
sentry-worker-59566f4cb5-l4xql sentry-worker     raise ConnectionError(e, request=request)
sentry-worker-59566f4cb5-l4xql sentry-worker requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=3021): Max retries exceeded with url: /symbolicate-js?timeout=5&scope=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b577df7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
sentry-worker-59566f4cb5-l4xql sentry-worker 15:25:10 [ERROR] sentry.errors.events: tasks.store.symbolicate_event.symbolication
```

### Expected behavior

```
No errors
```

### values.yaml

```
user:
  password: "xxxxxxxxxxxxxxxxxxxxxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
#nginx:
#  enabled: false
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
  regexPathStyle: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    # https://github.com/getsentry/self-hosted/issues/1927
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
hooks:
  activeDeadlineSeconds: 600
```

### Helm chart version

```
sentry-25.5.0
```

### Steps to reproduce

```
helm install -n test sentry sentry/sentry --wait --timeout=1000s --values values-test.yaml

wait 12h
```

### Additional context

```
k get configmaps -n test sentry-sentry -o yaml | grep symbolic
    # See https://getsentry.github.io/symbolicator/api/
    symbolicator.enabled: false
```

**Comment by patsevanton** [comment]
Fixed by values:
```
symbolicator:
  enabled: true
```
