### ISSUE TITLE
sentry-snuba-subscription pod terminated

### ISSUE THREAD

**Issue by cataglyphis** [sentry-kubernetes/charts#1498]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

we deploy sentry successfully, but 3 pods can not start.
- sentry-snuba-subscription-consumer-events
- sentry-snuba-subscription-consumer-metrics
- sentry-snuba-subscription-consumer-transactions

### values.yaml

null

### Helm chart version

- chart: 25.8.1
- app: 24.7.1

### Steps to reproduce

- deploy sentry with chart version 25.8.1

### Logs

2024-09-30 11:02:40,838 Initializing Snuba...
2024-09-30 11:02:41,985 Snuba initialization took 1.147067103000154s
{"module": "builtins", "event": "Checking Clickhouse connections", "severity": "info", "timestamp": "2024-09-30T11:02:41.994856Z"}
2024-09-30 11:02:45,062 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 0}
2024-09-30T19:02:45.064542371+08:00 2024-09-30 11:02:45,063 Caught exception, shutting down...
Traceback (most recent call last):
2024-09-30T19:02:45.064552648+08:00   File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 322, in run
2024-09-30T19:02:45.064557973+08:00     self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 410, in _run_once
2024-09-30T19:02:45.064566005+08:00     self.__processing_strategy.submit(message)
2024-09-30T19:02:45.064569219+08:00   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
2024-09-30T19:02:45.064574594+08:00   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 275, in submit
2024-09-30T19:02:45.064578873+08:00     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
                                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
2024-09-30T19:02:45.064585464+08:00 KeyError: 2
2024-09-30T19:02:45.066749293+08:00 2024-09-30 11:02:45,066 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7fdaa4260b10>...
2024-09-30 11:02:45,067 Partitions to revoke: [Partition(topic=Topic(name='snuba-commit-log'), index=0)]
2024-09-30T19:02:45.067936014+08:00 2024-09-30 11:02:45,067 Partition revocation complete.
2024-09-30T19:02:45.071949551+08:00 2024-09-30 11:02:45,071 Processor terminated
2024-09-30T19:02:45.098894452+08:00 Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
2024-09-30T19:02:45.098954656+08:00     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
2024-09-30T19:02:45.099243188+08:00              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
2024-09-30T19:02:45.099444255+08:00     return self.main(*args, **kwargs)
2024-09-30T19:02:45.099612172+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
2024-09-30T19:02:45.099773145+08:00     rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
2024-09-30T19:02:45.099908165+08:00   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
2024-09-30T19:02:45.100138400+08:00     return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-30T19:02:45.100399074+08:00   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
2024-09-30T19:02:45.100799634+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-30T19:02:45.100811770+08:00   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
2024-09-30T19:02:45.101119792+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-30T19:02:45.101131556+08:00   File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
2024-09-30T19:02:45.101209350+08:00   File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 322, in run
2024-09-30T19:02:45.101267346+08:00     self._run_once()
2024-09-30T19:02:45.101282974+08:00   File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 410, in _run_once
2024-09-30T19:02:45.101366633+08:00     self.__processing_strategy.submit(message)
2024-09-30T19:02:45.101379023+08:00   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
2024-09-30T19:02:45.101462676+08:00   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 275, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
2024-09-30T19:02:45.101813087+08:00                                    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
2024-09-30T19:02:45.101836494+08:00 KeyError: 2

### Additional context

_No response_

**Comment by cataglyphis** [comment]
only this 3 pods can not start...
sentry-snuba-subscription-consumer-events-74f54b866f-dhsdp        0/1     Error     2 (22s ago)   64s
sentry-snuba-subscription-consumer-metrics-796b48868-7bx99        0/1     Error     3 (33s ago)   64s
sentry-snuba-subscription-consumer-transactions-84fb6b46899lrdq   0/1     Error     2 (22s ago)   63s

**Comment by cataglyphis** [comment]
add TOPIC_PARTITION_COUNT config, fix this issue
