### ISSUE TITLE
Chart Doesnt Deploy?

### ISSUE THREAD

**Issue by jseiser** [sentry-kubernetes/charts#150]
Relay - This never comes up
```
2020-08-14T15:26:57Z [relay::setup] INFO: launching relay from config folder /work/.relay
2020-08-14T15:26:57Z [relay::setup] INFO:   relay mode: managed
2020-08-14T15:26:57Z [relay::setup] INFO:   relay id: f2964100-c31d-4b60-a97b-9457ca55fab1
2020-08-14T15:26:57Z [relay::setup] INFO:   public key: yauMdUAvLSsuk4fQleyB8tSU7j57KXMu2IFftn5dch0
2020-08-14T15:26:57Z [relay::setup] INFO:   log level: INFO
2020-08-14T15:26:57Z [relay_server::actors::upstream] INFO: upstream relay started
2020-08-14T15:26:57Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:26:57Z [relay_server::actors::outcome::processing] INFO: OutcomeProducer started.
2020-08-14T15:26:57Z [relay_server::actors::events] INFO: starting 1 event processing workers
2020-08-14T15:26:57Z [relay_server::actors::store] INFO: store forwarder started
2020-08-14T15:26:57Z [relay_server::service] INFO: spawning http server
2020-08-14T15:26:57Z [relay_server::service] INFO:   listening on: http://0.0.0.0:3000/
2020-08-14T15:26:57Z [actix_net::server::server] INFO: Starting 1 workers
2020-08-14T15:26:57Z [relay_server::actors::project_redis] INFO: redis project cache started
2020-08-14T15:26:57Z [actix_net::server::server] INFO: Starting server on 0.0.0.0:3000
2020-08-14T15:26:57Z [relay_server::actors::controller] INFO: relay server starting
2020-08-14T15:26:57Z [relay_server::actors::connector] INFO: metered connector started
2020-08-14T15:26:57Z [relay_server::actors::events] INFO: event manager started
2020-08-14T15:26:57Z [relay_server::actors::project_local] INFO: project local cache started
2020-08-14T15:26:57Z [relay_server::actors::project_upstream] INFO: project upstream cache started
2020-08-14T15:26:57Z [relay_server::actors::project_cache] INFO: project cache started
2020-08-14T15:26:57Z [relay_server::actors::project_keys] INFO: project cache started
2020-08-14T15:26:57Z [relay_server::actors::relays] INFO: key cache started
2020-08-14T15:26:57Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:26:57Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:26:57Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:26:58Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:26:58Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:27:00Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:27:00Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:27:02Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:27:02Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:27:05Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:27:05Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:27:10Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:27:10Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:27:18Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:27:18Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:27:30Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:27:30Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:27:47Z [relay_server::actors::upstream] INFO: registering with upstream (http://core-sentryops-web:9000/)
2020-08-14T15:27:47Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 500 Internal Server Error
2020-08-14T15:27:56Z [relay_server::actors::controller] INFO: SIGTERM received, stopping in 10s
2020-08-14T15:27:56Z [actix_net::server::worker] INFO: Shutting down worker, 0 connections
```

Web - Shows running
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 135, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 252, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/relay_register.py", line 102, in post
    relay = Relay.objects.get(relay_id=relay_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: UndefinedTable('relation "sentry_relay" does not exist\nLINE 1: ...y"."last_seen", "sentry_relay"."is_internal" FROM "sentry_re...\n                                                             ^\n',)
SQL: SELECT "sentry_relay"."id", "sentry_relay"."relay_id", "sentry_relay"."public_key", "sentry_relay"."first_seen", "sentry_relay"."last_seen", "sentry_relay"."is_internal" FROM "sentry_relay" WHERE "sentry_relay"."relay_id" = %s
10.110.33.93 - - [14/Aug/2020:15:26:15 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 500 605 "-" "actix-web/0.7.19"
10.110.38.94 - - [14/Aug/2020:15:26:20 +0000] "GET /_health/ HTTP/1.1" 200 203 "-" "kube-probe/1.17+"
10.110.38.94 - - [14/Aug/2020:15:26:20 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.17+"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 135, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 252, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/relay_register.py", line 102, in post
    relay = Relay.objects.get(relay_id=relay_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: UndefinedTable('relation "sentry_relay" does not exist\nLINE 1: ...y"."last_seen", "sentry_relay"."is_internal" FROM "sentry_re...\n                                                             ^\n',)
SQL: SELECT "sentry_relay"."id", "sentry_relay"."relay_id", "sentry_relay"."public_key", "sentry_relay"."first_seen", "sentry_relay"."last_seen", "sentry_relay"."is_internal" FROM "sentry_relay" WHERE "sentry_relay"."relay_id" = %s
```

Chart version: 5.0.0
Deployed onto EKS

I've set

```
user.email
user.password
system.url
system.adminEmail
system.public
system.secretKey
mail.backend
mail.host
mail.port
ingress.enabled
ingress.hostname
nginx.enabled: false
filestore.backend
filestore.s3.accessKey
filestore.s3.secretKey
filestore.s3.bucketName
filestore.s3.region_name
metrics.enabled
metrics.serviceMonitor.enabled
metrics.serviceMonitor.namespace
postgresql.postgresqlPassword
postgresql.persistence.size
```

**Comment by jseiser** [comment]
Database contains errors as well

```
postgresql 15:24:56.34 INFO  ==> ** Starting PostgreSQL **
2020-08-14 15:24:56.380 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-08-14 15:24:56.380 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2020-08-14 15:24:56.386 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-08-14 15:24:56.403 GMT [208] LOG:  database system was shut down at 2020-08-14 15:24:55 GMT
2020-08-14 15:24:56.413 GMT [1] LOG:  database system is ready to accept connections
2020-08-14 15:25:55.670 GMT [273] ERROR:  relation "sentry_option" does not exist at character 114
2020-08-14 15:25:55.670 GMT [273] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."key" = 'github.apps-install-url'
2020-08-14 15:25:55.852 GMT [273] ERROR:  relation "sentry_option" does not exist at character 114
```

This goes on and on.

**Comment by jseiser** [comment]
None of the jobs appear to exist/run either.

**Comment by jseiser** [comment]
Disabling relay allows everything to come up.

**Comment by jseiser** [comment]
Starting the relay, AFTER everything else appears to work.  

Closing out.
