### ISSUE TITLE
sentry-db-init failing

### ISSUE THREAD

**Issue by swade1987** [sentry-kubernetes/charts#1503]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

I am trying to upgrade from `v23.3.1-1` to `sentry:v24.7.1-2` and hit the following issue

### Expected behavior

The migration should run as expected and continue

### values.yaml

N/A

### Helm chart version

v25.9.0

### Steps to reproduce

1. Migrate existing Postgres database data to a new Postgres cluster
2. Deploy a fresh, new v25.9.0 of the chart pointing at the new postgres cluster

### Logs

Running migrations for default
Operations to perform:
  Apply all migrations: auth, contenttypes, feedback, hybridcloud, nodestore, remote_subscriptions, replays, sentry, sessions, sites, social_auth, uptime
Traceback (most recent call last):
  File "/.venv/bin/sentry", line 4, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/usr/src/sentry/src/sentry/runner/main.py", line 149, in main
    func(**kwargs)
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/decorators.py", line 35, in inner
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/commands/upgrade.py", line 148, in upgrade
    _upgrade(
  File "/usr/src/sentry/src/sentry/runner/commands/upgrade.py", line 64, in _upgrade
    dj_call_command(
  File "/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 302, in handle
    pre_migrate_apps = pre_migrate_state.apps
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/db/migrations/state.py", line 566, in apps
    return StateApps(self.real_apps, self.models)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/db/migrations/state.py", line 637, in __init__
    raise ValueError("\n".join(error.msg for error in errors))
ValueError: The field social_auth.UserSocialAuth.user was declared with a lazy reference to 'sentry.user', but app 'sentry' isn't installed.

**Comment by xvilo** [comment]
You can not always upgrade from version X to version Z, I think I had the same issue when trying something like this. 

You have to upgrade to these (in between versions) to get to the latest one:
- 9.1.2
- 21.5.0
- 21.6.3
- 23.6.2
- 23.11.0
- 24.8.0

Since you're from 23.3 and want to go to 24.7.1 you need to first upgrade from 23.3 to 23.6.2 then to 23.11.0, then to 24.8.0 and then to 24.7.1. 

Not all chart versions satisfy the specific sentry versions required, but I opted to deploy the version that was closest to the list above and then overriding the image tag to hit the specific version listed above.  More info about Sentry Hard Stops is here: https://develop.sentry.dev/self-hosted/releases/#hard-stops 

Good luck!

**Comment by swade1987** [comment]
@xvilo Thanks for the heads up! It seems the best approach would be to fork the 20.0.0 version of the chart and use it to upgrade to versions 23.6.2 and 23.11.0. Once that’s done, we can then proceed with upgrading to any newer chart version, to upgrade us to 24.X.

**Comment by swade1987** [comment]
@xvilo ever seen this before when upgrading to `23.6.2` from `23.3.1` https://gist.github.com/swade1987/13392a8f92cb6d26348adcd0c63cc84c

Currently, have this, no jobs have ran yet:

<img width="565" alt="Screenshot 2024-10-02 at 16 44 53" src="https://github.com/user-attachments/assets/bd77c16e-bf87-488a-95d3-ffaaac24470f">

**Comment by xvilo** [comment]
well did you do the following:
- Attempt upgrade
- Fail
- Create issue
- Attempt upgrade again, but then with older version, but not reverting the initial upgrade attempt changes?

**Comment by swade1987** [comment]
This is a fresh install:

1. Standup Postgres using 

```
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 16.4.0-debian-12-r11
```

2. Migrated the existing database data across to the new Postgres cluster

3. Stood up version `20.0.0` of the chart using images `23.6.2`

**Comment by swade1987** [comment]
I will create a brand new issue, will close this one.

**Comment by swade1987** [comment]
Opened https://github.com/sentry-kubernetes/charts/issues/1504
