### ISSUE TITLE
fresh install 25.16.0 failed

### ISSUE THREAD

**Issue by StandardStudent** [sentry-kubernetes/charts#1589]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

I tried fresh install 25.16.0 but failed, because of clickhouse migration failed, error like this
![image](https://github.com/user-attachments/assets/4d3a4328-559c-477d-840b-33a2710732b8)

### Expected behavior

hope migration successful

### values.yaml

 # Clickhouse Options
    CLUSTERS = [
      {
        "host": env("CLICKHOUSE_HOST", "cc-0xi761g749ud1f7ox.clickhouse.ads.aliyuncs.com"),
        "port": int(9000),
        "user":  env("CLICKHOUSE_USER", "sentry_version_24"),
        "password": env("CLICKHOUSE_PASSWORD", ""),
        "max_connections": int(os.environ.get("CLICKHOUSE_MAX_CONNECTIONS", 100)),
        "database": env("CLICKHOUSE_DATABASE", "default"),
        "http_port": 8123,
        "storage_sets": {
            "cdc",
            "discover",
            "events",
            "events_ro",
            "metrics",
            "migrations",
            "outcomes",
            "querylog",
            "sessions",
            "transactions",
            "profiles",
            "functions",
            "replays",
            "generic_metrics_sets",
            "generic_metrics_distributions",
            "search_issues",
            "generic_metrics_counters",
            "spans",
            "events_analytics_platform",
            "group_attributes",
            "generic_metrics_gauges",
            "metrics_summaries",
            "profile_chunks",
        },
        "single_node": False,
        "cluster_name": "cider-clickhouse",
        "distributed_cluster_name": "cider-clickhouse",
      },
    ]

### Helm chart version

25.16.0

### Steps to reproduce

1. change clickhouse url to cloud , use version 22.8 cluster, migrate failed
2. change clickhouse  use version 22.8 single , migrate failed
3. change clickhouse to pod that helm use, migrate failed

### Screenshots

![image](https://github.com/user-attachments/assets/05cf76c4-5ea5-4a78-a999-51aadb151b34)

### Logs

{"module": "snuba.migrations.runner", "event": "Running migration: 0001_functions", "severity": "info", "timestamp": "2024-10-31T02:13:57.231955Z"}
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/cli/migrations.py", line 116, in migrate
    runner.run_all(
  File "/usr/src/snuba/snuba/migrations/runner.py", line 219, in run_all
    self._run_migration_impl(
  File "/usr/src/snuba/snuba/migrations/runner.py", line 299, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 95, in forwards
    op.execute(logger)
  File "/usr/src/snuba/snuba/migrations/operations.py", line 625, in execute
    self._get_operation(None).execute()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/migrations/operations.py", line 620, in _get_operation
    return self.__operation_function(clickhouse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/snuba_migrations/functions/0001_functions.py", line 80, in _create_functions_mv_table
    clickhouse_version = migration_utilities.get_clickhouse_version_for_storage_set(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/migrations/migration_utilities.py", line 36, in get_clickhouse_version_for_storage_set
    raise RuntimeError(
RuntimeError: found multiple clickhouse versions in local nodes of storage set StorageSetKey.FUNCTIONS: set()

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
