### ISSUE TITLE
5.0.1 template stucks on install - db-init

### ISSUE THREAD

**Issue by ItsReddi** [sentry-kubernetes/charts#161]
Steps to reproduce:
1. Create a fresh install without upgrading.

Result Chart cannot finish install. sentry-db-init stucks on:
```
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 174, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 121, in _upgrade
    _migrate_from_south(verbosity)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 93, in _migrate_from_south
    if not _has_south_history(connection):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 78, in _has_south_history
    cursor = connection.cursor()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 97, in _cursor
    return super(DatabaseWrapper, self)._cursor()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "postgres"
```

**Comment by Mokto** [comment]
Hey,

Are you sure you remove all leftovers from a potential old installation of sentry ?

**Comment by ItsReddi** [comment]
Yes, and the 5.0.0 template installs fine without any issues

**Comment by ItsReddi** [comment]
Yes i'm sure. I can see following.
A Postgres Secret is created with password. init-db is creating some tables.
5 minutes later the secret password has changed and the init-db pod starts complaining.

It could be something like you mentioned in README?

**Comment by Mokto** [comment]
I would always recommend to setup a password for postgresql.
Because even if it should work for the initial install, the next updates will not work.

Not sure why you have this issue with a fresh install though.

**Comment by ItsReddi** [comment]
I can confirm after setting postgres password on install. Secret values does not change via install.

But now Relay starts to complain. 
Relay:
```
2020-08-27T11:49:40Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Server disconnected
  caused by: Server disconnected
2020-08-27T11:49:51Z [relay_server::actors::upstream] INFO: registering with upstream (http://sentry-web:9000/)
2020-08-27T11:49:51Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Server disconnected
  caused by: Server disconnected
2020-08-27T11:50:08Z [relay_server::actors::upstream] INFO: registering with upstream (http://sentry-web:9000/)
2020-08-27T11:50:08Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Server disconnected
```
sentry-web:
```
10.42.240.8 - - [27/Aug/2020:11:49:27 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"
10.42.240.0 - - [27/Aug/2020:11:49:30 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.18"
10.42.240.8 - - [27/Aug/2020:11:49:32 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"
10.42.240.0 - - [27/Aug/2020:11:49:33 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.18"
10.42.240.8 - - [27/Aug/2020:11:49:40 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"
10.42.240.0 - - [27/Aug/2020:11:49:40 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.18"
10.42.240.0 - - [27/Aug/2020:11:49:43 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.18"
10.42.240.0 - - [27/Aug/2020:11:49:50 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.18"
10.42.240.8 - - [27/Aug/2020:11:49:51 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"
10.42.240.0 - - [27/Aug/2020:11:49:53 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.18"
10.42.240.0 - - [27/Aug/2020:11:50:00 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.18"
10.42.240.0 - - [27/Aug/2020:11:50:03 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.18"
10.42.240.8 - - [27/Aug/2020:11:50:08 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"
10.42.240.0 - - [27/Aug/2020:11:50:10 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.18"
```

**Comment by ItsReddi** [comment]
After waiting getting a coffee and smoking a cigarette everything seems to be started. I am confused.

**Comment by Mokto** [comment]
It needs some time to setup authentication between relay&sentry. Cool you fixed it ;)

**Comment by ItsReddi** [comment]
We had to reinstall after upgrading to latest version. Since the relay was not accessbile and timeouts arrised.
After reinstalling the new version without setting postgres in beforehand password. Install still fails with the same issue.
