### ISSUE TITLE
Not able to setup azure sso login

### ISSUE THREAD

**Issue by Chethanibms** [sentry-kubernetes/charts#1638]
Geeting below error while setting up sso login through microsoft azure
Followed below document to setup
https://docs.sentry.io/organization/authentication/sso/azure-sso/
<img width="1190" alt="Screenshot 2024-12-17 at 12 24 36 PM" src="https://github.com/user-attachments/assets/24deab28-ead1-406d-a26f-4f884e53c959" />
`2024-12-17T06:50:51.910919038Z 06:50:51 [INFO] sentry.superuser: superuser.request (url='https://sentry.talview.com/organizations/talview/auth/configure/' method='POST' ip_address='172.16.18.183' user_id=1)
2024-12-17T06:50:52.057537832Z Traceback (most recent call last):
2024-12-17T06:50:52.057570853Z   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-12-17T06:50:52.057578258Z     response = get_response(request)
2024-12-17T06:50:52.057583708Z                ^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057589428Z   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
2024-12-17T06:50:52.057594848Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-12-17T06:50:52.057600188Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057606691Z   File "/usr/local/lib/python3.11/site-packages/sentry/../sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
2024-12-17T06:50:52.057611970Z     return callback(request, *args, **kwargs)
2024-12-17T06:50:52.057617411Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057622921Z   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
2024-12-17T06:50:52.057628471Z     return self.dispatch(request, *args, **kwargs)
2024-12-17T06:50:52.057634783Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057643840Z   File "/usr/local/lib/python3.11/site-packages/sentry/silo/base.py", line 146, in override
2024-12-17T06:50:52.057669307Z     return original_method(*args, **kwargs)
2024-12-17T06:50:52.057675178Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057680508Z   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
2024-12-17T06:50:52.057685959Z     return bound_method(*args, **kwargs)
2024-12-17T06:50:52.057690998Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057696077Z   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
2024-12-17T06:50:52.057701187Z     return view_func(request, *args, **kwargs)
2024-12-17T06:50:52.057706417Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057722647Z   File "/usr/local/lib/python3.11/site-packages/sentry/web/frontend/base.py", line 406, in dispatch
2024-12-17T06:50:52.057727957Z     return self.handle(request, *args, **kwargs)
2024-12-17T06:50:52.057732986Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057738396Z   File "/usr/local/lib/python3.11/site-packages/sentry/web/frontend/organization_auth_settings.py", line 283, in handle
2024-12-17T06:50:52.057743786Z     return helper.current_step()
2024-12-17T06:50:52.057753985Z            ^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057759425Z   File "/usr/local/lib/python3.11/site-packages/sentry/pipeline/base.py", line 188, in current_step
2024-12-17T06:50:52.057764665Z     return self.dispatch_to(step)
2024-12-17T06:50:52.057769905Z            ^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057777399Z   File "/usr/local/lib/python3.11/site-packages/sentry/auth/helper.py", line 759, in dispatch_to
2024-12-17T06:50:52.057782559Z     return step.dispatch(request=self.request, helper=self)
2024-12-17T06:50:52.057787809Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057792948Z   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
2024-12-17T06:50:52.057798148Z     return bound_method(*args, **kwargs)
2024-12-17T06:50:52.057803438Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057808567Z   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
2024-12-17T06:50:52.057813737Z     return view_func(request, *args, **kwargs)
2024-12-17T06:50:52.057827673Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057835297Z   File "/usr/local/lib/python3.11/site-packages/sentry/web/frontend/base.py", line 406, in dispatch
2024-12-17T06:50:52.057842300Z     return self.handle(request, *args, **kwargs)
2024-12-17T06:50:52.057847370Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057852509Z   File "/usr/local/lib/python3.11/site-packages/sentry/auth/providers/saml2/generic/views.py", line 75, in handle
2024-12-17T06:50:52.057857639Z     return helper.next_step()
2024-12-17T06:50:52.057863009Z            ^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057868239Z   File "/usr/local/lib/python3.11/site-packages/sentry/pipeline/base.py", line 235, in next_step
2024-12-17T06:50:52.057874731Z     return self.current_step()
2024-12-17T06:50:52.057883437Z            ^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057904587Z   File "/usr/local/lib/python3.11/site-packages/sentry/pipeline/base.py", line 188, in current_step
2024-12-17T06:50:52.057912832Z     return self.dispatch_to(step)
2024-12-17T06:50:52.057919975Z            ^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057928441Z   File "/usr/local/lib/python3.11/site-packages/sentry/auth/helper.py", line 759, in dispatch_to
2024-12-17T06:50:52.057940173Z     return step.dispatch(request=self.request, helper=self)
2024-12-17T06:50:52.057948769Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057967534Z   File "/usr/local/lib/python3.11/site-packages/sentry/auth/providers/saml2/provider.py", line 68, in dispatch
2024-12-17T06:50:52.057976210Z     auth = build_auth(request, saml_config)
2024-12-17T06:50:52.057984255Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.057994895Z   File "/usr/local/lib/python3.11/site-packages/sentry/auth/providers/saml2/provider.py", line 389, in build_auth
2024-12-17T06:50:52.058003140Z     return OneLogin_Saml2_Auth(saml_request, saml_config)
2024-12-17T06:50:52.058014432Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.058063152Z   File "/usr/local/lib/python3.11/site-packages/onelogin/saml2/auth.py", line 57, in __init__
2024-12-17T06:50:52.058094591Z     self._settings = OneLogin_Saml2_Settings(old_settings, custom_base_path)
2024-12-17T06:50:52.058108988Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-17T06:50:52.058117945Z   File "/usr/local/lib/python3.11/site-packages/onelogin/saml2/settings.py", line 128, in __init__
2024-12-17T06:50:52.058125809Z     raise OneLogin_Saml2_Error(
2024-12-17T06:50:52.058133584Z onelogin.saml2.errors.OneLogin_Saml2_Error: Invalid dict settings: sp_acs_url_invalid,sp_sls_url_invalid
2024-12-17T06:50:52.058150596Z 06:50:52 [ERROR] django.request: Internal Server Error: /organizations/talview/auth/configure/ (status_code=500 request=<WSGIRequest: POST '/organizations/talview/auth/configure/'>)
2024-12-17T06:50:52.059164478Z 06:50:52 [INFO] sentry.access.api: api.access (method='POST' view='sentry.web.frontend.organization_auth_settings.OrganizationAuthSettingsView' response=500 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/organizations/talview/auth/configure/' caller_ip='172.16.18.183' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.1735057830810547 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2024-12-17T06:50:52.445479932Z 06:50:52 [INFO] sentry.superuser: superuser.request (url='https://sentry.talview.com/api/0/organizations/talview/?detailed=0' method='GET' ip_address='172.16.18.183' user_id=1)
2024-12-17T06:50:52.447274940Z 06:50:52 [INFO] sentry.superuser: superuser.request (url='https://sentry.talview.com/api/0/organizations/talview/teams/' method='GET' ip_address='172.16.18.183' user_id=1)
2024-12-17T06:50:52.447939383Z 06:50:52 [INFO] sentry.superuser: superuser.request (url='https://sentry.talview.com/api/0/organizations/talview/projects/?all_projects=1&collapse=latestDeploys&collapse=unusedFeatures' method='GET' ip_address='172.16.18.183' user_id=1)
2024-12-17T06:50:52.511590033Z 06:50:52 [INFO] sentry.superuser: superuser.superuser_access (superuser_token_id='7eCUA5t3ucOQ' user_id=1 user_email='devopsteam@talview.com' su_org_accessed='talview')
2024-12-17T06:50:52.512699895Z 06:50:52 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_teams.OrganizationTeamsEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/talview/teams/' caller_ip='172.16.18.183' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.09032702445983887 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2024-12-17T06:50:52.514919656Z 06:50:52 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_projects.OrganizationProjectsEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/talview/projects/' caller_ip='172.16.18.183' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.09108901023864746 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
2024-12-17T06:50:52.545355224Z 06:50:52 [INFO] sentry.superuser: superuser.superuser_access (superuser_token_id='7eCUA5t3ucOQ' user_id=1 user_email='devopsteam@talview.com' su_org_accessed='talview')
2024-12-17T06:50:52.546897615Z 06:50:52 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_details.OrganizationDetailsEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/talview/' caller_ip='172.16.18.183' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.12509632110595703 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')`

Can somebody help with the issue

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
