### ISSUE TITLE
sentry-snuba-api CrashLoopBackOff

### ISSUE THREAD

**Issue by zjengjie** [sentry-kubernetes/charts#1643]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

Traceback (most recent call last):
  File "/.venv/bin/sentry", line 4, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/usr/src/sentry/src/sentry/runner/main.py", line 149, in main
    func(**kwargs)
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/decorators.py", line 83, in inner
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/decorators.py", line 34, in inner
    configure()
  File "/usr/src/sentry/src/sentry/runner/__init__.py", line 33, in configure
    _configure(ctx, py, yaml, skip_service_validation)
  File "/usr/src/sentry/src/sentry/runner/settings.py", line 117, in configure
    hasattr(settings, "INSTALLED_APPS")
  File "/.venv/lib/python3.12/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/.venv/lib/python3.12/site-packages/django/conf/__init__.py", line 68, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/django/conf/__init__.py", line 166, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/sentry/src/sentry/runner/default_settings.py", line 8, in <module>
    populate_module(sys.modules[__name__])
  File "/usr/src/sentry/src/sentry/runner/importer.py", line 17, in populate_module
    _load_settings(SENTRY_CONF_PY, settings=settings_mod)
  File "/usr/src/sentry/src/sentry/runner/importer.py", line 28, in _load_settings
    exec(source_file.read(), conf.__dict__)
  File "<string>", line 253, in <module>
Exception: Error: SENTRY_SECRET_KEY is undefined, run `generate-secret-key` and set to -e SENTRY_SECRET_KEY

### values.yaml

I use follow command install sentry:
```
helm install sentry sentry/sentry --wait --timeout=1000s --namespace sentry --set global.imageRegistry=docker.hlmirror.com --set image.repository=docker.hlmirror.com --set images.sentry.repository=docker.hlmirror.com/getsentry/sentry --set images.snuba.repository=docker.hlmirror.com/getsentry/sentry --set clickhouse.clickhouse.image=docker.hlmirror.com/clickhouse/clickhouse-server
```

### Helm chart version

chart:
sentry-26.9.0

app version:
24.9.0

### Steps to reproduce

```
helm install sentry sentry/sentry --wait --timeout=1000s --namespace sentry --set global.imageRegistry=docker.hlmirror.com --set image.repository=docker.hlmirror.com --set images.sentry.repository=docker.hlmirror.com/getsentry/sentry --set images.snuba.repository=docker.hlmirror.com/getsentry/sentry --set clickhouse.clickhouse.image=docker.hlmirror.com/clickhouse/clickhouse-server
```

### Additional context

Initially, the SENTRY_REDIS_HOST was missing, so I manually added it to the sentry-snuba-env. Later, I also added the SENTRY_SECRET_KEY. After that, the following error occurred:
```
!! Configuration error: ConfigurationError("sentry.tsdb service failed to call validate()\nmodule 'sentry.tsdb.redis' has no attribute 'RedisSnubaTSDB'")
```

**Comment by zjengjie** [comment]
I config the wrong image. close this
