### ISSUE TITLE
Outdated clickhouse version

### ISSUE THREAD

**Issue by madchap** [sentry-kubernetes/charts#1651]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

When wanting to update to sentry 24.12.1:

```
Traceback (most recent call last):                                                                                                                                                                                        │
│   File "/usr/local/bin/snuba", line 33, in <module>                                                                                                                                                                       │
│     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())                                                                                                                                                     │
│              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                      │
│   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__                                                                                                                                    │
│     return self.main(*args, **kwargs)                                                                                                                                                                                     │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                     │
│   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main                                                                                                                                        │
│     rv = self.invoke(ctx)                                                                                                                                                                                                 │
│          ^^^^^^^^^^^^^^^^                                                                                                                                                                                                 │
│   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke                                                                                                                                      │
│     return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                               │
│                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                │
│   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke                                                                                                                                      │
│     return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                               │
│                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                │
│   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke                                                                                                                                      │
│     return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                                        │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                        │
│   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke                                                                                                                                       │
│     return __callback(*args, **kwargs)                                                                                                                                                                                    │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                    │
│   File "/usr/src/snuba/snuba/cli/migrations.py", line 107, in migrate                                                                                                                                                     │
│     check_clickhouse_connections(clusters_to_check)                                                                                                                                                                       │
│   File "/usr/src/snuba/snuba/migrations/connect.py", line 90, in check_clickhouse_connections                                                                                                                             │
│     check_clickhouse(clickhouse)                                                                                                                                                                                          │
│   File "/usr/src/snuba/snuba/migrations/connect.py", line 117, in check_clickhouse                                                                                                                                        │
│     raise InvalidClickhouseVersion(                                                                                                                                                                                       │
│ snuba.migrations.errors.InvalidClickhouseVersion: Snuba requires minimum Clickhouse version 23.8.11.29 (lf-sentry-clickhouse:9000 - 23.3.19.32)                                                                           │
│ stream closed EOF for default/lf-sentry-snuba-migrate-7bwjv (snuba-migrate)
```

### Expected behavior

Clickhouse version is more recent and allows sentry updates.

### values.yaml

None useful.

### Helm chart version

26.9.1

### Steps to reproduce

Update sentry app to `appVersion: 24.12.1`, helm uninstall and install.

**Comment by madchap** [comment]
Despite https://github.com/sentry-kubernetes/charts/blob/develop/charts/clickhouse/Chart.yaml#L2 a `helm dependency update` still pulls the older version.

The version in the Chart.yaml is sufficient in itself.

This is what comes out of a `helm dependency update` tar'ed clickhouse file:

```
$ cat clickhouse/Chart.yaml
apiVersion: v1
appVersion: 23.3.19.32
description: ClickHouse is an open source column-oriented database management system
  capable of real time generation of analytical data reports using SQL queries
home: https://clickhouse.yandex/
icon: https://clickhouse.yandex/images/logo.png
keywords:
- clickhouse
- olap
- database
maintainers:
- name: sentry-kubernetes
name: clickhouse
sources:
- https://github.com/sentry-kubernetes/charts
version: 3.13.0
```

I am also unsure as to why the chart's version didn't get updated from `3.13.0` to `3.14.0` or whatever.

**Comment by madchap** [comment]
OK, I am guessing we're waiting on https://github.com/sentry-kubernetes/charts/pull/1650
