### ISSUE TITLE
[6.0.0] Sentry db-init job failing with "failed password authentication"

### ISSUE THREAD

**Issue by dnlsndr** [sentry-kubernetes/charts#206]
Running a `helm upgrade ...` command on a already installed Sentry Helm chart is impossible, since the db-init job failes with the following error:

_Note: I'm using the default postgres settings, no modifications whatsoever_

```
11:49:54 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
11:49:56 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 174, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 121, in _upgrade
    _migrate_from_south(verbosity)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 93, in _migrate_from_south
    if not _has_south_history(connection):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 78, in _has_south_history
    cursor = connection.cursor()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 99, in _cursor
    return super(DatabaseWrapper, self)._cursor()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "postgres"
```
This error has already been persisting since earlier versions, e.g. 5.6.0. 
Somehow the db-init job can't fetch the db password from the `sentry-sentry-postgresql` secret or the password stored in the secret is false. 

Maybe one should upgrade the postgres subchart to a more supported chart such as the bitnami one (https://hub.kubeapps.com/charts/bitnami/postgresql) since - as far as i know - the one currently used isn't even a thing anymore.

**Comment by Mokto** [comment]
Please read https://github.com/sentry-kubernetes/charts#postgressql

You have to setup a password.

Thanks.

**Comment by dnlsndr** [comment]
Thanks, oversaw that part! 
There should really be a default value for the password, since this is not apparent if one didn't notice the README.

**Comment by manuschillerdev** [comment]
@onmyflow May I ask how you solved that? 

I debuged my issue (https://github.com/sentry-kubernetes/charts/issues/319) until the same point, and updated my `values.yaml`. But unfortunately, the error persists.

my `values.yaml`
```yaml
postgresql:
  enabled: true
  nameOverride: sentry-postgresql
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: sentry
  replication:
    enabled: false
    readReplicas: 2
    password: postgres
    synchronousCommit: "on"
    numSynchronousReplicas: 1
    applicationName: sentry
```

**Comment by ghost** [comment]
> @onmyflow May I ask how you solved that?
> 
> I debuged my issue (#319) until the same point, and updated my `values.yaml`. But unfortunately, the error persists.
> 
> my `values.yaml`
> 
> ```yaml
> postgresql:
>   enabled: true
>   nameOverride: sentry-postgresql
>   postgresqlUsername: postgres
>   postgresqlPassword: postgres
>   postgresqlDatabase: sentry
>   replication:
>     enabled: false
>     readReplicas: 2
>     password: postgres
>     synchronousCommit: "on"
>     numSynchronousReplicas: 1
>     applicationName: sentry
> ```
@manuschillerdev
Did you ever fix it?
Still an issue
