### ISSUE TITLE
Unable to create sentry stack

### ISSUE THREAD

**Issue by Puneeth-n** [sentry-kubernetes/charts#227]
Issue: sentry-snuba-transactions-consumer, sentry-post-process-forward not coming up

Chart version: 7.1.0
Kubernetes version: 1.18
Helm version: 3

Sentry helm config
```hcl

resource "helm_release" "sentry" {
  name       = local.sentry.name
  repository = "https://sentry-kubernetes.github.io/charts"
  chart      = "sentry"
  version    = "7.1.0"
  namespace  = kubernetes_namespace.sentry.metadata[0].name
  lint       = true

  values = [
    yamlencode(
      {
        user = {
          create   = true
          email    = "lorem.ipsum@foo.com"
          password = random_password.sentry_password.result
        }

        ingress = {
          enabled = true
          annotations = {
            "kubernetes.io/ingress.class"               = "alb"
            "alb.ingress.kubernetes.io/scheme"          = "internet-facing"
            "alb.ingress.kubernetes.io/listen-ports"    = jsonencode([{ HTTP = 443 }])
            "alb.ingress.kubernetes.io/group.name"      = "infra"
            "alb.ingress.kubernetes.io/certificate-arn" = aws_acm_certificate.subdomain.arn
          }
          hostname = "sentry.${module.infra_vpc.public_subdomain}"
        }
      }
    )
  ]
}
```

kubectl -n sentry get all
```bash
NAME                                                      READY   STATUS             RESTARTS   AGE
pod/sentry-clickhouse-0                                   1/1     Running            0          50m
pod/sentry-clickhouse-1                                   1/1     Running            0          50m
pod/sentry-clickhouse-2                                   1/1     Running            0          50m
pod/sentry-clickhouse-replica-0                           1/1     Running            0          50m
pod/sentry-clickhouse-replica-1                           1/1     Running            0          50m
pod/sentry-clickhouse-replica-2                           1/1     Running            0          50m
pod/sentry-clickhouse-tabix-75698686bc-l8js6              1/1     Running            0          50m
pod/sentry-cron-768844c868-vq4dm                          1/1     Running            1          50m
pod/sentry-ingest-consumer-577bc9db4c-8z28h               1/1     Running            2          50m
pod/sentry-kafka-0                                        1/1     Running            2          50m
pod/sentry-kafka-1                                        1/1     Running            0          49m
pod/sentry-kafka-2                                        1/1     Running            1          49m
pod/sentry-nginx-58747db8cd-nl4qd                         1/1     Running            0          50m
pod/sentry-post-process-forward-5fb5fc7998-wcng8          0/1     CrashLoopBackOff   14         50m
pod/sentry-rabbitmq-0                                     1/1     Running            0          50m
pod/sentry-rabbitmq-1                                     1/1     Running            0          49m
pod/sentry-rabbitmq-2                                     1/1     Running            0          48m
pod/sentry-sentry-postgresql-0                            1/1     Running            0          50m
pod/sentry-sentry-redis-master-0                          1/1     Running            0          50m
pod/sentry-sentry-redis-slave-0                           1/1     Running            0          50m
pod/sentry-sentry-redis-slave-1                           1/1     Running            0          49m
pod/sentry-snuba-api-6497f5c8bf-4n5xc                     1/1     Running            0          50m
pod/sentry-snuba-consumer-c7d597ccb-bnfsg                 0/1     CrashLoopBackOff   14         50m
pod/sentry-snuba-transactions-consumer-8565f4d957-kckq2   0/1     CrashLoopBackOff   14         50m
pod/sentry-web-c98989bfc-rhhr8                            1/1     Running            0          50m
pod/sentry-worker-bc677846f-9g2fv                         1/1     Running            1          50m
pod/sentry-worker-bc677846f-d4fdz                         1/1     Running            1          50m
pod/sentry-worker-bc677846f-kvqsl                         1/1     Running            1          50m
pod/sentry-zookeeper-0                                    1/1     Running            0          50m

NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                       AGE
service/sentry-clickhouse                    ClusterIP   172.20.248.138   <none>        9000/TCP,8123/TCP,9009/TCP    50m
service/sentry-clickhouse-headless           ClusterIP   None             <none>        9000/TCP,8123/TCP,9009/TCP    50m
service/sentry-clickhouse-replica            ClusterIP   172.20.206.29    <none>        9000/TCP,8123/TCP,9009/TCP    50m
service/sentry-clickhouse-replica-headless   ClusterIP   None             <none>        9000/TCP,8123/TCP,9009/TCP    50m
service/sentry-clickhouse-tabix              ClusterIP   172.20.31.3      <none>        80/TCP                        50m
service/sentry-kafka                         ClusterIP   172.20.140.81    <none>        9092/TCP                      50m
service/sentry-kafka-headless                ClusterIP   None             <none>        9092/TCP                      50m
service/sentry-nginx                         ClusterIP   172.20.46.181    <none>        80/TCP,443/TCP                50m
service/sentry-rabbitmq                      ClusterIP   172.20.70.246    <none>        15672/TCP,5672/TCP,4369/TCP   50m
service/sentry-rabbitmq-discovery            ClusterIP   None             <none>        15672/TCP,5672/TCP,4369/TCP   50m
service/sentry-relay                         ClusterIP   172.20.127.163   <none>        3000/TCP                      50m
service/sentry-sentry-postgresql             ClusterIP   172.20.0.103     <none>        5432/TCP                      50m
service/sentry-sentry-postgresql-headless    ClusterIP   None             <none>        5432/TCP                      50m
service/sentry-sentry-redis-headless         ClusterIP   None             <none>        6379/TCP                      50m
service/sentry-sentry-redis-master           ClusterIP   172.20.221.254   <none>        6379/TCP                      50m
service/sentry-sentry-redis-slave            ClusterIP   172.20.92.191    <none>        6379/TCP                      50m
service/sentry-snuba                         ClusterIP   172.20.199.216   <none>        1218/TCP                      50m
service/sentry-web                           ClusterIP   172.20.107.138   <none>        9000/TCP                      50m
service/sentry-zookeeper                     ClusterIP   172.20.139.97    <none>        2181/TCP,2888/TCP,3888/TCP    50m
service/sentry-zookeeper-headless            ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP    50m

NAME                                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sentry-clickhouse-tabix              1/1     1            1           50m
deployment.apps/sentry-cron                          1/1     1            1           50m
deployment.apps/sentry-ingest-consumer               1/1     1            1           50m
deployment.apps/sentry-nginx                         1/1     1            1           50m
deployment.apps/sentry-post-process-forward          0/1     1            0           50m
deployment.apps/sentry-snuba-api                     1/1     1            1           50m
deployment.apps/sentry-snuba-consumer                0/1     1            0           50m
deployment.apps/sentry-snuba-transactions-consumer   0/1     1            0           50m
deployment.apps/sentry-web                           1/1     1            1           50m
deployment.apps/sentry-worker                        3/3     3            3           50m

NAME                                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/sentry-clickhouse-tabix-75698686bc              1         1         1       50m
replicaset.apps/sentry-cron-768844c868                          1         1         1       50m
replicaset.apps/sentry-ingest-consumer-577bc9db4c               1         1         1       50m
replicaset.apps/sentry-nginx-58747db8cd                         1         1         1       50m
replicaset.apps/sentry-post-process-forward-5fb5fc7998          1         1         0       50m
replicaset.apps/sentry-snuba-api-6497f5c8bf                     1         1         1       50m
replicaset.apps/sentry-snuba-consumer-c7d597ccb                 1         1         0       50m
replicaset.apps/sentry-snuba-transactions-consumer-8565f4d957   1         1         0       50m
replicaset.apps/sentry-web-c98989bfc                            1         1         1       50m
replicaset.apps/sentry-worker-bc677846f                         3         3         3       50m

NAME                                          READY   AGE
statefulset.apps/sentry-clickhouse            3/3     50m
statefulset.apps/sentry-clickhouse-replica    3/3     50m
statefulset.apps/sentry-kafka                 3/3     50m
statefulset.apps/sentry-rabbitmq              3/3     50m
statefulset.apps/sentry-sentry-postgresql     1/1     50m
statefulset.apps/sentry-sentry-redis-master   1/1     50m
statefulset.apps/sentry-sentry-redis-slave    2/2     50m
statefulset.apps/sentry-zookeeper             1/1     50m

NAME                                  SCHEDULE    SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/sentry-sentry-cleanup   0 0 * * *   False     0        <none>          50m
```

```
➜  infra git:(chore/sentry) ✗ kubectl -n sentry logs -f sentry-snuba-transactions-consumer-8565f4d957-kckq2
2020-11-03 16:16:17,195 Caught ConsumerError('KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: events: Broker: Unknown topic or partition"}'), shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 166, in consumer
    consumer.run()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 109, in run
    self._run_once()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 139, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/utils/streams/backends/kafka.py", line 398, in poll
    raise ConsumerError(str(error))
snuba.utils.streams.backends.abstract.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: events: Broker: Unknown topic or partition"}
```

```
➜  infra git:(chore/sentry) ✗ kubectl -n sentry logs -f sentry-snuba-consumer-c7d597ccb-bnfsg
2020-11-03 16:16:06,943 Caught ConsumerError('KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: events: Broker: Unknown topic or partition"}'), shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 166, in consumer
    consumer.run()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 109, in run
    self._run_once()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 139, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/utils/streams/backends/kafka.py", line 660, in poll
    return super().poll(timeout)
  File "/usr/src/snuba/snuba/utils/streams/backends/kafka.py", line 398, in poll
    raise ConsumerError(str(error))
snuba.utils.streams.backends.abstract.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: events: Broker: Unknown topic or partition"}
```

```
➜  infra git:(chore/sentry) ✗ kubectl -n sentry logs -f sentry-post-process-forward-5fb5fc7998-wcng8
16:16:45 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
16:16:48 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'postprocess.use-cache-key'
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 68, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/run.py", line 294, in post_process_forwarder
    initial_offset_reset=options["initial_offset_reset"],
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 105, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/eventstream/kafka/backend.py", line 195, in run_post_process_forwarder
    raise Exception(error)
Exception: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: events: Broker: Unknown topic or partition"}
```

**Comment by mariusmitrofanbostontr** [comment]
@Mokto looks like I'm not the only one :+1: 

My PR (https://github.com/sentry-kubernetes/charts/pull/229) should fix this ...

**Comment by Mokto** [comment]
Thanks @mariusmitrofanbostontr. Could you try 7.2.0 ? @Puneeth-n

**Comment by mariusmitrofanbostontr** [comment]
@Puneeth-n I've tested myself and it went fine for me with the new 7.2.0 release

**Comment by Puneeth-n** [comment]
Let me give it a spin :) Thanks for letting me know :)

**Comment by L-U-C-K-Y** [comment]
Hi all

I am facing the same issue, while deploying with ArgoCD. Is this related to Helm hooks?

I am using 8.0.0.

snuba-consumer:

```bash
│ 2020-11-29 19:05:18,527 Caught ConsumerError('KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: events: Broker: Unknown topic or partition"}'), shutting down...                                          │
│ Traceback (most recent call last):                                                                                                                                                                                                       │
│   File "/usr/local/bin/snuba", line 33, in <module>                                                                                                                                                                                      │
│     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())                                                                                                                                                                    │
│   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__                                                                                                                                                     │
│     return self.main(*args, **kwargs)                                                                                                                                                                                                    │
│   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main                                                                                                                                                         │
│     rv = self.invoke(ctx)                                                                                                                                                                                                                │
│   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke                                                                                                                                                      │
│     return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                                              │
│   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke                                                                                                                                                       │
│     return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                                                       │
│   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke                                                                                                                                                       │
│     return callback(*args, **kwargs)                                                                                                                                                                                                     │
│   File "/usr/src/snuba/snuba/cli/consumer.py", line 166, in consumer                                                                                                                                                                     │
│     consumer.run()                                                                                                                                                                                                                       │
│   File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 109, in run                                                                                                                                                    │
│     self._run_once()                                                                                                                                                                                                                     │
│   File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 139, in _run_once                                                                                                                                              │
│     self.__message = self.__consumer.poll(timeout=1.0)                                                                                                                                                                                   │
│   File "/usr/src/snuba/snuba/utils/streams/backends/kafka.py", line 660, in poll                                                                                                                                                         │
│     return super().poll(timeout)                                                                                                                                                                                                         │
│   File "/usr/src/snuba/snuba/utils/streams/backends/kafka.py", line 398, in poll                                                                                                                                                         │
│     raise ConsumerError(str(error))                                                                                                                                                                                                      │
│ snuba.utils.streams.backends.abstract.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: events: Broker: Unknown topic or partition"}
```

Edit: The issue was that I was trying to enable persistent workers. I did not change `accessMode: ReadWriteMany`in filestore.filesystem.persistence.accessMode. After changing it, the error was not present, but other errors appeared and I did disable persistent workers. Now it is working again.

**Comment by sfc-gh-pkommini** [comment]
@Puneeth-n Is the nginx needed in this case? Would this change in any way if I wanted to use `aws-alb`?

**Comment by Puneeth-n** [comment]
> @Puneeth-n Is the nginx needed in this case? Would this change in any way if I wanted to use `aws-alb`?

@sfc-gh-pkommini I have completely forgotten what the issue was. I might try to install the chart again sometime soon and can update you on this

**Comment by xvilo** [comment]
@sfc-gh-pkommini in my case it was while setting up a new instance, I had `asHooks` on false. This should be true

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
