### ISSUE TITLE
Exernal managed kafka - ingest-consumer is not able to create topic

### ISSUE THREAD

**Issue by mariusmitrofanbostontr** [sentry-kubernetes/charts#235]
I could use some pointers here guys.

The only thing I did different was having a different (external) kafka cluster empty, and because of it, the ingest-consumer cannot start because it cannot find the topic 'ingest-transactions'.

Is there some  sort of command that needs to run separately maybe to have the kafka initialize with some specific cluster?

Thanks...

Error is this:

```
22:32:18 [WARNING] batching-kafka-consumer: Topic 'ingest-transactions' or its partitions are not ready, retrying...
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 68, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/run.py", line 440, in ingest_consumer
    get_ingest_consumer(consumer_types=consumer_types, **options).run()
  File "/usr/local/lib/python2.7/site-packages/sentry/ingest/ingest_consumer.py", line 277, in get_ingest_consumer
    topic_names=topic_names, worker=IngestConsumerWorker(), **options
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/kafka.py", line 80, in create_batching_kafka_consumer
    **options
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/batching_kafka_consumer.py", line 155, in __init__
    queued_min_messages,
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/batching_kafka_consumer.py", line 236, in create_consumer
    self._wait_for_topics(admin_client, topics)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/batching_kafka_consumer.py", line 184, in _wait_for_topics
    topic, last_error
RuntimeError: Timeout when waiting for Kafka topic '%s' to become available, last error: %s
```

**Comment by mariusmitrofanbostontr** [comment]
For anyone else having this problem -> AWS Kafka launches new clusters with property "auto.create.topics.enable" = "false".

You need to launch the cluster with custom aws kafka configuration that sets that property to "true".

**Comment by czomo** [comment]
@mariusmitrofanbostontr Could you share brief info how you set up MSK cluster? Are you used PLAINTEXT encryption?
I am setting brokers within chart like that 
externalKafka:
  - host: b-1.immense-sunbird-msk-se
    port: 9096
  - host: b-2.immense-sunbird-msk-se
    port: 9096
  - host: b-3.immense-sunbird-msk-se
    port: 9096

**Comment by czomo** [comment]
oki doki, i managed to set it up. I set TLS_PLAINTEXT encryption along with two options:
auto.create.topics.enable=true 
min.insync.replicas=1
Remember to use Plaintext endpoints

**Comment by sfc-gh-pkommini** [comment]
@czomo Did you use a terraform module to create the MSK cluster?

**Comment by czomo** [comment]
@sfc-gh-pkommini yes, I highly recomend it

**Comment by sfc-gh-pkommini** [comment]
@czomo Is [this](https://registry.terraform.io/modules/cloudposse/msk-apache-kafka-cluster/aws/latest) the module you used? Do you have a sample config? of what you used. This is my config and I wanted to know if I'm missing something:

```terraform
resource "random_id" "config_id" {
  byte_length = 2
}

module "sentry_kafka" {
  source  = "cloudposse/msk-apache-kafka-cluster/aws"
  version = "0.8.3"

  name                      = "${local.sentry_prefix}-${try(random_id.config_id.hex, "")}"
  kafka_version             = var.kafka_version
  number_of_broker_nodes    = 4
  broker_instance_type      = var.broker_instance_type
  cloudwatch_logs_enabled   = true
  cloudwatch_logs_log_group = aws_cloudwatch_log_group.sentry_msk.name

  vpc_id                = var.vpc_id
  zone_id               = var.private_hosted_zone_id
  subnet_ids            = var.private_subnet_ids
  create_security_group = true

  allowed_security_group_ids = [
    module.eks.node_security_group_id,
    module.eks.cluster_security_group_id,
  ]
}
```

Are you using the `zone_id` param? I'm unsure whether to use it or not should we use a private hosted zone ID or public hosted zone ID. Also where do you set the TLS_PLAINTEXT etc. that you mentioned?

**Comment by czomo** [comment]
I guess zone_id  depends how your sentry is deployed, i think private zone is better. When it comes to TLS_PLAINTEXT please check client_broker var in aws msk provider, here https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster
