### ISSUE TITLE
Unable to list sentry projects - Table default.sentry_dist doesn't exist

### ISSUE THREAD

**Issue by Hassnain-Alvi** [sentry-kubernetes/charts#236]
I have installed sentry via helm chart with default configuration. Somehow the migrations failed and i don't want to reinstall again as there are lots of dynamic PVCs created.
I am getting following error in web pod logs
```
1:34:17 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'localhost:8080/api/0/organizations/sentry/projects/?statsPeriod=24h&query=id%3A2+id%3A1' method=u'GET' ip_address=u'10.244.4.1')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 124, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 237, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/organization_projects.py", line 116, in get
    paginator_cls=OffsetPaginator,
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 325, in paginate
    results = on_results(cursor_result.results)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/organization_projects.py", line 109, in serialize_on_result
    return serialize(result, request.user, serializer)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 41, in serialize
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/project.py", line 318, in get_attrs
    attrs = super(ProjectSummarySerializer, self).get_attrs(item_list, user)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/project.py", line 282, in get_attrs
    attrs = super(ProjectWithTeamSerializer, self).get_attrs(item_list, user)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/project.py", line 143, in get_attrs
    environment_ids=self.environment_id and [self.environment_id],
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 105, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/redissnuba.py", line 87, in method
    return getattr(self.backends[backend], key)(*a, **kw)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/snuba.py", line 363, in get_range
    conditions=conditions,
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/snuba.py", line 288, in get_data
    is_grouprelease=(model == TSDBModel.frequent_releases_by_group),
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 755, in query
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 633, in raw_query
    return bulk_raw_query([snuba_params], referrer=referrer)[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 712, in bulk_raw_query
    error["message"]
QueryExecutionError: [60] DB::Exception: Table default.sentry_dist doesn't exist.. Stack trace:
```
I tried running sentry upgrade command but still it didn't worked 
tried `snuba-api upgrade` command but that command is not found inside web and snuba-api pod 

I am using latest v7.0.0 release of sentry 
Can anyone tell me how can i fix it ?

**Comment by Mokto** [comment]
hi,

Can you share the logs of your helm hooks ? (sentry-db-init.job.yaml ?)

**Comment by Hassnain-Alvi** [comment]
Fixed by running upgrade command
