### ISSUE TITLE
snuba-transactions-consumer CrashLoopBackOff

### ISSUE THREAD

**Issue by thewilli** [sentry-kubernetes/charts#244]
While everything else seems fine with the current `7.3.0` Sentry chart, the `snuba-transactions-consumer` constantly crashes with the following message:

```plain
2020-11-16 11:46:55,412 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 146}
2020-11-16 11:46:56,430 Caught ClickhouseWriterError(code=117, message='Unknown field found while parsing JSONEachRow format: http_method (version 19.17.10.1 (official build))', row=None), shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 166, in consumer
    consumer.run()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 109, in run
    self._run_once()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 144, in _run_once
    self.__processing_strategy.poll()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/transform.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 122, in poll
    self.__close_and_reset_batch()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 104, in __close_and_reset_batch
    self.__batch.close()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 64, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumer.py", line 217, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumer.py", line 90, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 175, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 129, in join
    raise ClickhouseWriterError(code, message, row)
snuba.clickhouse.errors.ClickhouseWriterError: [117] Unknown field found while parsing JSONEachRow format: http_method (version 19.17.10.1 (official build))
stream closed
```

Do you have any idea what the problem might be and how I might solve it without loosing data?

**Comment by DandyDeveloper** [comment]
@thewilli I haven't seen this before myself, the best thing to do might be to reset the offset in the Kafka group by following this: 

https://gist.github.com/marwei/cd40657c481f94ebe273ecc16601674b

You'll lose some transactions, but typically they are far in few between and you can afford to lose some. 

That being said, it might be good to look at why the consumer originally crashed, because it's likely that sent everything into a hot mess and left you with the situation above

**Comment by nilpntr** [comment]
I got this problem:
```bash
2021-04-06 07:57:34,739 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 333}
2021-04-06 07:57:35,864 Caught ClickhouseWriterError(code=49, message='Block structure mismatch in RemoteBlockOutputStream stream: different types:', row=None), shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 161, in consumer
    consumer.run()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 112, in run
    self._run_once()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 147, in _run_once
    self.__processing_strategy.poll()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/transform.py", line 61, in poll
    self.__next_step.poll()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 122, in poll
    self.__close_and_reset_batch()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 104, in __close_and_reset_batch
    self.__batch.close()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 64, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 220, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 91, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 180, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 131, in join
    raise ClickhouseWriterError(code, message, row)
snuba.clickhouse.errors.ClickhouseWriterError: [49] Block structure mismatch in RemoteBlockOutputStream stream: different types:
```

**Comment by taxilian** [comment]
I was having a similar-ish issue and fixed it with this command: 

```/opt/bitnami/kafka/bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --group snuba-events-subscriptions-consumers --reset-offsets --to-earliest --all-topics --execute```

That was run in one of the kafka pods

**Comment by sagor999** [comment]
Happened on my staging instance as well. 
They have a troubleshooting guide for this specific case that apparently can happen sometimes:
https://develop.sentry.dev/self-hosted/troubleshooting/#kafka

**Comment by taxilian** [comment]
I've had it happen twice; I wish I could figure out *why* it's happening and prevent it

**Comment by sagor999** [comment]
There is this thread that discusses this issue:
https://github.com/getsentry/onpremise/issues/478
It seems to happen when Kafka gets out of sync (maybe because it runs out of space or memory). And seems to be an issue with Kafka, not with sentry. But that thread goes into more detail. Check your kafka pod logs, maybe it crashes around that time? or not shutdown cleanly? :thinking:

**Comment by DandyDeveloper** [comment]
@sagor999 Correct. Specifically, this occurs because Kafka loses track of its partitions in the topic for "some reason" I don't know exactly why. That thread probably explains it better. 

Resetting the partition position / offset in the topic fixes it. I don't think from a chart perspective there's a lot that can be done to mitigate this problem though because it needs to be a reactionary action that happens under specific circumstyances. 

Oh, I just realised that's my issue :D

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
