### ISSUE TITLE
sentry-ingest-consumer not work, error: Broker: Invalid replication factor 

### ISSUE THREAD

**Issue by jk2K** [sentry-kubernetes/charts#271]
got error
```
/usr/local/lib/python3.6/site-packages/sentry/runner/initializer.py:189: DeprecatedSettingWarning: The EMAIL_USE_SSL setting is deprecated. Please use SENTRY_OPTIONS['mail.use-ssl'] instead.
  warnings.warn(DeprecatedSettingWarning(options_mapper[k], "SENTRY_OPTIONS['%s']" % k))
08:27:15 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
08:27:18 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'postprocess.use-cache-key'
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/decorators.py", line 68, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/run.py", line 488, in ingest_consumer
    get_ingest_consumer(consumer_types=consumer_types, **options).run()
  File "/usr/local/lib/python3.6/site-packages/sentry/ingest/ingest_consumer.py", line 277, in get_ingest_consumer
    topic_names=topic_names, worker=IngestConsumerWorker(), **options
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/kafka.py", line 78, in create_batching_kafka_consumer
    **options
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/batching_kafka_consumer.py", line 195, in __init__
    queued_min_messages,
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/batching_kafka_consumer.py", line 240, in create_consumer
    wait_for_topics(admin_client, topics)
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/batching_kafka_consumer.py", line 61, in wait_for_topics
    % (topic, topic_metadata.error)
RuntimeError: Unknown error when waiting for Kafka topic 'ingest-transactions': KafkaError{code=INVALID_REPLICATION_FACTOR,val=38,str="Broker: Invalid replication
```

sentry/sentry

Chart Version: 8.1.0

App Version: 20.12.1

**Comment by jk2K** [comment]
ingore, I have successfully installed sentry in [GCP](https://cloud.google.com/kubernetes-engine/?_ga=2.213681236.-1104575422.1608632604).

reason: my previous k8s cluster does not have enough disk space  to provision pv, which cause the initialization to be abnormal and fails to install successfully
