### ISSUE TITLE
Failed to upgrade from 8.0.0 to 8.1.0

### ISSUE THREAD

**Issue by leo108** [sentry-kubernetes/charts#273]
`helm upgrade --atomic --namespace sentry sentry -f sentry.yaml sentry/sentry`

Job `sentry-snuba-db-init` failed

```
2020-12-27 01:38:57,407 Using Kafka with ()
2020-12-27 01:38:57,408 Attempting to connect to Kafka (attempt 0)
2020-12-27 01:38:57,563 Adding topic ingest-sessions to creation list
2020-12-27 01:38:57,564 Adding topic cdc to creation list
2020-12-27 01:38:57,564 Adding topic events to creation list
2020-12-27 01:38:57,564 Adding topic errors-replacements to creation list
2020-12-27 01:38:57,564 Adding topic event-replacements to creation list
2020-12-27 01:38:57,564 Adding topic snuba-commit-log to creation list
2020-12-27 01:38:57,565 Adding topic outcomes to creation list
2020-12-27 01:38:57,566 Initiating topic creation
2020-12-27 01:38:57,576 Failed to create topic ingest-sessions
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'ingest-sessions' already exists."}
2020-12-27 01:38:57,576 Failed to create topic cdc
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'cdc' already exists."}
2020-12-27 01:38:57,577 Failed to create topic events
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'events' already exists."}
2020-12-27 01:38:57,577 Failed to create topic errors-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'errors-replacements' already exists."}
2020-12-27 01:38:57,577 Failed to create topic event-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'event-replacements' already exists."}
2020-12-27 01:38:57,577 Failed to create topic snuba-commit-log
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'snuba-commit-log' already exists."}
2020-12-27 01:38:57,577 Failed to create topic outcomes
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'outcomes' already exists."}
2020-12-27 01:38:57,578 Attempting to connect to Clickhouse cluster sentry-clickhouse-0.sentry-clickhouse-headless:9000 (attempt 0)
2020-12-27 01:38:57,578 Connecting. Database: default. User: default
2020-12-27 01:38:57,582 Connected to ClickHouse server version 19.17.10, revision: 54428
2020-12-27 01:38:57,590 Query: SELECT 1
2020-12-27 01:38:57,590 Block send time: 0.000086
2020-12-27 01:38:57,592 Query: SELECT group, migration_id, status FROM migrations_local FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'sessions')
2020-12-27 01:38:57,592 Block send time: 0.000079
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 98, in bootstrap
    Runner().run_all(force=True)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 132, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 257, in _get_pending_migrations
    raise MigrationInProgress(migration_key)
snuba.migrations.errors.MigrationInProgress: transactions: 0008_transactions_add_timestamp_index
```

**Comment by DandyDeveloper** [comment]
Those topic errors should be red herrings, it's that last migration error that concerns me. Maybe Kafka is in a weird state from a previous migration and is stuck in a loop? 

If you don't mind loosing some events/documents, I'd recommend just deleting the kafka PVC, restarting the pod to have a fresh kafka state, then run those migrations again. It's relatively painless / should have no impact on Sentry itself.

**Comment by Mokto** [comment]
I'll close, please reopen if needed.

**Comment by theophanevie** [comment]
I got the same issue when i tried to do a fresh install with `9.0.0`

```install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/moonkey/.cache/helm/repository/sentry-9.0.0.tgz

client.go:122: [debug] creating 53 resource(s)
client.go:282: [debug] Starting delete for "sentry-1612891574-db-check" Job
client.go:311: [debug] jobs.batch "sentry-1612891574-db-check" not found
client.go:122: [debug] creating 1 resource(s)
client.go:491: [debug] Watching for changes to Job sentry-1612891574-db-check with timeout of 5m0s
client.go:519: [debug] Add/Modify event for sentry-1612891574-db-check: ADDED
client.go:558: [debug] sentry-1612891574-db-check: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for sentry-1612891574-db-check: MODIFIED
client.go:558: [debug] sentry-1612891574-db-check: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for sentry-1612891574-db-check: MODIFIED
client.go:282: [debug] Starting delete for "sentry-1612891574-snuba-db-init" Job
client.go:311: [debug] jobs.batch "sentry-1612891574-snuba-db-init" not found
client.go:122: [debug] creating 1 resource(s)
client.go:491: [debug] Watching for changes to Job sentry-1612891574-snuba-db-init with timeout of 5m0s
client.go:519: [debug] Add/Modify event for sentry-1612891574-snuba-db-init: ADDED
client.go:558: [debug] sentry-1612891574-snuba-db-init: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for sentry-1612891574-snuba-db-init: MODIFIED
client.go:558: [debug] sentry-1612891574-snuba-db-init: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for sentry-1612891574-snuba-db-init: MODIFIED
client.go:282: [debug] Starting delete for "sentry-1612891574-snuba-migrate" Job
client.go:311: [debug] jobs.batch "sentry-1612891574-snuba-migrate" not found
client.go:122: [debug] creating 1 resource(s)
client.go:491: [debug] Watching for changes to Job sentry-1612891574-snuba-migrate with timeout of 5m0s
client.go:519: [debug] Add/Modify event for sentry-1612891574-snuba-migrate: ADDED
client.go:558: [debug] sentry-1612891574-snuba-migrate: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for sentry-1612891574-snuba-migrate: MODIFIED
client.go:558: [debug] sentry-1612891574-snuba-migrate: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for sentry-1612891574-snuba-migrate: MODIFIED
client.go:558: [debug] sentry-1612891574-snuba-migrate: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for sentry-1612891574-snuba-migrate: MODIFIED
client.go:558: [debug] sentry-1612891574-snuba-migrate: Jobs active: 1, jobs failed: 2, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for sentry-1612891574-snuba-migrate: MODIFIED
client.go:558: [debug] sentry-1612891574-snuba-migrate: Jobs active: 1, jobs failed: 3, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for sentry-1612891574-snuba-migrate: MODIFIED
client.go:558: [debug] sentry-1612891574-snuba-migrate: Jobs active: 1, jobs failed: 4, jobs succeeded: 0
Error: failed post-install: timed out waiting for the condition
helm.go:81: [debug] failed post-install: timed out waiting for the condition
```

the error log got from the first pods
```Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 50, in migrate
    runner.run_all(force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 132, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 257, in _get_pending_migrations
    raise MigrationInProgress(migration_key)
snuba.migrations.errors.MigrationInProgress: transactions: 0008_transactions_add_timestamp_index```

Any idea ? it would be a great help to me :see_no_evil:

**Comment by theophanevie** [comment]
It doesn't seem to be deterministic. I deleted everything and then started again and it works fine.

**Comment by leo108** [comment]
Fixed by deleted clickhouse PVCs

**Comment by mekza** [comment]
Note that clickhouse docker image is running a `chown` on the data directory everytime it starts (c.f https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/entrypoint.sh#L73). This operation can lead OOM. Maybe @Mokto you should re-open the issue while someone adds a way in clickhouse chart to control that, what do you think?

**Comment by Mokto** [comment]
Sure, but I would open another issue.

TBH, my knowledge in Clickhouse is far too limited ;)

**Comment by mekza** [comment]
Indeed

**Comment by DandyDeveloper** [comment]
It'll just be a case of adding the env var into the chart. Open a new issue for it, probably worthwhile:

https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/entrypoint.sh#L6-L9

**Comment by mekza** [comment]
Yes
