### ISSUE TITLE
DNS issues on K8s 1.19+

### ISSUE THREAD

**Issue by jadbaz** [sentry-kubernetes/charts#276]
I tried this chart (8.0.0) with [K3s](https://github.com/k3s-io/k3s) 1.18, 1.19 and 1.20
It only works on 1.18
I haven't yet tried it on a different K8s engine with these versions.
But I expect the issue is with the chart itself and not K8s.

The issue is that rabbitmq and kafka are not starting
 
```
NAMESPACE     NAME                                      READY   STATUS             RESTARTS   AGE
kube-system   local-path-provisioner-7c458769fb-2rb2d   1/1     Running            0          9m43s
kube-system   helm-install-traefik-ck7f2                0/1     Completed          0          9m43s
kube-system   coredns-854c77959c-q5wp5                  1/1     Running            0          9m43s
kube-system   svclb-traefik-g2frk                       2/2     Running            0          9m16s
kube-system   metrics-server-86cbb8457f-vlnxv           1/1     Running            0          9m43s
kube-system   traefik-6f9cbd9bd4-fg5jc                  1/1     Running            0          9m16s
sentry        sentry-snuba-api-78588cbf45-g7r5s         1/1     Running            0          4m35s
sentry        sentry-zookeeper-0                        1/1     Running            0          4m35s
sentry        sentry-sentry-postgresql-0                1/1     Running            0          4m35s
sentry        sentry-sentry-redis-master-0              1/1     Running            0          4m35s
sentry        sentry-clickhouse-0                       1/1     Running            0          4m35s
sentry        sentry-clickhouse-tabix-5564dc468-ppdgv   1/1     Running            0          4m35s
sentry        sentry-clickhouse-replica-2               1/1     Running            0          4m35s
sentry        sentry-clickhouse-replica-0               1/1     Running            0          4m35s
sentry        sentry-clickhouse-replica-1               1/1     Running            0          4m35s
sentry        sentry-clickhouse-1                       1/1     Running            0          4m35s
sentry        sentry-clickhouse-2                       1/1     Running            0          4m35s
sentry        sentry-nginx-79b8cf6989-l2xbt             0/1     CrashLoopBackOff   5          4m35s
sentry        sentry-kafka-0                            0/1     CrashLoopBackOff   4          4m35s
sentry        sentry-kafka-2                            0/1     CrashLoopBackOff   4          4m34s
sentry        sentry-sentry-redis-slave-0               0/1     Running            2          4m35s
sentry        sentry-kafka-1                            0/1     CrashLoopBackOff   4          4m34s
sentry        sentry-rabbitmq-0                         0/1     CrashLoopBackOff   4          4m35s
sentry        sentry-ingest-consumer-7c66c4bb95-m6x8q   0/1     CrashLoopBackOff   3          4m35s
sentry        sentry-cron-56c58d75b7-mj4bg              0/1     CrashLoopBackOff   3          4m35s
sentry        sentry-worker-b66bd8888-pcwj9             0/1     CrashLoopBackOff   3          4m35s
sentry        sentry-web-dcbdbd44b-t5wx8                0/1     CrashLoopBackOff   4          4m35s
```

The logs indicate a DNS issue

sentry-kafka-0 logs:
```
[2021-01-01 15:36:57,082] ERROR Unable to resolve address: sentry-zookeeper:2181 (org.apache.zookeeper.client.StaticHostProvider)
java.net.UnknownHostException: sentry-zookeeper
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
        at org.apache.zookeeper.client.StaticHostProvider$1.getAllByName(StaticHostProvider.java:92)
        at org.apache.zookeeper.client.StaticHostProvider.resolve(StaticHostProvider.java:147)
        at org.apache.zookeeper.client.StaticHostProvider.next(StaticHostProvider.java:375)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1137)
```

sentry-rabbitmq-0 logs:

```
2021-01-01 15:35:54.888 [info] <0.275.0> Failed to get nodes from k8s - {failed_connect,[{to_address,{"kubernetes.default.svc.cluster.local",443}},
                 {inet,[inet],nxdomain}]}
2021-01-01 15:35:54.889 [error] <0.274.0> CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: no case clause matching {error,"{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",443}},\n                 {inet,[inet],nxdomain}]}"} in rabbit_mnesia:init_from_config/0 line 140 in application_master:init/4 line 138
```

This relates to [k3s-io/k3s/issues/2766](https://github.com/k3s-io/k3s/issues/2766)

**Comment by DandyDeveloper** [comment]
@jadbaz What happens if you try the FQDN of `service.namespace.svc.cluster.local` from a random pod elsewhere on your cluster? 

Since CoreDNS should be managing the internal k8s resolution, this sounds like a deployment bug, perhaps in the CoreDNS configuration? 

What do the CoreDNS pods in the `kube-system` namespace say? Logs may indicate some failures and the reason why. 

I don't think this is a chart issue, just to be clear.

**Comment by jadbaz** [comment]
I don't have the setup to try this anymore
Will need some time to set it up again
In any case, can anyone try this on any K8s 1.19+ (other than k3s)
If it shows the same behavior, then it must be a chart issue. If not, then the issue is with k3s.

**Comment by JMSwag** [comment]
~I'm also seeing this issue on DO K8s v1.20. All was well on v1.18.~

~Note: I was able to bring up sentry by using an external Kafka cluster from the bitnami helm chart.~

It seems as the particular chart version I was using was causing my issue. v11.0.0 works without issue on K8s 1.20

**Comment by Mokto** [comment]
I just upgraded to 1.19, and AFAIK, everything seems fine.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
