### ISSUE TITLE
ModuleNotFoundError: No module named 'mail'

### ISSUE THREAD

**Issue by thanhtoan1196** [sentry-kubernetes/charts#297]
Logs from worker

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/base.py", line 48, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/email.py", line 76, in send_email
    send_messages([message])
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/email.py", line 407, in send_messages
    connection = get_connection(fail_silently=fail_silently)
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/email.py", line 440, in get_connection
    fail_silently=fail_silently,
  File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 36, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mail'
05:42:24 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[bff98705-1192-4bc4-b89d-cbcab2d8864e] raised unexpected: ModuleNotFoundError("No module named 'mail'",) (data={'hostname': 'sentry-worker-7f946dbdc-sjzs9', 'id': 'bff98705-1192-4bc4-b89d-cbcab2d8864e', 'name': 'sentry.tasks.email.send_email', 'exc': 'ModuleNotFoundError("No module named \'mail\'",)', 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/base.py", line 48, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/email.py", line 76, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.6/site-packages/sentry/utils/email.py", line 407, in send_messages\n    connection = get_connection(fail_silently=fail_silently)\n  File "/usr/local/lib/python3.6/site-packages/sentry/utils/email.py", line 440, in get_connection\n    fail_silently=fail_silently,\n  File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 36, in get_connection\n    klass = import_string(backend or settings.EMAIL_BACKEND)\n  File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string\n    module = import_module(module_path)\n  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 994, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 971, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n  File "<frozen importlib._bootstrap>", line 994, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 971, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked\nModuleNotFoundError: No module named \'mail\'\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f1b99ab1e80>}", 'description': 'raised unexpected', 'internal': False})
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
