### ISSUE TITLE
"Enable JavaScript source fetching" makes Sentry unsuable

### ISSUE THREAD

**Issue by scoopex** [sentry-kubernetes/charts#392]
If i activate "Enable JavaScript source fetching" in my javascript project, sentry globally stops processing of event after a few hours.
"sentry-worker" print millions of messages which look like this:

```
sentry-worker-58469dc5d-qwmqg sentry-worker 21:15:56 [WARNING] sentry.http: source.disabled (type='too_large_for_cache' url='https://obfuscated.foobar.com/polyfills-es2015.ba86aeb7228abd9b40ae.js')
sentry-worker-58469dc5d-qwmqg sentry-worker 21:15:56 [WARNING] sentry.http: source.disabled (type='too_large_for_cache' url='https://obfuscated.foobar.com/polyfills-es2015.ba86aeb7228abd9b40ae.js')
sentry-worker-58469dc5d-qwmqg sentry-worker 21:15:56 [WARNING] sentry.http: source.disabled (type='too_large_for_cache' url='https://obfuscated.foobar.com/polyfills-es2015.ba86aeb7228abd9b40ae.js')
```

I checked the files:
- this happens for high numbers of files, probably all javascript files
- the file are downloadable without a problem
- the files are only ~40kb sized, the larges file in my setup is 2MB
- the corresponding sourcemap file can be downloaded without a problem (~190KB)

Sentry-Worker seems to be a uwsgi server, is it necessary to create configuration for the wsgi server to work with larger payloads?

**Comment by Mokto** [comment]
What filestore type are you using ? filesystem?

**Comment by scoopex** [comment]
Yes i suppose that is the case. We are using the default of "https://github.com/sentry-kubernetes/charts/tree/develop/sentry".
This means that /var/lib/sentry/files is mounted of type EmptyDir (recreated on every deployment and it does not contain any files)

**Comment by Mokto** [comment]
I would really recommend using a different filestore system.

filesystem can't scale properly.

**Comment by scoopex** [comment]
iThere are no files visible in the pod. I am not sure what type of filestore is used.

The startup messages of the pod
```
sentry-worker-76b49cdb9-6xpxq sentry-worker Please specify a different user using the --uid option.
sentry-worker-76b49cdb9-6xpxq sentry-worker 
sentry-worker-76b49cdb9-6xpxq sentry-worker User information: uid=0 euid=0 gid=0 egid=0
sentry-worker-76b49cdb9-6xpxq sentry-worker 
sentry-worker-76b49cdb9-6xpxq sentry-worker   uid=uid, euid=euid, gid=gid, egid=egid,
sentry-worker-76b49cdb9-6xpxq sentry-worker  -------------- celery@sentry-worker-76b49cdb9-6xpxq v4.4.7 (cliffs)
sentry-worker-76b49cdb9-6xpxq sentry-worker --- ***** ----- 
sentry-worker-76b49cdb9-6xpxq sentry-worker -- ******* ---- Linux-5.4.0-1040-azure-x86_64-with-debian-10.9 2021-05-26 08:37:18
sentry-worker-76b49cdb9-6xpxq sentry-worker - *** --- * --- 
sentry-worker-76b49cdb9-6xpxq sentry-worker - ** ---------- [config]
sentry-worker-76b49cdb9-6xpxq sentry-worker - ** ---------- .> app:         sentry:0x7f92d7d1a4a8
sentry-worker-76b49cdb9-6xpxq sentry-worker - ** ---------- .> transport:   amqp://guest:**@sentry-rabbitmq:5672//
sentry-worker-76b49cdb9-6xpxq sentry-worker - ** ---------- .> results:     disabled://
sentry-worker-76b49cdb9-6xpxq sentry-worker - *** --- * --- .> concurrency: 8 (prefork)
sentry-worker-76b49cdb9-6xpxq sentry-worker -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
sentry-worker-76b49cdb9-6xpxq sentry-worker --- ***** ----- 
sentry-worker-76b49cdb9-6xpxq sentry-worker  -------------- [queues]
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> activity.notify  exchange=default(direct) key=activity.notify
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> alerts           exchange=default(direct) key=alerts
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> app_platform     exchange=default(direct) key=app_platform
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> assemble         exchange=default(direct) key=assemble
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> auth             exchange=default(direct) key=auth
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> buffers.process_pending exchange=default(direct) key=buffers.process_pending
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> cleanup          exchange=default(direct) key=cleanup
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> commits          exchange=default(direct) key=commits
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> counters-0       exchange=counters(direct) key=default
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> data_export      exchange=default(direct) key=data_export
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> default          exchange=default(direct) key=default
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> digests.delivery exchange=default(direct) key=digests.delivery
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> digests.scheduling exchange=default(direct) key=digests.scheduling
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> email            exchange=default(direct) key=email
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> events.preprocess_event exchange=default(direct) key=events.preprocess_event
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> events.process_event exchange=default(direct) key=events.process_event
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> events.reprocess_events exchange=default(direct) key=events.reprocess_events
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> events.reprocessing.preprocess_event exchange=default(direct) key=events.reprocessing.preprocess_event
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> events.reprocessing.process_event exchange=default(direct) key=events.reprocessing.process_event
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> events.reprocessing.symbolicate_event exchange=default(direct) key=events.reprocessing.symbolicate_event
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> events.save_event exchange=default(direct) key=events.save_event
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> events.symbolicate_event exchange=default(direct) key=events.symbolicate_event
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> files.delete     exchange=default(direct) key=files.delete
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> group_owners.process_suspect_commits exchange=default(direct) key=group_owners.process_suspect_commits
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> incident_snapshots exchange=default(direct) key=incident_snapshots
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> incidents        exchange=default(direct) key=incidents
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> integrations     exchange=default(direct) key=integrations
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> merge            exchange=default(direct) key=merge
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> options          exchange=default(direct) key=options
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> relay_config     exchange=default(direct) key=relay_config
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> reports.deliver  exchange=default(direct) key=reports.deliver
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> reports.prepare  exchange=default(direct) key=reports.prepare
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> search           exchange=default(direct) key=search
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> sleep            exchange=default(direct) key=sleep
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> stats            exchange=default(direct) key=stats
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> subscriptions    exchange=default(direct) key=subscriptions
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> triggers-0       exchange=triggers(direct) key=default
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> unmerge          exchange=default(direct) key=unmerge
sentry-worker-76b49cdb9-6xpxq sentry-worker                 .> update           exchange=default(direct) key=update

sentry-worker-76b49cdb9-6xpxq sentry-worker Traceback (most recent call last):
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
sentry-worker-76b49cdb9-6xpxq sentry-worker     (self._dns_host, self.port), self.timeout, **extra_kw)
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
sentry-worker-76b49cdb9-6xpxq sentry-worker     raise err
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
sentry-worker-76b49cdb9-6xpxq sentry-worker     sock.connect(sa)
sentry-worker-76b49cdb9-6xpxq sentry-worker ConnectionRefusedError: [Errno 111] Connection refused
sentry-worker-76b49cdb9-6xpxq sentry-worker 
sentry-worker-76b49cdb9-6xpxq sentry-worker During handling of the above exception, another exception occurred:
sentry-worker-76b49cdb9-6xpxq sentry-worker 
sentry-worker-76b49cdb9-6xpxq sentry-worker Traceback (most recent call last):
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
sentry-worker-76b49cdb9-6xpxq sentry-worker     chunked=chunked)
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
sentry-worker-76b49cdb9-6xpxq sentry-worker     conn.request(method, url, **httplib_request_kw)
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/http/client.py", line 1287, in request
sentry-worker-76b49cdb9-6xpxq sentry-worker     self._send_request(method, url, body, headers, encode_chunked)
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/http/client.py", line 1333, in _send_request
sentry-worker-76b49cdb9-6xpxq sentry-worker     self.endheaders(body, encode_chunked=encode_chunked)
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/http/client.py", line 1282, in endheaders
sentry-worker-76b49cdb9-6xpxq sentry-worker     self._send_output(message_body, encode_chunked=encode_chunked)
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/http/client.py", line 1042, in _send_output
sentry-worker-76b49cdb9-6xpxq sentry-worker     self.send(msg)
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/http/client.py", line 980, in send
sentry-worker-76b49cdb9-6xpxq sentry-worker     self.connect()
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
sentry-worker-76b49cdb9-6xpxq sentry-worker     conn = self._new_conn()
sentry-worker-76b49cdb9-6xpxq sentry-worker   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
sentry-worker-76b49cdb9-6xpxq sentry-worker     self, "Failed to establish a new connection: %s" % e)
sentry-worker-76b49cdb9-6xpxq sentry-worker urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f92c834e048>: Failed to establish a new connection: [Errno 111] Connection refused
sentry-worker-76b49cdb9-6xpxq sentry-worker 

```

**Comment by scoopex** [comment]
With chart version 12.0.0 you can run Sentry with activated Sourcemaps fetching again.
Unfortunately it is still not capable to fetch simple sourcemaps which a usual size of 2MB.
```
sentry-worker-5f9c664584-48gz5 sentry-worker 08:29:24 [WARNING] sentry.http: source.disabled (type='too_large_for_cache' url='https://REDACTED/vendor-es2015.0aa7897503a066670eaf.js')
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
