### ISSUE TITLE
sentry-snuba-api pod not starting

### ISSUE THREAD

**Issue by UbiquitousBear** [sentry-kubernetes/charts#396]
The pod seems to be in the state `CrashLoopBackOff`. 

Logs:
```
kubectl logs -f sentry-snuba-api-<id>
./docker_entrypoint.sh: line 15: exec: api: not found
```

Node system info:

```
System Info:
  Kernel Version:             4.19.0-0.bpo.16-amd64
  OS Image:                   Debian GNU/Linux 9 (stretch)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.4.3
  Kubelet Version:            v1.21.1
  Kube-Proxy Version:         v1.21.1
```

The node is an on-premise node, so not a cloud host. 

I tried running the pod manually with: `kubectl run sentry-db-check --image=getsentry/snuba:latest` however it still fails with the same error as above. 

It seems to run if I manually start it using `ctr`:
```
# ctr image pull docker.io/getsentry/snuba:latest

# ctr run docker.io/getsentry/snuba:latest snuba-api
*** Starting uWSGI 2.0.18 (64bit) on [Thu May 27 19:49:54 2021] ***
compiled with version: 8.3.0 on 13 May 2021 22:46:50
os: Linux-4.19.0-0.bpo.16-amd64 #1 SMP Debian 4.19.181-1~deb9u1 (2021-03-29)
nodename: ldn-lp-k8s-00-node
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 32
current working directory: /usr/src/snuba
detected binary path: /usr/local/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:1218 fd 3
Python version: 3.8.10 (default, May 12 2021, 15:56:47)  [GCC 8.3.0]
Set PythonHome to /usr/local
Python main interpreter initialized at 0x5589192747e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
initialized 38 metrics
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 14, cores: 1)
metrics collector thread started
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5589192747e0 pid: 14 (default app)

# ctr i rm docker.io/getsentry/snuba:latest
...



```

**Comment by brogger71** [comment]
exact same issue here. Did you find a solution? I tried different chart versions, different snuba images, no success.

**Comment by aca** [comment]
@UbiquitousBear @brogger71 Hi, do you have any updates on this issue?

**Comment by brogger71** [comment]
@aca i could solve the problem with removing "gosu" in "docker_entrypoint.sh". Therefor ok for me.

**Comment by trgkyle** [comment]
i have the same error, @brogger71 so needs to fork this repo ?

**Comment by brogger71** [comment]
@truonghdpk as written above, removing "gosu" in "docker_entrypoint.sh" did the trick for me. Not sure if that is worth forking the repo.

**Comment by iburrows** [comment]
I am receiving the same but in db init I receive the following
```
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/bin/snuba", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/snuba/snuba/cli/__init__.py", line 21, in <module>
    module = __import__(module_name, globals(), locals(), ["__name__"])
  File "/usr/src/snuba/snuba/cli/admin.py", line 6, in <module>
    from snuba.environment import setup_logging
  File "/usr/src/snuba/snuba/environment.py", line 13, in <module>
    from snuba import settings
  File "/usr/src/snuba/snuba/settings/__init__.py", line 225, in <module>
    _validate_settings(locals())
  File "/usr/src/snuba/snuba/settings/validation.py", line 58, in _validate_settings
    storage_set_to_cluster[StorageSetKey(cluster_storage_set)] = cluster
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 663, in __new__
    raise ve_exc
ValueError: 'errors_v2_ro' is not a valid StorageSetKey
```
which is referenced in the snuba configmap. Removing errors_v2 and errors_v2_ro from the configmap "fixes" this and snuba api can start.

Looks like the storage sets are not compatible.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
