### ISSUE TITLE
Error during upgrade: needed to specify '--bootstrap-server' argument to snuba bootstrap in snuba-db-init

### ISSUE THREAD

**Issue by jwoglom** [sentry-kubernetes/charts#413]
I ran into an issue while upgrading the Sentry version in my deployment from 21.4 to 21.5.1 where the following error messages scrolled indefinitely in the snuba-db-init batch job:

```
2021-06-11 14:03:44,070 Using Kafka with ()
2021-06-11 14:03:44,071 Attempting to connect to Kafka (attempt 0)...
%3|1623420224.075|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1623420225.075|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2021-06-11 14:03:45,075 Connection to Kafka failed (attempt 0)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 69, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
2021-06-11 14:03:46,076 Attempting to connect to Kafka (attempt 1)...
%3|1623420226.078|FAIL|rdkafka#producer-2| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1623420227.078|FAIL|rdkafka#producer-2| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2021-06-11 14:03:47,079 Connection to Kafka failed (attempt 1)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 69, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
```

The root cause seemed to be that `snuba bootstrap` in snuba-db-init was not properly getting the address of the Kafka cluster. I fixed it by modifying the `snuba bootstrap --force` inside the for loop in the snuba-init container to also include `--bootstrap-server 'sentry-kafka:9092'`. After this, the snuba-db-init batch job functioned properly and the upgrade succeeded.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
