### ISSUE TITLE
[Raven] Unable to record event with remote Sentry server (Raven::Error - the server responded with status 403)

### ISSUE THREAD

**Issue by billakuduru** [sentry-kubernetes/charts#427]
Hello,

I am getting this error while running the helm chart on my EKS cluster.

** [Raven] Unable to record event with remote Sentry server (Raven::Error - the server responded with status 403):
/usr/lib/ruby/gems/2.7.0/gems/sentry-raven-3.1.2/lib/raven/transports/http.rb:33:in `rescue in send_event'
/usr/lib/ruby/gems/2.7.0/gems/sentry-raven-3.1.2/lib/raven/transports/http.rb:14:in `send_event'
/usr/lib/ruby/gems/2.7.0/gems/sentry-raven-3.1.2/lib/raven/client.rb:47:in `send_event'
/usr/lib/ruby/gems/2.7.0/gems/sentry-raven-3.1.2/lib/raven/instance.rb:83:in `send_event'
/usr/lib/ruby/gems/2.7.0/gems/sentry-raven-3.1.2/lib/raven/instance.rb:131:in `capture_type'
/usr/lib/ruby/2.7.0/forwardable.rb:235:in `capture_message'
/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-raven-0.1.4/lib/fluent/plugin/out_raven.rb:49:in `block in write'
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/event.rb:315:in `each'
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/event.rb:315:in `block in each'
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/plugin/buffer/file_chunk.rb:171:in `open'
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.4/lib/fluent/event.rb:314:in `each'
W, [2021-06-28T09:59:30.228826 #15]  WARN -- sentry: ** [Raven] Failed to submit event: starting fluentd worker pid=15 ppid=6 worker=0
W, [2021-06-28T09:59:30.229542 #15]  WARN -- sentry: ** [Raven] Not sending event due to previous failure(s).

Can anyone help me with this?

**Comment by billakuduru** [comment]
I finally able to resolve the issue,

The problem is in the relay section.
set mode: proxy in the relay section of the values.yaml worked for me

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
