### ISSUE TITLE
Migration sentry.0201_semver_package is applied before its dependency sentry.0001_squashed_0200_release_indices on database 'default'

### ISSUE THREAD

**Issue by oleksiibarabash** [sentry-kubernetes/charts#442]
Hello,
While trying to upgrade from version 11.4.1 to 11.5.0, I’m getting the following error:

```
08:43:25 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
08:43:29 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 196, in main
    func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 103, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 59, in _upgrade
    ignore_ghost_migrations=True,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor.loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 299, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration sentry.0201_semver_package is applied before its dependency sentry.0001_squashed_0200_release_indices on database 'default'.
```

Please, let me know if additional info is needed.
Thank you!

**Comment by echel0n** [comment]
I'm getting this same issue right now as well

**Comment by kuzaxak** [comment]
You need to upgrade to 21.6.3 from 21.6.1 first, and only then to 21.7.0 

https://github.com/getsentry/onpremise/issues/1043

**Comment by kuzaxak** [comment]
As a quick fix you can run the upgrade job to 21.6.3 separately:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: sentry-db-init-6
  namespace: support
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: sentry-db-init
    spec:
      containers:
      - command:
        - sentry
        - upgrade
        - --noinput
        image: getsentry/sentry:21.6.3
        imagePullPolicy: IfNotPresent
        name: db-init-job
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 300m
            memory: 2Gi
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: sentry-sentry
        name: config
```

**Comment by echel0n** [comment]
That fixed it, thanks!

**Comment by oleksiibarabash** [comment]
Thanks, it works!
