### ISSUE TITLE
django.security.csrf: Forbidden (CSRF cookie not set.): 

### ISSUE THREAD

**Issue by joker-bai** [sentry-kubernetes/charts#467]
When pushing  events, the following error is reported，what's wrong？

```
django.security.csrf: Forbidden (CSRF cookie not set.): /api/2/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/2/envelope/?sentry_key=97f57897affd420eb69fa7913fe64ec8&sentry_version=7'>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/../urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/sentry/../urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/sentry/../urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

ENV:
```
helm: 3.6.3
kubernetes: 1.17.17
chart: 11.6.0
appversion: 21.7.0
```

**Comment by prskr** [comment]
Are these events coming from an external system via an ingress controller and if so which ingress controller are you using?

**Comment by garettmd** [comment]
I'm getting this error as well. I have `nginx.enabled = true` and `ingress.enabled = false`. Alerts are coming from another django app. All the similar issues I could find here alluded to the nginx (that comes sentry-kubernetes) needing the `proxy_redirect` and `proxy_set_header` directives, but those are set in my case.

**Comment by prskr** [comment]
I think I was missing an [annotation](https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/#regular-expression-support) that actually made the HTTP rules working.
Probably give it a shot?

**Comment by garettmd** [comment]
I'm not using ingress, just nginx for pod to pod communication, so that wouldn't apply in my case

**Comment by bhargavsunkara9** [comment]
@garettmd : I have a similar issues, were you able to figure out a solution?

**Comment by garettmd** [comment]
@bhargavsunkara9 - I wasn't, I figured out some workaround, but I don't remember what it was

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
