### ISSUE TITLE
smtp settings

### ISSUE THREAD

**Issue by jiwanovski87** [sentry-kubernetes/charts#498]
Hi everybody,

I have created a self hosted sentry with these charts. Currently I am not able to invite members. 
I believe the problem is the mail settings. 

In the documentation it is written, das there should be a build in smtp. To use this, you should only mail.from.
See [here](https://develop.sentry.dev/self-hosted/email/). 

What am I making wrong?
Any tipps?

**Comment by sagor999** [comment]
Did you look at this settings:
https://github.com/sentry-kubernetes/charts/blob/1cd02c0984596c9f64a5b607a97f67fc98e7c2f6/sentry/values.yaml#L453
And did you set them up correctly?

**Comment by jiwanovski87** [comment]
@sagor999 yes I looked at these ones and I set ```mail.from``` as described [here](https://develop.sentry.dev/self-hosted/email/).

The question is, what else should I setup there, to use the build-in mail feature?
I believe ```mail.backend = dummy``` (default) is not correct. But ```mail.backend = smtp``` haven't worked for me yet. 

So what are the correct settings of the ```mail``` block to enable the build-in mail feature?

**Comment by sagor999** [comment]
Check worker logs and other sentry pods (not sure which one is actually responsible for sending email) and I hope there should be an error there that might explain why your settings are not working.
For me I have this and it is working (but it all depends on your smtp server):
```
mail:
  backend: smtp
  useTls: false
  username: secret
  password: secret
  port: 25
  host: "smtp.secret.com"
  from: "sentry@secret.com"
```

**Comment by jiwanovski87** [comment]
Well my original goal is not to use an external smtp server.

My linked [documentation](https://develop.sentry.dev/self-hosted/email/) is telling that there is a ```Self-hosted Sentry ships with a built-in outgoing SMTP server powered by exim4.``` So I would like to use this build-in feature instead of using another external smtp. 

So I still wonder how I can configure this. The documentation is only telling to set ```mail.from``` but this is not working.

**Comment by sagor999** [comment]
Oh. I am not familiar with that option at all. :(
But looking at:
https://github.com/getsentry/onpremise/blob/master/sentry/config.example.yml
Also did not shed any light into how that option is exactly setup. 
Maybe browse through that repo to see how they setup `exim4`.

**Comment by lapwat** [comment]
@jiwanovski87 Did you manage to use internal smtp server ?

**Comment by jiwanovski87** [comment]
@lapwat no I was not able to find the correct configuration to enable the internal smtp server.
We are now using an external smtp.

**Comment by lapwat** [comment]
Cool can you share your config here please ? I do not receive any email with mine when I try to reset my password.

```yml
mail:
  backend: smtp
  useTls: true
  useSsl: false
  username: x.y@gmail.com
  password: xxx
  port: 587
  host: smtp.gmail.com
  from: x.y@gmail.com
```

**Comment by jiwanovski87** [comment]
We have setup office365 as smtp. But it looks very similar.
```yaml
mail:
    backend: smtp
    useTls: true
    useSsl: false
    username: XXX@XXX.com
    password: XXX
    port: 587
    host: smtp.office365.com
    from: XXX@XXX.com
```

I believe I have read that there could be some different understandings ins the setting of Tls and Ssl. 
Maybe you play a bit with these values to find the correct for gmail.

**Comment by lapwat** [comment]
I have this error in my logs:

```txt
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/base.py", line 46, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/email.py", line 73, in send_email
    send_messages([message])
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/email.py", line 409, in send_messages
    sent = connection.send_messages(messages)
  File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
16:57:58 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[c4109c18-1c6c-4b9a-b533-bc4520cd7727] raised unexpected: timeout('timed out',) (data={'hostname': 'sentry-worker-5cfcf6df98-n9x4t', 'id': 'c4109c18-1c6c-4b9a-b533-bc4520cd7727', 'name': 'sentry.tasks.email.send_email', 'exc': "timeout('timed out',)", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/base.py", line 46, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/email.py", line 73, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.6/site-packages/sentry/utils/email.py", line 409, in send_messages\n    sent = connection.send_messages(messages)\n  File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open\n    self.connection = self.connection_class(self.host, self.port, **connection_params)\n  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__\n    (code, msg) = self.connect(host, port)\n  File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket\n    self.source_address)\n  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection\n    raise err\n  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection\n    sock.connect(sa)\nsocket.timeout: timed out\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7fb36669d160>}", 'description': 'raised unexpected', 'internal': False})
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by not-ajayy** [comment]
Any updates here on using built in smtp server ?

**Comment by lapwat** [comment]
We resolved this issue by disabling the firewall on the port 25 of our server. Some cloud providers block it by default to prevent email abuse.

**Comment by motoki317** [comment]
For those who want to use the "built-in" SMTP server as written in self-hosted document:
> Self-hosted Sentry ships with a built-in outgoing SMTP server powered by [exim4](https://hub.docker.com/r/tianon/exim4).
https://develop.sentry.dev/self-hosted/email/

The "smtp" service is located here in the original self-hosted docker-compose file,
https://github.com/getsentry/self-hosted/blob/9486a832eb80cb2833ea6fa0cbef60c4f1a2bfa9/docker-compose.yml#L92-L99
but a corresponding service is missing in this helm chart.

To use the same SMTP server as self-hosted, run `tianon/exim4` container like follows:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-smtp

spec:
  selector:
    matchLabels:
      app: sentry-smtp

  template:
    metadata:
      labels:
        app: sentry-smtp
    spec:
      volumes:
        - name: sentry-smtp
          emptyDir: {}
        - name: sentry-smtp-log
          emptyDir: {}

      containers:
        - name: smtp
          image: tianon/exim4
          volumeMounts:
            - mountPath: /var/spool/exim4
              name: sentry-smtp
            - mountPath: /var/log/exim4
              name: sentry-smtp-log

---
apiVersion: v1
kind: Service
metadata:
  name: sentry-smtp

spec:
  type: ClusterIP
  selector:
    app: sentry-smtp
  ports:
    - name: smtp
      port: 25
      targetPort: 25
```
and set the values to the following to use this Deployment and Service:
```yaml
mail:
  backend: smtp
  host: sentry-smtp
  from: system@your-self-hosted-domain
```

It may be a good idea to add this Deployment as an optional component in this helm chart.

**Comment by law-lee** [comment]
> For those who want to use the "built-in" SMTP server as written in self-hosted document:
> 
> > Self-hosted Sentry ships with a built-in outgoing SMTP server powered by [exim4](https://hub.docker.com/r/tianon/exim4).
> > https://develop.sentry.dev/self-hosted/email/
> 
> The "smtp" service is located here in the original self-hosted docker-compose file, https://github.com/getsentry/self-hosted/blob/9486a832eb80cb2833ea6fa0cbef60c4f1a2bfa9/docker-compose.yml#L92-L99 but a corresponding service is missing in this helm chart.
> 
> To use the same SMTP server as self-hosted, run `tianon/exim4` container like follows:
> 
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: sentry-smtp
> 
> spec:
>   selector:
>     matchLabels:
>       app: sentry-smtp
> 
>   template:
>     metadata:
>       labels:
>         app: sentry-smtp
>     spec:
>       volumes:
>         - name: sentry-smtp
>           emptyDir: {}
>         - name: sentry-smtp-log
>           emptyDir: {}
> 
>       containers:
>         - name: smtp
>           image: tianon/exim4
>           volumeMounts:
>             - mountPath: /var/spool/exim4
>               name: sentry-smtp
>             - mountPath: /var/log/exim4
>               name: sentry-smtp-log
> 
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: sentry-smtp
> 
> spec:
>   type: ClusterIP
>   selector:
>     app: sentry-smtp
>   ports:
>     - name: smtp
>       port: 25
>       targetPort: 25
> and set the values to the following to use this Deployment and Service:
> 
> mail:
>   backend: smtp
>   host: sentry-smtp
>   from: system@your-self-hosted-domain
> It may be a good idea to add this Deployment as an optional component in this helm chart.

mail.from field should be xxx@localhost. and due to mail.username and mail.user-ssl are empty, when first login we can't be validated by the form. follow the steps of this issue to get pass: https://github.com/getsentry/self-hosted/issues/3186
