### ISSUE TITLE
relation "sentry_discoverkeytransaction" does not exist

### ISSUE THREAD

**Issue by cleveritcz** [sentry-kubernetes/charts#509]
Hello,
I can't see any transactions and I got this error, could someone help me, please?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 75, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.ProgrammingError: relation "sentry_discoverkeytransaction" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "sentry_discoverkeytransac...
                                          ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 75, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.ProgrammingError: ProgrammingError('relation "sentry_discoverkeytransaction" does not exist\nLINE 1: SELECT COUNT(*) AS "__count" FROM "sentry_discoverkeytransac...\n                                          ^\n',)
SQL: SELECT COUNT(*) AS "__count" FROM "sentry_discoverkeytransaction" WHERE ("sentry_discoverkeytransaction"."organization_id" = %s AND "sentry_discoverkeytransaction"."owner_id" = %s AND "sentry_discoverkeytransaction"."project_id" IN (%s, %s, %s))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/api/base.py", line 125, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/sentry/api/base.py", line 241, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/discover/endpoints/discover_key_transactions.py", line 46, in get
    project__in=projects,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 500, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 75, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.ProgrammingError: ProgrammingError('relation "sentry_discoverkeytransaction" does not exist\nLINE 1: SELECT COUNT(*) AS "__count" FROM "sentry_discoverkeytransac...\n                                          ^\n',)
SQL: SELECT COUNT(*) AS "__count" FROM "sentry_discoverkeytransaction" WHERE ("sentry_discoverkeytransaction"."organization_id" = %s AND "sentry_discoverkeytransaction"."owner_id" = %s AND "sentry_discoverkeytransaction"."project_id" IN (%s, %s, %s))
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
