### ISSUE TITLE
[AWS] An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by yurymkomarov** [sentry-kubernetes/charts#514]
Here is my traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 502, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 643, in fetch_credentials
    return self._get_cached_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 653, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 863, in _get_credentials
    return client.assume_role_with_web_identity(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
19:26:45 [WARNING] botocore.credentials: Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/../sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/web/frontend/base.py", line 556, in get
    photo_file = photo.getfile()
  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 348, in getfile
    impl = self._get_chunked_blob(mode, prefetch)
  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 340, in _get_chunked_blob
    delete=delete,
  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 498, in __init__
    self.open()
  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 535, in open
    self.seek(0)
  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 599, in seek
    return self._seek(pos)
  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 595, in _seek
    self._curfile.seek(pos - self._curidx.offset)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/utils.py", line 20, in <lambda>
    seek = property(lambda self: self.file.seek)
  File "/usr/local/lib/python3.6/site-packages/sentry/filestore/s3.py", line 164, in _get_file
    self._file.write(self.obj.get()["Body"].read())
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 573, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 592, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 152, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 232, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 591, in get_frozen_credentials
    self._refresh()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 486, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 502, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 643, in fetch_credentials
    return self._get_cached_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 653, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 863, in _get_credentials
    return client.assume_role_with_web_identity(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
19:26:46 [ERROR] django.request: Internal Server Error: /organization-avatar/6d1bd0a73dd344d7b158c6b001d0d549/ (status_code=500 request=<WSGIRequest: GET '/organization-avatar/6d1bd0a73dd344d7b158c6b001d0d549/?s=120'>)
```

---

Here is my TF code:
```
resource "helm_release" "sentry" {
  name       = local.component["name"]
  repository = "https://sentry-kubernetes.github.io/charts"
  chart      = "sentry"
  version    = local.tfvars["chart_version"]

  namespace        = local.namespace
  create_namespace = true
  cleanup_on_fail  = true

  dynamic "set" {
    for_each = local.settings
    content {
      name  = set.key
      value = set.value
    }
  }

  values = [nonsensitive(yamlencode({
    ingress = {
      enabled        = true
      hostname       = local.dns_names["sentry"]["main"]["addr"]
      regexPathStyle = "aws-alb"
      alb            = { httpRedirect = true }
      annotations = {
        "kubernetes.io/ingress.class"                  = "alb"
        "alb.ingress.kubernetes.io/target-type"        = "instance"
        "alb.ingress.kubernetes.io/scheme"             = "internet-facing"
        "alb.ingress.kubernetes.io/load-balancer-name" = "${local.tfstate["eks-cluster"]["cluster_id"]}-public"
        "alb.ingress.kubernetes.io/group.name"         = "${local.tfstate["eks-cluster"]["cluster_id"]}-public" #Share a single ALB with all Ingress rules with a specific group name
        "alb.ingress.kubernetes.io/certificate-arn"    = local.tfstate["acm-cert"]["public"]["arn"]
        "external-dns.alpha.kubernetes.io/hostname"    = local.dns_names["sentry"]["main"]["addr"]
      }
    }

    config = {
      configYml = {
        "filestore.backend" = "s3"
        "filestore.options" = {
          bucket_name       = module.filestore_s3.id
          region_name       = module.filestore_s3.region
          signature_version = "s3v4"
          acl               = "private"
        }
      }
    }

    system = {
      url    = local.dns_names["sentry"]["main"]["url"]
      public = true
    }

    user = {
      email    = module.admin_user_sm.values["username"]
      password = module.admin_user_sm.values["password"]
    }

    externalRedis = {
      host = local.tfstate["redis"]["host"]
    }

    externalPostgresql = {
      host     = module.db.connection_secret["values"]["host"]
      database = module.db.connection_secret["values"]["name"]
      username = module.db.connection_secret["values"]["username"]
      password = module.db.connection_secret["values"]["password"]
    }

    mail = {
      backend  = "smtp"
      useTls   = true
      from     = local.email
      host     = local.stack_vars["ses"]["host"]
      port     = local.stack_vars["ses"]["port"]
      username = module.smtp_user.credentials["values"]["access_key_id"]
      password = module.smtp_user.credentials["values"]["password"]
    }

    serviceAccount = {
      enabled     = true
      annotations = { "eks.amazonaws.com/role-arn" = module.svc_account_iam_role.arn }
    }
  }))]
}

module "svc_account_iam_role" {
  source = "../../../../modules/aws/iam-role"

  name = "${local.component["name"]}-svc"
  policy_document_json = data.aws_iam_policy_document.svc_account.json
  eks = {
    cluster              = local.tfstate["eks-cluster"]
    namespace            = local.namespace
    service_account_name = local.service_account
  }
}

data "aws_iam_policy_document" "svc_account" {
  statement {
    effect    = "Allow"
    actions   = ["s3:*"]
    resources = [module.filestore_s3.arn, "${module.filestore_s3.arn}/*"]
  }
}
```

---
Trust Relationship configuration for `module "svc_account_iam_role"`:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::xxx:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/xxx"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.us-east-2.amazonaws.com/id/xxx:sub": "system:serviceaccount:sentry:sentry"
        }
      }
    }
  ]
}
```
---

What I'm doing wrong?

**Comment by cabrinha** [comment]
Check and see if you have a service account named "sentry" in the sentry namespace.

**Comment by sfc-gh-pkommini** [comment]
@yurymkomarov  Did you figure it out?

**Comment by sfc-gh-pkommini** [comment]
@yurymkomarov Did you set up `external-dns` using a helm chart also? Did you provision that separately into the `kube-system` namespace?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
