### ISSUE TITLE
Documentation improvement when using external database

### ISSUE THREAD

**Issue by tschale** [sentry-kubernetes/charts#519]
When using an external database, it seems that the user might need to be a superuser. Granting all privileges on the database wasn't sufficient for us (see also: https://github.com/getsentry/onpremise/issues/204#issuecomment-456529656). We're using an Azure database and needed to assign the `azure_pg_admin` role, in order for the job `sentry-db-init` to succeed. Before it failed with following stacktrace:
```
09:31:07 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
09:31:11 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 77, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: relation "auth_user" already exists


[...]
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 77, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: ProgrammingError('relation "auth_user" already exists\n',)
SQL: CREATE TABLE "auth_user" ("password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "id" serial NOT NULL PRIMARY KEY, "username" varchar(128) NOT NULL UNIQUE, "first_name" varchar(200) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "is_superuser" boolean NOT NULL, "is_managed" boolean NOT NULL, "is_sentry_app" boolean NULL, "is_password_expired" boolean NOT NULL, "last_password_change" timestamp with time zone NULL, "flags" bigint NULL, "session_nonce" varchar(12) NULL, "date_joined" timestamp with time zone NOT NULL, "last_active" timestamp with time zone NULL)
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
