### ISSUE TITLE
Snuba Bootstrap Fails with "cluster_name" must be set

### ISSUE THREAD

**Issue by cabrinha** [sentry-kubernetes/charts#528]
Install the helm chart with `asHook=true`, exec into the sentry-web pod and run `sentry upgrade`. Set `asHook=false` and get this error, as well as similar errors from other "comsumer" pods:

```
snuba.clickhouse.errors.ClickhouseWriterError: [60] Table default.outcomes_raw_dist doesn't exist. (version 20.8.9.6 (official build))
```

Then, exec into snuba-api pod and try running `snuba bootstrap --force`:
```
2021-12-01 19:00:24,169 Attempting to connect to Kafka (attempt 0)...
2021-12-01 19:00:24,178 Connected to Kafka on attempt 0
2021-12-01 19:00:24,178 Creating Kafka topics...
2021-12-01 19:00:24,244 Running migration: 0001_migrations
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 107, in bootstrap
    Runner().run_all(force=True)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 157, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 215, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 145, in forwards
    op.execute(local=True)
  File "/usr/src/snuba/snuba/migrations/operations.py", line 23, in execute
    nodes = cluster.get_local_nodes() if local else cluster.get_distributed_nodes()
  File "/usr/src/snuba/snuba/clusters/cluster.py", line 263, in get_local_nodes
    assert self.__cluster_name is not None, "cluster_name must be set"
AssertionError: cluster_name must be set
```

Is there a step here that I'm missing? Tried with these chart versions: "11.9.0" and "12.0.0".

I'm using ArgoCD to manage the helm chart installation, so setting the values of `asHook=true/false` is easy and gets applied as a `kubectl apply -f`.

This PR might help, just haven't tested it yet: https://github.com/sentry-kubernetes/charts/pull/521

**Comment by atzawada** [comment]
@cabrinha What was your resolution here? Running into the same issue

**Comment by taxilian** [comment]
Also hitting the same thing
