### ISSUE TITLE
Disable SSL Verify

### ISSUE THREAD

**Issue by soer7022** [sentry-kubernetes/charts#534]
Is it possible to disable SSL Verification?
My sentry-worker spams the following in it's log:
```
11:12:52 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 347, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/transport.py", line 340, in send_envelope_wrapper
    self._send_envelope(envelope)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/transport.py", line 267, in _send_envelope
    endpoint_type="envelope",
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/sdk.py", line 216, in patched_send_request
    return _send_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/transport.py", line 180, in _send_request
    headers=headers,
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 362, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='internal-k8s-default-********.eu-west-1.elb.amazonaws.com', port=443): Max retries exceeded with url: /api/1/envelope/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by mFeigeInvia** [comment]
Hi,
i have the same issue. For the sentry-web, I managed it with the customCA configuration and a SENTRY_SDK_CONFIG overwrite, but in worker there is no customCA. It might be easy to copy the part of the sentry deployment to the worker deployment?

**Comment by rubemlrm** [comment]
> SENTRY_SDK_CONFIG

Can you share the extra configuration that you did relative to the SENTRY_SDK_CONFIG? 

/cc @xavipt

**Comment by mFeigeInvia** [comment]
> > SENTRY_SDK_CONFIG
> 
> Can you share the extra configuration that you did relative to the SENTRY_SDK_CONFIG?
> 
> /cc @xavipt
something like this:
```
config:
  sentryConfPy: |
    CSRF_TRUSTED_ORIGINS = ['xxx.xxx.com']
    SENTRY_SDK_CONFIG = {
        'ca_certs': '/etc/pki/ca-trust/custom/ca.crt',
        "release": sentry.__build__,
        "environment": ENVIRONMENT,
        "in_app_include": ["sentry", "sentry_plugins"],
        "debug": True,
        "send_default_pii": True,
        "auto_enabling_integrations": False,
    }
```

**Comment by rubemlrm** [comment]
> > > SENTRY_SDK_CONFIG
> > 
> > 
> > Can you share the extra configuration that you did relative to the SENTRY_SDK_CONFIG?
> > /cc @xavipt
> > something like this:
> 
> ```
> config:
>   sentryConfPy: |
>     CSRF_TRUSTED_ORIGINS = ['xxx.xxx.com']
>     SENTRY_SDK_CONFIG = {
>         'ca_certs': '/etc/pki/ca-trust/custom/ca.crt',
>         "release": sentry.__build__,
>         "environment": ENVIRONMENT,
>         "in_app_include": ["sentry", "sentry_plugins"],
>         "debug": True,
>         "send_default_pii": True,
>         "auto_enabling_integrations": False,
>     }
> ```

I've tried those configuration without success :/ @Mokto can we have some feedback relative to this kind of issue?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
