### ISSUE TITLE
sentry-db-init fails with django.db.utils.ProgrammingError: ProgrammingError('relation "auth_user" already exists\n',)

### ISSUE THREAD

**Issue by reakaleek** [sentry-kubernetes/charts#569]
I'm trying to freshly install the helm chart `13.0.1` using terraform as suggested in the [README](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/README.md#usage-with-terraform--aws), with the difference that I am using an `externalPostgresql`  instance (AWS RDS).

during the job `sentry-db-init` the pod fails and yields the error message `django.db.utils.ProgrammingError: ProgrammingError('relation "auth_user" already exists\n',)`.

**Comment by surbhitayal** [comment]
I am facing the same issue where I cloned the 12.0.0 tag and the helm install command fails while running sentry-db-init job.
Below are the " sentry-db-init" pod logs:

```
`07:51:08 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
07:51:47 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, sentry, sessions, sites, social_auth
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 79, in execute
    return self.cursor.execute(sql)
**psycopg2.errors.DuplicateTable: relation "auth_user" already exists**


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 79, in execute
    return self.cursor.execute(sql)
**psycopg2.errors.DuplicateTable: DuplicateTable('relation "auth_user" already exists\n')**
SQL: CREATE TABLE "auth_user" ("password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "id" serial NOT NULL PRIMARY KEY, "username" varchar(128) NOT NULL UNIQUE, "first_name" varchar(200) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "is_superuser" boolean NOT NULL, "is_managed" boolean NOT NULL, "is_sentry_app" boolean NULL, "is_password_expired" boolean NOT NULL, "last_password_change" timestamp with time zone NULL, "flags" bigint NULL, "session_nonce" varchar(12) NULL, "date_joined" timestamp with time zone NOT NULL, "last_active" timestamp with time zone NULL)
```
`

Can someone please suggest? Thanks in advance!

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by TaiSHiNet** [comment]
Was this ever resolved?

**Comment by reakaleek** [comment]
Not really.


To overcome the issue, I used the postgres installation provided by the chart.

Then I created a dump and restored it on the RDS postgres instance. Finally, I switched the configuration to `externalPostgresql` again.

**Comment by TaiSHiNet** [comment]
FYI, this is likely due to people missing the [hard stops](https://develop.sentry.dev/self-hosted/releases/#hard-stops)
If you follow the version update instructions in there it'll solve your issue

**Comment by spectrogram** [comment]
I ran into this while doing a fresh install of 22.9 (so highly unlikely to be because of hard stops).

It was because my DB user didn't have superuser permissions (which would be the case for AWS/GCP managed SQL), so you need to temporarily grant superuser to your DB user for the migrations and revoke them afterward. You'll need to do it again for any future DB migrations.
