### ISSUE TITLE
Snuba consumer CrashLoopBackOff

### ISSUE THREAD

**Issue by yeouchien** [sentry-kubernetes/charts#61]
`sentry-snuba-consumer-6d8ccf79ff-lcdjj         0/1     CrashLoopBackOff   8          27m`

version:
release `0.12.3`
```
  snuba:
    repository: getsentry/snuba
    tag: 477561d1d5ae17ed9b88ed67cf208d0029dd07b4
    pullPolicy: IfNotPresent
```
```
clickhouse:
  enabled: true
  clickhouse:
    imageVersion: "19.16"
```

error log:
```
2020-04-23 14:11:42,904 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 538}
2020-04-23 14:11:43,912 Flushing 8 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=538, hi=545)}): forced:False size:False time:True
2020-04-23 14:11:43,933 Worker flush took 20ms
2020-04-23 14:12:14,119 Flushing 1 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=546, hi=546)}): forced:False size:False time:True
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 11, in <module>
    load_entry_point('snuba', 'console_scripts', 'snuba')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 178, in consumer
    consumer.run()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 137, in run
    self._run_once()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 142, in _run_once
    self._flush()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 242, in _flush
    self.worker.flush_batch(self.__batch_results)
  File "/usr/src/snuba/snuba/consumer.py", line 101, in flush_batch
    self.__writer.write(inserts)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 83, in write
    raise ClickhouseError(int(code), message)
snuba.clickhouse.errors.ClickhouseError: [60] Table default.sentry_local doesn't exist. (version 19.16.17.1 (official build))
```

**Comment by Mokto** [comment]
Seems like the snuba db init job hasn't been runned properly.
Or you lost data because [Clickhouse doesn't have a PVC](https://github.com/sentry-kubernetes/charts/pull/50).

Might that be the case ?

**Comment by yeouchien** [comment]
thanks for adding Clickhouse PVC it to README.md, you are right.
adding the following and rerun snuba db init works
```
clickhouse:
  enabled: true
  clickhouse:
    imageVersion: 19.16
    persistentVolumeClaim:
      enabled: true
      dataPersistentVolume:
        enabled: true
        accessModes:
        - ReadWriteOnce
        storageClassName: gp2 # I am using AWS, so gp2 here
        storage: 20Gi
```

**Comment by sagor999** [comment]
@Mokto 
I am having same issue. My snuba-consumer keeps crashing with same error.
I added PVC for clickhouse, and re-deployed sentry. db-init seemed to finished fine (no errors).
But snuba-consumer still keeps crashing. 
`snuba.clickhouse.errors.ClickhouseError: [60] Table default.sentry_local doesn't exist. (version 19.16.19.85 (official build)) `

Any ideas how to fix it? 
Sentry itself seemed to be working fine. But that pod keeps crashing non stop.

**Comment by Mokto** [comment]
You need to "restart" your hooks.

What I usually do is put "enabled" false on hooks, helm upgrade, then "enabled" true, helm upgrade

**Comment by sagor999** [comment]
@Mokto Perfect. Thank you! That seemed to fixed it.
