### ISSUE TITLE
snuba-transactions-consumer error after upgrade to chart 14.1.1

### ISSUE THREAD

**Issue by ruiengana** [sentry-kubernetes/charts#628]
After upgrade to chart 14.1.1 (Sentry 22.5.0) we are seeing ```snuba-transactions-consumer``` pod to be crashing with below stack trace.
Feels like some migration is missing, but running ```snuba migrations migrate``` for every single clickhouse node it looks like all migrations have been applied correctly.

```
2022-05-25 12:45:46,446 Consumer Starting
2022-05-25 12:45:46,448 librdkafka log level: 6
2022-05-25 12:45:46,501 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 23109}
2022-05-25 12:46:27,594 Caught {
  "__type__": "SerializableException",
  "__name__": "ClickhouseWriterError",
  "__message__": "No such column _tags_flattened in table default.transactions_local: Insertion status:",
  "__should_report__": true,
  "__extra_data__": {
    "code": 16,
    "row": null
  }
}, shutting down...
2022-05-25 12:46:27,594 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7fa9abb29430>...
2022-05-25 12:46:27,594 Closing <snuba.utils.streams.kafka_consumer_with_commit_log.KafkaConsumerWithCommitLog object at 0x7fa9abaabaf0>...
2022-05-25 12:46:27,598 Partitions revoked: [Partition(topic=Topic(name='events'), index=0)]
2022-05-25 12:46:27,603 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 188, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 121, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 156, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/filter.py", line 26, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 199, in close_and_reset_batch
    self.future.result(timeout=5)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 210, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 284, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 100, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: No such column _tags_flattened in table default.transactions_local: Insertion status:
```

**Comment by ruiengana** [comment]
See https://github.com/getsentry/snuba/issues/2768

**Comment by xyfleet** [comment]
@Mokto Sorry for mentioning you. Or if you can help find someone in this community to fix this one, that will be appreciated. Do you have a min to take a look this issue. For now, upgrading from chart 14.1.0 to later one, like 15.3.0 100% fail. Based on https://github.com/getsentry/snuba/issues/2768, it's still hard to get issue fixed. Not sure if it's the chart issue or Snuba itself. (Do not plan to delete the PVs.)

**Comment by hyunkj42** [comment]
I have the same symptoms.
The above error occurs in the snuba-transactions-consumer pod and is periodically restarted. ㅜ.ㅜ
```
2022-11-29 11:49:48,474 Initializing Snuba CLI...
2022-11-29 11:49:48,476 Initializing Snuba
2022-11-29 11:49:50,663 Snuba initialization took 2.188385618850589s
2022-11-29 11:49:50,671 Consumer Starting
2022-11-29 11:49:50,671 librdkafka log level: 6
2022-11-29 11:49:50,774 New partitions assigned: {Partition(topic=Topic(name='transactions'), index=0): 2, Partition(topic=Topic(name='transactions'), index=1): 1, Partition(topic=Topic(name='transactions'), index=2): 0}






2022-11-29 11:51:30,832 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 185, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 288, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 104, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: No such column _tags_flattened in table transactions_local: Insertion status:
2022-11-29 11:51:30,835 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7f6ba6e66a90>...
2022-11-29 11:51:30,836 Closing <snuba.utils.streams.kafka_consumer_with_commit_log.KafkaConsumerWithCommitLog object at 0x7f6ba6e4e100>...
2022-11-29 11:51:30,836 Partitions revoked: [Partition(topic=Topic(name='transactions'), index=0), Partition(topic=Topic(name='transactions'), index=1), Partition(topic=Topic(name='transactions'), index=2)]
2022-11-29 11:51:30,840 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 11, in <module>
    load_entry_point('snuba', 'console_scripts', 'snuba')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 202, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 185, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 288, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 104, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: No such column _tags_flattened in table transactions_local: Insertion status:
```

**Comment by maxboone** [comment]
For anyone running into this, in recent versions of `Snuba` or the Sentry k8s chart, clickhouse usage is switched to "distributed" mode instead of "local" mode. It might be that your migrations were borked and as such, consumers and other parts of the application mess up because the table structure is not as expected.

If you run into the above error, check the structures of the `_dist` and `_local` table about which you get the error. The `_dist` table **relies** on the `_local` table to have a similar structure. So even if your `INSERT INTO` does not mention the `_local` table anywhere, it's structure is important. Check the columns using:

```
SHOW CREATE TABLE default.transactions_dist
SHOW CREATE TABLE default.transactions_local
```

And, compare this to the migrations in `snuba`: https://github.com/getsentry/snuba/tree/22.10.0/snuba/snuba_migrations

Notice that most migrations PRs have the generated SQL attached to it, this can be useful when manually running migrations on the database tables. Personally I used a `tmux` with synced split windows to do this fast, but do as you wish.

Hopefully this saves you some precious time.
