### ISSUE TITLE
Snuba migrate job fails with DB::Exception: Cannot link

### ISSUE THREAD

**Issue by klis** [sentry-kubernetes/charts#636]
Hi, I'm trying to install the latest Chart. 
When I add PVCs to the ClickHouse my sentry-snuba-migrate job starts to fail. This isn't the case when I leave ClickHouse to use `emptyDir`. If anyone ever encountered this type of error please let me know if you have solved it. 
I'm running k8s bare-metal cluster version1.22 with BeeGFS CSI driver.
Stack trace: 
```
2022-06-06 08:21:04,303 Attempting to connect to Clickhouse cluster sentry-clickhouse:9000 (attempt 0)
2022-06-06 08:21:04,306 Connecting. Database: default. User: default
2022-06-06 08:21:04,306 Connecting to sentry-clickhouse:9000
2022-06-06 08:21:04,313 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-06-06 08:21:04,313 Query: SELECT version()
2022-06-06 08:21:04,314 Block "" send time: 0.000091
2022-06-06 08:21:04,321 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions')
2022-06-06 08:21:04,321 Block "" send time: 0.000072
2022-06-06 08:21:04,330 Running migration: 0001_migrations
2022-06-06 08:21:04,331 Connecting. Database: default. User: default
2022-06-06 08:21:04,331 Connecting to sentry-clickhouse:9000
2022-06-06 08:21:04,336 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-06-06 08:21:04,337 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='sentry-clickhouse'
2022-06-06 08:21:04,337 Block "" send time: 0.000071
2022-06-06 08:21:04,348 Connecting. Database: default. User: default
2022-06-06 08:21:04,349 Connecting to sentry-clickhouse-0.sentry-clickhouse-headless.sentry-system.svc.cluster.local:9000
2022-06-06 08:21:04,352 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-06-06 08:21:04,353 Query: CREATE TABLE IF NOT EXISTS migrations_local (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/migrations/{shard}/default/migrations_local', '{replica}', version) ORDER BY (group, migration_id);
2022-06-06 08:21:04,353 Block "" send time: 0.000087
2022-06-06 08:21:04,517 Connecting. Database: default. User: default
2022-06-06 08:21:04,517 Connecting to sentry-clickhouse-1.sentry-clickhouse-headless.sentry-system.svc.cluster.local:9000
2022-06-06 08:21:04,521 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-06-06 08:21:04,522 Query: CREATE TABLE IF NOT EXISTS migrations_local (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/migrations/{shard}/default/migrations_local', '{replica}', version) ORDER BY (group, migration_id);
2022-06-06 08:21:04,522 Block "" send time: 0.000103
2022-06-06 08:21:04,657 Connecting. Database: default. User: default
2022-06-06 08:21:04,658 Connecting to sentry-clickhouse-2.sentry-clickhouse-headless.sentry-system.svc.cluster.local:9000
2022-06-06 08:21:04,661 Failed to connect to sentry-clickhouse-2.sentry-clickhouse-headless.sentry-system.svc.cluster.local:9000
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 319, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 283, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 235, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
2022-06-06 08:21:04,763 Connecting. Database: default. User: default
2022-06-06 08:21:04,763 Connecting to sentry-clickhouse-2.sentry-clickhouse-headless.sentry-system.svc.cluster.local:9000
2022-06-06 08:21:04,766 Failed to connect to sentry-clickhouse-2.sentry-clickhouse-headless.sentry-system.svc.cluster.local:9000
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 319, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 283, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 235, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
2022-06-06 08:21:04,867 Connecting. Database: default. User: default
2022-06-06 08:21:04,867 Connecting to sentry-clickhouse-2.sentry-clickhouse-headless.sentry-system.svc.cluster.local:9000
2022-06-06 08:21:04,873 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-06-06 08:21:04,874 Query: CREATE TABLE IF NOT EXISTS migrations_local (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/migrations/{shard}/default/migrations_local', '{replica}', version) ORDER BY (group, migration_id);
2022-06-06 08:21:04,874 Block "" send time: 0.000065
2022-06-06 08:21:05,007 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='sentry-clickhouse'
2022-06-06 08:21:05,007 Block "" send time: 0.000081
2022-06-06 08:21:05,024 Query: CREATE TABLE IF NOT EXISTS migrations_dist (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE Distributed(sentry-clickhouse, default, migrations_local, cityHash64(group));
2022-06-06 08:21:05,024 Block "" send time: 0.000088
2022-06-06 08:21:05,036 Query: CREATE TABLE IF NOT EXISTS migrations_dist (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE Distributed(sentry-clickhouse, default, migrations_local, cityHash64(group));
2022-06-06 08:21:05,037 Block "" send time: 0.000107
2022-06-06 08:21:05,050 Query: CREATE TABLE IF NOT EXISTS migrations_dist (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE Distributed(sentry-clickhouse, default, migrations_local, cityHash64(group));
2022-06-06 08:21:05,050 Block "" send time: 0.000079
2022-06-06 08:21:05,062 Finished: 0001_migrations
2022-06-06 08:21:05,062 Connecting. Database: default. User: default
2022-06-06 08:21:05,062 Connecting to sentry-clickhouse:9000
2022-06-06 08:21:05,066 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-06-06 08:21:05,067 Query: SELECT version FROM migrations_dist FINAL WHERE group = 'system' AND migration_id = '0001_migrations';
2022-06-06 08:21:05,067 Block "" send time: 0.000079
2022-06-06 08:21:05,095 Query: INSERT INTO migrations_dist FORMAT JSONEachRow
2022-06-06 08:21:05,096 Block "" send time: 0.000076
/usr/local/lib/python3.8/site-packages/clickhouse_driver/columns/datetimecolumn.py:199: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  local_timezone = get_localzone().zone
2022-06-06 08:21:05,106 Block "" send time: 0.007495
2022-06-06 08:21:05,106 Block "" send time: 0.000104
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 187, in execute
    result_data = query_execute()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 280, in execute
    rv = self.process_insert_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 506, in process_insert_query
    self.receive_end_of_query()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 572, in receive_end_of_query
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 424.
DB::Exception: Cannot link /var/lib/clickhouse/data/default/migrations_dist/default@sentry%2Dclickhouse%2D0%2Esentry%2Dclickhouse%2Dheadless%2Esentry%2Dsystem%2Esvc%2Ecluster%2Elocal:9000/tmp/1.bin to /var/lib/clickhouse/data/default/migrations_dist/default@sentry%2Dclickhouse%2D0%2Esentry%2Dclickhouse%2Dheadless%2Esentry%2Dsystem%2Esvc%2Ecluster%2Elocal:9000/1.bin, errno: 1, strerror: Operation not permitted. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cefaa0 in /usr/bin/clickhouse
1. DB::ErrnoException::ErrnoException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) @ 0xe63f4cb in /usr/bin/clickhouse
2. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0xe63d9f4 in /usr/bin/clickhouse
3. DB::createHardLink(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15699131 in /usr/bin/clickhouse
4. DB::DistributedBlockOutputStream::writeToShard(DB::Block const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x160a6fbf in /usr/bin/clickhouse
5. DB::DistributedBlockOutputStream::writeAsyncImpl(DB::Block const&, unsigned long) @ 0x160a813c in /usr/bin/clickhouse
6. DB::DistributedBlockOutputStream::writeSplitAsync(DB::Block const&) @ 0x160a83b3 in /usr/bin/clickhouse
7. DB::DistributedBlockOutputStream::write(DB::Block const&) @ 0x160a8a3d in /usr/bin/clickhouse
8. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0x15989f86 in /usr/bin/clickhouse
9. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0x159cd80f in /usr/bin/clickhouse
10. DB::SquashingBlockOutputStream::finalize() @ 0x1598f5d7 in /usr/bin/clickhouse
11. DB::SquashingBlockOutputStream::writeSuffix() @ 0x1598f6bd in /usr/bin/clickhouse
12. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0x163baf0a in /usr/bin/clickhouse
13. DB::TCPHandler::runImpl() @ 0x163bc10b in /usr/bin/clickhouse
14. DB::TCPHandler::run() @ 0x163bc7b0 in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0x18c0d76b in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0x18c0dcf8 in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0x18d8c7e6 in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d87be0 in /usr/bin/clickhouse
19. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
20. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 64, in migrate
    runner.run_all(force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 157, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 217, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 149, in forwards
    update_status(Status.COMPLETED)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 329, in _update_migration_status
    self.__connection.execute(statement, data)
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 263, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Cannot link /var/lib/clickhouse/data/default/migrations_dist/default@sentry%2Dclickhouse%2D0%2Esentry%2Dclickhouse%2Dheadless%2Esentry%2Dsystem%2Esvc%2Ecluster%2Elocal:9000/tmp/1.bin to /var/lib/clickhouse/data/default/migrations_dist/default@sentry%2Dclickhouse%2D0%2Esentry%2Dclickhouse%2Dheadless%2Esentry%2Dsystem%2Esvc%2Ecluster%2Elocal:9000/1.bin, errno: 1, strerror: Operation not permitted. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cefaa0 in /usr/bin/clickhouse
1. DB::ErrnoException::ErrnoException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) @ 0xe63f4cb in /usr/bin/clickhouse
2. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0xe63d9f4 in /usr/bin/clickhouse
3. DB::createHardLink(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15699131 in /usr/bin/clickhouse
4. DB::DistributedBlockOutputStream::writeToShard(DB::Block const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x160a6fbf in /usr/bin/clickhouse
5. DB::DistributedBlockOutputStream::writeAsyncImpl(DB::Block const&, unsigned long) @ 0x160a813c in /usr/bin/clickhouse
6. DB::DistributedBlockOutputStream::writeSplitAsync(DB::Block const&) @ 0x160a83b3 in /usr/bin/clickhouse
7. DB::DistributedBlockOutputStream::write(DB::Block const&) @ 0x160a8a3d in /usr/bin/clickhouse
8. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0x15989f86 in /usr/bin/clickhouse
9. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0x159cd80f in /usr/bin/clickhouse
10. DB::SquashingBlockOutputStream::finalize() @ 0x1598f5d7 in /usr/bin/clickhouse
11. DB::SquashingBlockOutputStream::writeSuffix() @ 0x1598f6bd in /usr/bin/clickhouse
12. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0x163baf0a in /usr/bin/clickhouse
13. DB::TCPHandler::runImpl() @ 0x163bc10b in /usr/bin/clickhouse
14. DB::TCPHandler::run() @ 0x163bc7b0 in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0x18c0d76b in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0x18c0dcf8 in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0x18d8c7e6 in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d87be0 in /usr/bin/clickhouse
19. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
20. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

**Comment by xgengsjc2021** [comment]
@klis are you using external clickhouse or internal one?

**Comment by klis** [comment]
> @klis are you using external clickhouse or internal one?

Internal, default that is deployed with the Sentry chart

**Comment by xgengsjc2021** [comment]
@klis Ok. I am using an external clickhouse created by [clickhouse-operator](https://github.com/Altinity/clickhouse-operator). I cannot connect to the clickhouse from sentry. 
```

2022-06-24 06:38:34,780 Attempting to connect to Clickhouse cluster xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000 (attempt 0)
2022-06-24 06:38:34,786 Connecting. Database: default. User: clickhouse_operator
2022-06-24 06:38:34,786 Connecting to xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000
2022-06-24 06:38:34,789 Connected to ClickHouse server version 22.3.7, revision: 54455
2022-06-24 06:38:34,790 Query: SELECT version()
2022-06-24 06:38:34,790 Block "" send time: 0.000047
2022-06-24 06:38:34,793 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions')
2022-06-24 06:38:34,793 Block "" send time: 0.000052
2022-06-24 06:38:34,797 Running migration: 0001_migrations
2022-06-24 06:38:34,797 Connecting. Database: default. User: clickhouse_operator
2022-06-24 06:38:34,797 Connecting to xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000
2022-06-24 06:38:35,804 Connected to ClickHouse server version 22.3.7, revision: 54455
2022-06-24 06:38:35,804 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='ch-cluster'
2022-06-24 06:38:35,804 Block "" send time: 0.000042
2022-06-24 06:38:35,820 Connecting. Database: default. User: clickhouse_operator
2022-06-24 06:38:35,820 Connecting to chi-ch-install-ch-cluster-shard0-0:9000
2022-06-24 06:38:35,870 Failed to connect to chi-ch-install-ch-cluster-shard0-0:9000
```

**Comment by klis** [comment]
@xgengsjc2021 what I have noticed is that when clickhouse is using a PVC then I get an error, but when clickhouse is using a emptyDir, then the migrations run fine. And after the first migration fails, next one have random errors.

**Comment by xgengsjc2021** [comment]
@klis Thanks for you reminder, I will double check since my external CH is using PV for each replica. But based on the log above, it mentioned connect network issue. But I will test emptyDir. 
```
snuba.clickhouse.errors.ClickhouseError: Name or service not known (chi-ch-install-ch-cluster-shard0-0:9000)
```

**Comment by xgengsjc2021** [comment]
@klis unfortunately, empltyDir did not fix my issue. I still see the same issue as mentioned above.

**Comment by klis** [comment]
@xgengsjc2021 so there is some general issue with the chart?

**Comment by xgengsjc2021** [comment]
@klis There is no issue with the chart but my own DNS settings. Another issue about CH version, you can take a look when you want to upgrade to the new version.
https://forum.sentry.io/t/support-for-clickhouse-21-x/13341/4

**Comment by klis** [comment]
> @klis There is no issue with the chart but my own DNS settings. Another issue about CH version, you can take a look when you want to upgrade to the new version. https://forum.sentry.io/t/support-for-clickhouse-21-x/13341/4

@xgengsjc2021 I will try to downgrade CH Which version do you suggest? In the chart, I'm using 20.8.19.4 and still getting errors

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by revathi-murali** [comment]
@xgengsjc2021 I am getting the same error as you mentioned `Name or service not known` . Can you let me know what changes you made with respect to DNS settings? 
FYI I am also using `altinity/clickhouse_operator`
