### ISSUE TITLE
deploying in non-default namespace, connection refused

### ISSUE THREAD

**Issue by christopher-wong** [sentry-kubernetes/charts#650]
I'm trying to deploy the latest chart `14.1.0` using the default configuration in a non-default namespace named `sentry`. It appears that deploying into any namespace other than `default` causes issues with DNS resolution for Redis.

```
redis.exceptions.ConnectionError: Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.
```

It seems like sentry is failing to connect to the Redis pod over cluster DNS. The pod is healthy and should be reachable at that address.

```
04:10:41 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
04:10:44 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 552, in connect
 sock = self._connect()
 File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 609, in _connect
 raise err
 File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 597, in _connect
 sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/sentry/buffer/redis.py", line 64, in validate
 client.ping()
 File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1351, in ping
 return self.execute_command('PING')
 File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
 return old_execute_command(self, name, *args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/rb/clients.py", line 488, in execute_command
 buf = self._get_command_buffer(host_id, args[0])
 File "/usr/local/lib/python3.6/site-packages/rb/clients.py", line 355, in _get_command_buffer
 buf = CommandBuffer(host_id, connect, self.auto_batch)
 File "/usr/local/lib/python3.6/site-packages/rb/clients.py", line 91, in __init__
 self.connect()
 File "/usr/local/lib/python3.6/site-packages/rb/clients.py", line 107, in connect
 self.connection = self._connect_func()
 File "/usr/local/lib/python3.6/site-packages/rb/clients.py", line 353, in connect
 return self.connection_pool.get_connection(command_name, shard_hint=host_id)
 File "/usr/local/lib/python3.6/site-packages/rb/clients.py", line 254, in get_connection
 con = real_pool.get_connection(command_name)
 File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1185, in get_connection
 connection.connect()
 File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 557, in connect
 raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.
```

the web pod also fails to boot with these logs before getting killed by the cluster

```

04:10:03 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
04:10:54 [INFO] sentry.plugins.github: apps-not-configured
*** Starting uWSGI 2.0.18 (64bit) on [Sat Jun 18 04:11:03 2022] ***
compiled with version: 8.3.0 on 12 March 2021 22:35:35
os: Linux-5.4.196-108.356.amzn2.x86_64 #1 SMP Thu May 26 12:49:47 UTC 2022
nodename: sentry-web-6ddd5d9b9f-ks4nr
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 0.0.0.0:9000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:39689 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.6.13 (default, Mar 12 2021, 21:13:53) [GCC 8.3.0]
Set PythonHome to /usr/local
Python main interpreter initialized at 0x5592c4493a90
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 543520 bytes (530 KB) for 2 cores
*** Operational MODE: threaded ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 10, cores: 2)
spawned uWSGI http 1 (pid: 11)
04:11:09 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
04:11:37 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
04:12:11 [INFO] sentry.plugins.github: apps-not-configured
04:16:04 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
```

**Comment by Glaaj** [comment]
Hey, did you by any chance also face this issue on version 14.0.0? I'm having the same setup except my version is 14.0.0 atm

**Comment by bumarcell** [comment]
Try the solution here: [https://github.com/sentry-kubernetes/charts/issues/663](663)

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Glaaj** [comment]
Is there a solution for this problem, the issue is open and stale but I have no clue if it's fixed or being worked on..

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
