### ISSUE TITLE
sentry-snuba-migrate failed to connect to external clickhouse DB::Exception: default: Authentication failed

### ISSUE THREAD

**Issue by xgengsjc2021** [sentry-kubernetes/charts#655]
I have clickhouse installed by clickhouse-operator (https://github.com/Altinity/clickhouse-operator). 3 shards with 2 replicas respectively. In this CH cluster, I have an internal LB as service. 
```
kubectl -n clickhouse get svc
service-ch-install                   LoadBalancer   172.20.57.73   xxxxxxxxxxx.elb.us-west-1.amazonaws.com   8123:32454/TCP,9000:31189/TCP   4h33m
```
My external click setting in sentry
```
externalClickhouse:
  host: " xxxxxxxxxxx.elb.us-west-1.amazonaws.com"
  username: default
  password: ""
  singleNode: false
  clusterName: ch-cluster
```

However, I got this error:
```

2022-06-23 01:28:06,058 Attempting to connect to Clickhouse cluster xxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000 (attempt 9)
2022-06-23 01:28:06,059 Error on xxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000 ping: Unexpected EOF while reading bytes
2022-06-23 01:28:06,059 Connection was closed, reconnecting.
2022-06-23 01:28:06,059 Connecting. Database: default. User: default
2022-06-23 01:28:06,059 Connecting to xxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000
2022-06-23 01:28:06,075 Connection to Clickhouse cluster xxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000 failed (attempt 9)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 187, in execute
    result_data = query_execute()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 271, in execute
    self.connection.force_connect()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 217, in force_connect
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 319, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 295, in _init_connection
    self.receive_hello()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 433, in receive_hello
    raise self.receive_exception()
clickhouse_driver.errors.ServerException: Code: 516.
DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. Stack trace:

```
Any idea why get this error, Authentication failed

**Comment by xgengsjc2021** [comment]
I also tried to use different username: clickhouse_operator. 

Below command can access to CH.
```
clickhouse-client -u clickhouse_operator --password clickhouse_operator_password --host xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com
```

When I set up this in sentry got below error:
```
externalClickhouse:
  host: "xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com"
  username: clickhouse_operator
  password: clickhouse_operator_password
  singleNode: false
  clusterName: ch-cluster
```

```

2022-06-24 06:38:34,780 Attempting to connect to Clickhouse cluster xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000 (attempt 0)
2022-06-24 06:38:34,786 Connecting. Database: default. User: clickhouse_operator
2022-06-24 06:38:34,786 Connecting to xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000
2022-06-24 06:38:34,789 Connected to ClickHouse server version 22.3.7, revision: 54455
2022-06-24 06:38:34,790 Query: SELECT version()
2022-06-24 06:38:34,790 Block "" send time: 0.000047
2022-06-24 06:38:34,793 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions')
2022-06-24 06:38:34,793 Block "" send time: 0.000052
2022-06-24 06:38:34,797 Running migration: 0001_migrations
2022-06-24 06:38:34,797 Connecting. Database: default. User: clickhouse_operator
2022-06-24 06:38:34,797 Connecting to xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000
2022-06-24 06:38:35,804 Connected to ClickHouse server version 22.3.7, revision: 54455
2022-06-24 06:38:35,804 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='ch-cluster'
2022-06-24 06:38:35,804 Block "" send time: 0.000042
2022-06-24 06:38:35,820 Connecting. Database: default. User: clickhouse_operator
2022-06-24 06:38:35,820 Connecting to chi-ch-install-ch-cluster-shard0-0:9000
2022-06-24 06:38:35,870 Failed to connect to chi-ch-install-ch-cluster-shard0-0:9000
```

**Comment by bumarcell** [comment]
out if curiosity, which CH version are you using? :)

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by xgengsjc2021** [comment]
@bumarcell @Mokto Sorry for the late response. Based on this link, https://forum.sentry.io/t/support-for-clickhouse-21-x/13341/5
Sentry does not supports clickhouse version 21 or later.
