### ISSUE TITLE
snuba-migrate job fails on sentry 15.0.0

### ISSUE THREAD

**Issue by cdesch** [sentry-kubernetes/charts#661]
The job `sentry-15-1657291426-snuba-migrate: Jobs active: 1, jobs failed: 3, jobs succeeded: 0` fails with the following log:

```
2022-07-08 14:46:51,472 Attempting to connect to Clickhouse cluster sentry-15-1657291426-clickhouse:9000 (attempt 0)
2022-07-08 14:46:51,475 Connecting. Database: default. User: default
2022-07-08 14:46:51,475 Connecting to sentry-15-1657291426-clickhouse:9000
2022-07-08 14:46:51,485 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-07-08 14:46:51,486 Query: SELECT version()
2022-07-08 14:46:51,486 Block "" send time: 0.000048
2022-07-08 14:46:51,489 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'generic_metrics')
2022-07-08 14:46:51,489 Block "" send time: 0.000036
2022-07-08 14:46:51,492 Running migration: 0001_migrations
2022-07-08 14:46:51,492 Connecting. Database: default. User: default
2022-07-08 14:46:51,492 Connecting to sentry-15-1657291426-clickhouse:9000
2022-07-08 14:46:51,500 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-07-08 14:46:51,500 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='sentry-15-1657291426-clickhouse'
2022-07-08 14:46:51,500 Block "" send time: 0.000035
2022-07-08 14:46:51,505 Connecting. Database: default. User: default
2022-07-08 14:46:51,505 Connecting to sentry-15-1657291426-clickhouse-0.sentry-15-1657291426-clickhouse-headless.monitoring.svc.cluster.local:9000
2022-07-08 14:46:51,508 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-07-08 14:46:51,509 Query: CREATE TABLE IF NOT EXISTS migrations_local (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/migrations/{shard}/default/migrations_local', '{replica}', version) ORDER BY (group, migration_id);
2022-07-08 14:46:51,509 Block "" send time: 0.000040
2022-07-08 14:46:51,512 Connecting. Database: default. User: default
2022-07-08 14:46:51,513 Connecting to sentry-15-1657291426-clickhouse-1.sentry-15-1657291426-clickhouse-headless.monitoring.svc.cluster.local:9000
2022-07-08 14:46:51,515 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-07-08 14:46:51,516 Query: CREATE TABLE IF NOT EXISTS migrations_local (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/migrations/{shard}/default/migrations_local', '{replica}', version) ORDER BY (group, migration_id);
2022-07-08 14:46:51,516 Block "" send time: 0.000040
2022-07-08 14:46:51,517 Connecting. Database: default. User: default
2022-07-08 14:46:51,517 Connecting to sentry-15-1657291426-clickhouse-2.sentry-15-1657291426-clickhouse-headless.monitoring.svc.cluster.local:9000
2022-07-08 14:46:51,520 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-07-08 14:46:51,520 Query: CREATE TABLE IF NOT EXISTS migrations_local (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/migrations/{shard}/default/migrations_local', '{replica}', version) ORDER BY (group, migration_id);
2022-07-08 14:46:51,520 Block "" send time: 0.000040
2022-07-08 14:46:51,522 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='sentry-15-1657291426-clickhouse'
2022-07-08 14:46:51,522 Block "" send time: 0.000030
2022-07-08 14:46:51,527 Query: CREATE TABLE IF NOT EXISTS migrations_dist (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE Distributed(sentry-15-1657291426-clickhouse, default, migrations_local, cityHash64(group));
2022-07-08 14:46:51,527 Block "" send time: 0.000035
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 187, in execute
    result_data = query_execute()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 304, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 491, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 151, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 167, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 184, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 170.
DB::Exception: Bad get: has UInt64, requested String. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cefaa0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63b33d in /usr/bin/clickhouse
2. ? @ 0x15e83d22 in /usr/bin/clickhouse
3. DB::getClusterName(DB::IAST const&) @ 0x15e8210f in /usr/bin/clickhouse
4. DB::getClusterName(DB::IAST const&) @ 0x15e820a8 in /usr/bin/clickhouse
5. DB::getClusterName(DB::IAST const&) @ 0x15e820a8 in /usr/bin/clickhouse
6. DB::getClusterNameAndMakeLiteral(std::__1::shared_ptr<DB::IAST>&) @ 0x15e822d6 in /usr/bin/clickhouse
7. ? @ 0x15e77ea2 in /usr/bin/clickhouse
8. ? @ 0x15e78388 in /usr/bin/clickhouse
9. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15e8fba4 in /usr/bin/clickhouse
10. ? @ 0x158b76d6 in /usr/bin/clickhouse
11. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x158b9f0d in /usr/bin/clickhouse
12. DB::InterpreterCreateQuery::execute() @ 0x158bca69 in /usr/bin/clickhouse
13. ? @ 0x15d15782 in /usr/bin/clickhouse
14. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15d170a2 in /usr/bin/clickhouse
15. DB::TCPHandler::runImpl() @ 0x163bba45 in /usr/bin/clickhouse
16. DB::TCPHandler::run() @ 0x163bc7b0 in /usr/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x18c0d76b in /usr/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x18c0dcf8 in /usr/bin/clickhouse
19. Poco::PooledThread::run() @ 0x18d8c7e6 in /usr/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d87be0 in /usr/bin/clickhouse
21. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
22. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 64, in migrate
    runner.run_all(force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 157, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 217, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 147, in forwards
    op.execute(local=False)
  File "/usr/src/snuba/snuba/migrations/operations.py", line 29, in execute
    connection.execute(self.format_sql())
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 263, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Bad get: has UInt64, requested String. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cefaa0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63b33d in /usr/bin/clickhouse
2. ? @ 0x15e83d22 in /usr/bin/clickhouse
3. DB::getClusterName(DB::IAST const&) @ 0x15e8210f in /usr/bin/clickhouse
4. DB::getClusterName(DB::IAST const&) @ 0x15e820a8 in /usr/bin/clickhouse
5. DB::getClusterName(DB::IAST const&) @ 0x15e820a8 in /usr/bin/clickhouse
6. DB::getClusterNameAndMakeLiteral(std::__1::shared_ptr<DB::IAST>&) @ 0x15e822d6 in /usr/bin/clickhouse
7. ? @ 0x15e77ea2 in /usr/bin/clickhouse
8. ? @ 0x15e78388 in /usr/bin/clickhouse
9. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15e8fba4 in /usr/bin/clickhouse
10. ? @ 0x158b76d6 in /usr/bin/clickhouse
11. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x158b9f0d in /usr/bin/clickhouse
12. DB::InterpreterCreateQuery::execute() @ 0x158bca69 in /usr/bin/clickhouse
13. ? @ 0x15d15782 in /usr/bin/clickhouse
14. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15d170a2 in /usr/bin/clickhouse
15. DB::TCPHandler::runImpl() @ 0x163bba45 in /usr/bin/clickhouse
16. DB::TCPHandler::run() @ 0x163bc7b0 in /usr/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x18c0d76b in /usr/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x18c0dcf8 in /usr/bin/clickhouse
19. Poco::PooledThread::run() @ 0x18d8c7e6 in /usr/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d87be0 in /usr/bin/clickhouse
21. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
22. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2022-07-08T14:46:51.533343706Z
```

It looks like the migration contains a type error

**Comment by bumarcell** [comment]
Fails for me as well, with a different error (snuba.migrations.errors.MigrationInProgress: transactions: 0012_transactions_add_spans)

**Comment by czomo** [comment]
Could you paste your values folks? Did you pin version of clickhouse/snuba? What version did you update from?

**Comment by bumarcell** [comment]
I'm using all defaults on sentry chart v 15 :/

**Comment by czomo** [comment]
> I'm using all defaults on sentry chart v 15 :/

Is it fresh install?

**Comment by bumarcell** [comment]
basically yes
Only added some resource defs and disabled rabbitmq

**Comment by bumarcell** [comment]
`27
2022-07-11 15:56:39,609 Connected to ClickHouse server version 20.8.19, revision: 54438
26
2022-07-11 15:56:39,610 Query: SELECT version()
25
2022-07-11 15:56:39,610 Block "" send time: 0.000041
24
2022-07-11 15:56:39,612 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'generic_metrics')
23
2022-07-11 15:56:39,612 Block "" send time: 0.000023
22
Traceback (most recent call last):
21
  File "/usr/local/bin/snuba", line 33, in <module>
20
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
19
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
18
    return self.main(*args, **kwargs)
17
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
16
    rv = self.invoke(ctx)
15
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
14
    return _process_result(sub_ctx.command.invoke(sub_ctx))
13
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
12
    return _process_result(sub_ctx.command.invoke(sub_ctx))
11
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
10
    return ctx.invoke(self.callback, **ctx.params)
9
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
8
    return __callback(*args, **kwargs)
7
  File "/usr/src/snuba/snuba/cli/migrations.py", line 64, in migrate
6
    runner.run_all(force=force)
5
  File "/usr/src/snuba/snuba/migrations/runner.py", line 145, in run_all
4
    pending_migrations = self._get_pending_migrations()
3
  File "/usr/src/snuba/snuba/migrations/runner.py", line 297, in _get_pending_migrations
2
    raise MigrationInProgress(str(migration_key))
1
snuba.migrations.errors.MigrationInProgress: transactions: 0012_transactions_add_spans
`

**Comment by bumarcell** [comment]
snuba migration is failing for some reason
I tried reverting the stuck migration but it throws an exception :(

**Comment by czomo** [comment]
> snuba migration is failing for some reason
> I tried reverting the stuck migration but it throws an exception :(

Could you describe how you reverted it? You said that it is fresh install 

Second thing. It would be great to use helm install sentry sentry/sentry in case you are using default values and post here the results

**Comment by bumarcell** [comment]
I'm deploying in the k8s cluster. At first everything works fine until the snuba migration job starts, then those pods fail (see image) and block the rest of the deployment.
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/28063982/178309439-96dd273b-709d-4fde-ae1b-9bf907987dce.png">

I was able to open a terminal on the snuba api pod and revert the stuck migration (only worked with --force)
this managed somehow to bring me a step further but then got stuck at the next migration (see next image)
<img width="457" alt="image" src="https://user-images.githubusercontent.com/28063982/178310014-d6dc7964-54b0-4f89-82d8-9f874efaaeef.png">

This one I reverted as well, which removed the [-] symbol
<img width="401" alt="image" src="https://user-images.githubusercontent.com/28063982/178310536-e32fe482-56ec-4453-bde2-802530b3ee73.png">

but I cant find away to go further from here, as running `snuba migration migrate` throws an exception (see next image)
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/28063982/178310715-0ecdedeb-38a8-4d2f-ac4e-acf22eeb2ed1.png">

I hope my explanation of my problem is clear enough :)

**Comment by czomo** [comment]
Please try the same procedure as in here https://github.com/sentry-kubernetes/charts#upgrading-from-13xx-version-of-this-chart-to-1400 Warning: you may loose data

**Comment by bumarcell** [comment]
What are the steps exactly?
I've been deleting clickhouse pods the whoe time 🤔

**Comment by czomo** [comment]
You need to delete click house statefulset along with corresponding persistent volumes/persistence volume claims and deploy sentry one more time

> What are the steps exactly?
> I've been deleting clickhouse pods the whoe time 🤔

**Comment by bumarcell** [comment]
I deleted the pods then the pvcs then created them again and got the following error:
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/28063982/178322304-06b41f7e-4347-432f-80f5-85bd7e39c9fb.png">

**Comment by czomo** [comment]
Could you paste the output of `kubectl get pv | grep clickhouse` and `kubectl get pvc | grep clickhouse`

**Comment by bumarcell** [comment]
All quite fresh
<img width="2087" alt="image" src="https://user-images.githubusercontent.com/28063982/178326020-04080068-c438-4e0d-997e-5540bd5fa50e.png">

Same with pvcs

**Comment by bumarcell** [comment]
However, this time I was able to get quite far with the list-reverse-migrate-list sequence 
<img width="522" alt="image" src="https://user-images.githubusercontent.com/28063982/178328190-16ecd115-05f4-4d36-883f-257f139c087d.png">

**Comment by czomo** [comment]
What is the status of [snuba-migrate job](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/hooks/snuba-migrate.job.yaml) ? Did you tried to add `--timeout` during helm install?

**Comment by bumarcell** [comment]
Reading snuba migration docu it says regarding clickhouse "Currently only the single node configuration is fully supported through the migration system."
However, I cannot find a way to scale ch sts to 1 in the chart.. It always spawns 3 pods per default

**Comment by bumarcell** [comment]
So I was able to scale ch down to 1 replica and got the migrations going a lot further..

On migration got stuck but I was able to reverse it then run the migrations again and it succeeded:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/28063982/178505150-f0d0292d-ecdb-410e-859d-8666481dcf71.png">

But the don't know how to get further from here :)

**Comment by bumarcell** [comment]
Aright I was able to sync everything again and had a minor postgres error that I was able to fix 
All is working fine now. The biggest reason for failure I believe was that 3 ch replicas get created per default, which made snuba migration fail because it doesn't rly support clustered ch.

I'd suggest editing those defaults. 
I will try to create a PR for that soon :)

**Comment by cdesch** [comment]
@bumarcell Thank you. Can you point me to the line in the helm config customization to change the replica count from 3 to 1 for the snuba migration?

**Comment by czomo** [comment]
> Aright I was able to sync everything again and had a minor postgres error that I was able to fix

good to hear that, I couldn't reproduce that error

@cdesch try to add it here https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L666
```
clickhouse:
  enabled: true
  clickhouse:
    replicas: 1
```

**Comment by bumarcell** [comment]
Do I have to fork sentry in order to hange this variable? (SENTRY_DISTRIBUTED_CLICKHOUSE_TABLES) 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/28063982/178726876-c5c019d5-65b1-4c82-b18e-358f9815b1cd.png">

**Comment by bumarcell** [comment]
I was able to overwrite that field with the following section in values.yam:
`config:
    sentryConfPy: |
      SENTRY_DISTRIBUTED_CLICKHOUSE_TABLES = True`
But then snuba migration job seemed to stop working..

So this means Sentry can run with ONLY ONE CH NODE?! kind of problematic for production I'd say :/

**Comment by bumarcell** [comment]
Ok after some checking and trying it seems as if this variable doesn't play any role in the helm chart and now all is working.
I had to change the relay version tho (among many other things..)

**Comment by cdesch** [comment]
@bumarcell what did you change the relay version to?

I am using this Config and got the same error: https://gist.github.com/cdesch/7a9c7eb0e562c4c9e41c12f9c39990e0 

Reducing the number of replicas for clickhouse to 1 and setting the ` config: sentryConfPy: | SENTRY_DISTRIBUTED_CLICKHOUSE_TABLES = True` didn't seem to help.

This is using the 15.0.1 sentry chart that was recently released

**Comment by bumarcell** [comment]
I didn't change the variable `SENTRY_DISTRIBUTED_CLICKHOUSE_TABLES` at the end 
What error are you getting exactly?

**Comment by cdesch** [comment]
Same error as above in the initial opening of the issue or here: https://gist.github.com/cdesch/7a9c7eb0e562c4c9e41c12f9c39990e0#file-gistfile2-txt 

Just trying to do a stock deployment of the helm chart gets this error regarding the types.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by junowong0114** [comment]
@bumarcell @cdesch I have successfully upgraded from chart 11.9.0 to 15.1.0 using these procedures without losing clickhouse data and without reducing clickhouse replica, maybe this is something you would like to try as well?

https://github.com/sentry-kubernetes/charts/issues/652#issuecomment-1231106778

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
