### ISSUE TITLE
Snuba migrate job fails when using external zookeeper (Error: replica already exists)

### ISSUE THREAD

**Issue by nishaero** [sentry-kubernetes/charts#670]
I have my sentry v15.0.0 configured with external kafka, redis and zookeeper. 

During a fresh install, it worked fine, but when I uninstalled the chart and re deployed the chart, the snuba-migrate job complains that the replicas already exist.

Here is my configuration of clickhouse, I only added config for external redis, kafka and zookeeper.

I use the Host address directly since I want to connect with the existing instance of zookeeper

```yaml
clickhouse:
  enabled: true
  clickhouse:
    imageVersion: "20.8.19.4"
    configmap:
      remote_servers:
        internal_replication: false
      zookeeper_servers:
        enabled: true
        config:
          - index: "clickhouse"
            # hostTemplate: "localhost"
            host: 127.0.0.1
            port: "2181"
      users:
        enabled: false
    persistentVolumeClaim:
        enabled: true
        dataPersistentVolume:
          enabled: true
          accessModes:
            - "ReadWriteOnce"
          storage: "10Gi"
```

Here is the error log

```
2022-07-18 07:02:59,628 Connecting. Database: default. User: default
2022-07-18 07:02:59,628 Connecting to sentry-clickhouse:9000
2022-07-18 07:02:59,634 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-07-18 07:02:59,634 Query: SELECT version()
2022-07-18 07:02:59,634 Block "" send time: 0.000044
2022-07-18 07:02:59,640 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'generic_metrics')
2022-07-18 07:02:59,648 Block "" send time: 0.000031
2022-07-18 07:02:59,652 Running migration: 0001_migrations
2022-07-18 07:02:59,652 Connecting. Database: default. User: default
2022-07-18 07:02:59,653 Connecting to sentry-clickhouse:9000
2022-07-18 07:02:59,663 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-07-18 07:02:59,664 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='sentry-clickhouse'
2022-07-18 07:02:59,664 Block "" send time: 0.000029
2022-07-18 07:02:59,672 Connecting. Database: default. User: default
2022-07-18 07:02:59,672 Connecting to sentry-clickhouse-0.sentry-clickhouse-headless.default.svc.cluster.local:9000
2022-07-18 07:02:59,677 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-07-18 07:02:59,677 Query: CREATE TABLE IF NOT EXISTS migrations_local (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/migrations/{shard}/default/migrations_local', '{replica}', version) ORDER BY (group, migration_id);
2022-07-18 07:02:59,677 Block "" send time: 0.000043
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 187, in execute
    result_data = query_execute()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 304, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 491, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 151, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 167, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 184, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 253.
DB::Exception: Replica /clickhouse/tables/migrations/0/default/migrations_local/replicas/sentry-clickhouse-0 already exists.. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cefaa0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63b33d in /usr/bin/clickhouse
2. ? @ 0x15f9371c in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0x15f6eb01 in /usr/bin/clickhouse
4. ? @ 0x1630b7fb in /usr/bin/clickhouse
5. std::__1::__function::__func<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&), std::__1::allocator<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) @ 0x16310717 in /usr/bin/clickhouse
6. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15e8fba4 in /usr/bin/clickhouse
7. ? @ 0x158b76d6 in /usr/bin/clickhouse
8. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x158b9f0d in /usr/bin/clickhouse
9. DB::InterpreterCreateQuery::execute() @ 0x158bca69 in /usr/bin/clickhouse
10. ? @ 0x15d15782 in /usr/bin/clickhouse
11. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15d170a2 in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0x163bba45 in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0x163bc7b0 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x18c0d76b in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x18c0dcf8 in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x18d8c7e6 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d87be0 in /usr/bin/clickhouse
18. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
19. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

Is this a bug in clickhouse?

**Comment by bumarcell** [comment]
Maybe you did some deployment then tried to deploy again without deleting all PVCs?

**Comment by nishaero** [comment]
> Maybe you did some deployment then tried to deploy again without deleting all PVCs?

I deleted all PVCs used by Sentry but the PVC of zookeeper is external just like Kafka and Redis in my setup and I cannot delete its PVCs. In such scenario, shouldn't the migrate job either try to use the existing table or drop and recreate the table?

**Comment by bumarcell** [comment]
Hmmm did you try deleting clickhouse folder in zookeeper?

**Comment by bumarcell** [comment]
make sure the clickhouse folder you're deleting is only used for sentry :D

**Comment by nishaero** [comment]
> Hmmm did you try deleting clickhouse folder in zookeeper?

Yes, that worked. But shouldn't Clickhouse have a mechanism to handle such scenario's ? 
or is there a way I can add this (deleting the Clickhouse directory in zookeeper) as hook for helm uninstall??

**Comment by bumarcell** [comment]
That goes beyond my skills unfortunately 

Which clickhouse version are you running?

**Comment by nishaero** [comment]
> That goes beyond my skills unfortunately
> 
> Which clickhouse version are you running?

I'm using Clickhouse v 20.8.19.4, the latest one in the sentry chart v15.0.0

**Comment by bumarcell** [comment]
yeah, I also couldn't update ch version

What kafka auth method are you using?!

**Comment by bumarcell** [comment]
Would you please show me how you defined values for your external services?
I'm still having problems using any external services :/

**Comment by nishaero** [comment]
I'm using consul mesh and pod annotations to connect to external services.

```yaml
zookeeper:
  enabled: false

kafka:
  enabled: false
externalKafka:
  host: localhost
  port: 9092

redis:
  enabled: false
externalRedis:
  host: localhost
  port: 6379
  password: xxxx

clickhouse:
  enabled: true
  clickhouse:
    imageVersion: "20.8.19.4"
    configmap:
      remote_servers:
        internal_replication: true
      zookeeper_servers:
        enabled: true
        config:
          - index: "clickhouse"
            # hostTemplate: "localhost"
            host: 127.0.0.1
            port: "2181"
````

**Comment by bumarcell** [comment]
Ah ok. I hoped you were using tls/sasl for kafka auth 🙈

**Comment by nishaero** [comment]
> Ah ok. I hoped you were using tls/sasl for kafka auth 🙈

Steps to reproduce.

1. Add config for connecting sentry to external zookeeper
2. Do a Helm Uninstall sentry
3. Check in zookeeper container if Clickhouse node exists using zkCli.sh, do not delete the node!
4. Now, Install sentry again with hooks enabled. 
5. Check the snuba-migrate-job pod, it will fail with an error saying Replicas already exist. 

I have already posted the error log above. 

Shouldn't Clickhouse manage it if replica's exist like ALTER table if exists?

**Comment by nishaero** [comment]
I created a separate pre-delete hook job to delete the Clickhouse nodes in zookeeper entries using zkCli.sh. this fixed the issue. But this is still a workaround and not a straight fix.
