### ISSUE TITLE
snuba migrate Cannot use any of provided ZooKeeper nodes (Bad arguments)

### ISSUE THREAD

**Issue by dmekhov** [sentry-kubernetes/charts#717]
new install

chart: sentry-15.1.0
Image: getsentry/snuba:22.7.0
extarnal kafka
external db

Logs from job pod:
```
2022-08-24 12:14:41,505 Attempting to connect to Clickhouse cluster sentry-clickhouse:9000 (attempt 0)
2022-08-24 12:14:41,508 Connecting. Database: default. User: default
2022-08-24 12:14:41,508 Connecting to sentry-clickhouse:9000
2022-08-24 12:14:41,510 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-08-24 12:14:41,510 Query: SELECT version()
2022-08-24 12:14:41,511 Block "" send time: 0.000032
2022-08-24 12:14:41,513 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'generic_metrics')
2022-08-24 12:14:41,514 Block "" send time: 0.000022
2022-08-24 12:14:41,518 Running migration: 0001_migrations
2022-08-24 12:14:41,518 Connecting. Database: default. User: default
2022-08-24 12:14:41,518 Connecting to sentry-clickhouse:9000
2022-08-24 12:14:41,520 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-08-24 12:14:41,520 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='sentry-clickhouse'
2022-08-24 12:14:41,520 Block "" send time: 0.000027
2022-08-24 12:14:41,524 Connecting. Database: default. User: default
2022-08-24 12:14:41,524 Connecting to sentry-clickhouse-0.sentry-clickhouse-headless.sentry.svc.cluster.local:9000
2022-08-24 12:14:41,526 Connected to ClickHouse server version 20.8.19, revision: 54438
2022-08-24 12:14:41,526 Query: CREATE TABLE IF NOT EXISTS migrations_local (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/migrations/{shard}/default/migrations_local', '{replica}', version) ORDER BY (group, migration_id);
2022-08-24 12:14:41,526 Block "" send time: 0.000028
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 187, in execute
    result_data = query_execute()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 304, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 491, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 151, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 167, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 184, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 999.
DB::Exception: Cannot use any of provided ZooKeeper nodes (Bad arguments). Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cefaa0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63b33d in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x167681e8 in /usr/bin/clickhouse
3. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x167688de in /usr/bin/clickhouse
4. ? @ 0x1677abe1 in /usr/bin/clickhouse
5. zkutil::ZooKeeper::ZooKeeper(Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x16775087 in /usr/bin/clickhouse
6. DB::Context::getZooKeeper() const @ 0x156fb037 in /usr/bin/clickhouse
7. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0x15f6e455 in /usr/bin/clickhouse
8. ? @ 0x1630b7fb in /usr/bin/clickhouse
9. std::__1::__function::__func<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&), std::__1::allocator<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) @ 0x16310717 in /usr/bin/clickhouse
10. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15e8fba4 in /usr/bin/clickhouse
11. ? @ 0x158b76d6 in /usr/bin/clickhouse
12. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x158b9f0d in /usr/bin/clickhouse
13. DB::InterpreterCreateQuery::execute() @ 0x158bca69 in /usr/bin/clickhouse
14. ? @ 0x15d15782 in /usr/bin/clickhouse
15. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15d170a2 in /usr/bin/clickhouse
16. DB::TCPHandler::runImpl() @ 0x163bba45 in /usr/bin/clickhouse
17. DB::TCPHandler::run() @ 0x163bc7b0 in /usr/bin/clickhouse
18. Poco::Net::TCPServerConnection::start() @ 0x18c0d76b in /usr/bin/clickhouse
19. Poco::Net::TCPServerDispatcher::run() @ 0x18c0dcf8 in /usr/bin/clickhouse
20. Poco::PooledThread::run() @ 0x18d8c7e6 in /usr/bin/clickhouse
21. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d87be0 in /usr/bin/clickhouse
22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
23. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 64, in migrate
    runner.run_all(force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 157, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 217, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 145, in forwards
    op.execute(local=True)
  File "/usr/src/snuba/snuba/migrations/operations.py", line 29, in execute
    connection.execute(self.format_sql())
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 263, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Cannot use any of provided ZooKeeper nodes (Bad arguments). Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cefaa0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63b33d in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x167681e8 in /usr/bin/clickhouse
3. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x167688de in /usr/bin/clickhouse
4. ? @ 0x1677abe1 in /usr/bin/clickhouse
5. zkutil::ZooKeeper::ZooKeeper(Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x16775087 in /usr/bin/clickhouse
6. DB::Context::getZooKeeper() const @ 0x156fb037 in /usr/bin/clickhouse
7. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0x15f6e455 in /usr/bin/clickhouse
8. ? @ 0x1630b7fb in /usr/bin/clickhouse
9. std::__1::__function::__func<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&), std::__1::allocator<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) @ 0x16310717 in /usr/bin/clickhouse
10. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15e8fba4 in /usr/bin/clickhouse
11. ? @ 0x158b76d6 in /usr/bin/clickhouse
12. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x158b9f0d in /usr/bin/clickhouse
13. DB::InterpreterCreateQuery::execute() @ 0x158bca69 in /usr/bin/clickhouse
14. ? @ 0x15d15782 in /usr/bin/clickhouse
15. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15d170a2 in /usr/bin/clickhouse
16. DB::TCPHandler::runImpl() @ 0x163bba45 in /usr/bin/clickhouse
17. DB::TCPHandler::run() @ 0x163bc7b0 in /usr/bin/clickhouse
18. Poco::Net::TCPServerConnection::start() @ 0x18c0d76b in /usr/bin/clickhouse
19. Poco::Net::TCPServerDispatcher::run() @ 0x18c0dcf8 in /usr/bin/clickhouse
20. Poco::PooledThread::run() @ 0x18d8c7e6 in /usr/bin/clickhouse
21. Poco::ThreadImpl::runnableEntry(void*) @ 0x18d87be0 in /usr/bin/clickhouse
22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
23. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2022-08-24T12:14:41.537926230Z
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by andrewhearin** [comment]
hi @dmekhov  I was getting the same thing until I enabled zookeper_servers: https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L713

I'm also using external msk and postgres (however now I need to figure out how to specify the msk zookeeper endpoints)

edit: I couldn't find any reliable answers or documentation but after some trial and error, the below is how I specified my AWS MSK Zookeeper endpoints, in the above helm chart:

```sh
zookeeper_servers:
  enabled: true
  config:
    - index: "1"
      host: "z-1.myFirstEndpoint-west-2.amazonaws.com"
      port: "2181"
    - index: "2"
      host: "z-2.mySecondEndpoint-west-2.amazonaws.com"
      port: "2181"
    - index: "3"
      host: "z-3.myThirdEndPoint-west-2.amazonaws.com"
      port: "2181" 
```
