### ISSUE TITLE
AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline' errors with the latest chart (v15.2.1)

### ISSUE THREAD

**Issue by prasadkris** [sentry-kubernetes/charts#730]
Greetings! 👋 

I am getting the following errors while attempting to deploy sentry with the latest chart (v15.2.1) on our self hosted K8s cluster.

```
k logs sentry-web-7c44b7565d-pcpls | grep -i erro
AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline'
05:39:34 [ERROR] sentry_sdk.errors: Error occurred while patching `rediscluster` library
AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline'
05:39:37 [ERROR] sentry_sdk.errors: Error occurred while patching `rediscluster` library
AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline'
05:39:37 [ERROR] sentry_sdk.errors: Error occurred while patching `rediscluster` library
AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline'
05:39:37 [ERROR] sentry_sdk.errors: Error occurred while patching `rediscluster` library

k logs sentry-worker-8d8986879-62d64 -f
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 123, in setup_once
    _patch_rediscluster()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 88, in _patch_rediscluster
    pipeline_cls = rediscluster.ClusterPipeline
AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline'
06:15:49 [ERROR] sentry_sdk.errors: Error occurred while patching `rediscluster` library
```

This issue only exists with chart versions 15.2.x (15.2.0 and 15.2.1 - serving sentry 22.8.0), The older chart versions appears to work fine. I would greatly appreciate if someone could help me with this, Thanks! 🙏

**Comment by rajivmucheli** [comment]
which relay mode is being used ?

**Comment by prasadkris** [comment]
managed.

**Comment by spectrogram** [comment]
I believe this is due to https://github.com/getsentry/sentry-python/pull/1565
The fix hasn't been cut into a release yet, but I was able to work around this issue for now by using the `nightly` image.

**Comment by prasadkris** [comment]
Thank you, @spectrogram I tested the `nightly` image and it works without any errors. 👍 hopefully a new release will be available soon with this fix, thanks! 🙏

**Comment by schmidp** [comment]
@prasadkris did you just write:

```
images:
  sentry:
    tag: "nightly"
  snuba:
    tag: "nightly"
  relay:
    tag: "nightly"
  symbolicator:
    tag: 0.5.1
    imagePullSecrets: []
```

to get it working?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
