### ISSUE TITLE
UI login failure when deployed using Spinnaker

### ISSUE THREAD

**Issue by ns-mjagtap** [sentry-kubernetes/charts#731]
Hi,

I have deployed the Sentry vanilla chart v15.0.1 on a GKE cluster - without any helm overrides.

The helm chart was deployed successfully - but on sentry UI, I got the following error with default creds `admin@sentry.local/aaaa`

```Please enter a correct username and password. Note that both fields may be case-sensitive.```

Logs with the following info is at https://gist.github.com/ns-mjagtap/6d7a749708bb1bcb8234faa629faac40
 - baked manifest file
 - kubectl get output
 - `stern` logs collected after trying to login from UI

As seen in the manifest, the local user email and password is as expected as https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L3
The main error log is
```sentry-web-d945fb9d7-v89c9 sentry-web 2022-09-16T16:13:14.264203403+05:30 10:43:14 [INFO] sentry.access.api: api.access (method='POST' view='sentry.web.frontend.auth_organization_login.AuthOrganizationLoginView' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/auth/login/sentry/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.16381001472473145 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')```

Not sure why the `user_id='None'`.

Could someone pls check?

Thank you in advance.
Manish

**Comment by ns-mjagtap** [comment]
Debugging some more, `sentry-user-create` pod shows the following error logs.

```
$ kubectl get pod/sentry-user-create-psrrz
NAME                       READY   STATUS      RESTARTS   AGE
sentry-user-create-psrrz   0/1     Completed   0          44m

$ kubectl logs -f pod/sentry-user-create-psrrz
10:36:18 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
10:36:21 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.UndefinedColumn: column auth_user.actor_id does not exist
LINE 1: ..."auth_user"."flags", "auth_user"."session_nonce", "auth_user...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.UndefinedColumn: UndefinedColumn('column auth_user.actor_id does not exist\nLINE 1: ..."auth_user"."flags", "auth_user"."session_nonce", "auth_user...\n                                                             ^\n')
SQL: SELECT "auth_user"."password", "auth_user"."last_login", "auth_user"."id", "auth_user"."username", "auth_user"."first_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."is_superuser", "auth_user"."is_managed", "auth_user"."is_sentry_app", "auth_user"."is_password_expired", "auth_user"."last_password_change", "auth_user"."flags", "auth_user"."session_nonce", "auth_user"."actor_id", "auth_user"."date_joined", "auth_user"."last_active" FROM "auth_user" WHERE "auth_user"."username" = %s

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 187, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/createuser.py", line 92, in createuser
    user = User.objects.get(username=email)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/models/manager/base.py", line 225, in get
    model: M = super().get(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.ProgrammingError: UndefinedColumn('column auth_user.actor_id does not exist\nLINE 1: ..."auth_user"."flags", "auth_user"."session_nonce", "auth_user...\n                                                             ^\n')
SQL: SELECT "auth_user"."password", "auth_user"."last_login", "auth_user"."id", "auth_user"."username", "auth_user"."first_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."is_superuser", "auth_user"."is_managed", "auth_user"."is_sentry_app", "auth_user"."is_password_expired", "auth_user"."last_password_change", "auth_user"."flags", "auth_user"."session_nonce", "auth_user"."actor_id", "auth_user"."date_joined", "auth_user"."last_active" FROM "auth_user" WHERE "auth_user"."username" = %s```

**Comment by ns-mjagtap** [comment]
Irrespective of above probably fatal logs, the status of `sentry-user-create` pod shows successful completion - probably due to ` || true` after the `sentry createuser` command (code [link](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/hooks/user-create.yaml#L70))as shown below.
Default username/password (admin@sentry.local/aaaa)  can be seen in the following output - but the GUI login still fails with error `Please enter a correct username and password.` 

```
$ kubectl describe po/sentry-user-create-xxxx
...
Containers:
  user-create-job:
...
    Image:         getsentry/sentry:22.7.0
...
    Command:
      /bin/bash
      -c
    Args:
      sentry createuser \
        --no-input \
        --superuser \
        --email "admin@sentry.local" \
        --password "$ADMIN_PASSWORD" || true; \
      if [ $? -eq 0 ] || [ $? -eq 3 ]; then \
        exit 0; \
      else \
        exit 1; \
      fi

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
...
    Environment:
      ADMIN_PASSWORD:     aaaa
      POSTGRES_PASSWORD:  <set to the key 'postgresql-password' in secret 'sentry-sentry-postgresql-v000'>  Optional: false
    Mounts:```

**Comment by ns-mjagtap** [comment]
Error logs from `sentry-relay` pod:
```
$ kubectl get po/sentry-relay-6c457c766f-9g4sj
NAME                            READY   STATUS    RESTARTS   AGE
sentry-relay-6c457c766f-9g4sj   1/1     Running   0          122m

$ kubectl logs po/sentry-relay-6c457c766f-9g4sj
2022-09-20T11:28:44Z [relay_server::actors::upstream] INFO: registering with upstream (http://sentry-web:9000/)
2022-09-20T11:28:44Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by bernardolankheet** [comment]
Hi @ns-mjagtap, did you succeed in fixing this problem? I have the same problem in my environment.

**Comment by ns-mjagtap** [comment]
This issue was seen when the deployment was done using spinnaker.

Later, I just used helm CLI (sample below) and the GUI login worked.

```
$ helm repo add sentry https://sentry-kubernetes.github.io/charts

$ helm upgrade sentry sentry/sentry --version 15.1.0 \
  --install --create-namespace \
  --namespace ${NS} \
  -f ~/path/to/override-values.yml \
  --set user.email='sentry-admin@example.com' \
  --set user.password='<ADMIN_PASSWORD>' \
  --set postgresql.postgresqlPassword='<PGSQL_PASSWORD>' \
  --debug
```
I didn't get a chance to debug the login failure when deployed via spinnaker.

My helm override-values.yaml is 
```
  # Sentry images
images:
  sentry:
    tag: "22.8.0"
  snuba:
    tag: "22.8.0"
  relay:
    tag: "22.8.0"

nginx:
  enabled: false
  ```

**Comment by ns-mjagtap** [comment]
Update: 
Looks like Spinnaker doesn't support `helm hooks` - https://github.com/spinnaker/spinnaker/issues/5700

The sentry chart here has multiple helm hook files, and they are not executed when deployed via Spinnaker.
One of the hook is `user-create.yaml`. Since helm hooks are not executed, the GUI login fails when the chart is deployed via Spinnaker.

**Workaround:** Manage sentry helm deployments via `helm` CLI or any other CD tool that supports `helm hooks`.
