### ISSUE TITLE
Getting Too many parts (300). Merges are processing significantly slower than inserts from clickhouse

### ISSUE THREAD

**Issue by brianchan661** [sentry-kubernetes/charts#743]
My sentry is handling around 700k error per hour, and was running well for 5 months,
while suddenly I start getting below errors from click house.
Tried to delete most of the old data in click house pvc, but doesn't help.
Do some one have idea how should i solve it?

> 2022-10-04 13:34:42,299 librdkafka log level: 6
2022-10-04 13:34:45,094 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 27744513, Partition(topic=Topic(name='events'), index=1): 33082072, Partition(topic=Topic(name='events'), index=2): 46448020, Partition(topic=Topic(name='events'), index=3): 11878832, Partition(topic=Topic(name='events'), index=4): 39330301, Partition(topic=Topic(name='events'), index=5): 29221828, Partition(topic=Topic(name='events'), index=6): 17687435, Partition(topic=Topic(name='events'), index=7): 11550491, Partition(topic=Topic(name='events'), index=8): 27825289, Partition(topic=Topic(name='events'), index=9): 35082427, Partition(topic=Topic(name='events'), index=10): 11887986, Partition(topic=Topic(name='events'), index=11): 30928059, Partition(topic=Topic(name='events'), index=12): 16353313, Partition(topic=Topic(name='events'), index=13): 16767766, Partition(topic=Topic(name='events'), index=14): 12629837, Partition(topic=Topic(name='events'), index=15): 9684161, Partition(topic=Topic(name='events'), index=16): 25702358, Partition(topic=Topic(name='events'), index=17): 42009924, Partition(topic=Topic(name='events'), index=18): 31760085, Partition(topic=Topic(name='events'), index=19): 16385015}
2022-10-04 13:34:46,020 Caught {
  "__type__": "SerializableException",
  "__name__": "ClickhouseWriterError",
  "__message__": "Received from sentry-prod-clickhouse-2.sentry-prod-clickhouse-headless.sentry--prod.svc.cluster.local:9000. DB::Exception: Too many parts (301). Merges are processing significantly slower than inserts.. (version 20.8.19.4 (official build))",
  "__should_report__": true,
  "__extra_data__": {
    "code": 252,
    "row": null
  }
}, shutting down...
2022-10-04 13:34:46,020 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7f3b0dcb8f40>...
2022-10-04 13:34:46,020 Closing <snuba.utils.streams.kafka_consumer_with_commit_log.KafkaConsumerWithCommitLog object at 0x7f3b0dc99040>...
2022-10-04 13:34:46,025 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 191, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 108, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 143, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/filter.py", line 26, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/transform.py", line 58, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 109, in close_and_reset_batch
    self.batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 261, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 101, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Received from sentry-prod-clickhouse-2.sentry-prod-clickhouse-headless.sentry--prod.svc.cluster.local:9000. DB::Exception: Too many parts (301). Merges are processing significantly slower than inserts.. (version 20.8.19.4 (official build))

**Comment by Mokto** [comment]
I just started having those. Did you update your chart recently?

**Comment by brianchan661** [comment]
no, I am still using the v14.0.0
Spend the whole day googling and trial-an-error, but aren't able to solve it

maybe not useful but just for your information. 
My last commit was 1 week ago, to scale down some components and reset some kafka offset. 
and the problem start happening probably from a day ago (the new errors stop showing on Sentry from yesterday)

**Comment by brianchan661** [comment]
There are many files in var/lib/clickhouse/store and seem they are merging too slow.
```
root@sentry-prod-clickhouse-2:/var/lib/clickhouse/store# find . -type d | cut -d/ -f 2 | uniq -c
      1 .
    104 925
      2 e83
     78 b01
    309 be0
     29 e12
    195 6d6
```

And any idea who is writing to click house?
I though only snuba consumers are writing to it, but even one scale down all snuba components, 
the files are still creating in /var/lib/clickhouse/store/*

**Comment by brianchan661** [comment]
any updates for the issue?

**Comment by veyselsahin** [comment]
same issue here. are there any updates or thoughts? I guess there is a bug on the sentry side about writing queries. It might solve the issue by adding something to the code to make writing queries bulky.

**Comment by DmitriyLyalyuev** [comment]
Same here

**Comment by veyselsahin** [comment]
I changed my clickhouse's storageclass and the problem is solved. Unfortunately, there was no useful metric from clickhouse to determine it. I changed my sentry-clickhouse-config by adding these lines.
```
   <merge_tree>
     <parts_to_delay_insert>1000</parts_to_delay_insert> 
     <parts_to_throw_insert>1200</parts_to_throw_insert> 
      <max_part_loading_threads>48</max_part_loading_threads> 
    </merge_tree>
```
Also, I increased commit batch size to 15000 for post-process-forward by adding this parameter to startup
`--commit-batch-size 15000`

**Comment by brianchan661** [comment]
Great @veyselsahin ,
would you mind share the charts's values.yaml? I am not sure how to add those config in my charts.

and is the post-process-forward the only component writing to clickhouse?
If so, based on my understanding, we even doesn't need to change the clickhouse config as the writing queries is bulky enough.
(JFYI: I face this problem during my maxBatchSize set as 1000 for post-process-forward)

**Comment by veyselsahin** [comment]
@brianchan661 here is the my post-process-forward startup command:
`
sentry run post-process-forwarder --commit-batch-size 511 --initial-offset-reset latest
`
For the updated chart I can say that I stopped using the chart because it was so urgent for us and I did all my changes manually. 

Setting max-batch-size is depended on your messages behind the snuba-post-processor consumer group. If your consumers quickly consumes messages you can keep it lower but if you still struggling because of storage performance you can decrease partitions and increase max-batch-size to accumulate more message before pushing them to clickhouse. Anybody will be welcome to get corrected if I am wrong.

By the way, if you can't see any parameters in your chart values you can modify templates and in that case, you should put these files into a VCS to version and track them.

**Comment by brianchan661** [comment]
Thanks @veyselsahin 
Will you guide us how you add the config?
The problem start happening again on the snuba-consumer, even I set 2 partition with 1000max-batch-size..
I tried to update the config file manually in the clickhouse instance and restart the clickhouse, but seem i have trouble in restarting the clickhouse

This is my change
```
cat /var/lib/clickhouse/preprocessed_configs/config.xml |grep merge -A10
    <merge_tree>
        <max_suspicious_broken_parts>5</max_suspicious_broken_parts>
        <parts_to_delay_insert>1000</parts_to_delay_insert> 
        <parts_to_throw_insert>1200</parts_to_throw_insert> 
        <max_part_loading_threads>48</max_part_loading_threads> 	   
    </merge_tree>
```

before the change, i am able to get the value
```
ps aux | tail -n +2 | awk '{ printf("%s\t%s\n", $1, $4) }'     | clickhouse-local --structure "user String, mem Float64"         --query "select * from system.merge_tree_settings where name like 'parts_to_throw_insert' format Vertical;"
Row 1:
──────
name:        parts_to_throw_insert
value:       300
changed:     0
description: If more than this number active parts in single partition, throw 'Too many parts ...' exception.
type:        UInt64
```

but after i update the config file
```
root@sentry-prod-clickhouse-0:/etc/clickhouse-server# ps aux | tail -n +2 | awk '{ printf("%s\t%s\n", $1, $4) }'     | clickhouse-local --structure "user String, mem Float64"         --query "select * from system.merge_tree_settings where name like 'parts_to_throw_insert' format Vertical;"
Processing configuration file 'config.xml'.
Merging configuration file 'config.d/config.xml'.
Including configuration file '/etc/clickhouse-server/metrica.d/metrica.xml'.
Env variable is not set: SHARD
Include not found: clickhouse_compression
Saved preprocessed configuration to '/var/lib/clickhouse//preprocessed_configs/config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Logging trace to console
2022.11.16 05:07:11.308245 [ 1388 ] {} <Debug> ConfigProcessor: Processing configuration file 'users.xml'.
2022.11.16 05:07:11.310897 [ 1388 ] {} <Debug> ConfigProcessor: Merging configuration file 'users.d/users.xml'.
2022.11.16 05:07:11.310972 [ 1388 ] {} <Warning> ConfigProcessor: Include not found: networks
2022.11.16 05:07:11.311278 [ 1388 ] {} <Debug> ConfigProcessor: Saved preprocessed configuration to '/var/lib/clickhouse//preprocessed_configs/users.xml'.
2022.11.16 05:07:11.312287 [ 1388 ] {} <Information> StatusFile: Status file /var/lib/clickhouse/status already exists - unclean restart. Contents:
PID: 1
Started at: 2022-11-16 03:08:18
Revision: 54438

Code: 76, e.displayText() = DB::Exception: Cannot lock file /var/lib/clickhouse/status. Another server instance in same directory is already running. (version 20.8.19.4 (official build))
2022.11.16 05:07:11.312810 [ 1388 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2022.11.16 05:07:11.312831 [ 1388 ] {} <Information> Context: Shutdown disk default
```

It looks failed to restart.
and I tried different command to restart clickhouse, but either it failed to restart, or just create a new pod and revert my config changes

**Comment by brianchan661** [comment]
cc: @Mokto @veyselsahin 
Anyone can help?
I am facing this issue from time to time

**Comment by brianchan661** [comment]
I finally found out the issue and the way for solving it.
It is caused by a bug is some old version clickhouse when some parts were loss.
`Some GET_PART entry might hang in replication queue if part is lost on all replicas and there are no other parts in the same partition. It's fixed in cases when partition key contains only columns of integer types or Date[Time]`
It should be already fixed in the latest version. [ref: [changes log](https://clickhouse.com/docs/en/whats-new/changelog/2021/)]
Although I am not sure how the issue triggered, maybe the cleanup cron jobs is removing some old data in clickhouse?

And here is a workaround to solve the problem, my failed component is sunba-consumer and the errors is reported in the clickhouse2 (i have 3 replicas), and the failed table is errors_local

```
// access to the pod
kubectl --context=awscmhinfra2 -n sentry--prod exec -it sentry-prod-clickhouse-2 -- bash
 
// access to the clickhouse db, just press enter if it is asking for password
clickhouse-client --host 127.0.0.1 --password
 
// This show the parts of each table, you should see the top one's number match the error message.
select count() parts_count, database,table,partition from system.parts where active group by database,table,partition order by parts_count desc
 
// You should see there are few hundreds or thousand of queue in this table, normal should less than 10
select count() from system.replication_queue
 
// The position column of the next MERGE_PARTS query probably is far from the top
select * from system.replication_queue where type='MERGE_PARTS' limit 1
 
// you may also run this query and you should see a lot of GET_PARTS query are running slowly, and they are trying to get the parts which already deleted from servers/replicas.
// you may also find the actual parts file in /var/lib/clickhouse/data/default/table_name. The parts' prefix the queries is looking for, should be already removed in the folder.
// select * from system.replication_queue


// this query will get the partition id (the prefix of the parts) and return a query for you to execute
SELECT concat('alter table ', database, '.', table, ' drop partition id \'', partition_id, '\';')
FROM
(
    SELECT
        database,
        table,
        splitByChar('_', new_part_name)[1] AS partition_id
    FROM system.replication_queue
    WHERE (type = 'GET_PART') AND (NOT is_currently_executing) AND (create_time < toStartOfDay(yesterday()))
    GROUP BY
        database,
        table,
        partition_id
) AS q
LEFT JOIN
(
    SELECT
        database,
        table,
        partition_id,
        countIf(active) AS cnt_active,
        count() AS cnt_total
    FROM system.parts
    GROUP BY
        database,
        table,
        partition_id
) AS p USING (database, table, partition_id)
WHERE cnt_active = 0
 
 
// example response
┌─concat('alter table ', database, '.', table, ' drop partition id \'', partition_id, '\';')─┐
│ alter table default.errors_local drop partition id '14-20221114';                          │
└────────────────────────────────────────────────────────────────────────────────────────────┘

// execute the query returned previously
alter table default.errors_local drop partition id '14-20221114';
 
// Check the query again, the number should be significantly dropped, or even 0
select count() from system.replication_queue
 
// The position column of the next MERGE_PARTS query probably is far from the top
select * from system.replication_queue where type='MERGE_PARTS' limit 1
 
// Check the tables again, the table which have issues should have a lower number now.
select count() parts_count, database,table,partition from system.parts where active group by database,table,partition order by parts_count desc
```

@Mokto , @veyselsahin may i know your clickhouse version you are using?

**Comment by veyselsahin** [comment]
@brianchan661 yandex/clickhouse-server:20.8.19.4

**Comment by brianchan661** [comment]
@veyselsahin thanks, we are using the same version.
I expect we will have face the same issue again unless we update the version to >21.12

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
