### ISSUE TITLE
Consumers (eg session, outcomes) keep crashing 

### ISSUE THREAD

**Issue by bumarcell** [sentry-kubernetes/charts#747]
This keeps happening over and over again. Not sure what started it tho..
eg snuba outcomes consumer starts working fine the suddenly it catches an exception:
`2022-10-05 08:45:52,949 Consumer Starting 
2022-10-05 08:45:52,950 librdkafka log level: 6 
2022-10-05 08:45:53,753 New partitions assigned: {Partition(topic=Topic(name='ingest-sessions'), index=0): 13784173} 2022-10-05 08:45:59,686 Completed processing <Batch: 463 messages, open for 5.93 seconds>. 
2022-10-05 08:46:02,948 Completed processing <Batch: 20 messages, open for 8.40 seconds>. 
2022-10-05 08:46:05,941 Completed processing <Batch: 139 messages, open for 6.25 seconds>.
2022-10-05 08:46:06,134 Completed processing <Batch: 115 messages, open for 3.18 seconds>. 
2022-10-05 08:46:11,275 Completed processing <Batch: 90 messages, open for 5.33 seconds>. 
2022-10-05 08:46:14,290 Completed processing <Batch: 16 messages, open for 7.57 seconds>. 
2022-10-05 08:46:14,540 Completed processing <Batch: 124 messages, open for 3.26 seconds>. 
2022-10-05 08:46:16,990 Completed processing <Batch: 87 messages, open for 2.70 seconds>. 
2022-10-05 08:46:22,431 Completed processing <Batch: 21 messages, open for 7.38 seconds>. 
2022-10-05 08:46:26,354 Completed processing <Batch: 53 messages, open for 9.36 seconds>. 
2022-10-05 08:46:31,640 Completed processing <Batch: 162 messages, open for 9.21 seconds>. 
2022-10-05 08:46:31,643 Partitions revoked: [Partition(topic=Topic(name='ingest-sessions'), index=0)] 
2022-10-05 08:46:34,898 Connection pool is full, discarding connection: sentry-prod-clickhouse. Connection pool size: 1 2022-10-05 08:46:34,902 Completed processing <Batch: 116 messages, open for 8.54 seconds>. 
2022-10-05 08:46:34,905 Completed processing <Batch: 1 message, open for 3.26 seconds>. 
2022-10-05 08:46:34,910 New partitions assigned: {Partition(topic=Topic(name='ingest-sessions'), index=0): 13785580} 2022-10-05 08:46:41,440 Caught exception, shutting down... Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 131, in run self._run_once() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 166, in _run_once self.__processing_strategy.poll() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/transform.py", line 63, in poll self.__next_step.poll() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 135, in poll self.close_and_reset_batch() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 199, in close_and_reset_batch self.future.result(timeout=5) File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result raise TimeoutError() concurrent.futures._base.TimeoutError 
2022-10-05 08:46:41,442 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7f9f5f728280>... 
2022-10-05 08:46:41,442 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f9f5f75a070>... 2022-10-05 08:46:41,442 Partitions revoked: [Partition(topic=Topic(name='ingest-sessions'), index=0)] 
2022-10-05 08:46:41,444 Processor terminated Traceback (most recent call last): File "/usr/local/bin/snuba", line 33, in <module> sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')()) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/usr/src/snuba/snuba/cli/consumer.py", line 190, in consumer consumer.run() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 131, in run self._run_once() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 166, in _run_once self.__processing_strategy.poll() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/transform.py", line 63, in poll self.__next_step.poll() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 135, in poll self.close_and_reset_batch() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 199, in close_and_reset_batch self.future.result(timeout=5) File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result raise TimeoutError() concurrent.futures._base.TimeoutError`

Or a TimeoutError():
`2022-10-05 07:39:47,939 Consumer Starting 
2022-10-05 07:39:47,939 librdkafka log level: 6 
2022-10-05 07:39:49,937 New partitions assigned: {Partition(topic=Topic(name='ingest-sessions'), index=0): 13691565} 2022-10-05 07:39:50,960 Statsd buffering is disabled 
2022-10-05 07:39:50,961 Statsd periodic buffer flush is disabled 
2022-10-05 07:39:56,590 Statsd buffering is disabled 
2022-10-05 07:39:56,590 Statsd periodic buffer flush is disabled 
2022-10-05 07:39:56,594 Completed processing <Batch: 223 messages, open for 6.65 seconds>. 
2022-10-05 07:39:58,937 Partitions revoked: [Partition(topic=Topic(name='ingest-sessions'), index=0)] 
2022-10-05 07:39:58,943 New partitions assigned: {Partition(topic=Topic(name='ingest-sessions'), index=0): 13691788} 2022-10-05 07:40:13,001 Statsd buffering is disabled 
2022-10-05 07:40:13,002 Statsd periodic buffer flush is disabled 
2022-10-05 07:40:13,005 Completed processing <Batch: 10 messages, open for 4.36 seconds>. 
2022-10-05 07:40:16,330 Completed processing <Batch: 19 messages, open for 6.74 seconds>. 
2022-10-05 07:40:20,857 Completed processing <Batch: 27 messages, open for 7.85 seconds>. 
2022-10-05 07:40:24,499 Completed processing <Batch: 53 messages, open for 8.17 seconds>. 
2022-10-05 07:40:29,715 Completed processing <Batch: 41 messages, open for 8.85 seconds>. 
2022-10-05 07:40:34,382 Completed processing <Batch: 17 messages, open for 9.88 seconds>. 
2022-10-05 07:40:55,262 Completed processing <Batch: 5 messages, open for 3.33 seconds>. 
2022-10-05 07:41:01,502 Caught TimeoutError(), shutting down... 
2022-10-05 07:41:01,502 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7f3f05c97f70>... 
2022-10-05 07:41:01,503 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f3f05d241c0>... 2022-10-05 07:41:01,503 Partitions revoked: [Partition(topic=Topic(name='ingest-sessions'), index=0)] 
2022-10-05 07:41:01,504 Processor terminated Traceback (most recent call last): File "/usr/local/bin/snuba", line 33, in <module> sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')()) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/usr/src/snuba/snuba/cli/consumer.py", line 188, in consumer consumer.run() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 131, in run self._run_once() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 166, in _run_once self.__processing_strategy.poll() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/transform.py", line 63, in poll self.__next_step.poll() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 135, in poll self.close_and_reset_batch() File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 199, in close_and_reset_batch self.future.result(timeout=5) File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result raise TimeoutError() concurrent.futures._base.TimeoutError`

I would be very thankful for help 🙏

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
