### ISSUE TITLE
clickhouse server exception when running snuba-db-init job 

### ISSUE THREAD

**Issue by revathi-murali** [sentry-kubernetes/charts#752]
Hi,

I am using `11.3.0` version of the charts and I get the following error for `snuba-db-init` job.

```

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x94333cc in /usr/bin/clickhouse
1. DB::ConvertImpl<DB::DataTypeFixedString, DB::DataTypeString, DB::NameToString, DB::ConvertDefaultBehaviorTag>::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) @ 0xbaf14d4 in /usr/bin/clickhouse
2. bool DB::callOnIndexAndDataType<DB::DataTypeString, DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, auto const&)&, DB::ConvertDefaultBehaviorTag>(DB::TypeIndex, auto&&, DB::ToStringMonotonicity&&...) @ 0xbae0dec in /usr/bin/clickhouse
3. DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xbadf8c4 in /usr/bin/clickhouse
4. DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xbadeda0 in /usr/bin/clickhouse
5. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x118ecc3c in /usr/bin/clickhouse
6. DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x118ed260 in /usr/bin/clickhouse
7. DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x118ee504 in /usr/bin/clickhouse
8. DB::ActionsDAG::updateHeader(DB::Block) const @ 0x11f214bc in /usr/bin/clickhouse
9. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG>) @ 0x1342cdec in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::executeExpression(DB::QueryPlan&, std::__1::shared_ptr<DB::ActionsDAG> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x12347764 in /usr/bin/clickhouse
11. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x1233f128 in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1233d354 in /usr/bin/clickhouse
13. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x12498d90 in /usr/bin/clickhouse
14. DB::IInterpreterUnionOrSelectQuery::buildQueryPipeline() @ 0x1232092c in /usr/bin/clickhouse
15. DB::InterpreterInsertQuery::execute() @ 0x1231c470 in /usr/bin/clickhouse
16. ? @ 0x126b4f60 in /usr/bin/clickhouse
17. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x126b2edc in /usr/bin/clickhouse
18. DB::TCPHandler::runImpl() @ 0x13166a64 in /usr/bin/clickhouse
19. DB::TCPHandler::run() @ 0x13175704 in /usr/bin/clickhouse
20. Poco::Net::TCPServerConnection::start() @ 0x13d04200 in /usr/bin/clickhouse
21. Poco::Net::TCPServerDispatcher::run() @ 0x13d069f8 in /usr/bin/clickhouse
22. Poco::PooledThread::run() @ 0x13f02558 in /usr/bin/clickhouse
23. Poco::ThreadImpl::runnableEntry(void*) @ 0x13eff688 in /usr/bin/clickhouse
24. start_thread @ 0x751c in /usr/lib/aarch64-linux-gnu/libpthread-2.31.so
25. ? @ 0xd122c in /usr/lib/aarch64-linux-gnu/libc-2.31.so


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 107, in bootstrap
    Runner().run_all(force=True)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 149, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 207, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 74, in forwards
    op.execute()
  File "/usr/src/snuba/snuba/migrations/operations.py", line 309, in execute
    self.__func()
  File "/usr/src/snuba/snuba/migrations/snuba_migrations/events/0014_backfill_errors.py", line 174, in backfill_errors
    clickhouse.execute(operation.format_sql())
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 103, in execute
    raise ClickhouseError(e.code, e.message) from e
snuba.clickhouse.errors.ClickhouseError: [44] DB::Exception: Illegal column Nullable(FixedString(32)) of first argument of function toString. Stack trace:
```

Can you please let me know what could be the issue?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
