### ISSUE TITLE
sentry-web and worker errors with externalPostgresql

### ISSUE THREAD

**Issue by tejasnadgoud** [sentry-kubernetes/charts#760]
I configured sentry with `externalPostgresql` (aws-rds). This RDS already had sentry data from version 9.1.2 but that is not being loaded in the sentry-ui. New errors are logged but old ones are lost.
The sentry web and worker pods are running but wen I inspect the logs i found this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", line 470, in send_envelope_wrapper
    self._send_envelope(envelope)
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", line 387, in _send_envelope
    self._send_request(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 257, in patched_send_request
    return _send_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", line 230, in _send_request
    response = self._pool.request(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/stdlib.py", line 107, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
21:39:46 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
```
chart version : 16.0.0
helm version : v2.5.1

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
