### ISSUE TITLE
[22.10.0]inequivalent arg 'durable' for queue 'counters-0' in vhost '/': received 'false' but current is 'true'

### ISSUE THREAD

**Issue by throrin19** [sentry-kubernetes/charts#774]
After update to the last Sentry version 22.10.0 (helm 17.6.0), I have this error in the Sentry Worker : 

```
Traceback (most recent call last):
--
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 208, in start
Mon, Nov 7 2022 08:43:12 | self.blueprint.start(self)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
Mon, Nov 7 2022 08:43:12 | step.start(parent)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 369, in start
Mon, Nov 7 2022 08:43:12 | return self.obj.start()
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
Mon, Nov 7 2022 08:43:12 | blueprint.start(self)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
Mon, Nov 7 2022 08:43:12 | step.start(parent)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/tasks.py", line 40, in start
Mon, Nov 7 2022 08:43:12 | c.task_consumer = c.app.amqp.TaskConsumer(
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 301, in TaskConsumer
Mon, Nov 7 2022 08:43:12 | return self.Consumer(
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 386, in __init__
Mon, Nov 7 2022 08:43:12 | self.revive(self.channel)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 408, in revive
Mon, Nov 7 2022 08:43:12 | self.declare()
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 421, in declare
Mon, Nov 7 2022 08:43:12 | queue.declare()
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 611, in declare
Mon, Nov 7 2022 08:43:12 | self._create_queue(nowait=nowait, channel=channel)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 620, in _create_queue
Mon, Nov 7 2022 08:43:12 | self.queue_declare(nowait=nowait, passive=False, channel=channel)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 648, in queue_declare
Mon, Nov 7 2022 08:43:12 | ret = channel.queue_declare(
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 1148, in queue_declare
Mon, Nov 7 2022 08:43:12 | return queue_declare_ok_t(*self.wait(
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 88, in wait
Mon, Nov 7 2022 08:43:12 | self.connection.drain_events(timeout=timeout)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 508, in drain_events
Mon, Nov 7 2022 08:43:12 | while not self.blocking_read(timeout):
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 514, in blocking_read
Mon, Nov 7 2022 08:43:12 | return self.on_inbound_frame(frame)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/amqp/method_framing.py", line 55, in on_frame
Mon, Nov 7 2022 08:43:12 | callback(channel, method_sig, buf, None)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 520, in on_inbound_method
Mon, Nov 7 2022 08:43:12 | return self.channels[channel_id].dispatch_method(
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
Mon, Nov 7 2022 08:43:12 | listener(*args)
Mon, Nov 7 2022 08:43:12 | File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 279, in _on_close
Mon, Nov 7 2022 08:43:12 | raise error_for_code(
Mon, Nov 7 2022 08:43:12 | amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'counters-0' in vhost '/': received 'false' but current is 'true'
Mon, Nov 7 2022 08:43:12 | 07:43:12 [CRITICAL] celery.worker: Unrecoverable error: PreconditionFailed(406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'counters-0' in vhost '/': received 'false' but current is 'true'", (50, 10), 'Queue.declare')
Mon, Nov 7 2022 08:43:14 | 07:43:14 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_dsymcache:clean_dsymcache')
Mon, Nov 7 2022 08:43:14 | 07:43:14 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_releasefilecache:clean_releasefilecache')


```

**Comment by Mokto** [comment]
Yeah I think the only way is to delete the queue so that sentry can recreate it with the proper arguments

**Comment by throrin19** [comment]
Isn't it easier to manage it directly in the helm with a job to launch at deployment time?

**Comment by Mokto** [comment]
Ideally yes. It would be nice to have that.

**Comment by throrin19** [comment]
I don't know how to do it myself, It's possible to manage that directly in the helm package for us ?

**Comment by ocdi** [comment]
I had this issue also, I solved it by shelling into the rabbitmq pod and executing

```bash
rabbitmqctl delete_queue counters-0
rabbitmqctl delete_queue triggers-0
```

Then the worker seemed to work

**Comment by farodin91** [comment]
Deleting the solves the issue, i had to do it multiple since the upgrade.

**Comment by danat-cc** [comment]
I can confirm the issue exists and the workaround mentioned by ocdi fixed the issue for us.

**Comment by azlydnev** [comment]
Same Issue on 22.10.0 
Downgraded to 22.9.0

**Comment by throrin19** [comment]
Any news ?

**Comment by farodin91** [comment]
I had to fix my rabbitmq definition.

**Comment by throrin19** [comment]
No news about this really annoyed problem ? Without this fix, I'm blocked in the 16.x chart version

**Comment by farodin91** [comment]
@throrin19 Does your rabbitmq loads a definition during the start? I had to update definition and issue was fixed.

**Comment by Mokto** [comment]
Just delete the old queue.

**Comment by throrin19** [comment]
@Mokto Normally using chart we don't have to do this manually, the chart does do all this migration things using jobs on helm upgrade

@farodin91 I don't know how to do/verify this

**Comment by onmomo** [comment]
We experienced the same, also for a vanilla install. This resolved it. 🙏 
* https://github.com/sentry-kubernetes/charts/issues/774#issuecomment-1324454100

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by venmad** [comment]
Thanks @ocdi , your solution helped me to fix the issue.
