### ISSUE TITLE
sentry.exceptions.InvalidConfiguration: Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#777]
Hello! Thanks for sentry helm chart
I install clean k8s cluster.
Install sentry chart.
```
helm repo add sentry https://sentry-kubernetes.github.io/charts
helm install sentry sentry/sentry
```

Get error:
```
kubectl get pod -A
NAMESPACE     NAME                                        READY   STATUS              RESTARTS   AGE
default       ingress-nginx-controller-55dcf56b68-xrh4r   1/1     Running             0          40m
default       sentry-clickhouse-0                         0/1     Init:0/1            0          4m16s
default       sentry-clickhouse-1                         0/1     Pending             0          4m16s
default       sentry-clickhouse-2                         0/1     Pending             0          4m15s
default       sentry-cron-ff8699b58-9sphq                 1/1     Running             2          4m17s
default       sentry-kafka-0                              0/1     ContainerCreating   0          4m16s
default       sentry-kafka-1                              0/1     ContainerCreating   0          4m16s
default       sentry-kafka-2                              0/1     Pending             0          4m16s
default       sentry-nginx-6dfb7f9f47-tdxf5               1/1     Running             0          4m17s
default       sentry-rabbitmq-0                           0/1     ContainerCreating   0          4m15s
default       sentry-sentry-postgresql-0                  0/1     ContainerCreating   0          4m16s
default       sentry-sentry-redis-master-0                0/1     Pending             0          4m16s
default       sentry-sentry-redis-replicas-0              0/1     Running             1          4m16s
default       sentry-snuba-api-55d9fdd85b-xc2ln           1/1     Running             0          4m17s
default       sentry-web-56d5575b6c-xf6dj                 0/1     Running             1          4m17s
default       sentry-worker-55d47b65bd-7cmrj              0/1     Error               1          4m17s
default       sentry-worker-55d47b65bd-hntb9              0/1     Error               2          4m17s
default       sentry-worker-55d47b65bd-kfrj6              0/1     Error               2          4m17s
default       sentry-zookeeper-0                          0/1     ContainerCreating   0          4m16s
default       sentry-zookeeper-clickhouse-0               0/1     Pending             0          4m16s
default       sentry-zookeeper-clickhouse-1               0/1     Pending             0          4m15s
default       sentry-zookeeper-clickhouse-2               0/1     Pending             0          4m15s
...
```

Logs pod where error
```
 kubectl logs        sentry-worker-55d47b65bd-7cmrj
08:26:03 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
08:26:14 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 552, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 609, in _connect
    raise err
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 597, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/buffer/redis.py", line 65, in validate
    client.ping()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1351, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 167, in sentry_patched_execute_command
    return old_execute_command(self, name, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 488, in execute_command
    buf = self._get_command_buffer(host_id, args[0])
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 355, in _get_command_buffer
    buf = CommandBuffer(host_id, connect, self.auto_batch)
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 91, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 107, in connect
    self.connection = self._connect_func()
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 353, in connect
    return self.connection_pool.get_connection(command_name, shard_hint=host_id)
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 254, in get_connection
    con = real_pool.get_connection(command_name)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 28, in inner
    configure()
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 124, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/settings.py", line 153, in configure
    initialize_app(
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 382, in initialize_app
    setup_services(validate=not skip_service_validation)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 425, in setup_services
    service.validate()
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/buffer/redis.py", line 69, in validate
    raise InvalidConfiguration(str(e))
sentry.exceptions.InvalidConfiguration: Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by patsevanton** [comment]
May be merge Pull request ?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
