### ISSUE TITLE
sentry-snuba-api sentry-snuba redis.exceptions.ConnectionError: Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#778]
Hello! Thanks for sentry helm chart
I install clean k8s cluster.
Install sentry chart.
```
helm repo add sentry https://sentry-kubernetes.github.io/charts
helm install sentry sentry/sentry
```

Get error:

```
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba Traceback (most recent call last):
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 611, in connect
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     sock = self.retry.call_with_retry(
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     return do()
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 612, in <lambda>
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     lambda: self._connect(), lambda error: self.disconnect(error)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 677, in _connect
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     raise err
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 665, in _connect
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     sock.connect(socket_address)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba ConnectionRefusedError: [Errno 111] Connection refused
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba 
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba During handling of the above exception, another exception occurred:
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba 
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba Traceback (most recent call last):
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/src/snuba/snuba/state/__init__.py", line 209, in get_raw_configs
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     all_configs = rds.hgetall(config_hash)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 4776, in hgetall
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     return self.execute_command("HGETALL", name)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1235, in execute_command
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     conn = self.connection or pool.get_connection(command_name, **options)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1387, in get_connection
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     connection.connect()
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 617, in connect
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     raise ConnectionError(self._error_message(e))
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba redis.exceptions.ConnectionError: Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba Traceback (most recent call last):
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 611, in connect
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     sock = self.retry.call_with_retry(
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     return do()
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 612, in <lambda>
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     lambda: self._connect(), lambda error: self.disconnect(error)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 677, in _connect
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     raise err
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 665, in _connect
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     sock.connect(socket_address)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba ConnectionRefusedError: [Errno 111] Connection refused
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba 
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba During handling of the above exception, another exception occurred:
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba 
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba Traceback (most recent call last):
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/src/snuba/snuba/state/__init__.py", line 209, in get_raw_configs
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     all_configs = rds.hgetall(config_hash)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 4776, in hgetall
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     return self.execute_command("HGETALL", name)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1235, in execute_command
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     conn = self.connection or pool.get_connection(command_name, **options)
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1387, in get_connection
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     connection.connect()
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 617, in connect
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba     raise ConnectionError(self._error_message(e))
sentry-snuba-api-55d9fdd85b-mcs52 sentry-snuba redis.exceptions.ConnectionError: Error 111 connecting to sentry-sentry-redis-master:6379. Connection refused.
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by patsevanton** [comment]
May be merge Pull request ?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by bru9squi** [comment]
#779 fix this bug.
when will release the fix?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
