### ISSUE TITLE
KeryError:2 in snuba-subscription-consumer-events

### ISSUE THREAD

**Issue by hyunkj42** [sentry-kubernetes/charts#786]
hello.
I'm trying to upgrade to sentry 22.11.0.
By the way
An error is occurring in the snuba-subscription-consumer-events pod.
```
2022-11-18 10:13:03,185 Initializing Snuba CLI...
2022-11-18 10:13:03,187 Initializing Snuba
2022-11-18 10:13:05,193 Snuba initialization took 2.007629305124283s
2022-11-18 10:13:05,298 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 0, Partition(topic=Topic(name='snuba-commit-log'), index=1): 0, Partition(topic=Topic(name='snuba-commit-log'), index=2): 0}
2022-11-18 10:13:05,304 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 188, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 2
2022-11-18 10:13:05,306 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f97bb0b4910>...
2022-11-18 10:13:05,307 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1), Partition(topic=Topic(name='snuba-commit-log'), index=2)]
2022-11-18 10:13:05,311 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 11, in <module>
    load_entry_point('snuba', 'console_scripts', 'snuba')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 188, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 2
```

subscription-consumer-transactions
The pod was running normally, but I don't know why that error occurs.
![image](https://user-images.githubusercontent.com/22021000/202594538-c9a823a1-c371-4075-9cfd-b4e522c025af.png)

If anyone knows why, please let me know.

**Comment by ilyakuchaev** [comment]
https://forum.sentry.io/t/perfomance-metric-alarm-related-to-snuba-events-subscriptions-consumers-snuba-transactions-subscriptions-consumers/15102

**Comment by hyunkj42** [comment]
@ilyakuchaev 
Thank you for answer. :)
I have 3 partitions for every topic. So, I added the following to /etc/snuba/settings.py configuration file and restarted the pod.
```
TOPIC_PARTITION_COUNTS = {
                 .
                 .    
      "snuba-commit-log": 3,
    }
```
Some time has passed since the restart, but no error occurs.
I will close that issue.
