### ISSUE TITLE
snuba consumer events and transactions pods are in crashloop

### ISSUE THREAD

**Issue by netgurru** [sentry-kubernetes/charts#793]
Hi,

We are continuously getting snuba consumer events and transactions pods crashlooping. Here is the error in it

`:~$ kubectl logs sentry-snuba-subscription-consumer-transactions-6c5959cd4fcvtnn -n sentry
2022-12-02 20:55:04,128 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 19686643, Partition(topic=Topic(name='snuba-commit-log'), index=1): 0, Partition(topic=Topic(name='snuba-commit-log'), index=2): 7824662}
2022-12-02 20:55:06,591 Caught KeyError(1), shutting down...
2022-12-02 20:55:06,591 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7ff966a134c0>...
2022-12-02 20:55:06,593 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1), Partition(topic=Topic(name='snuba-commit-log'), index=2)]
2022-12-02 20:55:06,611 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 152, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 121, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 159, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 248, in submit
    tasks.ext`

We are unable to find solution on it.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
