### ISSUE TITLE
`snuba-outcomes-consumer` and `snuba-consumer` pods keeps restarting with table does not exist

### ISSUE THREAD

**Issue by revathi-murali** [sentry-kubernetes/charts#795]
Hi,

I am using `17.7.1` of the chart which in turn is using `22.10.0` version of Sentry. `snuba-outcomes-consumer` and `snuba-consumer` pods keeps restarting with few tables does not exist (Table default.outcomes_raw_local ) and Table default.errors_local doesn't exist.

<details>
<summary> Error from snuba consumer pod - Table default.errors_local does not exist </summary>
 
```
022-12-09 08:11:41,088 Consumer Starting
2022-12-09 08:11:41,094 librdkafka log level: 6
2022-12-09 08:11:43,042 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 7}
2022-12-09 08:11:44,103 Completed processing <Batch: 2 messages, open for 1.04 seconds>.
2022-12-09 08:11:46,043 Partitions revoked: [Partition(topic=Topic(name='events'), index=0)]
2022-12-09 08:11:46,055 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 9}
2022-12-09 08:13:16,538 Completed processing <Batch: 1 message, open for 1.04 seconds>.
2022-12-09 08:15:00,613 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 185, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 291, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 107, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Table default.errors_local doesn't exist (version 21.3.20.1 (official build))
022-12-09 08:15:00,618 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7efd007db340>...
2022-12-09 08:15:00,618 Closing <snuba.utils.streams.kafka_consumer_with_commit_log.KafkaConsumerWithCommitLog object at 0x7efd007c9190>...
2022-12-09 08:15:00,618 Partitions revoked: [Partition(topic=Topic(name='events'), index=0)]
2022-12-09 08:15:00,624 Processor terminated
```
</details>

<details>
<summary>Error from snuba -outcomes-consumer pod - Table default.outcomes_raw_localdoes not exist </summary>
```
022-12-09 08:11:30,979 Consumer Starting
2022-12-09 08:11:30,980 librdkafka log level: 6
2022-12-09 08:11:31,016 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 19}
2022-12-09 08:11:33,050 Completed processing <Batch: 1 message, open for 2.03 seconds>.
2022-12-09 08:11:43,029 Partitions revoked: [Partition(topic=Topic(name='outcomes'), index=0)]
2022-12-09 08:11:43,041 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 20}
2022-12-09 08:11:46,042 Partitions revoked: [Partition(topic=Topic(name='outcomes'), index=0)]
2022-12-09 08:11:46,055 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 20}
2022-12-09 08:12:41,520 Completed processing <Batch: 2 messages, open for 2.03 seconds>.
2022-12-09 08:14:59,404 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 185, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 291, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 107, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Table default.outcomes_raw_local doesn't exist (version 21.3.20.1 (official build))
2022-12-09 08:14:59,409 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7fcb98839460>...
2022-12-09 08:14:59,409 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7fcb9d8a16a0>...
2022-12-09 08:14:59,410 Partitions revoked: [Partition(topic=Topic(name='outcomes'), index=0)]
2022-12-09 08:14:59,414 Processor terminated
```
</details>

But when I checked the `snuba-migrate` logs I can see that the table was created.

So, can you please let me know how to get around this issue??

FYI - I am using `clickhouse version 21.3`

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
