### ISSUE TITLE
Snuba Consumer connect timed out to Clickhouse

### ISSUE THREAD

**Issue by Antiarchitect** [sentry-kubernetes/charts#796]
No errors on Clickhouse side. Snuba consumer crashes regularly with this:

```
2022-12-12 05:28:26,073 Partitions revoked: [Partition(topic=Topic(name='events'), index=0)]
2022-12-12 05:28:26,116 Completed processing <Batch: 1 message, open for 0.09 seconds>.
2022-12-12 05:28:28,253 New partitions assigned: {}
2022-12-12 05:28:50,793 Partitions revoked: []
2022-12-12 05:28:52,274 New partitions assigned: {}
2022-12-12 05:28:56,793 Partitions revoked: []
2022-12-12 05:28:58,383 New partitions assigned: {}
2022-12-12 05:30:35,793 Partitions revoked: []
2022-12-12 05:30:37,931 New partitions assigned: {}
2022-12-12 05:31:06,430 Partitions revoked: []
2022-12-12 05:31:08,013 New partitions assigned: {}
2022-12-12 05:35:25,925 Partitions revoked: []
2022-12-12 05:35:28,758 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 14340233}
2022-12-12 05:35:29,867 Completed processing <Batch: 8 messages, open for 1.09 seconds>.
2022-12-12 05:35:30,940 Completed processing <Batch: 3 messages, open for 1.06 seconds>.
2022-12-12 05:35:32,942 Completed processing <Batch: 3 messages, open for 1.41 seconds>.
2022-12-12 05:35:34,875 Completed processing <Batch: 4 messages, open for 1.13 seconds>.
2022-12-12 05:35:36,984 Completed processing <Batch: 1 message, open for 1.23 seconds>.
2022-12-12 05:35:38,180 Completed processing <Batch: 3 messages, open for 1.10 seconds>.
2022-12-12 05:35:42,592 Completed processing <Batch: 4 messages, open for 1.59 seconds>.
2022-12-12 05:35:45,709 Completed processing <Batch: 4 messages, open for 1.83 seconds>.
2022-12-12 05:35:49,313 Completed processing <Batch: 4 messages, open for 1.10 seconds>.
2022-12-12 05:35:53,662 Completed processing <Batch: 3 messages, open for 3.85 seconds>.
2022-12-12 05:35:53,729 Completed processing <Batch: 3 messages, open for 1.78 seconds>.
2022-12-12 05:35:56,412 Completed processing <Batch: 2 messages, open for 1.46 seconds>.
2022-12-12 05:36:00,924 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 185, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 291, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 107, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Timeout: connect timed out: 10.32.28.203:9000 (app-sentry-clickhouse-0.app-sentry-clickhouse-headless.app-sentry.svc.cluster.local:9000): Insertion status:
2022-12-12 05:36:00,929 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7f91f80e0e50>...
2022-12-12 05:36:00,930 Closing <snuba.utils.streams.kafka_consumer_with_commit_log.KafkaConsumerWithCommitLog object at 0x7f91fb15f640>...
2022-12-12 05:36:00,930 Partitions revoked: [Partition(topic=Topic(name='events'), index=0)]
2022-12-12 05:36:00,932 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 190, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 185, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 291, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 107, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Timeout: connect timed out: 10.32.28.203:9000 (app-sentry-clickhouse-0.app-sentry-clickhouse-headless.app-sentry.svc.cluster.local:9000): Insertion status:
```

I have single rack baremetal K8s cluster with gigabit network which works perfectly. Other apps do not suffer from any network issues.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Antiarchitect** [comment]
Is there some additional info I could provide?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by shulandmimi** [comment]
same problem, is there any solution?
