### ISSUE TITLE
Snuba InvalidRangeError

### ISSUE THREAD

**Issue by maciejmaz** [sentry-kubernetes/charts#797]
I'm running self hosted sentry on my EKS cluster, installed using helm chart v.17.0.0, and recently I encountered some issues with Kafka and Snuba.

I have 3 replicas of Kafka statefulset and one of them (kafka-1) started crashlooping because there wasn't enough space on the PVC linked with this pod. I removed some .log files from this PVC to retrieve the space, what made the Kafka work, but unfortunately after that, snuba-subscription-consumer-events pod started crashlooping with the following error:

```
2022-12-12 12:43:46,758 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 405018}
2022-12-12 12:44:03,398 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 166, in poll
    Interval(previous_message.offset, commit.offset),
  File "<string>", line 5, in __init__
  File "/usr/src/snuba/snuba/utils/types.py", line 64, in __post_init__
    raise InvalidRangeError(self.lower, self.upper)
snuba.utils.types.InvalidRangeError: (4214404, 77)
2022-12-12 12:44:03,400 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f7dc5270e50>...
2022-12-12 12:44:03,401 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0)]
2022-12-12 12:44:03,406 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 166, in poll
    Interval(previous_message.offset, commit.offset),
  File "<string>", line 5, in __init__
  File "/usr/src/snuba/snuba/utils/types.py", line 64, in __post_init__
    raise InvalidRangeError(self.lower, self.upper)
snuba.utils.types.InvalidRangeError: (4214404, 77)
```

Unofrtunately I can't find any solution for this issue. 
Does anyone have any idea how to solve this?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
