### ISSUE TITLE
sentry-snuba-consumer: restarting with Kafka error

### ISSUE THREAD

**Issue by aosavitski** [sentry-kubernetes/charts#804]
Hi all.

After fresh helm chard deployment with external Kafka, everything works fine, however looking to the pods with kubectl I see a lot of restarts from sentry-snuba-consumer. In the logs, when restart happens I see this:
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 190, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/utils/streams/kafka_consumer_with_commit_log.py", line 31, in poll
    self.__producer.poll(0.0)
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 187, in __delivery_callback
    raise error
cimpl.KafkaError: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}

What could be the problem? All other consumers have 0 restarts. 

P.S. because I am using external Kafka, how I can reconfigure kafka topic names (via values.yaml) to have some prefix? sentry-events instead of events etc?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
