### ISSUE TITLE
[CRITICAL] celery.worker: Unrecoverable error: NotFound(404, "NOT_FOUND - failed to perform operation on queue 'activity.notify' in vhost '/' due to timeout", (50, 10), 'Queue.declare')

### ISSUE THREAD

**Issue by throrin19** [sentry-kubernetes/charts#819]
Hello,

After a problem with a node in my kubernetes cluster, kubernetes move sentry pods in others nodes. But, after that, I have this error in sentry-workers : 

```


warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
--
Wed, Jan 18 2023 15:14:31 | Traceback (most recent call last):
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 208, in start
Wed, Jan 18 2023 15:14:31 | self.blueprint.start(self)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
Wed, Jan 18 2023 15:14:31 | step.start(parent)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 369, in start
Wed, Jan 18 2023 15:14:31 | return self.obj.start()
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
Wed, Jan 18 2023 15:14:31 | blueprint.start(self)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
Wed, Jan 18 2023 15:14:31 | step.start(parent)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/tasks.py", line 40, in start
Wed, Jan 18 2023 15:14:31 | c.task_consumer = c.app.amqp.TaskConsumer(
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 301, in TaskConsumer
Wed, Jan 18 2023 15:14:31 | return self.Consumer(
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 386, in __init__
Wed, Jan 18 2023 15:14:31 | self.revive(self.channel)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 408, in revive
Wed, Jan 18 2023 15:14:31 | self.declare()
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 421, in declare
Wed, Jan 18 2023 15:14:31 | queue.declare()
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 611, in declare
Wed, Jan 18 2023 15:14:31 | self._create_queue(nowait=nowait, channel=channel)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 620, in _create_queue
Wed, Jan 18 2023 15:14:31 | self.queue_declare(nowait=nowait, passive=False, channel=channel)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 648, in queue_declare
Wed, Jan 18 2023 15:14:31 | ret = channel.queue_declare(
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 1148, in queue_declare
Wed, Jan 18 2023 15:14:31 | return queue_declare_ok_t(*self.wait(
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 88, in wait
Wed, Jan 18 2023 15:14:31 | self.connection.drain_events(timeout=timeout)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 508, in drain_events
Wed, Jan 18 2023 15:14:31 | while not self.blocking_read(timeout):
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 514, in blocking_read
Wed, Jan 18 2023 15:14:31 | return self.on_inbound_frame(frame)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/amqp/method_framing.py", line 55, in on_frame
Wed, Jan 18 2023 15:14:31 | callback(channel, method_sig, buf, None)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 520, in on_inbound_method
Wed, Jan 18 2023 15:14:31 | return self.channels[channel_id].dispatch_method(
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
Wed, Jan 18 2023 15:14:31 | listener(*args)
Wed, Jan 18 2023 15:14:31 | File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 279, in _on_close
Wed, Jan 18 2023 15:14:31 | raise error_for_code(
Wed, Jan 18 2023 15:14:31 | amqp.exceptions.NotFound: Queue.declare: (404) NOT_FOUND - failed to perform operation on queue 'activity.notify' in vhost '/' due to timeout
Wed, Jan 18 2023 15:14:31 | 14:14:31 [CRITICAL] celery.worker: Unrecoverable error: NotFound(404, "NOT_FOUND - failed to perform operation on queue 'activity.notify' in vhost '/' due to timeout", (50, 10), 'Queue.declare')
Wed, Jan 18 2023 15:14:32 | 14:14:32 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_dsymcache:clean_dsymcache')
Wed, Jan 18 2023 15:14:32 | 14:14:32 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_releasefilecache:clean_releasefilecache')
```

Anyone to know ow to resolve that ? 

My version of the chart : 16.0.0

Thanks in advance

**Edit** : I have the same error on the `sentry-ingest-consumer` but on the queue `events.process_event`.

After researchs, I have this error on the rabbitmq statefulset : 

```
Channel error on connection <0.31330.952> (10.13.240.231:48542 -> 10.13.237.99:5672, vhost: '/', user: 'guest'), channel 1:
--
Wed, Jan 18 2023 15:07:26 | 2023-01-18 14:07:26.018662+00:00 [erro] <0.31342.952> operation queue.declare caused a channel exception not_found: failed to perform operation on queue 'activity.notify' in vhost '/' due to timeout
Wed, Jan 18 2023 15:07:27 | 2023-01-18 14:07:27.651483+00:00 [info] <0.31330.952> closing AMQP connection <0.31330.952> (10.13.240.231:48542 -> 10.13.237.99:5672, vhost: '/', user: 'guest')
Wed, Jan 18 2023 15:07:38 | 2023-01-18 14:07:38.956516+00:00 [erro] <0.31396.952> Channel error on connection <0.31384.952> (10.13.243.224:48108 -> 10.13.237.99:5672, vhost: '/', user: 'guest'), channel 1:
Wed, Jan 18 2023 15:07:38 | 2023-01-18 14:07:38.956516+00:00 [erro] <0.31396.952> operation queue.declare caused a channel exception not_found: failed to perform operation on queue 'activity.notify' in vhost '/' due to timeout
Wed, Jan 18 2023 15:07:40 | 2023-01-18 14:07:40.487619+00:00 [info] <0.31384.952> closing AMQP connection <0.31384.952> (10.13.243.224:48108 -> 10.13.237.99:5672, vhost: '/', user: 'guest')
Wed, Jan 18 2023 15:08:00 | 2023-01-18 14:08:00.843550+00:00 [warn] <0.31450.952> closing AMQP connection <0.31450.952> (10.13.206.71:46164 -> 10.13.237.99:5672, vhost: '/', user: 'guest'):
Wed, Jan 18 2023 15:08:00 | 2023-01-18 14:08:00.843550+00:00 [warn] <0.31450.952> client unexpectedly closed TCP connection
```

**Comment by throrin19** [comment]
I've found the problem. Thanks to @rgaoistheone in this comment : https://github.com/sentry-kubernetes/charts/issues/341#issuecomment-806469173

To resolve this problem, the solution is to reduce rabbitmq statefulset size to 0 replicas, and increase gradually the cluster.

After that, the cluster load successfully and I have no more error
