### ISSUE TITLE
sentry-sessions-consumer pod is in CrashLoopBackOff

### ISSUE THREAD

**Issue by shariqmus** [sentry-kubernetes/charts#825]
I have installed release 17.0.0 of the charts on AKS.

After installation, snuba consumer pod (sentry-sessions-consumer) is constantly in CrashLoopBackOff (other pods are running fine). Checking the stdout gives the following:

```

2023-02-06 06:38:36,832 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7f25fbac7a60>...
2023-02-06 06:38:36,833 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f25fbac7190>...
2023-02-06 06:38:36,833 Partitions revoked: [Partition(topic=Topic(name='ingest-sessions'), index=0)]
2023-02-06 06:38:36,836 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 202, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 220, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 288, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 104, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 224, in join
    raise HTTPError(
urllib3.exceptions.HTTPError: Received unexpected 404 response: Code: 60. DB::Exception: Table default.sessions_raw_local doesn't exist. (UNKNOWN_TABLE) (version 22.13.1.2740 (official build))

```

I have tried multiple times to migrate manually:

```
  $ snuba bootstrap --force
  $ snuba migrations migrate --force
  $ snuba migrations list
  $ snuba migrations migrate --group discover --force
  $ snuba migrations migrate --group events  --force
  $ snuba migrations migrate --group generic_metrics  --force
  $ snuba migrations migrate --group metrics --force
  $ snuba migrations migrate --group outcomes --force
  $ snuba migrations migrate --group replays  --force
  $ snuba migrations migrate --group sessions --force
  $ snuba migrations migrate --group system --force
  $ snuba migrations migrate --group transactions --force
```

I even tried to manually create the table:
```
$ clickhouse-client  --user default --password "" --database=default

# CREATE TABLE default.transactions_local ........ 
```

But seems it is not reflected and it keeps complaining about *Table default.sessions_raw_local doesn't exist.*

What am I missing. Any pointers please?

**Comment by source-xm** [comment]
you can try the following steps
1.  snuba-sessions-consumer replica set 0
2.  run : snuba bootstrap --force
3. snuba-sessions-consumer replica set 1

If not
1.  stop all snuba pod
2.  recreate clickohouse / kafka / zookeeper / zookeeper-clickhouse  and associated pvc
3.  run snuba-api and  execute command:  snuba bootstrap --force
4. restart all snuba pod

**Comment by source-xm** [comment]
you can try the following steps

clickohouse/zookeeper-clickhouse  set 1
snuba-sessions-consumer replica set 0
run : snuba bootstrap --force
snuba-sessions-consumer replica set 1

If not

stop all snuba pod
recreate clickohouse / kafka / zookeeper / zookeeper-clickhouse and associated pvc
run snuba-api and execute command: snuba bootstrap --force
restart all snuba pod

the reason is that multiple container service problems in clickhouse are not synchronized

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by Sodawyx** [comment]
Have you ever solved this problem? I used external clickhouse and I encountered the same problem!

**Comment by shariqmus** [comment]
> Have you ever solved this problem? I used external clickhouse and I encountered the same problem!

Using external clickhouse also didnt solve the issue for me.

I just ended up switching to SIgnoz.
