### ISSUE TITLE
Clickhouse `*_local` and `*_dist` tables are not created/initialized with the new chart 17.0.0

### ISSUE THREAD

**Issue by larasika** [sentry-kubernetes/charts#839]
Hi there,

We're using the new chart version 17.0.0 along with kustomize to generate our kubenertes manifest file and deploy it to kubernetes.
After running the deployment, some pods are constantly failing in `CrashLoopBackOff` because they can find the tables they're expecting in Clickhouse. And those pods that are:
- sentry-sessions-consumer
- sentry-snuba-consumer
- sentry-snuba-outcomes-consumer
- sentry-snuba-transactions-consumer

The error in each failing pod is similar, which (as example for `sentry-snuba-transactions-consumer`) looks like : 
```
[larasika.nadela]$ kubectl logs --tail 100 -n sentry sentry-snuba-transactions-consumer-67df9444fb-crmt7
2023-03-07 20:57:56,730 Consumer Starting
2023-03-07 20:57:56,731 librdkafka log level: 6
2023-03-07 20:57:56,749 New partitions assigned: {Partition(topic=Topic(name='transactions'), index=0): 0}
2023-03-07 20:57:58,753 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 185, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 291, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 107, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Table default.transactions_dist doesn't exist. (version 20.8.19.4 (official build))
```

The other failing pods are also looking for a `*_dist` table:
- sentry-sessions-consumer: `snuba.clickhouse.errors.ClickhouseWriterError: Table default.sessions_raw_dist doesn't exist. (version 20.8.19.4 (official build))`
- sentry-snuba-consumer: `snuba.clickhouse.errors.ClickhouseWriterError: Table default.errors_dist doesn't exist. (version 20.8.19.4 (official build))`
- sentry-snuba-outcomes-consumer: `snuba.clickhouse.errors.ClickhouseWriterError: Table default.outcomes_raw_dist doesn't exist. (version 20.8.19.4 (official build))`

If we try to create the `*_dist` tables manually from a `sentry-clickhouse` pod:
`clickhouse-client --database=default --host=sentry-clickhouse-0.sentry-clickhouse-headless --port=9000 --query="CREATE TABLE transactions_dist AS transactions_local ENGINE = Distributed('sentry-clickhouse', default, transactions_local, rand())";`

we will get another error complaining that the `*_local` table doesn't exist:
`Code: 60. DB::Exception: Received from sentry-clickhouse-0.sentry-clickhouse-headless:9000. DB::Exception: Table default.errors_local doesn't exist..`

We've noticed that there used to be a `clickhouse-init` job in the old version that was responsible for creating the tables in Clickhouse. But now it's removed and I can't seem to find where the tables creation is supposed to happen in the new verions 17.0.0.

Could anyone please help and give some pointers about what I could be missing in my setup, please ? Thank you !

**Comment by ghost** [comment]
hey, in my case changing the snuba/clickhouse version helped a lot. it was painfull process to find out what the problem was but i got it working using the 21.8 for clickhouse and 22.12.0 for snuba. Hope it helps!  

also check this one out : [https://github.com/sentry-kubernetes/charts/issues/652](url)

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
