### ISSUE TITLE
Unable to run snuba migration

### ISSUE THREAD

**Issue by iburrows** [sentry-kubernetes/charts#851]
Hi,
I am using the latest charts and sentry version and I am receiving the following in snuba-migrate
```
2023-03-28 15:34:59,319 Attempting to connect to Clickhouse cluster sentry-clickhouse:9000 (attempt 0)
2023-03-28 15:34:59,320 Connecting. Database: default. User: default
2023-03-28 15:34:59,320 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,323 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,323 Query: SELECT version()
2023-03-28 15:34:59,323 Block "" send time: 0.000052
2023-03-28 15:34:59,332 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'metrics', 'outcomes', 'sessions', 'replays', 'generic_metrics')
2023-03-28 15:34:59,333 Block "" send time: 0.000039
2023-03-28 15:34:59,334 Connecting. Database: default. User: default
2023-03-28 15:34:59,334 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,337 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,338 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'metrics', 'outcomes', 'sessions', 'replays', 'generic_metrics')
2023-03-28 15:34:59,338 Block "" send time: 0.000039
2023-03-28 15:34:59,340 Connecting. Database: default. User: default
2023-03-28 15:34:59,340 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,408 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,408 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'metrics', 'outcomes', 'sessions', 'replays', 'generic_metrics')
2023-03-28 15:34:59,408 Block "" send time: 0.000033
2023-03-28 15:34:59,412 Connecting. Database: default. User: default
2023-03-28 15:34:59,412 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,417 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,418 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'metrics', 'outcomes', 'sessions', 'replays', 'generic_metrics')
2023-03-28 15:34:59,418 Block "" send time: 0.000048
2023-03-28 15:34:59,420 Connecting. Database: default. User: default
2023-03-28 15:34:59,420 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,427 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,428 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'metrics', 'outcomes', 'sessions', 'replays', 'generic_metrics')
2023-03-28 15:34:59,428 Block "" send time: 0.000060
2023-03-28 15:34:59,430 Connecting. Database: default. User: default
2023-03-28 15:34:59,430 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,437 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,438 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'metrics', 'outcomes', 'sessions', 'replays', 'generic_metrics')
2023-03-28 15:34:59,438 Block "" send time: 0.000037
2023-03-28 15:34:59,449 Connecting. Database: default. User: default
2023-03-28 15:34:59,449 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,479 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,479 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'metrics', 'outcomes', 'sessions', 'replays', 'generic_metrics')
2023-03-28 15:34:59,480 Block "" send time: 0.000034
2023-03-28 15:34:59,490 Connecting. Database: default. User: default
2023-03-28 15:34:59,491 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,499 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,499 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'metrics', 'outcomes', 'sessions', 'replays', 'generic_metrics')
2023-03-28 15:34:59,500 Block "" send time: 0.000051
2023-03-28 15:34:59,502 Connecting. Database: default. User: default
2023-03-28 15:34:59,502 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,509 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,509 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'metrics', 'outcomes', 'sessions', 'replays', 'generic_metrics')
2023-03-28 15:34:59,509 Block "" send time: 0.000037
2023-03-28 15:34:59,513 Running migration: 0001_migrations
2023-03-28 15:34:59,514 Connecting. Database: default. User: default
2023-03-28 15:34:59,514 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,521 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,522 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='sentry-clickhouse'
2023-03-28 15:34:59,522 Block "" send time: 0.000041
2023-03-28 15:34:59,525 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='sentry-clickhouse'
2023-03-28 15:34:59,525 Block "" send time: 0.000041
2023-03-28 15:34:59,527 Finished: 0001_migrations
2023-03-28 15:34:59,528 Connecting. Database: default. User: default
2023-03-28 15:34:59,528 Connecting to sentry-clickhouse:9000
2023-03-28 15:34:59,539 Connected to ClickHouse server version 23.2.4, revision: 54461
2023-03-28 15:34:59,541 Query: SELECT version FROM migrations_dist FINAL WHERE group = 'system' AND migration_id = '0001_migrations';
2023-03-28 15:34:59,541 Block "" send time: 0.000040
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 192, in execute
    result_data = query_execute()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 304, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 491, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 151, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 167, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 184, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 60.
DB::Exception: Table default.migrations_dist doesn't exist. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c86b5 in /opt/bitnami/clickhouse/bin/clickhouse
1. ? @ 0x893f7c4 in /opt/bitnami/clickhouse/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x12c6029a in /opt/bitnami/clickhouse/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x12c66f6a in /opt/bitnami/clickhouse/bin/clickhouse
4. DB::JoinedTables::getLeftTableStorage() @ 0x1369f314 in /opt/bitnami/clickhouse/bin/clickhouse
5. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x135c7eb2 in /opt/bitnami/clickhouse/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x1365bd02 in /opt/bitnami/clickhouse/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x13659caa in /opt/bitnami/clickhouse/bin/clickhouse
8. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x13582f50 in /opt/bitnami/clickhouse/bin/clickhouse
9. ? @ 0x1397f260 in /opt/bitnami/clickhouse/bin/clickhouse
10. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1397c9ad in /opt/bitnami/clickhouse/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x14703d39 in /opt/bitnami/clickhouse/bin/clickhouse
12. DB::TCPHandler::run() @ 0x14719259 in /opt/bitnami/clickhouse/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x1761d1b4 in /opt/bitnami/clickhouse/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x1761e3db in /opt/bitnami/clickhouse/bin/clickhouse
15. Poco::PooledThread::run() @ 0x177a5767 in /opt/bitnami/clickhouse/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x177a319d in /opt/bitnami/clickhouse/bin/clickhouse
17. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
18. __clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 70, in migrate
    runner.run_all(force=force, group=group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 169, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 229, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 149, in forwards
    update_status(Status.COMPLETED)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 334, in _update_migration_status
    next_version = self._get_next_version(migration_key)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 349, in _get_next_version
    result = self.__connection.execute(
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 268, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Table default.migrations_dist doesn't exist. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c86b5 in /opt/bitnami/clickhouse/bin/clickhouse
1. ? @ 0x893f7c4 in /opt/bitnami/clickhouse/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x12c6029a in /opt/bitnami/clickhouse/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x12c66f6a in /opt/bitnami/clickhouse/bin/clickhouse
4. DB::JoinedTables::getLeftTableStorage() @ 0x1369f314 in /opt/bitnami/clickhouse/bin/clickhouse
5. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x135c7eb2 in /opt/bitnami/clickhouse/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x1365bd02 in /opt/bitnami/clickhouse/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x13659caa in /opt/bitnami/clickhouse/bin/clickhouse
8. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x13582f50 in /opt/bitnami/clickhouse/bin/clickhouse
9. ? @ 0x1397f260 in /opt/bitnami/clickhouse/bin/clickhouse
10. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1397c9ad in /opt/bitnami/clickhouse/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x14703d39 in /opt/bitnami/clickhouse/bin/clickhouse
12. DB::TCPHandler::run() @ 0x14719259 in /opt/bitnami/clickhouse/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x1761d1b4 in /opt/bitnami/clickhouse/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x1761e3db in /opt/bitnami/clickhouse/bin/clickhouse
15. Poco::PooledThread::run() @ 0x177a5767 in /opt/bitnami/clickhouse/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x177a319d in /opt/bitnami/clickhouse/bin/clickhouse
17. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
18. __clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so
```
The db init runs successfully
```
2023-03-28 15:34:19,211 Using Kafka with ()
2023-03-28 15:34:19,211 Attempting to connect to Kafka (attempt 0)...
2023-03-28 15:34:19,345 Connected to Kafka on attempt 0
2023-03-28 15:34:19,345 Adding topic events to creation list
2023-03-28 15:34:19,346 Adding topic event-replacements to creation list
2023-03-28 15:34:19,346 Adding topic snuba-commit-log to creation list
2023-03-28 15:34:19,346 Adding topic cdc to creation list
2023-03-28 15:34:19,346 Adding topic transactions to creation list
2023-03-28 15:34:19,346 Adding topic snuba-transactions-commit-log to creation list
2023-03-28 15:34:19,346 Adding topic snuba-metrics to creation list
2023-03-28 15:34:19,346 Adding topic outcomes to creation list
2023-03-28 15:34:19,346 Adding topic ingest-sessions to creation list
2023-03-28 15:34:19,346 Adding topic snuba-metrics-commit-log to creation list
2023-03-28 15:34:19,346 Adding topic scheduled-subscriptions-events to creation list
2023-03-28 15:34:19,346 Adding topic scheduled-subscriptions-transactions to creation list
2023-03-28 15:34:19,346 Adding topic scheduled-subscriptions-metrics to creation list
2023-03-28 15:34:19,346 Adding topic scheduled-subscriptions-generic-metrics-sets to creation list
2023-03-28 15:34:19,346 Adding topic scheduled-subscriptions-generic-metrics-distributions to creation list
2023-03-28 15:34:19,346 Adding topic events-subscription-results to creation list
2023-03-28 15:34:19,346 Adding topic transactions-subscription-results to creation list
2023-03-28 15:34:19,346 Adding topic metrics-subscription-results to creation list
2023-03-28 15:34:19,346 Adding topic generic-metrics-sets-subscription-results to creation list
2023-03-28 15:34:19,346 Adding topic generic-metrics-distributions-subscription-results to creation list
2023-03-28 15:34:19,346 Adding topic snuba-queries to creation list
2023-03-28 15:34:19,346 Adding topic processed-profiles to creation list
2023-03-28 15:34:19,346 Adding topic profiles-call-tree to creation list
2023-03-28 15:34:19,346 Adding topic ingest-replay-events to creation list
2023-03-28 15:34:19,346 Adding topic snuba-generic-metrics to creation list
2023-03-28 15:34:19,346 Adding topic snuba-generic-metrics-sets-commit-log to creation list
2023-03-28 15:34:19,346 Adding topic snuba-generic-metrics-distributions-commit-log to creation list
2023-03-28 15:34:19,346 Adding topic snuba-dead-letter-inserts to creation list
2023-03-28 15:34:19,346 Adding topic snuba-attribution to creation list
2023-03-28 15:34:19,346 Adding topic snuba-dead-letter-metrics to creation list
2023-03-28 15:34:19,346 Adding topic snuba-dead-letter-sessions to creation list
2023-03-28 15:34:19,347 Adding topic snuba-dead-letter-generic-metrics to creation list
2023-03-28 15:34:19,347 Adding topic snuba-dead-letter-replays to creation list
2023-03-28 15:34:19,347 Creating Kafka topics..
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by ggolin** [comment]
This is still an issue w/the latest chart and images.
