### ISSUE TITLE
KafkaOffset / not leader for partition errors after upgrading from 15.x to 17.x chart

### ISSUE THREAD

**Issue by audunsolemdal** [sentry-kubernetes/charts#866]
Pods such as

sentry-ingest-metrics-consumer-perf
sentry-ingest-metrics-consumer-rb
sentry-ingest-metrics-consumer-transactions

are in a CrashLoopBackOff with the below output

while `sentry-snuba-transactions-consumer` was stuck for a while, but seems to have recovered (it has 110 restarts while the other components have 157 currently)

Would appreciate any advice on how to resolve this issue as my knowledge of Kafka is 

```
2023-04-23 07:39:40,573 Initializing Snuba CLI...
2023-04-23 07:39:40,575 Initializing Snuba
2023-04-23 07:39:43,411 Snuba initialization took 2.8380904130171984s
2023-04-23 07:39:43,439 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 211, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 126, in poll
    message = self.__consumer.poll(timeout)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 428, in poll
    message: Optional[ConfluentMessage] = self.__consumer.poll(
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 317, in assignment_callback
    self.__resolve_partition_starting_offset(partition)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 230, in __resolve_partition_offset_earliest
    low, high = self.__consumer.get_watermark_offsets(partition)
cimpl.KafkaException: KafkaError{code=NOT_LEADER_FOR_PARTITION,val=6,str="Failed to get watermark offsets: Broker: Not leader for partition"}
2023-04-23 07:39:43,441 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7ff3ea1ce4f0>...
2023-04-23 07:39:43,441 Partitions revoked: [Partition(topic=Topic(name='snuba-transactions-commit-log'), index=0)]
2023-04-23 07:39:43,442 failed to delete offset for unknown partition: Partition(topic=Topic(name='snuba-transactions-commit-log'), index=0)
2023-04-23 07:39:43,445 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 211, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 126, in poll
    message = self.__consumer.poll(timeout)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 428, in poll
    message: Optional[ConfluentMessage] = self.__consumer.poll(
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 317, in assignment_callback
    self.__resolve_partition_starting_offset(partition)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 230, in __resolve_partition_offset_earliest
    low, high = self.__consumer.get_watermark_offsets(partition)
cimpl.KafkaException: KafkaError{code=NOT_LEADER_FOR_PARTITION,val=6,str="Failed to get watermark offsets: Broker: Not leader for partition"}
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by audunsolemdal** [comment]
Still relevant

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
