### ISSUE TITLE
Snuba pods are in `Error` and `CrashLoopBackOff` state when `Clickhouse` pod restarted

### ISSUE THREAD

**Issue by kseniyashaydurova** [sentry-kubernetes/charts#867]
### Problem
Currently there is situation that when any of `sentry-clickhouse` pods is restarted, there appears  crashed snuba related pods

![image](https://user-images.githubusercontent.com/26448672/234196312-a2b78afb-e8bb-45ba-a657-b9a759e252cd.png)

**Can you please explain is it possible to avoid somehow such a behavior?**

### Expected

No pods would fail if any of `Clickhouse` replicas is restarted, because clickhouse is configured as replicaset (as I understand), so snuba should take any other available pod if one becomes not available. But now snuba restarts if any of `clickhouse` pods restarted that doesn't look sensible for HA approach.

### Logs
```
✗  klo sentry-snuba-transactions-consumer-b4d77f6b7-n7sbc --previous
2023-04-25 06:42:37,541 Initializing Snuba CLI...
2023-04-25 06:42:37,544 Initializing Snuba
2023-04-25 06:42:38,939 Snuba initialization took 1.396822193171829s
2023-04-25 06:42:38,943 Consumer Starting
2023-04-25 06:42:38,944 librdkafka log level: 6
2023-04-25 06:42:38,955 New partitions assigned: {Partition(topic=Topic(name='transactions'), index=0): 27728}
2023-04-25 06:42:42,785 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 220, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 288, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 104, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Host not found: sentry-clickhouse-0.sentry-clickhouse-headless.sentry.svc.cluster.local (sentry-clickhouse-0.sentry-clickhouse-headless.sentry.svc.cluster.local:9000): Insertion status:
2023-04-25 06:42:42,787 Terminating <snuba.consumers.consumer.ProcessedMessageBatchWriter object at 0x7fc5708ce7c0>...
2023-04-25 06:42:42,787 Closing <snuba.utils.streams.kafka_consumer_with_commit_log.KafkaConsumerWithCommitLog object at 0x7fc570a19e50>...
2023-04-25 06:42:42,787 Partitions revoked: [Partition(topic=Topic(name='transactions'), index=0)]
2023-04-25 06:42:42,791 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 202, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 220, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/transform.py", line 63, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 135, in poll
    self.close_and_reset_batch()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 201, in close_and_reset_batch
    self.future.result(timeout=self.wait_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 213, in __finish_batch
    batch.close()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/collect.py", line 66, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 288, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 104, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 274, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 222, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Host not found: sentry-clickhouse-0.sentry-clickhouse-headless.sentry.svc.cluster.local (sentry-clickhouse-0.sentry-clickhouse-headless.sentry.svc.cluster.local:9000): Insertion status:
```

### values.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sentry
  project: default
  source:
    chart: sentry
    helm:
      values: |

        # should be initially set to `true`, but after install converted to `false`
        # https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L14-L18
        asHook: false
        filestore:
          backend: s3
          s3:
            bucketName: sentry-filestore
            default_acl: private
            region_name: us-west-2

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
            # https://www.servicenow.com/community/grc-forum/slack-integration-ip-restriction-issues/m-p/1329213/page/2
            # currently Slack integration can't work ok with `whitelists`, needs proxy
          hostname: sentry.example.com
          tls:
          - hosts:
            - "sentry.example.com"
            secretName: sentry.example.com-crt
        user:
          create: true
          email: sentry@sentry.example.com
          existingSecret: sentry-secret
        mail:
          backend: smtp
          existingSecret: sentry-secret
          from: sentry@sentry.example.com
          host: smtp.sendgrid.net
          port: 587
          useSsl: false
          useTls: false
          username: apikey
        github:
          appId: 123123
          appName: sentry
          existingSecret: sentry-secret
          existingSecretClientIdKey: github-client-id
          existingSecretClientSecretKey: github-client-secret
        slack:
          existingSecret: sentry-secret

        clickhouse:
          clickhouse:
            metrics:
              enabled: true

        hooks:
          enabled: true
          dbCheck:
            nodeSelector:
              sentry: "true"
          dbInit:
            nodeSelector:
              sentry: "true"
          snubaInit:
            nodeSelector:
              sentry: "true"

        kafka:
          enabled: true
          nodeSelector:
            sentry: "true"
          metrics:
            kafka:
              enabled: true
              nodeSelector:
                sentry: "true"

          zookeeper:
            enabled: true
            nodeSelector:
              sentry: "true"
            metrics:
              enabled: true

        memcached:
          autoscaling:
            enabled: false
          nodeSelector:
            sentry: "true"
          metrics:
            enabled: true

        metrics:
          enabled: true
          nodeSelector:
            sentry: "true"

        nginx:
          enabled: false
          autoscaling:
            enabled: false
          nodeSelector:
            sentry: "true"
          metrics:
            enabled: true

        postgresql:
          enabled: true
          existingSecret: sentry-secret
          postgresqlDatabase: sentry
          postgresqlUsername: postgres
          primary:
            nodeSelector:
              sentry: "true"
          readReplicas:
            nodeSelector:
              sentry: "true"
          metrics:
            enabled: true

        rabbitmq:
          enabled: false
          nodeSelector:
              sentry: "true"
          metrics:
            enabled: true

        redis:
          enabled: true
          metrics:
            enabled: true
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 50m
                memory: 100Mi
          master:
            nodeSelector:
              sentry: "true"
          replica:
            autoscaling:
              enabled: false
            nodeSelector:
              sentry: "true"
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 300Mi

        relay:
          autoscaling:
            enabled: false
          nodeSelector:
            sentry: "true"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 100Mi

        sentry:
          autoscaling:
            enabled: false
          billingMetricsConsumer:
            nodeSelector:
              sentry: "true"
          cron:
            nodeSelector:
              sentry: "true"
          ingestConsumer:
            autoscaling:
              enabled: false
            nodeSelector:
              sentry: "true"
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 50m
                memory: 200Mi
          ingestMetricsConsumerPerf:
            autoscaling:
              enabled: false
            nodeSelector:
              sentry: "true"
          ingestMetricsConsumerRh:
            autoscaling:
              enabled: false
            nodeSelector:
              sentry: "true"
          postProcessForwardErrors:
            nodeSelector:
              sentry: "true"
          postProcessForwardTransactions:
            nodeSelector:
              sentry: "true"
          subscriptionConsumerEvents:
            nodeSelector:
              sentry: "true"
          subscriptionConsumerTransactions:
            nodeSelector:
              sentry: "true"
          web:
            autoscaling:
              enabled: false
            nodeSelector:
              sentry: "true"
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 500Mi
          worker:
            autoscaling:
              enabled: false
            nodeSelector:
              sentry: "true"
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 500Mi

        snuba:
          api:
            autoscaling:
              enabled: false
            nodeSelector:
              sentry: "true"
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 500Mi
          consumer:
            nodeSelector:
              sentry: "true"
          outcomesConsumer:
            nodeSelector:
              sentry: "true"
          replacer:
            nodeSelector:
              sentry: "true"
          sessionsConsumer:
            nodeSelector:
              sentry: "true"
          subscriptionConsumerEvents:
            nodeSelector:
              sentry: "true"
          subscriptionConsumerTransactions:
            nodeSelector:
              sentry: "true"
          transactionsConsumer:
            nodeSelector:
              sentry: "true"
        symbolicator:
          enabled: false
          api:
            autoscaling:
              enabled: false
            nodeSelector:
              sentry: "true"

        zookeeper:
          enabled: true
          nodeSelector:
            sentry: "true"
          metrics:
            enabled: true

    repoURL: https://sentry-kubernetes.github.io/charts
    targetRevision: 17.11.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
```

**Comment by adamwirth** [comment]
Bump. This is a really big deal for our team for whether or not we use Sentry.

**Comment by sajoku** [comment]
(I am trying to fix an unrelated error but also saw this).
It appears that the snuba-pods are connected to any one of these clickhouse pods and so restarting one will cut the connection, making the snuba-pod also fail. 

I am by no means an expert but what would you expect to happen in this situation?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by zetaab** [comment]
also during restart ANY of clickhouse pods snuba-api says:

![image](https://github.com/sentry-kubernetes/charts/assets/22482503/5616b0fe-522e-4357-a178-761c7746ba44)

and performance view is unavailable:

![image](https://github.com/sentry-kubernetes/charts/assets/22482503/2464d23f-2a53-4f37-9699-c18c218746e1)


I am just trying to setup highly available sentry and it looks like this clickhouse component is issue currently. All other components can behave if one availability zone is away. However, clickhouse requires all 3 pods to be online 24/7 that performance views will work. Is there something misconfigured or does it really work like this in sentry itself?

**Comment by begemotik** [comment]
Linking the discussion - https://github.com/sentry-kubernetes/charts/discussions/854

**Comment by zetaab** [comment]
longer explanation what is going on with this clickhouse setup https://github.com/sentry-kubernetes/charts/pull/915#issuecomment-1600888450

if someone could solve the clickhouse HA issues, then this issue can be closed as well. Current clickhouse (installed from this repo) is not HA.

**Comment by zetaab** [comment]
@begemotik & others I tested this and got it working in "performance" view in sentry UI. However, still some pods are restarting, but as I see it: that is not huge issue because those are just processing data (there might be some delays when those are doing that).

helm chart https://gist.github.com/zetaab/96599b10f0746661fe93f3049e0e38ef

the important part

```
clickhouse:
  enabled: true
  clickhouse:
    configmap:
      remote_servers:
        internal_replication: false
        replica:
          backup:
            enabled: true
```

you need to define backup replica for clickhouse. Then it can handle the situation that first replica is not available.

Note! it is worth of checking that replica will get the tables and data. That can be done in following way:

connect to normal clickhouse and replica. 

```
kubectl exec -it sentry-clickhouse-replica-0 -- sh
kubectl exec -it sentry-clickhouse-0 -- sh
```

in both pods execute command 
`clickhouse-client -h 127.0.0.1`

and then

`select count(event_id) from transactions_dist`

it should return same results from both

the problem with existing sentry setup is that it does not create tables to replica instances, those are created only when the setup is new it seems.

**Comment by cabrinha** [comment]
Yeah, doesn't make sense that losing a single clickhouse pod causes all these other services to fail.

What needs to be done in order to allow a pod failure on clickhouse?

**Comment by zetaab** [comment]
@cabrinha see my post above, you need to have clickhouse replica installed. The easiest way is to install that when starting the clickhouse cluster. Its working for us now when we use replica

**Comment by kseniyashaydurova** [comment]
Hi @zetaab, do I correctly understand that you made these changes in your Sentry set up https://github.com/sentry-kubernetes/charts/pull/915/files + added `clickhouse.clickhouse.configmap.remote_servers.replica.backup.enabled=true` and that solved the problem with restarting `snuba` pods?

**Comment by zetaab** [comment]
yep, but reminder once again: if you use replicas in EXISTING clickhouse cluster, you need somehow create tables yourself in replica pods (in all of them). If you start from fresh it should work afaik.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
