### ISSUE TITLE
Base install: Cannot use any of provided ZooKeeper nodes

### ISSUE THREAD

**Issue by davidcorbin** [sentry-kubernetes/charts#891]
Getting an error during the post install hook when installing the chart without any customized values. It appears zookeeper `sentry-zookeeper-clickhouse` is not being created.

```
> helm upgrade --install sentry sentry/sentry

Release "sentry" does not exist. Installing it now.
coalesce.go:175: warning: skipped value for kafka.config: Not a table.
Error: failed post-install: 1 error occurred:
        * job failed: DeadlineExceeded
```

```
> helm list

NAME    NAMESPACE       REVISION        UPDATED                                 STATUS  CHART           APP VERSION
sentry  default         1               2023-05-24 10:16:05.531189 -0400 EDT    failed  sentry-19.0.0   23.5.0
```

<details>
<summary><code>kubectl logs job.batch/sentry-snuba-migrate</code></summary>

```
...
2023-05-24 14:17:58,936 Query: CREATE TABLE IF NOT EXISTS migrations_local (group String, migration_id String, timestamp DateTime, status Enum('completed' = 0, 'in_progress' = 1, 'not_started' = 2), version UInt64 DEFAULT 1) ENGINE ReplicatedReplacingMergeTree('/clickhouse/tables/migrations/{shard}/default/migrations_local', '{replica}', version) ORDER BY (group, migration_id);
2023-05-24 14:17:58,937 Block "" send time: 0.000042
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 193, in execute
    result_data = query_execute()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 304, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 491, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 151, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 167, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 184, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 999.
DB::Exception: Cannot use any of provided ZooKeeper nodes (Bad arguments). Stack trace:

0. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0xe99d943 in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0xe99dbc2 in /usr/bin/clickhouse
2. zkutil::ZooKeeper::init(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe9a0685 in /usr/bin/clickhouse
3. zkutil::ZooKeeper::ZooKeeper(Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe9a0da4 in /usr/bin/clickhouse
4. std::__1::__compressed_pair_elem<zkutil::ZooKeeper, 1, false>::__compressed_pair_elem<Poco::Util::AbstractConfiguration const&, char const (&) [10], 0ul, 1ul>(std::__1::piecewise_construct_t, std::__1::tuple<Poco::Util::AbstractConfiguration const&, char const (&) [10]>, std::__1::__tuple_indices<0ul, 1ul>) @ 0xd9e1fbe in /usr/bin/clickhouse
5. DB::Context::getZooKeeper() const @ 0xd9c3ea3 in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, bool) @ 0xe28e746 in /usr/bin/clickhouse
7. std::__1::shared_ptr<DB::StorageReplicatedMergeTree> ext::shared_ptr_helper<DB::StorageReplicatedMergeTree>::create<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool const&, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool const&, bool&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool const&, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >&&, bool const&, bool&) @ 0xe661ff3 in /usr/bin/clickhouse
8. ? @ 0xe65c268 in /usr/bin/clickhouse
9. std::__1::__function::__func<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&), std::__1::allocator<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) @ 0xe405bed in /usr/bin/clickhouse
10. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0xe1bc03a in /usr/bin/clickhouse
11. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0xdacffbe in /usr/bin/clickhouse
12. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0xdaced57 in /usr/bin/clickhouse
13. DB::InterpreterCreateQuery::execute() @ 0xdad21e7 in /usr/bin/clickhouse
14. ? @ 0xe021267 in /usr/bin/clickhouse
15. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xe01fe3d in /usr/bin/clickhouse
16. DB::TCPHandler::runImpl() @ 0xe6fa8f6 in /usr/bin/clickhouse
17. DB::TCPHandler::run() @ 0xe706df7 in /usr/bin/clickhouse
18. Poco::Net::TCPServerConnection::start() @ 0x10eb1e6f in /usr/bin/clickhouse
19. Poco::Net::TCPServerDispatcher::run() @ 0x10eb3881 in /usr/bin/clickhouse
20. Poco::PooledThread::run() @ 0x10fe0e59 in /usr/bin/clickhouse
21. Poco::ThreadImpl::runnableEntry(void*) @ 0x10fdcdea in /usr/bin/clickhouse
22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
23. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 96, in migrate
    runner.run_all(
  File "/usr/src/snuba/snuba/migrations/runner.py", line 220, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 284, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 141, in forwards
    op.execute()
  File "/usr/src/snuba/snuba/migrations/operations.py", line 58, in execute
    connection.execute(self.format_sql(), settings=self._settings)
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 269, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Cannot use any of provided ZooKeeper nodes (Bad arguments). Stack trace:

0. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0xe99d943 in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0xe99dbc2 in /usr/bin/clickhouse
2. zkutil::ZooKeeper::init(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe9a0685 in /usr/bin/clickhouse
3. zkutil::ZooKeeper::ZooKeeper(Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe9a0da4 in /usr/bin/clickhouse
4. std::__1::__compressed_pair_elem<zkutil::ZooKeeper, 1, false>::__compressed_pair_elem<Poco::Util::AbstractConfiguration const&, char const (&) [10], 0ul, 1ul>(std::__1::piecewise_construct_t, std::__1::tuple<Poco::Util::AbstractConfiguration const&, char const (&) [10]>, std::__1::__tuple_indices<0ul, 1ul>) @ 0xd9e1fbe in /usr/bin/clickhouse
5. DB::Context::getZooKeeper() const @ 0xd9c3ea3 in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, bool) @ 0xe28e746 in /usr/bin/clickhouse
7. std::__1::shared_ptr<DB::StorageReplicatedMergeTree> ext::shared_ptr_helper<DB::StorageReplicatedMergeTree>::create<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool const&, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool const&, bool&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool const&, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >&&, bool const&, bool&) @ 0xe661ff3 in /usr/bin/clickhouse
8. ? @ 0xe65c268 in /usr/bin/clickhouse
9. std::__1::__function::__func<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&), std::__1::allocator<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) @ 0xe405bed in /usr/bin/clickhouse
10. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0xe1bc03a in /usr/bin/clickhouse
11. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0xdacffbe in /usr/bin/clickhouse
12. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0xdaced57 in /usr/bin/clickhouse
13. DB::InterpreterCreateQuery::execute() @ 0xdad21e7 in /usr/bin/clickhouse
14. ? @ 0xe021267 in /usr/bin/clickhouse
15. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xe01fe3d in /usr/bin/clickhouse
16. DB::TCPHandler::runImpl() @ 0xe6fa8f6 in /usr/bin/clickhouse
17. DB::TCPHandler::run() @ 0xe706df7 in /usr/bin/clickhouse
18. Poco::Net::TCPServerConnection::start() @ 0x10eb1e6f in /usr/bin/clickhouse
19. Poco::Net::TCPServerDispatcher::run() @ 0x10eb3881 in /usr/bin/clickhouse
20. Poco::PooledThread::run() @ 0x10fe0e59 in /usr/bin/clickhouse
21. Poco::ThreadImpl::runnableEntry(void*) @ 0x10fdcdea in /usr/bin/clickhouse
22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
23. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

```
</details>

<details>
<summary><code>kubectl get all</code></summary>

```
NAME                                    READY   STATUS      RESTARTS        AGE
pod/sentry-clickhouse-0                 1/1     Running     0               5h23m
pod/sentry-clickhouse-1                 1/1     Running     0               5h23m
pod/sentry-clickhouse-2                 1/1     Running     0               5h23m
pod/sentry-cron-979c979f8-2rp6s         1/1     Running     2 (5h23m ago)   5h23m
pod/sentry-db-check-v8x2g               0/1     Completed   0               5h23m
pod/sentry-kafka-0                      1/1     Running     0               5h23m
pod/sentry-kafka-1                      1/1     Running     0               5h23m
pod/sentry-kafka-2                      1/1     Running     0               5h23m
pod/sentry-nginx-ff8649858-ztssl        1/1     Running     0               5h23m
pod/sentry-rabbitmq-0                   1/1     Running     0               5h23m
pod/sentry-rabbitmq-1                   1/1     Running     0               5h22m
pod/sentry-rabbitmq-2                   1/1     Running     0               5h22m
pod/sentry-sentry-postgresql-0          1/1     Running     0               5h23m
pod/sentry-sentry-redis-master-0        1/1     Running     0               5h23m
pod/sentry-sentry-redis-replicas-0      1/1     Running     0               5h23m
pod/sentry-sentry-redis-replicas-1      1/1     Running     0               5h23m
pod/sentry-sentry-redis-replicas-2      1/1     Running     0               5h22m
pod/sentry-snuba-api-7965bdc546-z2vjf   1/1     Running     0               5h23m
pod/sentry-snuba-db-init-nj9mw          0/1     Completed   0               5h22m
pod/sentry-snuba-migrate-7k75k          0/1     Error       0               5h21m
pod/sentry-snuba-migrate-8g576          0/1     Error       0               5h21m
pod/sentry-snuba-migrate-c68bt          0/1     Error       0               5h22m
pod/sentry-snuba-migrate-txccn          0/1     Error       0               5h22m
pod/sentry-web-ffddc44f9-jw7zx          1/1     Running     2 (5h23m ago)   5h23m
pod/sentry-worker-6778ddd79b-fd6jw      1/1     Running     2 (5h23m ago)   5h23m
pod/sentry-worker-6778ddd79b-qqplb      1/1     Running     2 (5h23m ago)   5h23m
pod/sentry-worker-6778ddd79b-xh9rm      1/1     Running     2 (5h23m ago)   5h23m

NAME                                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                 AGE
service/kubernetes                     ClusterIP   10.43.0.1       <none>        443/TCP                                 5h32m
service/sentry-clickhouse              ClusterIP   10.43.154.196   <none>        9000/TCP,8123/TCP,9009/TCP              5h23m
service/sentry-clickhouse-headless     ClusterIP   None            <none>        9000/TCP,8123/TCP,9009/TCP              5h23m
service/sentry-kafka                   ClusterIP   10.43.119.156   <none>        9092/TCP                                5h23m
service/sentry-kafka-headless          ClusterIP   None            <none>        9092/TCP,9094/TCP,9093/TCP              5h23m
service/sentry-nginx                   ClusterIP   10.43.25.66     <none>        80/TCP                                  5h23m
service/sentry-rabbitmq                ClusterIP   10.43.196.0     <none>        5672/TCP,4369/TCP,25672/TCP,15672/TCP   5h23m
service/sentry-rabbitmq-headless       ClusterIP   None            <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   5h23m
service/sentry-relay                   ClusterIP   10.43.41.11     <none>        3000/TCP                                5h23m
service/sentry-sentry-postgresql       ClusterIP   10.43.7.53      <none>        5432/TCP                                5h23m
service/sentry-sentry-postgresql-hl    ClusterIP   None            <none>        5432/TCP                                5h23m
service/sentry-sentry-redis-headless   ClusterIP   None            <none>        6379/TCP                                5h23m
service/sentry-sentry-redis-master     ClusterIP   10.43.175.29    <none>        6379/TCP                                5h23m
service/sentry-sentry-redis-replicas   ClusterIP   10.43.33.133    <none>        6379/TCP                                5h23m
service/sentry-snuba                   ClusterIP   10.43.121.199   <none>        1218/TCP                                5h23m
service/sentry-web                     ClusterIP   10.43.15.4      <none>        9000/TCP                                5h23m

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sentry-cron        1/1     1            1           5h23m
deployment.apps/sentry-nginx       1/1     1            1           5h23m
deployment.apps/sentry-snuba-api   1/1     1            1           5h23m
deployment.apps/sentry-web         1/1     1            1           5h23m
deployment.apps/sentry-worker      3/3     3            3           5h23m

NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/sentry-cron-979c979f8         1         1         1       5h23m
replicaset.apps/sentry-nginx-ff8649858        1         1         1       5h23m
replicaset.apps/sentry-snuba-api-7965bdc546   1         1         1       5h23m
replicaset.apps/sentry-web-ffddc44f9          1         1         1       5h23m
replicaset.apps/sentry-worker-6778ddd79b      3         3         3       5h23m

NAME                                            READY   AGE
statefulset.apps/sentry-clickhouse              3/3     5h23m
statefulset.apps/sentry-kafka                   3/3     5h23m
statefulset.apps/sentry-rabbitmq                3/3     5h23m
statefulset.apps/sentry-sentry-postgresql       1/1     5h23m
statefulset.apps/sentry-sentry-redis-master     1/1     5h23m
statefulset.apps/sentry-sentry-redis-replicas   3/3     5h23m

NAME                                  SCHEDULE    SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/sentry-sentry-cleanup   0 0 * * *   False     0        <none>          5h23m

NAME                             COMPLETIONS   DURATION   AGE
job.batch/sentry-db-check        1/1           86s        5h23m
job.batch/sentry-snuba-db-init   1/1           9s         5h22m
job.batch/sentry-snuba-migrate   0/1           5h22m      5h22m
```
</details>

**Comment by pavels** [comment]
Something somewhere changed

I have the same problem now - after upgrade the zookeeper for clickhouse statefullset is gone - and clickhouse went read only

**Comment by pavels** [comment]
Ok - so the problem is apparently version 19.0.0 of this chart - it is very broken
19.1.0 is fixed

**Comment by davidcorbin** [comment]
Confirmed fixed.
