### ISSUE TITLE
snuba-subscription-consumer-events pod CrashLoopBackOff

### ISSUE THREAD

**Issue by aosavitski** [sentry-kubernetes/charts#893]
Hello.
We are using k8s version of sentry (v 22.10.0) a couple of months. And just noticed that one of the pods is constantly in a CrashLoopBackOff state and restarted already ~7K times. It is snuba-subscription-consumer-events pod. Here is pod log:
```
2023-05-23 11:00:18,562 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 395403}
2023-05-23 11:00:18,574 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 188, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 2
2023-05-23 11:00:18,575 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f5fdf826af0>...
2023-05-23 11:00:18,577 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0)]
2023-05-23 11:00:18,578 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 188, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 2
```
What could be the reason? What is this consumer used for? Visually in the GUI everything continues to work. Perhaps the consumer is used in features that we do not use?

P.S. we also noticed that all consumer pods are using --auto-offset-reset=earliest param, while in self-hosted version of sentry that I have locally this parameter is latest. And If I edit snuba-subscription-consumer-events manifest and change auto-offset-reset param to latest then pod starting without this error.

**Comment by brianchan661** [comment]
Hi @aosavitski 
try add this to your values.yaml

```
snubaSettingsPy: |
      TOPIC_PARTITION_COUNTS = {
        "snuba-commit-log": 20
      }
```

I am not sure what is this component used for, but just found solution in another ISSUE.  
The error is because the component doesn't know how many partition the "snuba-commit-log" have, and was deafulted to zero. So when it tries to get the partition > 0, it got key error.(please correct me if i am wrong)  
And only this topic (which is recently new added topic) have the issue.

**Comment by aosavitski** [comment]
We have 1 partition in snuba-commit-log topic

**Comment by brianchan661** [comment]
try set to 1 then?

**Comment by hyunkj42** [comment]
@brianchan661 
Hello.
I am also experiencing the same phenomenon. T.T
![image](https://github.com/sentry-kubernetes/charts/assets/22021000/69c1ff63-0cea-48d5-ab1a-fe0845d1e35f)

```
  snubaSettingsPy: |
        TOPIC_PARTITION_COUNTS = {
          "snuba-transactions-commit-log": 3,
          "snuba-commit-log": 3,
          "snuba-sessions-commit-log": 3
        }
```
I added and installed like this, but the status is the same.

Do you have any solution?

**Comment by brianchan661** [comment]
That is how I fixed mine=[
I still believe this is because of the partition count.
can you check the partition on the topic from Kafka, and also check the error message (I believe the key Error ranging from 0 to 2)?

**Comment by hyunkj42** [comment]
@brianchan661 
Thank you for your reply.

Error log, topic information, and snuba setting information.

* error logs
```
k logs -f sentry-test-snuba-subscription-consumer-sessions-6649bfb5bctgh4
2023-06-30 10:32:20,550 Initializing Snuba...
2023-06-30 10:32:23,155 Snuba initialization took 2.606515166349709s
2023-06-30 10:32:23,263 New partitions assigned: {Partition(topic=Topic(name='snuba-sessions-commit-log'), index=0): 705, Partition(topic=Topic(name='snuba-sessions-commit-log'), index=1): 0, Partition(topic=Topic(name='snuba-sessions-commit-log'), index=2): 1359}
2023-06-30 10:35:10,863 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 181, in run
    self._run_once()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 231, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1
2023-06-30 10:35:10,864 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f3eece1ebb0>...
2023-06-30 10:35:10,865 Partitions revoked: [Partition(topic=Topic(name='snuba-sessions-commit-log'), index=0), Partition(topic=Topic(name='snuba-sessions-commit-log'), index=1), Partition(topic=Topic(name='snuba-sessions-commit-log'), index=2)]
2023-06-30 10:35:10,869 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 11, in <module>
    load_entry_point('snuba', 'console_scripts', 'snuba')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 141, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 181, in run
    self._run_once()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 231, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1
```

* kafka topics
![image](https://github.com/sentry-kubernetes/charts/assets/22021000/f923eb20-1a2a-4642-b94a-2925e6389eb7)

* snuba config
```

TOPIC_PARTITION_COUNTS = {
  "snuba-transactions-commit-log": 3,
  "snuba-commit-log": 3,
  "snuba-sessions-commit-log": 3
}
```

* snuba version : 23.3.1

**Comment by brianchan661** [comment]
its looks correct. it your config in the correct indentation? Do your sentry chart version support the snubaSettingsPy?

Below is my config just for your ref (i guess the missing "," is fine)
  ```
config:
    snubaSettingsPy: |
      TOPIC_PARTITION_COUNTS = {
        "event-replacements": 1,
        "events": 20,
        "ingest-attachments": 20,
        "ingest-events": 20,
        "ingest-sessions": 20,
        "ingest-transactions": 20,
        "outcomes": 20,
        "snuba-commit-log": 20,
      }
```

I forgot where the config will be set in the snuba pod (maybe [setting.py](https://sourcegraph.com/github.com/sentry-kubernetes/charts/-/blob/sentry/templates/configmap-snuba.yaml?L79:19)?) May you try to check is your config being set correctly to the pod?  

JFYI : found the same issue on [stackoverflow](https://stackoverflow.com/questions/73294110/keyerror-1-sentry-snuba-subscription-consumer-events)

**Comment by hyunkj42** [comment]
@brianchan661 
![image](https://github.com/sentry-kubernetes/charts/assets/22021000/aa97431f-6340-422e-9751-0e937766f84c)
Indentation seems to be correct.

This is the only error that occurs.
![image](https://github.com/sentry-kubernetes/charts/assets/22021000/c14eb297-8328-4e8b-b869-10f2a5c3a232)

**Comment by brianchan661** [comment]
@hyunkj42 
If the other 2 is working.... Why not try  to add the comma behind your `"snuba-sessions-commit-log" : 3`
if that doesn't work ,i am ran out of idea =[

**Comment by hyunkj42** [comment]
@brianchan661 
Even if you add a comma, the state is the same.
The other two are working normally, not by adding the number of topics setting.
I guess it's because I changed autoOffsetReset: "earliest" -> "latest".
![image](https://github.com/sentry-kubernetes/charts/assets/22021000/8be7ddb0-d6a6-4ba8-9b60-c13a7cc7917a)
When executed as "earliest", errors occur in events and transactions.
 T_T

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
