### ISSUE TITLE
Question about upgrading Postgresql to 15.x.x

### ISSUE THREAD

**Issue by christiangonre** [sentry-kubernetes/charts#898]
First of all, thanks for the fantastic work doing this helm chart!

Trying to upgrade the Helm chart of Sentry to the 19.1.0 version I saw that this version requires upgrading the Postgresql database to 15.x.x as we can see on this [PR](https://github.com/sentry-kubernetes/charts/pull/882)

I want to know if someone did this and if it can explain how to do this upgrade inside Kubernetes, I think this would be helpful for the community.

Looking at the Postgresql official docs they talk about this [guide](https://www.postgresql.org/docs/current/upgrading.html#UPGRADING-VIA-PG-UPGRADE), but it requires deploying an external Postgresql. This means that the only solution to upgrade to version 19.x.x of Sentry is using an external Postgresql?

Thanks in advance for your help.

**Comment by zffocussss** [comment]
I tried to upgrade from 17.9.0 to 19.2.0 recently, but it failed.
may you keep the pgsql same version,and just upgrade the others charts?I do not know if it can work this way.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by christiangonre** [comment]
For all the people that is trying to upgrade this version, I did the following and it works fine:
1. Take a full backup of the Sentry Postgres database.
2. Scale to zero the web, worker and relay pods.
3. Delete the Postgresql statefulset and the pvc attached.
4. Upgrade the helm chart to 19.1.0 without starting the pods web, worker and relay.
5. Restore the dump into the new Postgresql.

Following these steps, everything should work fine.
Be careful if you set a Postgresql password in your values.yaml file, the new Postgresql version of the Helm chart introduced some changes.

If you want to do this upgrade easier in the future, I recommend using an externalPostgres instead of the default of the helm chart to make easier this upgrades.

**Comment by sourcegiegie** [comment]
> For all the people that is trying to upgrade this version, I did the following and it works fine:
> 
> 1. Take a full backup of the Sentry Postgres database.
> 2. Scale to zero the web, worker and relay pods.
> 3. Delete the Postgresql statefulset and the pvc attached.
> 4. Upgrade the helm chart to 19.1.0 without starting the pods web, worker and relay.
> 5. Restore the dump into the new Postgresql.
> 
> Following these steps, everything should work fine. Be careful if you set a Postgresql password in your values.yaml file, the new Postgresql version of the Helm chart introduced some changes.
> 
> If you want to do this upgrade easier in the future, I recommend using an externalPostgres instead of the default of the helm chart to make easier this upgrades.



How did you backup and migrate pgsql? I migrated data from pgsql11.0->pgsql15.0 using ‘pg_restore -W -c -U xx -d xx -v xx ’, service error 502 appears, indicating some errors during import

**Comment by adonskoy** [comment]
Postgres version has been updated due to sentry requirements (previously the minimum version was 11, now 14)
You can upgrade Postgres using [this tool](https://github.com/tianon/docker-postgres-upgrade)

**Comment by christiangonre** [comment]
> 

I used this command:
`pg_dump -Fc --username=<user> dbname=<db-name> /tmp/sentry.dump>` and it worked without any problem.
Same for pg_restore, you should use this one:
`pg_restore -Fc --username=<user> dbname=<db-name> /tmp/sentry.dump`

**Comment by christiangonre** [comment]
> > For all the people that is trying to upgrade this version, I did the following and it works fine:
> > 
> > 1. Take a full backup of the Sentry Postgres database.
> > 2. Scale to zero the web, worker and relay pods.
> > 3. Delete the Postgresql statefulset and the pvc attached.
> > 4. Upgrade the helm chart to 19.1.0 without starting the pods web, worker and relay.
> > 5. Restore the dump into the new Postgresql.
> > 
> > Following these steps, everything should work fine. Be careful if you set a Postgresql password in your values.yaml file, the new Postgresql version of the Helm chart introduced some changes.
> > If you want to do this upgrade easier in the future, I recommend using an externalPostgres instead of the default of the helm chart to make easier this upgrades.
> 
> How did you backup and migrate pgsql? I migrated data from pgsql11.0->pgsql15.0 using ‘pg_restore -W -c -U xx -d xx -v xx ’, service error 502 appears, indicating some errors during import

I used this command:
`pg_dump -Fc --username=<user> dbname=<db-name> /tmp/sentry.dump>` and it worked without any problem.
Same for pg_restore, you should use this one:
`pg_restore -Fc --username=<user> dbname=<db-name> /tmp/sentry.dump`

**Comment by sourcegiegie** [comment]
> > > For all the people that is trying to upgrade this version, I did the following and it works fine:
> > > 
> > > 1. Take a full backup of the Sentry Postgres database.
> > > 2. Scale to zero the web, worker and relay pods.
> > > 3. Delete the Postgresql statefulset and the pvc attached.
> > > 4. Upgrade the helm chart to 19.1.0 without starting the pods web, worker and relay.
> > > 5. Restore the dump into the new Postgresql.
> > > 
> > > Following these steps, everything should work fine. Be careful if you set a Postgresql password in your values.yaml file, the new Postgresql version of the Helm chart introduced some changes.
> > > If you want to do this upgrade easier in the future, I recommend using an externalPostgres instead of the default of the helm chart to make easier this upgrades.
> > 
> > 
> > How did you backup and migrate pgsql? I migrated data from pgsql11.0->pgsql15.0 using ‘pg_restore -W -c -U xx -d xx -v xx ’, service error 502 appears, indicating some errors during import
> 
> I used this command: `pg_dump -Fc --username=<user> dbname=<db-name> /tmp/sentry.dump>` and it worked without any problem. Same for pg_restore, you should use this one: `pg_restore -Fc --username=<user> dbname=<db-name> /tmp/sentry.dump`

Thank you for your reply :)
But after completing the migration, I was unable to run normally. After executing the Sentry upgrade -- force, I reported an error:
` Traceback (most recent call last):

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner

     return func(self, sql, *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute

     return self.cursor.execute(sql, clean_bad_params(params))

 psycopg2.errors.DuplicateColumn: column "org_role" of relation "sentry_team" already exists

 

 

 During handling of the above exception, another exception occurred:

 

 Traceback (most recent call last):

   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

     return self.cursor.execute(sql, params)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner

     raise_the_exception(self.db, e)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner

     return func(self, *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner

     return func(self, *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner

     raise exc_info[0](msg).with_traceback(exc_info[2])

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner

     return func(self, sql, *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute

     return self.cursor.execute(sql, clean_bad_params(params))

 psycopg2.errors.DuplicateColumn: DuplicateColumn('column "org_role" of relation "sentry_team" already exists\n')

 SQL: ALTER TABLE "sentry_team" ADD COLUMN "org_role" varchar(32) NULL

 

 The above exception was the direct cause of the following exception:

 

 Traceback (most recent call last):

   File "/usr/local/bin/sentry", line 8, in <module>

     sys.exit(main())

   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main

     func(**kwargs)

   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__

     return self.main(*args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main

     rv = self.invoke(ctx)

   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke

     return _process_result(sub_ctx.command.invoke(sub_ctx))

   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke

     return ctx.invoke(self.callback, **ctx.params)

   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke

     return __callback(*args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func

     return f(get_current_context(), *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner

     return ctx.invoke(f, *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke

     return __callback(*args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func

     return f(get_current_context(), *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 99, in upgrade

     _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)

   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 50, in _upgrade

     dj_call_command(

   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command

     return command.execute(*args, **defaults)

   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute

     output = self.handle(*args, **options)

   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped

     res = handle_func(*args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle

     post_migrate_state = executor.migrate(

   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate

     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)

   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards

     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)

   File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/monkey/executor.py", line 79, in apply_migration

     return super().apply_migration(state, migration, fake=fake, fake_initial=fake_initial)

   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration

     state = migration.apply(state, schema_editor)

   File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/migrations.py", line 22, in apply

     return super().apply(project_state, schema_editor, collect_sql)

   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply

     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)

   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 110, in database_forwards

     schema_editor.add_field(

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/schema.py", line 52, in inner

     func(self, *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 447, in add_field

     self.execute(sql, params)

   File "/usr/local/lib/python3.8/site-packages/django_zero_downtime_migrations/backends/postgres/schema.py", line 302, in execute

     super().execute(statement, params)

   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 137, in execute

     cursor.execute(sql, params)

   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 597, in execute

     return real_execute(self, sql, params)

   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute

     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

     return executor(sql, params, many, context)

   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

     return self.cursor.execute(sql, params)

   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__

     raise dj_exc_value.with_traceback(traceback) from exc_value

   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

     return self.cursor.execute(sql, params)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner

     raise_the_exception(self.db, e)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner

     return func(self, *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner

     return func(self, *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner

     raise exc_info[0](msg).with_traceback(exc_info[2])

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner

     return func(self, sql, *args, **kwargs)

   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute

     return self.cursor.execute(sql, clean_bad_params(params))

 django.db.utils.ProgrammingError: DuplicateColumn('column "org_role" of relation "sentry_team" already exists\n')

 SQL: ALTER TABLE "sentry_team" ADD COLUMN "org_role" varchar(32) NULL

   Applying sentry.0352_add_org_role_to_team_model...`


Perhaps there is a problem with my upgrade method? I am upgrading from 23.1 to 23.6.1, 
and after completing the migration of PGSQL（11.0->15）, do I not need db-init?

**Comment by itodorova1** [comment]
@christiangonre - did you actually restore only the system data?
We are looking into upgrading production environment and need to keep the Sentry issues database as well, however not sure if anyone managed to do this. Maybe clickhouse dump, but this is getting very complex and risky.
