### ISSUE TITLE
kafka issue Fatal error during KafkaServer shutdown

### ISSUE THREAD

**Issue by visla-xugeng** [sentry-kubernetes/charts#907]
Hi All,

I just found an issue about my kafka cluster(3 nodes) in my sentry deployment. My manually upgraded kafka only from 8G volume(EBS) to 20GB after receiving alerts of lack of volume . All other 2 nodes works fine but the third one keep restarting. I got the error in below. 
I also tried to reboot the Zookeeper cluster and not work. 

```
[2023-06-14 04:29:49,730] ERROR [KafkaServer id=2] Fatal error during KafkaServer shutdown. (kafka.server.KafkaServer)
java.lang.IllegalStateException: Kafka server is still starting up, cannot shut down!
	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:696)
	at kafka.Kafka$.$anonfun$main$3(Kafka.scala:100)
	at kafka.utils.Exit$.$anonfun$addShutdownHook$1(Exit.scala:38)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-14 04:29:49,731] ERROR Halting Kafka. (kafka.Kafka$)
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
