### ISSUE TITLE
Sentry relay causes web error: null value in column "first_seen" of relation "sentry_relay" violates not-null constraint

### ISSUE THREAD

**Issue by fzyzcjy** [sentry-kubernetes/charts#922]
Logs

<details>

```
django.db.utils.IntegrityError: NotNullViolation('null value in column "first_seen" of relation "sentry_relay" violates not-null constraint\nDETAIL:  Failing row contains (10, 9c95e47e-ac68-436b-8e76-6bd32cc745f8, 78INhr5o0HDxWhEfiBSEXxMywxaxY8bYivXqRxrCDlY, null, null, t).\n')
SQL: INSERT INTO "sentry_relay" ("relay_id", "public_key", "first_seen", "last_seen", "is_internal") VALUES (%s, %s, %s, %s, %s) RETURNING "sentry_relay"."id"
06:01:18 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.register_response.RelayRegisterResponseEndpoint' response=500 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/register/response/' caller_ip='10.0.0.1' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.03632473945617676 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
06:01:18 [ERROR] django.request: Internal Server Error: /api/0/relays/register/response/ (status_code=500 request=<WSGIRequest: POST '/api/0/relays/register/response/'>)
06:01:35 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.register_challenge.RelayRegisterChallengeEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/register/challenge/' caller_ip='10.0.0.1' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.015294313430786133 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.NotNullViolation: null value in column "first_seen" of relation "sentry_relay" violates not-null constraint
DETAIL:  Failing row contains (11, 9c95e47e-ac68-436b-8e76-6bd32cc745f8, 78INhr5o0HDxWhEfiBSEXxMywxaxY8bYivXqRxrCDlY, null, null, t).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.NotNullViolation: NotNullViolation('null value in column "first_seen" of relation "sentry_relay" violates not-null constraint\nDETAIL:  Failing row contains (11, 9c95e47e-ac68-436b-8e76-6bd32cc745f8, 78INhr5o0HDxWhEfiBSEXxMywxaxY8bYivXqRxrCDlY, null, null, t).\n')
SQL: INSERT INTO "sentry_relay" ("relay_id", "public_key", "first_seen", "last_seen", "is_internal") VALUES (%s, %s, %s, %s, %s) RETURNING "sentry_relay"."id"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 222, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 345, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/relay/register_response.py", line 83, in post
    relay = Relay.objects.create(
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 152, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 152, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 152, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 152, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 910, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 597, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.IntegrityError: NotNullViolation('null value in column "first_seen" of relation "sentry_relay" violates not-null constraint\nDETAIL:  Failing row contains (11, 9c95e47e-ac68-436b-8e76-6bd32cc745f8, 78INhr5o0HDxWhEfiBSEXxMywxaxY8bYivXqRxrCDlY, null, null, t).\n')
SQL: INSERT INTO "sentry_relay" ("relay_id", "public_key", "first_seen", "last_seen", "is_internal") VALUES (%s, %s, %s, %s, %s) RETURNING "sentry_relay"."id"
06:01:35 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.register_response.RelayRegisterResponseEndpoint' response=500 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/register/response/' caller_ip='10.0.0.1' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.03294968605041504 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
06:01:35 [ERROR] django.request: Internal Server Error: /api/0/relays/register/response/ (status_code=500 request=<WSGIRequest: POST '/api/0/relays/register/response/'>)

```

</details>

**Comment by fzyzcjy** [comment]
I see: it seems db migration is not done due to OOM kill.
