### ISSUE TITLE
When accessing the replays page, an Internal Error occurs.

### ISSUE THREAD

**Issue by hyunkj42** [sentry-kubernetes/charts#943]
useed charts : 18.0.0

Hello.
When accessing the replays page, an Internal Error occurs.
![image](https://github.com/sentry-kubernetes/charts/assets/22021000/45646803-2c90-4a3a-87bc-b835cd6947f4)

An error occurs when clicking on these Replays.
![image](https://github.com/sentry-kubernetes/charts/assets/22021000/544269b2-39eb-4e70-bea8-a91a34603237)
![image](https://github.com/sentry-kubernetes/charts/assets/22021000/e3dc4e76-c9d5-472c-9d29-7e991f18ff1e)
![image](https://github.com/sentry-kubernetes/charts/assets/22021000/5b17ef0f-9d3f-4643-8dd9-44f8f933aff6)

Web log generated when replays is clicked
```
02:43:03 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.react_page.ReactPageView' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/organizations/sentry/replays/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.07514429092407227 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:03 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_projects.OrganizationProjectsEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/projects/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.0771331787109375 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:03 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_teams.OrganizationTeamsEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/teams/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.08616828918457031 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:03 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_details.OrganizationDetailsEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.08512735366821289 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:04 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.assistant.AssistantEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/assistant/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.016216278076171875 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:04 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.system_health.SystemHealthEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/internal/health/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.017198801040649414 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:04 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_index.OrganizationIndexEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/organizations/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.02904200553894043 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:04 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.client_state.ClientStateListEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/client-state/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.043738365173339844 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:04 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.broadcast_index.BroadcastIndexEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/broadcasts/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.042017221450805664 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:04 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_tags.OrganizationTagsEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/tags/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.10915255546569824 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sentry/api/base.py", line 188, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/sentry/api/base.py", line 305, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sentry/replays/endpoints/organization_replay_index.py", line 67, in get
    return self.paginate(
  File "/usr/local/lib/python3.8/dist-packages/sentry/api/base.py", line 390, in paginate
    cursor_result = paginator.get_result(
  File "/usr/local/lib/python3.8/dist-packages/sentry/api/paginator.py", line 483, in get_result
    data = self.data_fn(offset=offset, limit=limit + 1)
  File "/usr/local/lib/python3.8/dist-packages/sentry/replays/endpoints/organization_replay_index.py", line 54, in data_fn
    return query_replays_collection(
  File "/usr/local/lib/python3.8/dist-packages/sentry/replays/query.py", line 70, in query_replays_collection
    response = query_replays_dataset(
  File "/usr/local/lib/python3.8/dist-packages/sentry/replays/query.py", line 169, in query_replays_dataset
    return raw_snql_query(snuba_request, "replays.query.query_replays_dataset")
  File "/usr/local/lib/python3.8/dist-packages/sentry/utils/snuba.py", line 762, in raw_snql_query
    return _apply_cache_and_build_results([params], referrer=referrer, use_cache=use_cache)[0]
  File "/usr/local/lib/python3.8/dist-packages/sentry/utils/snuba.py", line 838, in _apply_cache_and_build_results
    query_results = _bulk_snuba_query([item[1] for item in to_query], headers)
  File "/usr/local/lib/python3.8/dist-packages/sentry/utils/snuba.py", line 921, in _bulk_snuba_query
    raise clickhouse_error_codes_map.get(error["code"], QueryExecutionError)(
sentry.utils.snuba.QueryIllegalTypeOfArgument: DB::Exception: Function tuple can't have lambda-expressions as arguments: While processing project_id AS _snuba_project_id, replay_id AS _snuba_replay_id, dateDiff('second', min(replay_start_timestamp AS _snuba_replay_start_timestamp) AS _snuba_started_at, max(timestamp AS _snuba_timestamp) AS _snuba_finished_at) AS _snuba_duration, sum(length(urls AS _snuba_urls)) AS _snuba_count_urls, IPv4NumToString(groupArray(1)(ip_address_v4 AS _snuba_ip_address_v4)[1]) AS _snuba_user_ip, _snuba_finished_at, groupArray(1)(os_version)[1] AS _snuba_os_version, groupArray(1)(browser_version)[1] AS _snuba_browser_version, groupArray(1)(user_name)[1] AS _snuba_user_name, sum(length(error_ids AS _snuba_error_ids)) AS _snuba_count_errors, notEmpty(groupArray(is_archived AS _snuba_is_archived)) AS _snuba_isArchived, groupArray((segment_id AS _snuba_segment_id, _snuba_urls)) AS _snuba_agg_urls, _snuba_started_at, groupArray(1)(os_name)[1] AS _snuba_os_name, _snuba_replay_id, arrayFlatten(arraySort(tuple((urls, sequence_id) -> identity(sequence_id)), arrayMap(url_tuple -> (url_tuple.2), _snuba_agg_urls), arrayMap(url_tuple -> (url_tuple.1), _snuba_agg_urls))) AS _snuba_urls_sorted, groupArray(1)(user_email)[1] AS _snuba_user_email, _snuba_project_id, floor(greatest(1, least(10, intDivOrZero((_snuba_count_errors * 25) + (_snuba_count_urls * 5), 10)))) AS _snuba_activity, groupArray(1)(browser_name)[1] AS _snuba_browser_name, groupArray(1)(user_id)[1] AS _snuba_user_id, groupArray(1)(environment AS _snuba_environment)[1] AS _snuba_agg_environment. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xce3f77a in /usr/bin/clickhouse
1. ? @ 0x7c29ca2 in /usr/bin/clickhouse
2. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x12050be3 in /usr/bin/clickhouse
3. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x1204ebad in /usr/bin/clickhouse
4. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x1204ebad in /usr/bin/clickhouse
5. DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x12054538 in /usr/bin/clickhouse
6. ? @ 0x1201457c in /usr/bin/clickhouse
7. DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0x1201431e in /usr/bin/clickhouse
8. DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0x12023905 in /usr/bin/clickhouse
9. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterDAGInfo> const&, std::__1::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0x120289fd in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x125e44a3 in /usr/bin/clickhouse
11. ? @ 0x125dcbf5 in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x125d7940 in /usr/bin/clickhouse
13. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x126715c2 in /usr/bin/clickhouse
14. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1266f340 in /usr/bin/clickhouse
15. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x125969fe in /usr/bin/clickhouse
16. ? @ 0x12979320 in /usr/bin/clickhouse
17. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x12976c0d in /usr/bin/clickhouse
18. DB::TCPHandler::runImpl() @ 0x1353dd04 in /usr/bin/clickhouse
19. DB::TCPHandler::run() @ 0x13551cf9 in /usr/bin/clickhouse
20. Poco::Net::TCPServerConnection::start() @ 0x1636274f in /usr/bin/clickhouse
21. Poco::Net::TCPServerDispatcher::run() @ 0x16364adb in /usr/bin/clickhouse
22. Poco::PooledThread::run() @ 0x16520372 in /usr/bin/clickhouse
23. Poco::ThreadImpl::runnableEntry(void*) @ 0x1651dafd in /usr/bin/clickhouse
24. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
25. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so

02:43:04 [INFO] sentry.access.api: api.access (method='GET' view='sentry.replays.endpoints.organization_replay_index.OrganizationReplayIndexEndpoint' response=500 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/replays/' caller_ip='127.0.0.1' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.20561933517456055 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:43:05 [ERROR] django.request: Internal Server Error: /api/0/organizations/sentry/replays/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/sentry/replays/?field=activity&field=browser&field=count_errors&field=duration&field=finished_at&field=id&field=os&field=project_id&field=started_at&field=urls&field=user&per_page=50&query=&sort=-started_at&statsPeriod=14d'>)
```
May I know how to solve it???

**Comment by hyunkj42** [comment]
It was installed using used charts: 20.0.0, and it was confirmed that the function worked normally.
