### ISSUE TITLE
The following error occurs in the sentry-db-init process.

### ISSUE THREAD

**Issue by hyunkj42** [sentry-kubernetes/charts#945]
charts : 20.0.0

While installing 20.0.0, the following error occurs in the sentry-db-init process.
do you know how to solve it?

```
  Applying sentry.0295_backfill_alertrule_type... OK
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 99, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 50, in _upgrade
    dj_call_command(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/monkey/executor.py", line 79, in apply_migration
    return super().apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/migrations.py", line 22, in apply
    return super().apply(project_state, schema_editor, collect_sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/schema.py", line 52, in inner
    func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 534, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 661, in _alter_field
    fragment = self._alter_column_null_sql(model, old_field, new_field)
  File "/usr/local/lib/python3.8/site-packages/django_zero_downtime_migrations/backends/postgres/schema.py", line 592, in _alter_column_null_sql
    return self._alter_column_set_not_null(model, new_field)
  File "/usr/local/lib/python3.8/site-packages/django_zero_downtime_migrations/backends/postgres/schema.py", line 536, in _alter_column_set_not_null
    raise UnsafeOperationException(Unsafe.ALTER_COLUMN_NOT_NULL)
django_zero_downtime_migrations.backends.postgres.schema.UnsafeOperationException: ALTER COLUMN NOT NULL is unsafe operation
See details for safe alternative https://github.com/tbicr/django-pg-zero-downtime-migrations#dealing-with-not-null-constraint
  Applying sentry.0296_alertrule_type_not_null...%
```

**Comment by Robing** [comment]
I have the samm issue, how do you to solve it?

**Comment by Robing** [comment]
@hyunkj42 did you solve the issue?

**Comment by hyunkj42** [comment]
@Robing Hello.
It seems that the clickhouse and postgresql versions were the problem.
I used the following version and the installation was completed normally.
clickhouse - 21.8.15.7
postgresql - 15.3

**Comment by Robing** [comment]
@hyunkj42 thx for your reply,  I used clickhouse - 21.8.15.7, postgresql - 15.3, zookeeper - 3.8.1，The error was still there, I deployed these three chart in the different namespace with sentry chart。Do you have any suggestion?

`{"module": "snuba.migrations.runner", "event": "Finished: 0001_migrations", "severity": "info", "timestamp": "2023-08-25T09:12:09.038606Z"}
2023-08-25 09:12:09,038 Connecting. Database: default. User: default
2023-08-25 09:12:09,038 Connecting to clickhouse.clickhouse-pass.svc.cluster.local:9000
2023-08-25 09:12:09,043 Connected to ClickHouse server version 21.8.15, revision: 54449
2023-08-25 09:12:09,043 Query: SELECT version FROM migrations_dist FINAL WHERE group = 'system' AND migration_id = '0001_migrations';
2023-08-25 09:12:09,043 Block "" send time: 0.000037
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 192, in execute
    result_data = query_execute()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 304, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 491, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 151, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 167, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 184, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 60.
DB::Exception: Table default.migrations_dist doesn't exist. Stack trace:
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8feddda in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x9104d43 in /usr/bin/clickhouse
2. void std::__1::__optional_storage_base<DB::Exception, false>::__construct<int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x1010eeb1 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x10100f4a in /usr/bin/clickhouse
4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x10107608 in /usr/bin/clickhouse
5. DB::JoinedTables::getLeftTableStorage() @ 0x10694bbc in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x1047cbdc in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1047c1be in /usr/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1065915a in /usr/bin/clickhouse
9. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x10267797 in /usr/bin/clickhouse
10. ? @ 0x1081dbc6 in /usr/bin/clickhouse
11. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1081c503 in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0x110c281e in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0x110d57b9 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x13c4ee2f in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x13c508ba in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x13d82b39 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d7edca in /usr/bin/clickhouse
18. start_thread @ 0x8609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
19. clone @ 0x11f163 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 97, in migrate
    runner.run_all(
  File "/usr/src/snuba/snuba/migrations/runner.py", line 217, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 281, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 144, in forwards
    update_status(Status.COMPLETED)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 431, in _update_migration_status
    next_version = self._get_next_version(migration_key)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 446, in _get_next_version
    result = self.__connection.execute(
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 268, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Table default.migrations_dist doesn't exist. Stack trace:
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8feddda in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x9104d43 in /usr/bin/clickhouse
2. void std::__1::__optional_storage_base<DB::Exception, false>::__construct<int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x1010eeb1 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x10100f4a in /usr/bin/clickhouse
4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x10107608 in /usr/bin/clickhouse
5. DB::JoinedTables::getLeftTableStorage() @ 0x10694bbc in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x1047cbdc in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1047c1be in /usr/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1065915a in /usr/bin/clickhouse
9. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x10267797 in /usr/bin/clickhouse
10. ? @ 0x1081dbc6 in /usr/bin/clickhouse
11. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1081c503 in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0x110c281e in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0x110d57b9 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x13c4ee2f in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x13c508ba in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x13d82b39 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d7edca in /usr/bin/clickhouse
18. start_thread @ 0x8609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
19. clone @ 0x11f163 in /usr/lib/x86_64-linux-gnu/libc-2.31.so`

sentry chart value.yaml

![image](https://github.com/sentry-kubernetes/charts/assets/63043/9ff4de14-8c87-45f0-a46a-eb503d7f7528)


the clickhouse value.yaml

![image](https://github.com/sentry-kubernetes/charts/assets/63043/0a1a2a63-f3e3-4acc-bdf6-1d20a8bacd51)


the zookeeper value.yaml

![image](https://github.com/sentry-kubernetes/charts/assets/63043/331cccf7-9684-4615-ac2e-2a886f8b8dca)

**Comment by hyunkj42** [comment]
@Robing 
First, I checked whether the installation was successful with the images that provide clickhouse and postgresql as default.
Then I created an image and used my own image.
And I didn't use externalpostgresql, externalclickhouse.

<img width="713" alt="image" src="https://github.com/sentry-kubernetes/charts/assets/22021000/875e9580-2e72-4bc5-ac9b-93b4c95f56e9">

<img width="743" alt="image" src="https://github.com/sentry-kubernetes/charts/assets/22021000/902b944a-2714-4bab-aaea-db8ba165a1b5">
