### ISSUE TITLE
Migration Error: MigrationInProgress for 0035_metrics_raw_timeseries_id

### ISSUE THREAD

**Issue by TartanLeGrand** [sentry-kubernetes/charts#970]
# Environment:

Sentry Version: 23.7.2
Helm Chart Version: 20.4.0

# Description:
While trying to run migrations on a fresh installation of Sentry using the default values, I encountered an error indicating that the migration 0035_metrics_raw_timeseries_id is in progress. This happens despite several attempts to restart or manually trigger the migration.

#  Traceback:
```arduino
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 97, in migrate
    runner.run_all(
  File "/usr/src/snuba/snuba/migrations/runner.py", line 176, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 392, in _get_pending_migrations
    group_migrations = self._get_pending_migrations_for_group(group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 415, in _get_pending_migrations_for_group
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: metrics: 0035_metrics_raw_timeseries_id
```

# Steps to Reproduce:
Perform a fresh installation of Sentry using Helm chart version 20.4.0 with the default values.
Attempt to run migrations.

# Expected Behavior:
I expected the migration to complete successfully.

# Actual Behavior:
The migration remains stuck in the in_progress state.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
