### ISSUE TITLE
Snuba: Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1

### ISSUE THREAD

**Issue by cabrinha** [sentry-kubernetes/charts#977]
This log line is mainly coming from `sentry-snuba-outcomes-consumer`.

Ah, I see: https://github.com/urllib3/urllib3/blob/d6605c541558d97de305d3afd2300f5d7d6edc68/src/urllib3/connectionpool.py#L183

**Comment by ohjongsung** [comment]
same issue. version : 20.4.0

```text
2023-08-29 05:10:57,493 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
2023-08-29 05:11:04,482 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
2023-08-29 05:11:42,557 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 365, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 149, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 98, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 122, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 330, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 160, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 347, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 239, in join
    response = self._result.result(timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
2023-08-29 05:11:47,596 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
2023-08-29 05:11:47,596 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7fa27e6e0940>...
2023-08-29 05:11:47,598 Partitions to revoke: [Partition(topic=Topic(name='events'), index=0)]
2023-08-29 05:11:47,598 Partition revocation complete.
2023-08-29 05:11:47,601 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 260, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 365, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 149, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 98, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 122, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 330, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 160, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 347, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 239, in join
    response = self._result.result(timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by cabrinha** [comment]
I can't tell where this config option is controlled, I'm trying to edit `<pool_size>` inside of the `<distributed_ddl>` section:

```xml
    <!-- Allow to execute distributed DDL queries (CREATE, DROP, ALTER, RENAME) on cluster.
         Works only if ZooKeeper is enabled. Comment it if such functionality isn't required. -->
    <distributed_ddl>
        <!-- Path in ZooKeeper to queue with DDL queries -->
        <path>/clickhouse/task_queue/ddl</path>

        <!-- Settings from this profile will be used to execute DDL queries -->
        <!-- <profile>default</profile> -->

        <!-- Controls how much ON CLUSTER queries can be run simultaneously. -->
        <!-- <pool_size>1</pool_size> -->

        <!--
             Cleanup settings (active tasks will not be removed)
        -->

        <!-- Controls task TTL (default 1 week) -->
        <!-- <task_max_lifetime>604800</task_max_lifetime> -->

        <!-- Controls how often cleanup should be performed (in seconds) -->
        <!-- <cleanup_delay_period>60</cleanup_delay_period> -->

        <!-- Controls how many tasks could be in the queue -->
        <!-- <max_tasks_in_queue>1000</max_tasks_in_queue> -->


        <pool_size>1024</pool_size>
    </distributed_ddl>
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by rojinebrahimi** [comment]
Any news on this topic?

**Comment by izeal** [comment]
+1

**Comment by sohahm** [comment]
I am also having the same issue.

**Comment by mischka** [comment]
+1

**Comment by kzonov** [comment]
It looks like no help is coming to this issue thread, so I will be just one of those who adds the +1 :) We also experience this issue, helm chart version `20.5.3`

**Comment by mischka** [comment]
@graffzon I guess the problem https://github.com/getsentry/snuba/issues/4596 still exists because the PR https://github.com/getsentry/snuba/pull/4988 has not been merged yet. So everyone here is waiting for the merge and maybe a chart version with support for the env CLICKHOUSE_MAX_CONNECTIONS.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by daviddale** [comment]
+1 Also arrived here researching this issue.

**Comment by fayak** [comment]
how is the pool size configured other than via this env variable not available yet ? I'm facing the same issue

**Comment by hd-deman** [comment]
> @graffzon I guess the problem [getsentry/snuba#4596](https://github.com/getsentry/snuba/issues/4596) still exists because the PR [getsentry/snuba#4988](https://github.com/getsentry/snuba/pull/4988) has not been merged yet. So everyone here is waiting for the merge and maybe a chart version with support for the env CLICKHOUSE_MAX_CONNECTIONS.

I tried this after it merged. It didn't help.

CLICKHOUSE_MAX_CONNECTIONS=100 
but still 

```log
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 243, in join
    response = self._result.result(timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
2024-01-19 19:11:46,442 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
```

**Comment by adonskoy** [comment]
> > @graffzon I guess the problem [getsentry/snuba#4596](https://github.com/getsentry/snuba/issues/4596) still exists because the PR [getsentry/snuba#4988](https://github.com/getsentry/snuba/pull/4988) has not been merged yet. So everyone here is waiting for the merge and maybe a chart version with support for the env CLICKHOUSE_MAX_CONNECTIONS.
> 
> I tried this after it merged. It didn't help.
> 
> CLICKHOUSE_MAX_CONNECTIONS=100 but still
> 
> ```
>     batch.join(timeout=batch_join_timeout)
>   File "/usr/src/snuba/snuba/clickhouse/http.py", line 243, in join
>     response = self._result.result(timeout)
>   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 460, in result
>     raise TimeoutError()
> concurrent.futures._base.TimeoutError
> 2024-01-19 19:11:46,442 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
> ```

This fix will only work with the next Sentry release. Either Sentry will release a patch update this month, or it will be with the February release. 

I will create a PT  with new envs and default values as soon as the new version of sentry will be available.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by kerkeniw** [comment]
+1

**Comment by jhass** [comment]
Looks like the PR was released with Sentry 24.2.0

**Comment by begemotik** [comment]
> > > @graffzon I guess the problem [getsentry/snuba#4596](https://github.com/getsentry/snuba/issues/4596) still exists because the PR [getsentry/snuba#4988](https://github.com/getsentry/snuba/pull/4988) has not been merged yet. So everyone here is waiting for the merge and maybe a chart version with support for the env CLICKHOUSE_MAX_CONNECTIONS.
> > 
> > 
> > I tried this after it merged. It didn't help.
> > CLICKHOUSE_MAX_CONNECTIONS=100 but still
> > ```
> >     batch.join(timeout=batch_join_timeout)
> >   File "/usr/src/snuba/snuba/clickhouse/http.py", line 243, in join
> >     response = self._result.result(timeout)
> >   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 460, in result
> >     raise TimeoutError()
> > concurrent.futures._base.TimeoutError
> > 2024-01-19 19:11:46,442 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
> > ```
> 
> This fix will only work with the next Sentry release. Either Sentry will release a patch update this month, or it will be with the February release.
> 
> I will create a PT with new envs and default values as soon as the new version of sentry will be available.

@adonskoy, would you like to add the support to Helm Chart since the aforementioned PR is merged?

**Comment by hobbyFind** [comment]
> I can't tell where this config option is controlled, I'm trying to edit `<pool_size>` inside of the `<distributed_ddl>` section:
>
> ```
>  
>  <distributed_ddl>
>      
>      <path>/clickhouse/task_queue/ddl</path>
> 
>      
>      
> 
>      
>      
> 
>      
> 
>      
>      
> 
>      
>      
> 
>      
>      
> 
> 
>      <pool_size>1024</pool_size>
>  </distributed_ddl>
> ```

so,Where is this file and can it be resolved effectively? This problem has been bothering me for a long time, please help me，thanks!   chart version is 21.5.0.

sentry-snuba-metrics-consumer, sentry-snuba-generic-metrics-distributions-consumer, sentry-snuba-outcomes-consumer The logs for this component look like this:

```
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/cli/consumer.py", line 284, in consumer
    consumer.run()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 319, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 393, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/filter.py", line 69, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/reduce.py", line 101, in poll
    self.__buffer_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/buffer.py", line 169, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 137, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 300, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 136, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 359, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 243, in join
    response = self._result.result(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 458, in result
    raise TimeoutError()
TimeoutError
```

**Comment by jhass** [comment]
```
snuba:
  outcomesConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "5"
```

Seems to have helped me a bit.

**Comment by hobbyFind** [comment]
> ```
> snuba:
>   outcomesConsumer:
>     env:
>       - name: CLICKHOUSE_MAX_CONNECTIONS
>         value: "5"
> ```
> 
> Seems to have helped me a bit.

The problem remains. I was trying to build environment variables into the image, like this ：

```
FROM getsentry/snuba:24.1.2
ENV CLICKHOUSE_MAX_CONNECTIONS 100
```

Now, I will try your method again, but it still does not work：

```
    spec:
      containers:
      - command:
        - snuba
        - consumer
        - --storage
        - outcomes_raw
        - --auto-offset-reset
        - earliest
        - --max-batch-size                      
        - "3"
        env:
        - name: SNUBA_SETTINGS
          value: /etc/snuba/settings.py
        - name: DEFAULT_BROKERS
          value: sentry-kafka:9092
        - name: CLICKHOUSE_MAX_CONNECTIONS             # here
          value: "5"
```

```
2024-03-07 01:16:33,810 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 42899}
2024-03-07 01:17:01,493 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
2024-03-07 01:17:04,736 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
```

**Comment by janosmiko** [comment]
I was able to solve it by adding the CLICKHOUSE_MAX_CONNECTIONS env var to all pods in the values.yaml:
```
snuba:
  consumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  outcomesConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  replacer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  metricsConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  subscriptionConsumerEvents:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  genericMetricsCountersConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  genericMetricsDistributionConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  genericMetricsSetsConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  subscriptionConsumerMetrics:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  subscriptionConsumerTransactions:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  subscriptionConsumerSessions:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  replaysConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  sessionsConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  transactionsConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  profilingProfilesConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  profilingFunctionsConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
  issueOccurrenceConsumer:
    env:
      - name: CLICKHOUSE_MAX_CONNECTIONS
        value: "25"
```

**Comment by dongdorrong** [comment]
@janosmiko
I was wondering if you could tell me what version of Helm chart you are using?

I'm using appVersion 24.1.2, chart 21.5.0, and I've applied the same method you applied to values.yaml and deployed it, and the symptoms are the same.

**Comment by dromadaire54** [comment]
Hi,
I'm using the version 24.2.0 of sentry and I tried all the solutions but none of them work for me. The env var `CLICKHOUSE_MAX_CONNECTIONS` is maybe not yet available in the chart this PR is not merged https://github.com/sentry-kubernetes/charts/pull/1175 ?

**Comment by IvanTurgenev1** [comment]
same for me. 21.6.2 chart version, CLICKHOUSE_MAX_CONNECTIONS not working at all

**Comment by geckiss** [comment]
Hello,

I was able to change the value of `CLICKHOUSE_MAX_CONNECTIONS` by setting `.Values.snuba.clickhouse.maxConnections`. Without this value set, CLICKHOUSE_MAX_CONNECTIONS is set to 100. 

I'm using chart version `22.0.2`. Seems like [this](https://github.com/sentry-kubernetes/charts/blob/a148a57d7480e23adc912fe8700914792bea9807/sentry/templates/_helper.tpl#L454C38-L454C52) helper template is responsible.

```yaml
...

  snuba:
    clickhouse:
      maxConnections: 5
    api:
      replicas: 1
...
```

I can see the value changed in all the other underlying pods, e.g. `generic-metrics-sets-consumer`:

```yaml
...
ports:
- containerPort: 1218
env:
- name: SNUBA_SETTINGS
  value: /etc/snuba/settings.py
- name: DEFAULT_BROKERS
  value: "sentry-kafka:9092"
- name: CLICKHOUSE_MAX_CONNECTIONS
  value: "5"
envFrom:
- secretRef:
    name: sentry-snuba-env
...
```

**Comment by bkk-bcd** [comment]
See https://github.com/getsentry/snuba/pull/5795

**Comment by rdziwinski** [comment]
Hello,
i upgraded Sentry helm chart to 22.2.0 version and I confirm that env CLICKHOUSE_MAX_CONNECTIONS is available in deployments but seem it's not working. At many pods i still have error
` Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1`

**Comment by kimxogus** [comment]
It looks like fixed in https://github.com/getsentry/snuba/commit/f76f99994288eca5eee32e8316e3e14648fba042 which is released in 24.4.2
I wrote a pr to bump 24.4.2 in #1248

**Comment by xjxtree** [comment]
hi all. I had this problem with version:
CHART         	APP VERSION
sentry-26.14.1	25.1.0
my relative helm chart values:
snuba:
  clickhouse:
    maxConnections: 1000
problem:
some consumers :
sentry-snuba-generic-metrics-distributions-consumer
sentry-snuba-generic-metrics-counters-consumer
sentry-snuba-outcomes-billing-consumer
sentry-snuba-outcomes-consumer
had error log:
2025-02-26 07:43:00,497 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
I enter pod, checked these pod 's env , surely had CLICKHOUSE_MAX_CONNECTIONS var
and check /etc/snuba/settings.py 's CLUSTERS config, looks like below:
CLUSTERS = [
  {
    "host": env("CLICKHOUSE_HOST", "sentry-clickhouse"),
    "port": int(9000),
    "user":  env("CLICKHOUSE_USER", "default"),
    "password": env("CLICKHOUSE_PASSWORD", ""),
    "max_connections": int(os.environ.get("CLICKHOUSE_MAX_CONNECTIONS", 100)),
    "database": env("CLICKHOUSE_DATABASE", "default"),
    "http_port": 8123,
...
It seems all right
so, anyone can help you with this problem? tks

**Comment by yildizozgur** [comment]
We use version 25.1.0 for snuba and clickhouse/clickhouse-server:23.8.16.16.
I have set in my helm chart values.yaml file 

snuba:
  clickhouse:
    maxConnections: 1024 

Also in snuba-consumers pod there is an env which is set:

CLICKHOUSE_MAX_CONNECTIONS=100

But in snuba-consumers pod log I see still:

2025-03-12 10:09:08,062 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
2025-03-12 10:09:17,761 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
2025-03-12 10:09:41,261 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1

**Comment by xjxtree** [comment]
> hi all. I had this problem with version: CHART APP VERSION sentry-26.14.1 25.1.0 my relative helm chart values: snuba: clickhouse: maxConnections: 1000 problem: some consumers : sentry-snuba-generic-metrics-distributions-consumer sentry-snuba-generic-metrics-counters-consumer sentry-snuba-outcomes-billing-consumer sentry-snuba-outcomes-consumer had error log: 2025-02-26 07:43:00,497 Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1 I enter pod, checked these pod 's env , surely had CLICKHOUSE_MAX_CONNECTIONS var and check /etc/snuba/settings.py 's CLUSTERS config, looks like below: CLUSTERS = [ { "host": env("CLICKHOUSE_HOST", "sentry-clickhouse"), "port": int(9000), "user": env("CLICKHOUSE_USER", "default"), "password": env("CLICKHOUSE_PASSWORD", ""), "max_connections": int(os.environ.get("CLICKHOUSE_MAX_CONNECTIONS", 100)), "database": env("CLICKHOUSE_DATABASE", "default"), "http_port": 8123, ... It seems all right so, anyone can help you with this problem? tks

I had resolved this problem with PR https://github.com/getsentry/snuba/pull/6919
waiting for new version of snuba and helm chart

**Comment by pshen** [comment]
The issue was NOT fixed in snuba image 25.2.0.

**Comment by xjxtree** [comment]
> The issue was NOT fixed in snuba image 25.2.0.

25.3.0 had

**Comment by pshen** [comment]
@xjxtree in the recent helm charts, snuba 25.2.0 is still used.

**Comment by xjxtree** [comment]
> [@xjxtree](https://github.com/xjxtree) in the recent helm charts, snuba 25.2.0 is still used.

yes  ,  I'm also waiting for the release of the new version of the helmchart.
