### ISSUE TITLE
ingest-replay-recordings POD error

### ISSUE THREAD

**Issue by hyunkj42** [sentry-kubernetes/charts#987]
Hello.

use tag : 20.0.0

The ingest-replay-recordings POD works normally, but suddenly crashes with the error below.
 
```
WARNING: Deprecated command, use sentry run consumer ingest-replay-recordings --consumer-group ingest-replay-recordings ...
06:18:18 [INFO] arroyo.processing.processor: New partitions assigned: {Partition(topic=Topic(name='ingest-replay-recordings'), index=0): 7998, Partition(topic=Topic(name='ingest-replay-recordings'), index=1): 7664, Partition(topic=Topic(name='ingest-replay-recordings'), index=2): 7737}
06:18:18 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:18 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:18 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:18 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:18 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='34be7a282f9b4c259517054933b40e60')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='72259835dbe14cfdaaa09dec0f8645e9')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='2293b513d17e418fac8b4a53c91a6813')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='129fe14dc29e427d9efc6ea24b83fed8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='129fe14dc29e427d9efc6ea24b83fed8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='129fe14dc29e427d9efc6ea24b83fed8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='c0596d837ac94a3b9c87d003f3f8ca72')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='83ad8244387744ec84e489cac1dbf34e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='83ad8244387744ec84e489cac1dbf34e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='83ad8244387744ec84e489cac1dbf34e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=3 replay_id='a69ddfa3a685474aaa08c222d6af8643')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='83ad8244387744ec84e489cac1dbf34e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='83ad8244387744ec84e489cac1dbf34e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='1b60210e6a3d4e2791fb8cf20b01db11')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='9d7a63cb453849e0a656b5d6c9ab29e8')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='40a8038b941147b4bc198baeb778f464')
06:18:21 [WARNING] root: Recording segment was already processed. (project_id=2 replay_id='fc81dbeb518045e39ac995aa036c916e')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sentry_kafka_schemas/codecs/msgpack.py", line 35, in validate
    self.__validate(data)
  File "<string>", line 10, in validate
fastjsonschema.exceptions.JsonSchemaValueException: data must contain ['type', 'replay_id', 'org_id', 'project_id', 'received', 'retention_days', 'payload'] properties

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 381, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/guard.py", line 82, in submit
    self.__inner_strategy.submit(message)
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/run_task.py", line 50, in submit
    result = self.__function(cast(Message[TStrategyPayload], message))
  File "/usr/local/lib/python3.8/dist-packages/sentry/replays/consumers/recording.py", line 69, in initialize_message_context
    message_dict = RECORDINGS_CODEC.decode(message.payload.value)
  File "/usr/local/lib/python3.8/dist-packages/sentry_kafka_schemas/codecs/msgpack.py", line 30, in decode
    self.validate(decoded)
  File "/usr/local/lib/python3.8/dist-packages/sentry_kafka_schemas/codecs/msgpack.py", line 37, in validate
    raise ValidationError from exc
sentry_kafka_schemas.codecs.ValidationError
06:18:22 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
06:18:23 [INFO] arroyo.processing.processor: Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7fe5251e33a0>...
06:18:23 [INFO] arroyo.processing.processor: Partitions to revoke: [Partition(topic=Topic(name='ingest-replay-recordings'), index=0), Partition(topic=Topic(name='ingest-replay-recordings'), index=1), Partition(topic=Topic(name='ingest-replay-recordings'), index=2)]
06:18:23 [INFO] arroyo.processing.processor: Partition revocation complete.
06:18:23 [WARNING] arroyo.backends.kafka.consumer: Dropping staged offset for revoked partition (Partition(topic=Topic(name='ingest-replay-recordings'), index=2))!
06:18:23 [INFO] arroyo.processing.processor: Processor terminated
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sentry_kafka_schemas/codecs/msgpack.py", line 35, in validate
    self.__validate(data)
  File "<string>", line 10, in validate
fastjsonschema.exceptions.JsonSchemaValueException: data must contain ['type', 'replay_id', 'org_id', 'project_id', 'received', 'retention_days', 'payload'] properties

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sentry/runner/commands/run.py", line 773, in replays_recordings_consumer
    run_processor_with_signals(consumer)
  File "/usr/local/lib/python3.8/dist-packages/sentry/utils/kafka.py", line 14, in run_processor_with_signals
    processor.run()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/processor.py", line 381, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/guard.py", line 82, in submit
    self.__inner_strategy.submit(message)
  File "/usr/local/lib/python3.8/dist-packages/arroyo/processing/strategies/run_task.py", line 50, in submit
    result = self.__function(cast(Message[TStrategyPayload], message))
  File "/usr/local/lib/python3.8/dist-packages/sentry/replays/consumers/recording.py", line 69, in initialize_message_context
    message_dict = RECORDINGS_CODEC.decode(message.payload.value)
  File "/usr/local/lib/python3.8/dist-packages/sentry_kafka_schemas/codecs/msgpack.py", line 30, in decode
    self.validate(decoded)
  File "/usr/local/lib/python3.8/dist-packages/sentry_kafka_schemas/codecs/msgpack.py", line 37, in validate
    raise ValidationError from exc
sentry_kafka_schemas.codecs.ValidationError
%4|1693289904.091|TERMINATE|rdkafka#producer-2| [thrd:app]: Producer terminating with 1 message (178 bytes) still in queue or transit: use flush() to wait for outstanding message delivery
```

If you know a solution, please explain. 
Thank you.

**Comment by hyunkj42** [comment]
I restarted the entire system through helm upgrade.
Then, the following error occurred in ingest-replay-recordingsPOD.
```
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 0)"}
```
I changed the offset to latest in the ingest-replay-recordings group of the ingest-replay-recordings topic in kafka.

After that, it runs normally.

**Comment by hyunkj42** [comment]
data must contain ['type', 'replay_id', 'org_id', 'project_id', 'received', 'retention_days', 'payload'] properties

There are cases where replay data is stored in the ingest-replay-recordings topic without an org_id value.
Afterwards, when trying to process it in the ingest-replay-recordings consumer, the above error occurs.

Do any happen to know the cause?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
